### ISSUE TITLE
[BUG] Rectnagle WM not detected on macOS

### ISSUE THREAD

**Issue by MatthiasPortzel** [fastfetch-cli/fastfetch#1007]
# General description of bug:

* What happened: Window manager identified as "Quartz Compositor"
* What should happen: Window manager identified as "Rectangle"
* Fastfetch version used: 2.15.0
* Did it work in an older version: No, checked in 2.14.0 (didn't check older)
* Where did you get the binary: Homebrew
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Yes

### Screenshot
<img width="966" alt="image" src="https://github.com/fastfetch-cli/fastfetch/assets/19734415/c9e80449-ccc9-44a5-ac9f-b358800cbdb6">

It works correctly in neofetch. This is the script neofetch uses to detect Rectangle and its output
```
% ps_line="$(ps -e | grep -o \
                    -e "[S]pectacle" \
                    -e "[A]methyst" \
                    -e "[k]wm" \
                    -e "[c]hun[k]wm" \
                    -e "[y]abai" \
                    -e "[R]ectangle")"
% echo $ps_line
Rectangle
Rectangle
```

Happy to run test scripts but I don't know C well enough to debug myself.

**Comment by CarterLi** [comment]
Duplicate #984
