### ISSUE TITLE
[FEAT] Illumos; Solaris OS Support: Logos

### ISSUE THREAD

**Issue by Oichkatzelesfrettschen** [fastfetch-cli/fastfetch#1008]
## Wanted features:
Support for Solaris OSs (Solaris 11.x, Solaris 10.x) 
Support for Illumos OSs, full list located [Here](https://github.com/sirredbeard/awesome-unix?tab=readme-ov-file#solaris-and-illumos)

## Motivation:

Solaris is still used on the Oracle cloud; and has 64-bit x86 and SPARC support. Can't flex on da noobs that I'm working with some weird servers without fastfetch! :) 

OpenIndiana is a great Illumos OS for daily use. Illumos is based on OpenSolaris. 

Therefore, Solaris and OpenIndiana remain the only "true UNIX" operating systems out there based on lineage and heritage, which means those screen captures need uberextra attention!

I tried modifying `CMakeLists.txt ` to "support" `SunOS` (which is how its detected) as a valid OS. I tried GCC, clang, but had way too many `Error: Implict Declaration of Function...` errors while trying to compile from ./run.sh after using` git clone `on the repo. It is clear more is to be done than what I messed with. But what though, I do not know. 

- Solaris you can download [here]https://www.oracle.com/solaris/solaris11/downloads/solaris-downloads.html) with an Oracle account, or deploy to the [Oracle Cloud Free Tier](https://www.oracle.com/cloud/free/) I do believe, unless the free tier is ARM cores only... 
- OpenIndiana can be downloaded from [their Downloads page here]https://www.openindiana.org/downloads/)
- Other Illumos distros from the link above can be found at their respective sites. (Tribblix is pretty fun, with a responsive dev, if you wish to play around with another)

All work great in VMWare Desktop 17, or VirtualBox - hardware acceleration is a bit tricky but its doable. Of course, they are installable on metal. 

-------

When that is up-and-running; requesting Logos for the two main Illumos Distros: OpenIndiana and Tribblix ++ for Oracle's Solaris. Other logos are up to you!

**Comment by CarterLi** [comment]
As said in <https://github.com/fastfetch-cli/fastfetch/issues/1010#issuecomment-2161883373>, I don't have motivation to port fastfetch to niche platforms I don't use personally, and I don't think others have wills to work on it. If you want to try it yourself, I can provide some help.

**Comment by Oichkatzelesfrettschen** [comment]
True. I'm trying to try something outside of the Windows - Mac - Linux -
BSD (distant 4th) vibe and using it as my primary workstation OS. I suppose
indeed I shall have to do, its good motivation. Thank you for your polite
and kind words!

**Comment by CarterLi** [comment]
Did some work in dev branch. You should try it.
