### ISSUE TITLE
[FEAT] Stripped Down Fastfetch for 16-bit/ia16 x86 OS ELKS

### ISSUE THREAD

**Issue by Oichkatzelesfrettschen** [fastfetch-cli/fastfetch#1009]
## Wanted features:

A "light" version of Fastfetch that works with [ELKS: Embeddable Linux Kernel Subset](https://github.com/ghaerr/elks) 16-bit x86/ia16 CPUS (Intel 8088, 8086, 80186, 80286, NEC V20, V30, and clones, etc) likely using[ gcc-ia16 ](https://github.com/tkchia/gcc-ia16) from the github or from the Arch Linux AUR, however it is [stuck on the 6.x branch due to issues with far pointers and the [hackiness needed to make them work.](https://github.com/tkchia/gcc-ia16/issues/103) OpenWatcom is what ELKS is looking to move to per this [comment](https://github.com/ghaerr/elks/issues/1443). (But LLVM is apparently an option!?)

## Motivation:

Really no cool "fetch" exists for this operating system. fastfetch is lightweight and is well-suited to be able to "shrink down" for the limits of such a tiny OS. Book8088 and Book8086 exist at this moment in time is brand-new 16-bit OSes. There are also 16-bit embedded boards and use cases involving these CPUs. 

Of course, older handheld PCs like the HP 100LX, HP 200LX, HP 1000LX exist as do others, and older desktops and laptops such as my Compaq LTE 286 and my NEC 286 exist. Hobby boards and tinker boards exist. These can run a modern Linux kernel subset, but sadly do not have fastfetch for support! 

Personally I also run [86Box]https://github.com/86Box) for emulation of an older machine when I do not want to lug the old chonker out and use that with the provided ROMs for tinkering with ELKS. (Or you could tinker with old Xenix builds if that floats your fancy for some fun practice with old old OSes) 

[2.11BSD](https://wfjm.github.io/home/211bsd/) is an elder 16-bit BSD for PDP-11, 8086, and more, that has patches as recently as 2023-26-04!!!!
----

I suppose it would be nice to see from the hardware end: 

- CPU, Clock Speed, Cache (if any), FPU (if any) 
- RAM (HiMem/LowMem/FreeMem, etc) 
- Any RAM paging for extended RAM or disk RAM "swap space" 
- Any video cards and types (CGA, EGA, VGA, amount of video memory) 
- X11 support and version 
- window manager support and what type
- OpenGL is really not a worry as that is just not available on these systems*
.......
- *OK so the ATI Mach64 4MB ISA-slot card COULD have OpenGL 1.0, or a subset thereof if someone wanted to take the time to make that happen on a 16-bit OS.**
- **Additionally... well... ISA to PCI bridges or "risers" exist and while its super sketchy, someone could *theoretically* use a "newer" OpenGL 1.x card with that bridge and have it running at 16-bit or 8-bit ISA speeds. But even then OpenGL would be as an academic activity only, or for fun, or to brag, as there would be hefty limits as to what the CPU could transfer. 

----

Anyway, once that is squared away the final request is for a logo! 

----

..... There is also the [16-bit Gloworm UNIX-like OS for 68000 computers](https://github.com/transistorfet/gloworm/) but that is super niche. However if you are playing with 16-bit stuff, that might be fun. Specifically it is for this homebrew 68000 CPU (which is a limited 32-bit, but 16-bit data bus CPU) board: [Computie](https://github.com/transistorfet/computie) however quite a few other 68000 homebrew boards [are referenced](https://github.com/transistorfet/computie?tab=readme-ov-file#references)

----- 

Order of Priority: 

- ELKS (x86 16-bit) 
- 211BSD (multiple platforms incl PDP-11. PDP-11 can be emulated via SIMH emulator) 
- Computie... and others? (68000 "16-bit"

**Comment by CarterLi** [comment]
We don't have plan to port fastfetch to any niche platforms.

**Comment by Oichkatzelesfrettschen** [comment]
Sadness, but understood!
