### ISSUE TITLE
[BUG] why do fastfetch and neofetch show different memory ammount being used

### ISSUE THREAD

**Issue by EducatedSuddenBucket** [fastfetch-cli/fastfetch#1021]
![screenshot](https://github.com/fastfetch-cli/fastfetch/assets/149485703/7e98bcd9-a379-4420-aafc-f80612b6dcf2)

**Comment by CarterLi** [comment]
I can't reproduce it. Both fastfetch and neofetch use `MemAvailable` if available.

https://github.com/dylanaraps/neofetch/blob/master/neofetch#L2691

https://github.com/fastfetch-cli/fastfetch/blob/dev/src/detection/memory/memory_linux.c#L30

What version of fastfetch did you use?

**Comment by EducatedSuddenBucket** [comment]
latest , i builded it on debian 12 i386 , it also happened when i used alpine inux

**Comment by EducatedSuddenBucket** [comment]
i could also show screen recording if you want

**Comment by CarterLi** [comment]
Seems fastfetch was correct?

**Comment by EducatedSuddenBucket** [comment]
see htop at the left

**Comment by EducatedSuddenBucket** [comment]
so they are not the same i think

**Comment by qaqland** [comment]
see https://github.com/KittyKatt/screenFetch/issues/386#issuecomment-249312716
