### ISSUE TITLE
[BUG] Incorrect Local IP since 2.12.0

### ISSUE THREAD

**Issue by Guiorgy** [fastfetch-cli/fastfetch#1028]
Today after upgrading I noticed that the value shown for `Local IP` had changed and is missing the actual IP:

![2 16 0](https://github.com/fastfetch-cli/fastfetch/assets/27736965/c7ee8950-5d96-44a8-9465-490822ee45f4)

As can be seen in the screenshot above, my system has 2 interfaces, of which only 1 is being used (hence the other defaults to 169.254.x.y), and as can be seen from the output of `ip address` and the title of the PuTTY window in the top left corner, the actual IP of interest is missing.

I tracked the regression to 2.11.5 -> 2.12.0:

![2 11 5](https://github.com/fastfetch-cli/fastfetch/assets/27736965/8e8ff1fb-6358-4d99-aec5-57cc1d7f0292)
![2 12 0](https://github.com/fastfetch-cli/fastfetch/assets/27736965/7f4c161e-880f-4c34-b4ad-afc680786797)

Additional info:

- All binaries were built from source on the machine.
- Config is default/no configuration used.
- Part of the output of `fastfetch -c ci.jsonc --format json` for `2.11.5`:
  ```json
  {
    "type": "OS",
    "result": {
      "buildID": "",
      "codename": "jammy",
      "id": "Ubuntu",
      "idLike": "debian",
      "name": "Ubuntu",
      "prettyName": "Ubuntu 22.04.4 LTS",
      "variant": "",
      "variantID": "",
      "version": "22.04",
      "versionID": "22.04"
    },
    "stat": 0
  },
  {
    "type": "LocalIp",
    "result": [
      {
        "defaultRoute": true,
        "ipv4": "169.254.254.61/16,192.168.0.7/24",
        "ipv6": "",
        "mac": "",
        "name": "eno1"
      }
    ],
    "stat": 0
  },
  {
    "type": "Version",
    "result": {
      "projectName": "fastfetch",
      "architecture": "x86_64",
      "version": "2.11.5",
      "versionTweak": "",
      "cmakeBuiltType": "RelWithDebInfo",
      "compileTime": "Jun 19 2024, 16:36:54",
      "compiler": "gcc 11.4.0",
      "debugMode": false,
      "libc": "glibc 2.35"
    },
    "stat": 0
  }
  ```
- Part of the output of `fastfetch -c ci.jsonc --format json` for `2.12.0`:
  ```json
  {
    "type": "OS",
    "result": {
      "buildID": "",
      "codename": "jammy",
      "id": "Ubuntu",
      "idLike": "debian",
      "name": "Ubuntu",
      "prettyName": "Ubuntu 22.04.4 LTS",
      "variant": "",
      "variantID": "",
      "version": "22.04",
      "versionID": "22.04"
    },
    "stat": 0
  },
  {
    "type": "LocalIp",
    "result": [
      {
        "defaultRoute": true,
        "ipv4": "169.254.254.61/16",
        "ipv6": "",
        "mac": "",
        "name": "eno1"
      }
    ],
    "stat": 1
  },
  {
    "type": "Version",
    "result": {
      "projectName": "fastfetch",
      "architecture": "x86_64",
      "version": "2.12.0",
      "versionTweak": "",
      "cmakeBuiltType": "RelWithDebInfo",
      "compileTime": "May 16 2024, 13:51:02",
      "compiler": "gcc 11.4.0",
      "debugMode": false,
      "libc": "glibc 2.35"
    },
    "stat": 0
  },
  ```
- Output of `fastfetch --list-features`:
  ```shell
  $ fastfetch --list-features
  threads
  Proprietary GPU driver API
  linux/videodev2
  linux/wireless
  ```

**Comment by Guiorgy** [comment]
Yeah, now I see this:

> Add option --localip-show-all-ips to show all IPs assigned to the same interface (LocalIP)
>
>    Default to false

In hindsight, should've checked the changelog -_-

If not all IPs are shown, is there a way to configure which of the several is shown? As the one shown by default is not the one I care...

**Comment by CarterLi** [comment]
No, it isn't. How can I know which one do you care?

**Comment by Guiorgy** [comment]
> No, it isn't. How can I know which one do you care?

Yeah, makes sense. Though, in this case I question if it is correct to only show 1 IP when it may not be the correct. Shouldn't the default be `true`?

Closing since this seems intentional.

**Comment by CarterLi** [comment]
Because long texts may mess the layout of fastfetch output. This flag is introduced purely for formatting purpose.
