### ISSUE TITLE
[BUG]  Dedicated GPU detected as integrated.

### ISSUE THREAD

**Issue by Null-Ping** [fastfetch-cli/fastfetch#1032]
# General description of bug:

* What happened: dedicated AMD Radeon HD 7570M GPU is detected as integrated.
* What should happen: it should be detected as dedicated.
* Fastfetch version used: 2.16.0.
* Did it work in an older version: NO.
* Where did you get the binary: Scoop for Windows 11.
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/): Yes.

# Often helpful information:

The content of the configuration file you use (if any): `fastfetch  c all`.

Output of `fastfetch -c ci.jsonc --format json`:
```json
{
  "type": "GPU",
  "result": [
    {
      "coreCount": null,
      "memory": {
        "dedicated": {
          "total": 1052770304,
          "used": null
        },
        "shared": {
          "total": 4026531840,
          "used": null
        }
      },
      "driver": "15.201.1301.0",
      "name": "AMD Radeon HD 7570M",
      "temperature": null,
      "type": "Integrated",
      "vendor": "AMD",
      "platformApi": "Direct3D 11.0",
      "frequency": null
    }
  ]
}
```

**Comment by FabioLolix** [comment]
I had this problem too on Arch Linux where the `AMD Radeon Pro WX 4100` was indicated as integrated but testing again with the latest build from git (2.16.0.r19.g63cdc47d) is fixed

**Comment by Null-Ping** [comment]
I will check again, and with Llinux later.

**Comment by Null-Ping** [comment]
Indeed, it doesn't happen on Linux.

**Comment by CarterLi** [comment]
Windows, Direct3D doesn't report the GPU type. I assume a GPU with VRAM smaller than 1 GiB is integrated.

Vulkan and OpenCL do. Test them with `--gpu-detection-method vulkan` and `--gpu-detection-method opencl` (requires the latest dev build)

GPU drivers (AMD and Intel, but not Nvidia) report it too. On Linux AMD and Intel GPU drivers are built into Linux kernel, so we can use it directly. On Windows it must be enabled with `--gpu-driver-specific`

**Comment by CarterLi** [comment]
I don't use AMD graphic cards and never tested the AMD driver. Fastfetch uses [AGS SDK](https://github.com/GPUOpen-LibrariesAndSDKs/AGS_SDK/). I don't know if it's bundled into AMD Windows driver package. If not, you must download it youself: https://github.com/GPUOpen-LibrariesAndSDKs/AGS_SDK/blob/master/ags_lib/lib/amd_ags_x64.dll

**Comment by Null-Ping** [comment]
PCI detection still thinks the GPU is integrated with the latest build, OpenGL doesn't know the type, OpenCL knows it is dGPU, but the name appears as `Turks` instead of `Radeon HD 7570M` when I use it, and the GPU is too old to support vulkan.
Here's more info:
```json
[
  {
    "type": "OS",
    "result": {
      "buildID": "",
      "codename": "",
      "id": "Windows 11",
      "idLike": "Windows",
      "name": "Windows",
      "prettyName": "Windows",
      "variant": "Pro",
      "variantID": "",
      "version": "11",
      "versionID": ""
    }
  },
  {
    "type": "GPU",
    "result": [
      {
        "coreCount": null,
        "memory": {
          "dedicated": {
            "total": 1052770304,
            "used": null
          },
          "shared": {
            "total": 4026531840,
            "used": null
          }
        },
        "driver": "15.201.1301.0",
        "name": "AMD Radeon HD 7570M",
        "temperature": null,
        "type": "Integrated",
        "vendor": "AMD",
        "platformApi": "Direct3D 11.0",
        "frequency": null,
        "deviceId": 40939
      }
    ]
  },
  {
    "type": "Vulkan",
    "error": "ffvkCreateInstance() failed: VK_ERROR_INCOMPATIBLE_DRIVER"
  },
  {
    "type": "OpenGL",
    "result": {
      "version": "4.5.13401 Compatibility Profile Context 15.201.1301.0",
      "renderer": "AMD Radeon HD 7570M",
      "vendor": "ATI Technologies Inc.",
      "slv": "4.40",
      "library": "WGL"
    }
  },
  {
    "type": "OpenCL",
    "result": {
      "version": "2.0 AMD-APP (1800.11)",
      "name": "AMD Accelerated Parallel Processing",
      "vendor": "Advanced Micro Devices, Inc.",
      "gpus": [
        {
          "type": "Discrete",
          "vendor": "AMD",
          "name": "Turks",
          "driver": "(VM)",
          "platformApi": "OpenCL 1.2 AMD-APP (1800.11)",
          "coreCount": 6,
          "frequency": 0.5,
          "memory": {
            "dedicated": {
              "total": 1073741824,
              "used": null
            },
            "shared": {
              "total": null,
              "used": null
            }
          },
          "deviceId": 3168419881552
        }
      ]
    }
  },
  {
    "type": "Version",
    "result": {
      "projectName": "fastfetch",
      "architecture": "x86_64",
      "version": "2.16.0",
      "versionTweak": "",
      "cmakeBuiltType": "RelWithDebInfo",
      "compileTime": "Jun 22 2024, 07:47:05",
      "compiler": "clang 18.1.6",
      "debugMode": false,
      "libc": "ucrt 14.0"
    }
  }
]
```

**Comment by CarterLi** [comment]
```json
  {
    "type": "GPU",
    "result": [
      {
        "coreCount": null,
        "memory": {
          "dedicated": {
            "total": 1052770304,
            "used": null
          },
          "shared": {
            "total": 4026531840,
            "used": null
          }
        },
        "driver": "15.201.1301.0",
        "name": "AMD Radeon HD 7570M",
        "temperature": null,
        "type": "Integrated",
        "vendor": "AMD",
        "platformApi": "Direct3D 11.0",
        "frequency": null,
        "deviceId": 40939
      }
    ]
  }
```

This result suggests that `--gpu-driver-specific` didn't work. Did you put `[amd_ags_x64.dll](https://github.com/GPUOpen-LibrariesAndSDKs/AGS_SDK/blob/master/ags_lib/lib/amd_ags_x64.dll)` in the same folder of fastfetch?

**Comment by Null-Ping** [comment]
Yes, I tried it and got same result, is anything more except for this file needed?

**Comment by CarterLi** [comment]
No. I don't know what happened. [The code](https://github.com/fastfetch-cli/fastfetch/blob/dev/src/detection/gpu/gpu_amd.c) is very simple. It would be appriciated if you can debug it.

**Comment by Null-Ping** [comment]
It looks like this check failed because revId was falsy (vendorId, deviceId and subSystemId were all truthy): https://github.com/fastfetch-cli/fastfetch/blob/88e075ad9dbb03bb4b5c8b8b756461441bc469db/src/detection/gpu/gpu_windows.c#L147
I'm not sure what this means, the check completes on my other, Intel integrated GPU.

**Comment by Null-Ping** [comment]
Oh, wait, my GPU DeviceID is `PCI\\VEN_1002&DEV_6841&SUBSYS_179D103C&REV_00`, so revId is actually 0, is this normal?

**Comment by Null-Ping** [comment]
There is one more problem; when I changed the check not to include revId, the liblary was loading, but apparently some race condition was occurring, since sometimes I got the right result (dedicated), sometimes I got the type as integrated, and sometimes fastfetch hanged an did not print the GPU module at all.
 I fixed it by removing this statement: https://github.com/fastfetch-cli/fastfetch/blob/88e075ad9dbb03bb4b5c8b8b756461441bc469db/src/detection/gpu/gpu_amd.c#L28
Apparently it was called to early and sometimes interfered with processing of the GPU information.
I'm not sure though when to call it correctly (and if revId check can be safely skipped), so I won't send you a PR.

Also, I **did** need to add the amd_ags_x64.dll file to fastfetch directory for it to work, my Windows doesn't have it by default, I'm not sure if it is the same for newer cards.

**Comment by CarterLi** [comment]
> Apparently it was called to early and sometimes interfered with processing of the GPU information.

Seems `ffagsDeInitialize` will free pointers allocated in `gpuInfo`. Just leak them.

**Comment by CarterLi** [comment]
> Also, I did need to add the amd_ags_x64.dll file to fastfetch directory for it to work, my Windows doesn't have it by default, I'm not sure if it is the same for newer cards.

Seems it's not included in the AMD GPU drivers. Can you check it in `Device Manager`?

![image](https://github.com/fastfetch-cli/fastfetch/assets/6134068/59175bf9-3587-415e-b282-6f80fca3954c)

This is what we use for NV cards. Please also check if `amdadlx64.dll` is available.

**Comment by Null-Ping** [comment]
1. The patches work, and GPU type is now detected correctly.
2. I don't have amd_adg_x64.dll in device manager, here's full list of files shown there for my GPU: [list.txt](https://github.com/user-attachments/files/15943304/list.txt).
3. Are those `(vendorId && deviceId && subSystemId)` checks useful, or can they cause simillar bug as with revId?
4. Now I noticed that my Laptop win Intel iGPU doesn't have ControlLib.dll, I downloaded it, but now this fails with error code`CTL_RESULT_ERROR_UNSUPPORTED_VERSION` (I still don't know why): https://github.com/fastfetch-cli/fastfetch/blob/a6c006221d21d8db370f1e29c1fbd27c65e888bb/src/detection/gpu/gpu_intel.c#L49-L55

**Comment by Null-Ping** [comment]
Maybe my ControlLib.dll version is wrong as I couldn't find an official download for it.

**Comment by CarterLi** [comment]
In my laptop `ControlLib.dll` is installed by Intel GPU driver.

**Comment by Null-Ping** [comment]
This was on Intel HD Graphics 620.
I also tested it on Intel UHD Graphics (from i3-1125g4), and this time it failed with code `CTL_RESULT_ERROR_PLATFORM_NOT_SUPPORTED`, that shouldn't ever occur according to the [documantation](https://intel.github.io/drivers.gpu.control-library/Control/api.html#ctlinit).

**Comment by CarterLi** [comment]
What if you copy the content of https://github.com/intel/drivers.gpu.control-library/blob/master/include/igcl_api.h and paste it into `src\detection\gpu\igcl.h`?

**Comment by Null-Ping** [comment]
Nothing changed, I also tried copying UHD Graphics dll and using it with but it HD Graphics 620 - nothing. looks like my 7th and 11th gen processors and iGPUs may be just unsupported: https://intel.github.io/drivers.gpu.control-library/prog.html#system-requirements.

**Comment by Null-Ping** [comment]
> In my laptop `ControlLib.dll` is installed by Intel GPU driver.

Does it work for you on any Intel processor from 11th gen or lower?

**Comment by CarterLi** [comment]
It works on my i7-12700H

**Comment by Null-Ping** [comment]
The igcl docs say it it supported on 12th gen +, so I guess it makes sense.

**Comment by Null-Ping** [comment]
Will you add amd_ags_x64.dll to fastfetch, or is there some good reason not to?
Anyway I think this can be closed now.

**Comment by CarterLi** [comment]
Done
