### ISSUE TITLE
[BUG] Incorrect number of flatpaks reported

### ISSUE THREAD

**Issue by elydpg** [fastfetch-cli/fastfetch#1035]
# General description of bug:

* What happened: Fastfetch reported the incorrect number of flatpaks
* What should happen: Fastfetch reports the correct number of flatpaks
* Fastfetch version used: 2.16.0 (x86_64)
* Did it work in an older version: Unsure
* Where did you get the binary: openSUSE tumbleweed main repo

# Often helpful information:

In my testing, it seems one more than the number of flatpaks reported by running `flatpak list`. Is it counting the number of lines in that output?

**Comment by CarterLi** [comment]
We count the directories in `/var/lib/flatpak/{app,runtime}`

Please paste the result of `ls -l /var/lib/flatpak/{app,runtime}` and `flatpak list` for investigation.

**Comment by elydpg** [comment]
I have installed more flatpaks; now it's reporting three more flatpaks than `flatpak list`. On the other hand, it agrees with the number of directories in `ls -l /var/lib/flatpak/{app,runtime}`. I'm not sure what the "real" number of flatpaks is but I
