### ISSUE TITLE
[FEAT] Truncate field in format

### ISSUE THREAD

**Issue by aarondill** [fastfetch-cli/fastfetch#1043]
## Wanted features:

I would like to be able to truncate format fields to arbitrary lengths.
For example, this *could* be implemented like this `format: "{1:10}"` which would display the first 10 characters of field 1.
Thoughts:
- Should this show an ellipsis (`...`)? 
- Should unnumbered fields be supported (`format: "{:10}"`)?

## Motivation:

I'd like to be able to shorten very long hardware names (in order to avoid wrapped lines in smaller terminals), such as Sound cards, Cameras, and Cpus.

For an example of this issue. This is shown without the logo, but when the logo is displayed and a terminal is tiled across half the screen, then the text in each line will wrap, interrupting the logo:
```shell
> fastfetch -s monitor:cpu:gpu:sound:camera -l none
Monitor (AUO20EC): 1366x768 px - 344x193 mm (15.53 inches, 100.91 ppi)
CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 (8) @ 4.20 GHz
GPU: Intel Iris Xe Graphics @ 1.30 GHz [Integrated]
Sound: Tiger Lake-LP Smart Sound Technology Audio Controller Speaker (13%)
Camera: HP TrueVision HD Camera: HP Tru - sRGB (640x360 px)
```
While modifying `format` strings can fix some of these issues, very long hardware names (like `Tiger Lake-LP Smart Sound Technology Audio Controller Speaker`) are impossible to fix without removing the information or writing a COMMAND module.

## Why this should be added to the format specs
- While these specific hardware items *could* have options or fields added to shorten their output, this is just bandaging the larger problem of very long fields.
- Adding this option to the format specs allows greater flexibility for user freedom. For example, I could truncate the name of playing songs in the `media` module.

**Comment by CarterLi** [comment]
```
$ ./fastfetch -l none -s command --command-text 'echo 1234567890' --command-format '{1}'
Command: 1234567890
$ ./fastfetch -l none -s command --command-text 'echo 1234567890' --command-format '{1:5}'
Command: 12345
$ ./fastfetch -l none -s command --command-text 'echo 1234567890' --command-format '{1:-5}'
Command: 12345…
$ ./fastfetch -l none -s command --command-text 'echo 1234567890' --command-format '{:5}'
Command: 12345
$ ./fastfetch -l none -s command --command-text 'echo 1234567890' --command-format '{:-5}'
Command: 12345…
$ ./fastfetch -l none -s command --command-text 'echo 1234567890' --command-format '{:0}'
Command:
$ ./fastfetch -l none -s command --command-text 'echo 1234567890' --command-format '{:}'
Command:
```

Please test the dev branch

**Comment by aarondill** [comment]
@CarterLi This works great! I just have one slight request that I didn't think about in the original issue.
Is it possible to make it trim whitespace *after* truncating the field?
This way, when using truncation, it looks a bit nicer when truncated on a space.

For example:
```shell

$ ./fastfetch -l none -s command --command-text 'echo 12345 67890' --command-format 'output({1})'
Command: output(12345 67890)
$ ./fastfetch -l none -s command --command-text 'echo 12345 67890' --command-format 'output({1:6})'
Command: output(12345)
$ ./fastfetch -l none -s command --command-text 'echo 12345 67890' --command-format 'output({1:-6})'
Command: output(12345…)
$ ./fastfetch -l none -s command --command-text 'echo 12345 67890' --command-format 'output({:6})'
Command: output(12345)
$ ./fastfetch -l none -s command --command-text 'echo 12345 67890' --command-format 'output({:-6})'
Command: output(12345…)
$ ./fastfetch -l none -s command --command-text 'echo 12345 67890' --command-format 'output({:0})'
Command: output()
$ ./fastfetch -l none -s command --command-text 'echo 12345 67890' --command-format 'output({:})'
Command: output()
```

I don't see any usecase in which someone would want the field to *sometimes* end in a space, depending on where it truncated.

**Comment by CarterLi** [comment]
White spaces can be used for aligning texts

**Comment by aarondill** [comment]
@CarterLi wouldn't one want these to be hard coded into the format string then? rather than generated from the truncated fields?

**Comment by CarterLi** [comment]
https://github.com/fastfetch-cli/fastfetch/commit/4370c0944bd2922d7d1f2502deb9400eab5eaddd
