### ISSUE TITLE
[FEAT] Supports for npm global packages

### ISSUE THREAD

**Issue by nolddor** [fastfetch-cli/fastfetch#1048]
## Wanted features:
https://nodejs.org/en/learn/getting-started/an-introduction-to-the-npm-package-manager
> **npm** is the standard package manager for Node.js.

Would be great if `packages` module from **fastfetch** add support for global packages installed system wide using de facto node.js package manager.

## Motivation:
Same as `apt` or `snap` I personally use `npm` eventually to add system-wide packages. By running the `npm install <package> -g` command. As for now, I have no way to check how many npm global packages there are on my system.

Current workaround is to use the `command` **fastfetch** module as per sample below:
```
    {
      "type": "command",
      "text": "ls -l \"$(npm root -g)\" | grep -c ^d |  awk '{print $1 \" (npm)\"}'",
      "key": "Packages"
   }
```

**Comment by CarterLi** [comment]
Currently we have no plan for programming language specific package managers. I think the command module is enough for your personal use.

> de facto node.js package manager

There are also `yarn global` and `pnpm -g`

**Comment by nolddor** [comment]
Sounds fair. Thx for your time checking this request!
