### ISSUE TITLE
[Request for help] Test fastfetch on real Windows On Arm (X Elite?)

### ISSUE THREAD

**Issue by CarterLi** [fastfetch-cli/fastfetch#1051]
Does WOA have SMBIOS?

**Comment by CarterLi** [comment]
Everything seems fine.

I'd like to have `fastfetch -c all --format json`. Be sure remove your location information (Public IP, Weather)

**Comment by jimkoutso2008** [comment]
Sure here you go.
txt file has the json output
[test.txt](https://github.com/user-attachments/files/16087606/test.txt)


Will also throw in a screenshot too
![image](https://github.com/fastfetch-cli/fastfetch/assets/82086687/0b8ce834-4cb9-4434-93a3-19b05190ab0d)

**Comment by Ryuushen** [comment]
Unrelated but is it possible to use custom logo image for windows fastfetch by anychance?

**Comment by CarterLi** [comment]
Please open a discussion. @Ryuushen

**Comment by wezm** [comment]
Here's the output from an Snapdragon X Elite machine (Lenovo Yoga Slim 7x).

![image](https://github.com/user-attachments/assets/5c4be912-cdcc-4f72-8221-a49d89c7107b)

Here's the JSON output: https://files.wezm.net/fastfetch.json

**Comment by CarterLi** [comment]
Thanks @wezm, really helpful. Seems everything is ok for now.

I recently made [some changes to GPU detection](https://github.com/fastfetch-cli/fastfetch/commit/0354fd5d9de1d70778cbd3e16778511ec4f5d372) that may break WOA devices. Can you help me to test the dev build? I need only the JSON output. https://github.com/fastfetch-cli/fastfetch/actions/runs/10217217571/artifacts/1769548828 (it's an x64 binary but should not be problematic)

**Comment by wezm** [comment]
Here you go: https://files.wezm.net/fastfetch-0354fd5.json

**Comment by CarterLi** [comment]
Seems fine too. Thanks @wezm
