### ISSUE TITLE
[BUG] `--pipe` option does not disable icon

### ISSUE THREAD

**Issue by scarf005** [fastfetch-cli/fastfetch#1058]
Be sure to read the [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

# General description of bug:

* What happened: `fastfetch --pipe` shows icon
* What should happen: it should not display icon as seen in `--help` menu
```
$ fastfetch --help
# ...
Display options:
  -s, --structure <structure>                Set the structure of the fetch
      --stat <?bool>                         Show time usage (in ms) for individual modules
      --pipe <?bool>                         Disable logo and all escape sequences
```

* Fastfetch version used: fastfetch 2.16.0 (x86_64)
* Did it work in an older version: doesn't know
* Where did you get the binary: home-manager (nixpkgs-unstable channel)
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? haven't checked

# Often helpful information:

Screenshot:

![image](https://github.com/fastfetch-cli/fastfetch/assets/54838975/61c56a52-b303-4469-a79d-f0a9263783db)

Output of `fastfetch -c ci.jsonc --format json`:

[output.json](https://github.com/user-attachments/files/16039576/output.json)

Output of `fastfetch --list-features`:
```
threads
vulkan
wayland
xcb-randr
xcb
xrandr
x11
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
sqlite3
egl
glx
opencl
libpulse
libnm
libddcutil
Proprietary GPU driver API
System yyjson
linux/videodev2
linux/wireless
```

**Comment by CarterLi** [comment]
The behavior was changed but I forgot to update the help message.

**Comment by scarf005** [comment]
would there be any option to disable icon as well? it helps to be terse when uploading system info for troubleshooting.

**Comment by CarterLi** [comment]
`-l none`

**Comment by scarf005** [comment]
thanks. it doesn't seem to be documented tho, could i open a PR?
```
Logo options:
  -l, --logo <logo>                          Set the logo source
```
