### ISSUE TITLE
[BUG] archlinux package is built unoptimized

### ISSUE THREAD

**Issue by CarterLi** [fastfetch-cli/fastfetch#1064]
@Antiz96 

> -DCMAKE_BUILD_TYPE='None'

https://gitlab.archlinux.org/archlinux/packaging/packages/fastfetch/-/blob/main/PKGBUILD?ref_type=heads#L57

As far as I know, `None` is not a standard `CMAKE_BUILD_TYPE` option. I can't find the build log of arch packages. I tested the option locally and fastfetch was built without `-Ox` and `-DNDEBUG` specified, therefore, unoptimized.

Is there any reason for that? If not, I suggest using `-DCMAKE_BUILD_TYPE=RelWithDebInfo` ([which is the default option if not specified](https://github.com/fastfetch-cli/fastfetch/blob/dev/CMakeLists.txt#L99-L101)), so core dump will be generated with debug info if fastfetch crashes.

**Comment by Antiz96** [comment]
Hey,

`-DCMAKE_BUILD_TYPE='None'` is part of our CMake packaging guidelines, we have some explanations about why we use that [here](https://wiki.archlinux.org/title/CMake_package_guidelines#Fixing_the_automatic_optimization_flag_override) (according to it, `None` is actually the default CMake build type).

When it comes to `-Ox`, the current [default on Arch side is `-O2`](https://gitlab.archlinux.org/archlinux/packaging/packages/pacman/-/blob/main/makepkg.conf?ref_type=heads#L43). As for debug info, Arch provides separate [`-debug` packages](https://archlinux.org/news/debug-packages-and-debuginfod/) that one can [install](https://wiki.archlinux.org/title/Debugging/Getting_traces#Installing_debug_packages) to generate core dump with debug info. 

You can check the build logs for fastfecth [here](https://reproducible.archlinux.org/api/v0/builds/640036/log)

Let me know if that covers your concerns or not :)

**Comment by CarterLi** [comment]
`/usr/bin/fastfetch --version` prints `fastfetch 2.17.1-debug (x86_64)`

[Which suggests `NDEBUG` is not defined](https://github.com/fastfetch-cli/fastfetch/blob/dev/src/detection/version/version.c#L57-L61)

> You can check the build logs for fastfecth [here](https://reproducible.archlinux.org/api/v0/builds/640036/log) (CTRL + F on "Starting build()" 😉).

Well you can only see `Building C object CMakeFiles/libfastfetch.dir/*` but no actual gcc arguments

**Comment by Antiz96** [comment]
> `/usr/bin/fastfetch --version` prints `fastfetch 2.17.1-debug (x86_64)`
> 
> [Which suggests `NDEBUG` is not defined](https://github.com/fastfetch-cli/fastfetch/blob/dev/src/detection/version/version.c#L57-L61)

Indeed, sorry that I missed that. I made the [switch](https://gitlab.archlinux.org/archlinux/packaging/packages/fastfetch/-/commit/179a043357e89256f5bbc759a441102750031a85) to `-DCMAKE_BUILD_TYPE=RelWithDebInfo`. I guess in `fastfetch`'s specific case it makes sense using that over `None`.

**Comment by CarterLi** [comment]
Thanks
