### ISSUE TITLE
[BUG] Typo in the Wiki.

### ISSUE THREAD

**Issue by Code-Dreams** [fastfetch-cli/fastfetch#1067]
There is a typo in the Wiki logo options page. 

In the "Kitty Direct" section, second bullet point, it says, "This is by far the fastest image protocol because the image content is loaded **_dirently by terminal_**..."

I'm guessing this should be, "...loaded **_directly by the_** terminal..."

Thank you

**Comment by CarterLi** [comment]
Fixed
