### ISSUE TITLE
[BUG] Cinnamon version not detected properly

### ISSUE THREAD

**Issue by AxeldeWater** [fastfetch-cli/fastfetch#1068]
I have Cinnamon 6.0.4 installed on Linux Mint 21.3. Fastfetch does not show "Cinnamon 6.0.4", but "Cinnamon 5.8.4". Using the 2.17.1 version of Fastfetch.

**Comment by AxeldeWater** [comment]
Issue persists after update to 2.17.2. Fastfetch still showing Cinnamon 5.8.4. Could there be a mistake on my part? I know for sure I'm using Cinnamon 6.0.4.

**Comment by CarterLi** [comment]
echo $CINNAMON_VERSION

**Comment by AxeldeWater** [comment]
No response to that command

**Comment by CarterLi** [comment]
cinnamon --version

**Comment by AxeldeWater** [comment]
[CENSORED]       1256    1106  0 00:34 ?        00:00:00 cinnamon-session --session cinnamon
[CENSORED]       1462    1256  0 00:34 ?        00:00:00 cinnamon-launcher
[CENSORED]       1502    1462  6 00:34 ?        00:01:46 cinnamon --replace
[CENSORED]       1568    1256  0 00:34 ?        00:00:00 cinnamon-killer-daemon
[CENSORED]       6938    6434  0 01:02 pts/0    00:00:00 grep --color=auto cinnamon
Cinnamon 6.0.4

**Comment by AxeldeWater** [comment]
I'll add that neofetch detects it correctly

**Comment by CarterLi** [comment]
cat /usr/share/applications/cinnamon.desktop

**Comment by AxeldeWater** [comment]
cat: /usr/local/share/applications/cinnamon.desktop: No such file or directory
[Desktop Entry]
Type=Application
Name=Cinnamon
Comment=Window management and application launching
Exec=/usr/bin/cinnamon-launcher
X-GNOME-Bugzilla-Bugzilla=GNOME
X-GNOME-Bugzilla-Product=cinnamon
X-GNOME-Bugzilla-Component=general
X-GNOME-Bugzilla-Version=6.0.4
Categories=GNOME;GTK;System;Core;
OnlyShowIn=X-Cinnamon;
NoDisplay=true
X-GNOME-Autostart-Phase=WindowManager
X-GNOME-Provides=panel;windowmanager;
X-GNOME-Autostart-Notify=true
X-GNOME-AutoRestart=false

**Comment by CarterLi** [comment]
The string 5.8.4 cannot come from nowhere. I guess you used to install 5.8.4 but did not unimtall it entirely

**Comment by AxeldeWater** [comment]
Well, when I initially started using Mint, it was Mint 21.2, with indeed cinnamon 5.8.4. Not long after, I updated the system to Mint 21.3 with Cinnamon 6, now 6.0.4. The thing is that fastfetch was installed only recently, so I would have no idea where fastfetch would get the old information from.

**Comment by AxeldeWater** [comment]
It's also weird that neofetch does not have this same problem even though the project has not been changed since I installed it. What's the difference? Where does each get the cinnamon version from?

**Comment by CarterLi** [comment]
cat ～/.local/share/applications/cinnamon.desktop

**Comment by AxeldeWater** [comment]
[Desktop Entry]
Type=Application
Name=Cinnamon
Comment=Window management and application launching
Exec=/usr/bin/cinnamon-launcher
X-GNOME-Bugzilla-Bugzilla=GNOME
X-GNOME-Bugzilla-Product=cinnamon
X-GNOME-Bugzilla-Component=general
X-GNOME-Bugzilla-Version=5.8.4
Categories=GNOME;GTK;System;Core;
OnlyShowIn=GNOME;
NoDisplay=false
X-GNOME-Autostart-Phase=WindowManager
X-GNOME-Provides=panel;windowmanager;
X-GNOME-Autostart-Notify=true
X-GNOME-AutoRestart=false
Terminal=false
PrefersNonDefaultGPU=true
Icon=cinnamon-panel-launcher


This explains a lot

**Comment by CarterLi** [comment]
Just remove this file

**Comment by AxeldeWater** [comment]
This fixed it indeed. 

Why was fastfetch pulling the version info from this file if it is/could be outdated?

**Comment by CarterLi** [comment]
Everything can be outdated. Fastfetch prefer ~/.local rather than /usr because it is set by user and should override the global one
