### ISSUE TITLE
[LOGO] 

### ISSUE THREAD

**Issue by LeGamermc** [fastfetch-cli/fastfetch#1070]
Tip: A logo can be displayed by fastfetch without getting into fastfetch's official repo. For highly customized logo for personal use, it's recommended to keep it locally. Please refer to https://github.com/fastfetch-cli/fastfetch/wiki/Migrate-Neofetch-Logo-To-Fastfetch

# OS
```
PRETTY_NAME="Opak 1.0 (Purple)"
NAME="Opak"
VERSION_ID="1.0"
VERSION="1.0 (purple)"
VERSION_CODENAME=purple
ID=opak
```

# Ascii
```            .......           
       .':ldkOOOOkxo:,.       
     .:d0KKXXXXXXXXXXKkl,     
   .;xOOO0000KKKKXXXXXXX0l.   
  .cxxxkkkkOOO0000KKKKXXXXx'  
  ;ool;,,,,;coxkOOOO0000KKKd. 
 .clc'.........:oxkkkkOOOO0O, 
 .ccc:ccclc:,....,:oddxxdxkO; 
  cllllccccccc;'........'lxx. 
  'ooooolllllccc:;,''',,coo,  
   ,ddddooooollllllccccccl'   
     cxxxdddddooooollllc;     
       ,dxxxxxddddddol.       
           .';::,.            
                                                      
```

**Comment by LeGamermc** [comment]
there is for now none

**Comment by LeGamermc** [comment]
> Colors?

so yea as said on top there is no color for now but i plan on addid some later (its juste a  pain the logo is like a gradient and is very hard to remake like i did for kernelos) tho can it be added to the fastfetch please ^^

**Comment by CarterLi** [comment]
FYI: this logo was dropped due to lacking of logo colors and no distro repo and official website available.
