### ISSUE TITLE
[FEAT] Display the actual number of installed Flatpaks

### ISSUE THREAD

**Issue by loxoron218** [fastfetch-cli/fastfetch#1085]
## Wanted features:
Display again all Flatpak packages (and not only "apps") by default.

## Motivation:
In the version 2.17.2 the way Flatpak packages are counted and displayed on fastfetch was changed.

I guess that can be helpfull for a some people. In my opinion though, the way of counting "regular" packages (debs, rpm, etc) and flatpaks should be consistent. Now, the first one counts ALL packages, not only "apps" but also libraries and other dependencies, while the former one only shows some of the actually installed packages.

## Suggestions
Would it be possible to go back to the old way of counting the packages? Or at least make it easy to change it either via command or the config file?

Greetings and thanks for your amazing job!

**Comment by ekitru** [comment]
I have similar issue on Mint Cinnamon 22.

neofetch ->  Packages: 2226 (dpkg), 11 (flatpak)
fastfetch ->  Packages: 2223 (dpkg), 2 (flatpak)

**Comment by CarterLi** [comment]
You should test the dev build
