### ISSUE TITLE
Install issue - Ubuntu 20.04 

### ISSUE THREAD

**Issue by PaPaTheGMan** [fastfetch-cli/fastfetch#1088]
Be sure to read the [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

# General description of bug:

* What happened: Install failed with:
    The following packages have unmet dependencies:
    fastfetch : Depends: libc6 (>= 2.35) but 2.31-0ubuntu9.16 is to be installed
    E: Unable to correct problems, you have held broken packages.

* What should happen: Install should proceed smoothly

* Fastfetch version used: 2.18.1

* Did it work in an older version: No

* Where did you get the binary: GitHub release

* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Yes

**Comment by CarterLi** [comment]
What file did you download?

**Comment by PaPaTheGMan** [comment]
https://github.com/fastfetch-cli/fastfetch/releases/download/2.18.1/fastfetch-linux-aarch64.deb

**Comment by CarterLi** [comment]
The aarch64 version was built.on Ubuntu 22.04. You should download the arm64 version.

**Comment by PaPaTheGMan** [comment]
Sorry to be a pest, but can you give me a link?  I do not see 'arm64' in list of 2.18.1 assets.

You may also want to change the Installation instructions as they say:
"Debian / Ubuntu: Download fastfetch-linux-<proper architecture>.deb from Github release page and double-click it (for Ubuntu 20.04 or newer and Debian 11 or newer)."

My system is: Ubuntu 20.04.6 LTS aarch64

Thanks.

**Comment by CarterLi** [comment]
I meant amd64. Sorry

**Comment by CarterLi** [comment]
That suggested that your server is not supported.

**Comment by PaPaTheGMan** [comment]
Bummer, any plans to support it?

It's Ubuntu 20.04.6 LTS on aarch64 architecture.

**Comment by PaPaTheGMan** [comment]
It's ARM64.  Here's the output of a lscpu inquiry:

Architecture:                 aarch64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:                    Little Endian
CPU(s):                            4
On-line CPU(s) list:    0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):                       1
Vendor ID:                      ARM
Model:                              4
Model name:                 Cortex-A53
Stepping:                        r0p4
CPU max MHz:             1248.0000
CPU min MHz:              480.0000
BogoMIPS:                     48.00
Flags:                                fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid

lsb_release shows:
Distributor ID: Ubuntu
Description:     Ubuntu 20.04.6 LTS
Release:             20.04
Codename:       focal

I hope this helps.

**Comment by CarterLi** [comment]
You build it yourself

**Comment by PaPaTheGMan** [comment]
Are you asking a question?  No, I didn't build this image.  It's a stock image for the NanoPi-NEO2-Black board from Friendly Elec.  Web home - https://www.friendlyelec.com<https://www.friendlyelec.com/>.  Wiki for this board - https://wiki.friendlyelec.com/wiki/index.php/NanoPi_NEO2_Black

**Comment by PaPaTheGMan** [comment]
It appears this is fixed in 2.21.0

**Comment by H-e-l-l-oW-o-r-l-d** [comment]
The last version that can be used out of the box for old aarch64 systems is probably [2.36.0](https://github.com/fastfetch-cli/fastfetch/releases/tag/2.36.0), because [2.36.1](https://github.com/fastfetch-cli/fastfetch/releases/tag/2.36.1) used the native arm64 runner of Github Action, Linux aarch64 binary was built with Ubuntu 22.04 (Glibc 2.35, Debian 12).
