### ISSUE TITLE
[BUG]  ffProcessGetInfoLinux does not read /proc/PID/cmdline correctly

### ISSUE THREAD

**Issue by Dariqq** [fastfetch-cli/fastfetch#1091]
Hi,

The `ffProcessGetInfoLinux` function reads the "/proc/PID/cmdline" [here](https://github.com/fastfetch-cli/fastfetch/blob/beabaa90f13e7b95c7f6facab2dfc0a5766d6f67/src/common/processing_linux.c#L128) but with some print statements afterwards only the first section of `cmdline` is being read. I think the problem are the NULL characters in between arguments.

As an example `fastfetch -S initsystem --format json`
```json
[
  {
    "type": "InitSystem",
    "result": {
      "name": "systemd",
      "exe": "/usr/lib/systemd/systemd",
      "version": "255.8-1.fc40",
      "pid": 1
    }
  }
]
```

while the actual content of my `/proc/1/cmdline` is

```
/usr/lib/systemd/systemd\0--switched-root\0--system\0--deserialize=40\0rhgb\0
```

Is this intended? If so it has the awkward effect that if the process is a script with e.g. `#!/bin/sh`  exe will only contain `/bin/sh` instead of the thing being executed (which is how i found this).

~~Problem seems to be within `readUntilEOF`  but i have no idea why null characters are a problem for `read`.~~
Edit: Seems to read correctly but the null characters in between termiantes `buffer->chars` early

**Comment by CarterLi** [comment]
> Is this intended?

Yes

> If so it has the awkward effect that if the process is a script with e.g. `#!/bin/sh` exe will only contain `/bin/sh` instead of the thing being executed

In this case, we expect a user runs the script with `my_script` instead of `/bin/sh /path/to/my_script`. If so, `my_script` will be the first part of `cmdline`, that's what we want

> which is how i found this

What's your use case?

**Comment by CarterLi** [comment]
Then you have to make python a special case and use the 2rd argument, like what I have done for macOS and FreeBSD
