### ISSUE TITLE
[BUG] Broken on Windows 7

### ISSUE THREAD

**Issue by bt4ibwem8** [fastfetch-cli/fastfetch#1104]
* Fastfetch version used: 2.18.1
* Did it work in an older version: no
* Where did you get the binary: Scoop

Screenshot:
![image](https://github.com/user-attachments/assets/f6abc3b7-5efb-44a1-8fe8-cf0da8d2c452)

Output of `fastfetch -c ci.jsonc --format json`:
TEST
]10;?\

Output of `fastfetch --list-features`:
threads
vulkan
zlib
opencl

Neofetch shows the information correctly.

**Comment by CarterLi** [comment]
We don't support conhost on Windows 7. You have to use either [ConEmu](https://conemu.github.io/en/Downloads.html) or mintty (where you run neofetch)

**Comment by CarterLi** [comment]
Or try `fastfetch --logo-position top --pipe`

**Comment by bt4ibwem8** [comment]
`fastfetch --logo-position top --pipe` works better but not perfect. Anyway i tried now **Cmder** (based on ConEmu) and it works fine...
