### ISSUE TITLE
[BUG] SSHD physical disk detected as SSD.

### ISSUE THREAD

**Issue by ghost** [fastfetch-cli/fastfetch#1106]
# General description of bug:

* What happened: SSHD (solid state hybrid drive) physical disk was detected as SSD.
* What should happen: It should be detected as SSD.
* Fastfetch version used: Latest dev.
* Did it work in an older version: No.
* Where did you get the binary: GitHub Actions Windows11 (64).

# Often helpful information:

Screenshot **(The different name in fastfetch is probably because the disk is connected with SATA - USB adapter from Samsung [the disk is a normal 2.5'' SATA drive.]):**

![CrystalDiskInfo](https://github.com/user-attachments/assets/13e90708-b715-4f5e-aa2b-1549092ac664)

Output of `fastfetch --format json`:
```json
"name": "Samsung Portable SSD T1", <- should probably be TOSHIBA MQ02ABD100H
"devPath": "\\\\.\\PhysicalDrive1",
"interconnect": "USB", <- should probably be USB/SATA or something similar
"kind": "SSD", <- should be SSHD
"size": 1000204886016,
"serial": "53212121AA0987654321",
"removable": false, <- should probably be true
"readOnly": false,
"revision": "0",
"temperature": null
```

Output of `fastfetch --list-features`:
```txt
threads
vulkan
zlib
opencl
```

**Comment by CarterLi** [comment]
All these information is reported by Windows.

> should probably be TOSHIBA MQ02ABD100H
> should be SSHD

If you connect it via a USB adapter, you can only get the adapter info. Unless you  connect the adapter via USB4 / Thunderbolt

> should probably be true

Reported by Windows too. The logic behind this info is unknown. Windows can correctly report USB flash drive as removable, but not hard drive.

**Comment by Null-Ping** [comment]
So how does crystal disk info get the correct name, interface, and rotation speed?

**Comment by CarterLi** [comment]
You should be able to find these information in Windows Explorer.

CrystalDiskInfo may use a proprietary driver. I dont know.

**Comment by Null-Ping** [comment]
Actually CrystalDiskInfo is open source.

**Comment by CarterLi** [comment]
PR welcome

**Comment by CarterLi** [comment]
Why delete your account?
