### ISSUE TITLE
[BUG] Wrong date on Raspbian 10

### ISSUE THREAD

**Issue by XhmikosR** [fastfetch-cli/fastfetch#1108]
Be sure to read the [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

# General description of bug:

* What happened: The date reported is wrong `2010-04-05 03:19:20`
* What should happen: The date should be correct
* Fastfetch version used: 2.18.1
* Did it work in an older version: Unsure
* Where did you get the binary: GitHub release
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)?

# Often helpful information:

Screenshot:
![2024-07-19_17-12-36](https://github.com/user-attachments/assets/77319e87-abf9-4ce0-9048-e4fed6adb6ad)

The content of the configuration file you use (if any):
```
// Paste here
```

Output of `fastfetch -c ci.jsonc --format json`:

```
// Paste here
```

Output of `fastfetch --list-features`:
```
// Paste here
```

## If fastfatch crashed or froze

Paste the stacktrace here. You may get it with:

```shell
# You may need Ctrl+C to stop the process if it freezes
gdb -q -ex 'set confirm off' -ex run -ex 'bt full' -ex quit --args /path/to/fastfetch
```

If you are able to identify which module crashed, the strace can be helpful too

```shell
strace /path/to/fastfetch --multithreading false -s {MODULE} --pipe
```

If you cannot do the instructions above, please upload the core dump file:

## If fastfetch is slow

Use `time fastfetch --stat` to show time usage for each module.

## If an image or logo didn't show 

* The image protocol you used: 
* The terminal you used: 
* Upload the image file here, or paste the image URL: 
* Does it work with `--logo-width {WIDTH} --logo-height {HEIGHT}`? 

## If fastfetch behaves incorrectly on shell startup

* The bug is reproducible with a clean shell configuration (i.e. `fastfetch` is the only line in `.zshrc` or `~/.config/fish/config.fish`): 
* Does `sleep 1` before running `fastfetch` work? 

---

Is there something else that might help?

**Comment by CarterLi** [comment]
Please try the dev build

**Comment by XhmikosR** [comment]
Works fine now, thanks for the quick fix!
