### ISSUE TITLE
[BUG] Wrong WM/DE detection in TTY session

### ISSUE THREAD

**Issue by Dariqq** [fastfetch-cli/fastfetch#1110]
Hi,

# General description of bug:

* What happened:

Connected to my laptop over ssh and noticed that the wm detection is wrong:

```
fastfetch -S LM:WM --format json
[
  {
    "type": "LM",
    "result": {
      "service": "sshd",
      "type": "TTY",
      "version": "9.8p1"
    }
  },
  {
    "type": "WM",
    "result": {
      "processName": "sway",
      "prettyName": "Sway",
      "protocolName": "X11",
      "pluginName": ""
    }
  }
]
```
It seems to detect sway from the other session and classify it as X11 which is incorrect. When I run from the laptop from within sway things seem correct.

```
fastfetch -S LM:WM --format json
[
  {
    "type": "LM",
    "result": {
      "service": "greetd",
      "type": "Wayland",
      "version": ""
    }
  },
  {
    "type": "WM",
    "result": {
      "processName": "sway",
      "prettyName": "Sway",
      "protocolName": "Wayland",
      "pluginName": ""
    }
  }
]
```

When I sshed into a machine with gnome fastfetch found gnome-shell/mutter and where something it is x11 in the ssh session and wayland normaly.

* What should happen:  I would expect either one of
   - Detect Sway correctly as Wayland in this case
   - Dont detect WM/DE from another session
* Fastfetch version used: 2.19.0
* Did it work in an older version: idk
* Where did you get the binary: Build from source directly.
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Yes

**Comment by CarterLi** [comment]
> `ffdsConnectXcbRandr` : Sets to X11
> `ffdsConnectXrandr` : Sets to nothing.
> `ffdsConnectXcb` : Sets to X11.
> `ffdsConnectXlib` : Sets to nothing.

They all set ds->wmProtocolName to X11, don't they?

**Comment by CarterLi** [comment]
Fastfetch failed to connect wayland server, and couldn't find any environment variables about wayland, so fastfetch thought it was not wayland. However fastfetch connected x11 server successfully somehow.

**Comment by CarterLi** [comment]
If we can detect the x11 server is actually xwayland, we can fix this issue easily.

**Comment by CarterLi** [comment]
Please test the dev build
