### ISSUE TITLE
x86 or 64 ?

### ISSUE THREAD

**Issue by wincmd64** [fastfetch-cli/fastfetch#1116]
"type": "Kernel",
    "result": {
      "architecture": "x86_64",

I need to know for sure - its x86 or 64.

**Comment by CarterLi** [comment]
https://en.wikipedia.org/wiki/X86-64

**Comment by wincmd64** [comment]
How can I display information in one line from two different modules?

  {
    "type": "os",
    "format": "{id} {variant}"
  },
  {
    "type": "kernel",
    "format": "{5}"
  },

**Comment by CarterLi** [comment]
You can't
