### ISSUE TITLE
[FEAT] A new line detecting virtualization

### ISSUE THREAD

**Issue by GeekCornerGH** [fastfetch-cli/fastfetch#1117]
Be sure to read [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

## Wanted features:

To the best of my knowledge, most systems are running `systemd`.
This packages comes with a command called `systemd-detect-virt`, returning virtualization type. For example: `kvm`, `lxc`, `none` (dedicated), and many more (below's a list of the supported values).

<details>
<summary>List of possible values</summary>

```
none
kvm
amazon
qemu
bochs
xen
uml
vmware
oracle
microsoft
zvm
parallels
bhyve
qnx
acrn
powervm
vm-other
systemd-nspawn
lxc-libvirt
lxc
openvz
docker
podman
rkt
wsl
proot
pouch
container-other
```
</details>

## Motivation:
We're listing many things here, but it'd be nice to show the virtualization type too.

**Comment by CarterLi** [comment]
Please try

```jsonc
{
  "type": "command",
  "text": "systemd-detect-virt",
  "key": "Virtualization"
}
```

See https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#q-i-want-feature-a--b--c-will-fastfetch-support-it

**Comment by CarterLi** [comment]
IIRC I guess `host` module should work in most cases.

**Comment by GeekCornerGH** [comment]
> Please try
> 
> ```js
> {
>   "type": "command",
>   "text": "systemd-detect-virt",
>   "key": "Virtualization"
> }
> ```
> 
> See https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#q-i-want-feature-a--b--c-will-fastfetch-support-it

It indeed did the trick sorry for wasting your time
