### ISSUE TITLE
DateTime module: get Date only

### ISSUE THREAD

**Issue by wincmd64** [fastfetch-cli/fastfetch#1118]
Is it posible?

**Comment by CarterLi** [comment]
https://github.com/fastfetch-cli/fastfetch/blob/dev/presets/examples/4.jsonc#L19-L23

**Comment by wincmd64** [comment]
Maybe implement this in a more user friendly way?

d Day of the month as digits without leading zeros for single-digit days. 
dd Day of the month as digits with leading zeros for single-digit days. 
ddd Abbreviated day of the week, for example, «Mon». 
dddd Day of the week, for example, «Monday». 
M Month as digits without leading zeros for single-digit months. 
MM Month as digits with leading zeros for single-digit months. 
MMM Abbreviated month, for example, «Nov». 
MMMM Month, for example, «November» for English, and «Noviembre» for Spanish. 
y Year represented only by the last digit. 
yy Year represented only by the last two digits. A leading zero is added for single-digit years. 
yyyy Year represented by a full four or five digits, depending on the calendar used.

**Comment by CarterLi** [comment]
No. The current syntax was designed to be consistant to other modules. If you don't like magic numbers, you can also use `{year}-{month}-{day-in-month}`

You can find all placeholders supported by `DateTime` module with `fastfetch -h datetime-format`

**Comment by wincmd64** [comment]
day like 'friday' can be displayed?

**Comment by CarterLi** [comment]
{weekday}
