### ISSUE TITLE
[BUG] Printing GPU frequency on M1 MacBook Air causes segfault

### ISSUE THREAD

**Issue by BionicBison05** [fastfetch-cli/fastfetch#1122]
Be sure to read the [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

# General description of bug:

* What happened: Segfault when attempting to print GPU frequency
* What should happen: GPU frequency prints without crashing
* Fastfetch version used: 2.19.1 
* Did it work in an older version: Yes, 2.18.1 
* Where did you get the binary: GitHub release 
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Yes

Additional info: Building from source with no changes resulted in the bug occurring, but after commenting out the call to the `detectFrequency` function in `gpu_apple.c`, the bug stopped occurring, so it is likely to do with that function specifically. Also of note, I was not able to reproduce it on an M1 Max Mac Studio or an M3 MacBook Air, just an M1 MacBook Air.

# Often helpful information:

Screenshot:

<img width="645" alt="Screenshot" src="https://github.com/user-attachments/assets/ccc3d8cd-5664-4481-876a-fb423693d69c">

Output of `fastfetch -c ci.jsonc --format json`:

```
[1]    6380 segmentation fault  fastfetch -c ci.jsonc --format json
```

Output of `fastfetch --list-features`:
```
threads
vulkan
imagemagick7
chafa
zlib
sqlite3
```

## If fastfatch crashed or froze

If you cannot do the instructions above, please upload the core dump file:
https://drive.proton.me/urls/295CGSRPA4#VTvKXEv70Qc4

**Comment by CarterLi** [comment]
Please test the dev build

**Comment by BionicBison05** [comment]
Works great, thanks! Out of curiosity, does M1 simply not make a frequency available to report?

**Comment by CarterLi** [comment]
Seems yes. It doesn't have the property containing GPU frequency info.
