### ISSUE TITLE
[BUG] Wayland WM displayed as wl-restart

### ISSUE THREAD

**Issue by ErrorNoInternet** [fastfetch-cli/fastfetch#1135]
# General description of bug:

* What happened: I run Hyprland with [wl-restart](https://github.com/Ferdi265/wl-restart) (`wl-restart Hyprland`) so that whenever Hyprland crashes, it gets automatically restarted. However, my WM is now listed as `wl-restart` instead of `Hyprland`. wl-restart is the one that creates the Wayland socket though.

![image](https://github.com/user-attachments/assets/d80cbb1a-88e3-4854-8d04-43b1873ea12c)

* What should happen: WM listed as `Hyprland`
* Fastfetch version used: fastfetch 2.17.2 (x86_64)
* Did it work in an older version: no
* Where did you get the binary: Fedora repositories
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? yes

# Often helpful information:

Screenshot:
![image](https://github.com/user-attachments/assets/529b29f7-9363-4b09-87f1-471aa3001f84)

Output of `fastfetch -s wm --format json`:

```
[
  {
    "type": "WM",
    "result": {
      "processName": "wl-restart",
      "prettyName": "wl-restart",
      "protocolName": "Wayland",
      "pluginName": ""
    }
  }
]
```

Output of `fastfetch --list-features`:
```
threads
vulkan
wayland
xcb-randr
xcb
xrandr
x11
drm
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
sqlite3
rpm
egl
glx
osmesa
opencl
libpulse
libnm
libddcutil
System yyjson
linux/videodev2
linux/wireless
```

**Comment by CarterLi** [comment]
What does `xprop -id (xprop -root -notype _NET_SUPPORTING_WM_CHECK | awk '{print $5}') -notype _NET_WM_NAME` print?

**Comment by ErrorNoInternet** [comment]
![image](https://github.com/user-attachments/assets/34a5c6c1-08e0-49ce-9ae3-0a44a82c5fe5)
