### ISSUE TITLE
[BUG] Fastfetch displaying random characters

### ISSUE THREAD

**Issue by Strokkur424** [fastfetch-cli/fastfetch#1136]
Be sure to read the [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

# General description of bug:

* What happened: When I try to use fastfetch, I get a really weird string of random characters, which does not seem to be tied to any information.
* What should happen: I'd expect a nice and clean fastfetch :D
* Fastfetch version used: latest
* Did it work in an older version: no clue, I only used latest
* Where did you get the binary: `sudo pacman -S fastfetch`
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? No clue how to install that. I am new to linux

# Often helpful information:

Screenshot:
![image](https://github.com/user-attachments/assets/15b6672d-c742-451f-86ec-f0623007dcf7)

The content of the configuration file you use (if any): default config

Output of `fastfetch -c ci.jsonc --format json`: [Link](https://pastes.dev/pe1MOTXiu7)

Output of `fastfetch --list-features`: [Link](https://pastes.dev/eXJj2Ou9wp)

**Comment by CarterLi** [comment]
Playing fastfetch in VirtualBox is not fun. You should run fastfetch in your host machine.

Fastfetch supports Windows too. You should try it.

**Comment by CarterLi** [comment]
Should have been fixed in the dev branch

**Comment by Strokkur424** [comment]
> Playing fastfetch in VirtualBox is not fun. You should run fastfetch in your host machine.
> 
> Fastfetch supports Windows too. You should try it.
I am just messing around with Arch in a vm, as I don't want to wipe my disk for a dual boot setup now. And yeah, I can try it in windows too, thanks for the tip!

Also thanks for the fix
