### ISSUE TITLE
[FEAT] 

### ISSUE THREAD

**Issue by blackxored** [fastfetch-cli/fastfetch#1140]
Be sure to read [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

## Wanted features:

Display GPUs that are bound to vfio_pci.

## Motivation:

Finally migrating from `neofetch`, which used to display my 2 GPUs, `fastfetch` on the other hand only seems to display the one that's connected to the host, not the one bound to `vfio_pci`. Ideally there could be a detection method that does what neofetch did?

**Comment by CarterLi** [comment]
Please try `--gpu-detection-method pci`

**Comment by blackxored** [comment]
I did try all methods, only 1 GPU shows up. —Best Regards,Adrian Perezhttps://adrianperez.codesOn Aug 1, 2024, at 2:22 AM, Carter Li ***@***.***> wrote:﻿
Please try --gpu-detection-method pci
