### ISSUE TITLE
[LOGO] Oreon Linux

### ISSUE THREAD

**Issue by brandonilester** [fastfetch-cli/fastfetch#1146]
Tip: A logo can be displayed by fastfetch without getting into fastfetch's official repo. For highly customized logo for personal use, it's recommended to keep it locally. Please refer to https://github.com/fastfetch-cli/fastfetch/wiki/Migrate-Neofetch-Logo-To-Fastfetch
# OS
Oreon Linux
```
NAME="Oreon"
VERSION="Lime (R2)"
ID="oreon"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Oreon Lime Desktop Standard (R2)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:oreon:oreon:9::baseos"
HOME_URL="https://oreonproject.org/"
DOCUMENTATION_URL="https://oreonproject.org/"
BUG_REPORT_URL="https://bugs.oreonproject.org/"

OREON_MANTISBT_PROJECT="oreon-9"
OREON_MANTISBT_PROJECT_VERSION="9.3"
REDHAT_SUPPORT_PRODUCT="Oreon"
REDHAT_SUPPORT_PRODUCT_VERSION="9.3"
```

# Ascii
[ascii.txt](https://github.com/user-attachments/files/16483129/ascii.txt)

**Comment by CarterLi** [comment]
Your logo is too big. It should not be higher than 20 rows

**Comment by brandonilester** [comment]
ill fix that, thanks
