### ISSUE TITLE
[BUG] Disk size and percentage used are calculated wrongly on some configs

### ISSUE THREAD

**Issue by barracuda156** [fastfetch-cli/fastfetch#1148]
@CarterLi I got it to build and start normally, finally.
(A few secondary modules are disabled, and I probably won’t bother trying to fix those.)

![fastfetch](https://github.com/user-attachments/assets/4c9c583d-cb2e-4900-b903-7c2a1c859044)

I have a small question now: could you advise why disk info is way off? Everything else looks more or less sensible (I do not know what Swap is supposed to mean here though, and used memory, but these are minor things).

With disks, the actual structure is as follows:
1. SSD, 600 GB
a. OS volume, 400 GB (not shown)
b. Snow Leopard, 80 GB (not shown)
2. HDD, 250 GB
a. Leo, 85 GB (shown, but wrong size)
b. SL10.6.8_prev, 150 GB (shown, but wrong size)
3. DVD with FreeBSD (shown, correct size)

So 1.a and 1.b are not shown at all, and for 2.a and 2.b both size and percentage used are wrong. AFAICT, this cannot result from my patches, since I did not mess with that module, only reverted createTime support.

What may cause this?

**Comment by CarterLi** [comment]
Try --disk-use-available

**Comment by CarterLi** [comment]
Specify `--format json` to see what happened

**Comment by barracuda156** [comment]
```
  {
    "type": "Disk",
    "result": [
      {
        "bytes": {
          "available": 33406025728,
          "free": 33668169728,
          "total": 0,
          "used": 0
        },
        "files": {
          "total": 104857598,
          "used": 96701830
        },
        "filesystem": "hfs",
        "mountpoint": "/",
        "mountFrom": "/dev/disk0s3",
        "name": "Snow SSD",
        "volumeType": [
          "Regular",
          "Unknown"
        ],
        "createTime": null
      },
      {
        "bytes": {
          "available": 0,
          "free": 0,
          "total": 780462080,
          "used": 780462080
        },
        "files": {
          "total": null,
          "used": null
        },
        "filesystem": "cd9660",
        "mountpoint": "/Volumes/12_4_RELEASE_POWERPC64_CD",
        "mountFrom": "/dev/disk2",
        "name": "12_4_RELEASE_POWERPC64_CD",
        "volumeType": [
          "Regular",
          "Read-only"
        ],
        "createTime": null
      },
      {
        "bytes": {
          "available": 15987843072,
          "free": 15987843072,
          "total": 344416256,
          "used": 18446744058066124800
        },
        "files": {
          "total": 22104180,
          "used": 18200898
        },
        "filesystem": "hfs",
        "mountpoint": "/Volumes/Leo",
        "mountFrom": "/dev/disk1s3",
        "name": "Leo",
        "volumeType": [
          "Regular"
        ],
        "createTime": null
      },
      {
        "bytes": {
          "available": 116232421376,
          "free": 116232421376,
          "total": 338354176,
          "used": 18446743957815484416
        },
        "files": {
          "total": 38879916,
          "used": 10502860
        },
        "filesystem": "hfs",
        "mountpoint": "/Volumes/SL10.6.8_prev",
        "mountFrom": "/dev/disk1s5",
        "name": "SL10.6.8_prev",
        "volumeType": [
          "Regular"
        ],
        "createTime": null
      },
      {
        "bytes": {
          "available": 79662272512,
          "free": 79662272512,
          "total": 0,
          "used": 0
        },
        "files": {
          "total": 20971518,
          "used": 1522721
        },
        "filesystem": "hfs",
        "mountpoint": "/Volumes/Snow Leopard",
        "mountFrom": "/dev/disk0s5",
        "name": "Snow Leopard",
        "volumeType": [
          "Regular",
          "Unknown"
        ],
        "createTime": null
      }
    ]
  },
```

Ok, perhaps `volumeType` got wrong for two disks, and that is why they are not shown, which is likely an issue with one patch. I will fix it. (And `createTime` is set to null on purpose; I also tried to revert that commit completely, dropping this argument, and nothing changed.)
I may know what is going on with used memory, should be fixable too.

I do not have an explanation for wrong size calculations for correctly detected disks. Endianness unaccounted somewhere?

**Comment by CarterLi** [comment]
> Ok, perhaps volumeType got wrong for two disks, and that is why they are not shown

Because their total sizes are 0

> Endianness unaccounted somewhere

No. They are plain getfsstat(2) results. No any hack used.

**Comment by barracuda156** [comment]
@CarterLi Thank you. I will look into what’s going on with this.

**Comment by barracuda156** [comment]
Partly the issue is due to using 64-bit structs, it seems. Changing those to 32-bit, I got a bit more sane output for disks, but sizes are still wrong (percentage calculation is correct now):
```
                                  Disk (\/Volumes/12_4_RELEASE_POWERPC64_CD\): 744.31 MiB / 744.31 MiB (100%) - cd9660 [Read-only]
                                  Disk (\/Volumes/Leo\): 1.43 GiB / 328.46 MiB (446%) - hfs
                                  Disk (\/Volumes/SL10.6.8_prev\): 66.80 MiB / 322.68 MiB (21%) - hfs
```

Linux version has this:
```
#ifdef __USE_LARGEFILE64
    #define stat stat64
    #define statvfs statvfs64
    #define dirent dirent64
    #define readdir readdir64
#endif
```
MacOS version seems to use 64-version unconditionally.

**Comment by barracuda156** [comment]
I have fixed it. A silly issue, I did not try this earlier because assumed it cannot be that simple LOL

```
disk->bytesTotal = fs->f_blocks * fs->f_bsize;
```
should be
```
disk->bytesTotal = (uint64_t)fs->f_blocks * fs->f_bsize;
```

**Comment by CarterLi** [comment]
```diff
diff --git a/src/modules/disk/disk.c b/src/modules/disk/disk.c
index b66236d3..17b52bb1 100644
--- a/src/modules/disk/disk.c
+++ b/src/modules/disk/disk.c
@@ -470,7 +470,11 @@ void ffInitDiskOptions(FFDiskOptions* options)
 
     ffStrbufInit(&options->folders);
     options->showTypes = FF_DISK_VOLUME_TYPE_REGULAR_BIT | FF_DISK_VOLUME_TYPE_EXTERNAL_BIT | FF_DISK_VOLUME_TYPE_READONLY_BIT;
+    #if __APPLE__
+    options->calcType = FF_DISK_CALC_TYPE_AVAILABLE;
+    #else
     options->calcType = FF_DISK_CALC_TYPE_FREE;
+    #endif
     options->percent = (FFColorRangeConfig) { 50, 80 };
 }
```

Does this patch fix your issue?

**Comment by barracuda156** [comment]
And I got CPU detection working for PowerPC now.

**Comment by barracuda156** [comment]
> ```diff
> diff --git a/src/modules/disk/disk.c b/src/modules/disk/disk.c
> index b66236d3..17b52bb1 100644
> --- a/src/modules/disk/disk.c
> +++ b/src/modules/disk/disk.c
> @@ -470,7 +470,11 @@ void ffInitDiskOptions(FFDiskOptions* options)
>  
>      ffStrbufInit(&options->folders);
>      options->showTypes = FF_DISK_VOLUME_TYPE_REGULAR_BIT | FF_DISK_VOLUME_TYPE_EXTERNAL_BIT | FF_DISK_VOLUME_TYPE_READONLY_BIT;
> +    #if __APPLE__
> +    options->calcType = FF_DISK_CALC_TYPE_AVAILABLE;
> +    #else
>      options->calcType = FF_DISK_CALC_TYPE_FREE;
> +    #endif
>      options->percent = (FFColorRangeConfig) { 50, 80 };
>  }
> ```
> 
> Does this patch fix your issue?

Do you suggest in addition to the type fix? I can try. But I think everything is working correctly now (from the basic stuff, I mean; I disabled Bluetooth, WiFi and some other stuff).

Let me rebuild again, I need to make sure patches are not messed up, and I post a screen capture.

**Comment by barracuda156** [comment]
@CarterLi Disks sizes work, CPU detection on PowerPC works:

![fastfetch_ppc](https://github.com/user-attachments/assets/c0294932-c971-40ea-be22-c1c51a995959)

I think I had built Bluetooth module before (now disabled in this build), so I will see what can be added without too much of struggle against ObjC.

**Comment by CarterLi** [comment]
Does the Disk size work without my patch?

**Comment by barracuda156** [comment]
> Does the Disk size work without my patch?

Yes, at least what I get now are the correct values. I did not do any further testing, but it looks good, IMO.

**Comment by barracuda156** [comment]
@CarterLi Thanks for helping here!
