### ISSUE TITLE
[BUG] Python Version

### ISSUE THREAD

**Issue by objectdisorientedprogramming** [fastfetch-cli/fastfetch#1153]
CMakeLists.txt contains the following code segment:

__find_package(Python)
if(Python_FOUND)
    execute_process(COMMAND ${Python_EXECUTABLE} -c "import json,sys;json.dump(json.load(sys.stdin),sys.stdout,separators=(',',':'))"
                    INPUT_FILE "${CMAKE_CURRENT_SOURCE_DIR}/src/data/help.json"
                    OUTPUT_VARIABLE DATATEXT_JSON_HELP)
    if(DATATEXT_JSON_HELP STREQUAL "")
        message(ERROR "DATATEXT_JSON_HELP is empty, which should not happen!")
    endif()
else()
    message(STATUS "Python3 is not found, 'help.json' will not be minified")
    file(READ "src/data/help.json" DATATEXT_JSON_HELP)
endif()__

The comment __“Python3 is not found, ‘help.json’ will not be minified”__ suggests that this code segment requires Version 3 of Python.  Therefore, should ‘__Python__’ be changed to ‘__Python3__’ in ‘__find_package(Python)__’ and ‘__Python_FOUND__’ be changed to ‘__Python3_FOUND__’ in ‘__if(Python_FOUND)__’?

**Comment by CarterLi** [comment]
`import json,sys;json.dump(json.load(sys.stdin),sys.stdout,separators=(',',':'))` is a simple python script that supports both python2 and python3
