### ISSUE TITLE
[FEAT] Anticipate Support for Other BSDs

### ISSUE THREAD

**Issue by objectdisorientedprogramming** [fastfetch-cli/fastfetch#1154]
CMakeLists.txt contains the following code segment in which ‘__BSD__’ is defined if the target platform is FreeBSD:

__###################__
__# Target Platform #__
__###################__
__if(ANDROID)
    set(LINUX FALSE)
elseif("${CMAKE_SYSTEM_NAME}" STREQUAL "Linux")
    set(LINUX TRUE CACHE BOOL "..." FORCE) # LINUX means GNU/Linux, not just the kernel
elseif("${CMAKE_SYSTEM_NAME}" STREQUAL "FreeBSD")
    set(BSD TRUE CACHE BOOL "..." FORCE)
elseif("${CMAKE_SYSTEM_NAME}" STREQUAL "SunOS")
    set(SunOS TRUE CACHE BOOL "..." FORCE)
elseif(NOT APPLE AND NOT WIN32)
    message(FATAL_ERROR "Unsupported platform: ${CMAKE_SYSTEM_NAME}")
endif()__

‘__BSD__’ is subsequently used throughout CMakeLists.txt to customize the build for FreeBSD.

In anticipation of adding support for other BSDs, such as NetBSD and OpenBSD, I suggest defining and using ‘__FreeBSD__’ for FreeBSD instead of the more generic ‘__BSD__’.  This change should help prevent confusion over which BSD is being referred to and simplify porting to other BSDs.

**Comment by TheWanderer1983** [comment]
Looking forward to OpenBSD.
