### ISSUE TITLE
[BUG] `fastfetch -s icons -l none` and `fastfetch -s font -l none` no longer shows an output?

### ISSUE THREAD

**Issue by Samueru-sama** [fastfetch-cli/fastfetch#1162]
They stopped working after I updated 2.21.0, previous version is working fine, this likely was a change in fastfetch and not a bug, but I can't find any mention of such change in the release notes?

**Comment by CarterLi** [comment]
It works for me. 2.21.0 had no changes for icons and font so that I didn't metion then in the release notes.

**Comment by Samueru-sama** [comment]
Testing the last two released binaries:

![image](https://github.com/user-attachments/assets/221bac58-e47b-4f05-aeef-d3aa9ee2933e)

**Comment by CarterLi** [comment]
Are you running fastfetch in TTY? That's the only change that may affect these two modules I can come up with.

**Comment by Samueru-sama** [comment]
> Are you running fastfetch in TTY? That's the only change that may affect these two modules I can come up with.

The images are from the xfce4-terminal, but the graphical session (i3wm) was started on TTY though.

**Comment by CarterLi** [comment]
What does `echo $XDG_SESSION_TYPE` print?

**Comment by Samueru-sama** [comment]
> What does `echo $XDG_SESSION_TYPE` print?

tty 👀

![image](https://github.com/user-attachments/assets/38112d25-3531-4886-a46a-ad38c9149eaf)

Alright, thank you! I guess I have to add this now to my zprofile lol.

**Comment by CarterLi** [comment]
So that $XDG_SESSION_TYPE is unreliable. I wonder if I want to support this case. @Dariqq What's your opinion?

**Comment by CarterLi** [comment]
Partially reverted
