### ISSUE TITLE
[BUG] Flatpak-All Count Not Displaying Correctly in Fastfetch Configuration

### ISSUE THREAD

**Issue by mateowoetam** [fastfetch-cli/fastfetch#1171]
Sure, here is the minimized issue report with only the relevant parts:

---

# General description of bug:

* What happened:
  When configuring fastfetch on its `conf.json` and using the packages format:
  ```json
  {
      "type": "packages",
      "key": "Pkgs",
      "keyColor": "blue",
      "format": "{5} (rpm), {34} (flatpak-all)"
  }
  ```
  The option `{34} (flatpak-all)` no longer works properly and instead only displays `{15} (flatpak-user)` maybe as a fallback?

* What should happen:
  The correct number of all installed flatpaks should be displayed using `{34} (flatpak-all)`.

# Often helpful information:

The content of the configuration file you use (if any):
```json
{
    "type": "packages",
    "key": "Pkgs",
    "keyColor": "blue",
    "format": "{5} (rpm), {34} (flatpak-all)"
}
```

This is how many flatpaks I have installed:
```shell
flatpak list | grep -c ''
```
Output:
```
47
```

This is how many fastfetch is displaying:
```
Pkgs: 3939 (rpm), 15 (flatpak-all)
```

**Comment by CarterLi** [comment]
What is the output of `flatpak list --app | grep -c ''`?

**Comment by mateowoetam** [comment]
> What is the output of `flatpak list --app | grep -c ''`?

 ```
flatpak list --app | grep -c ''                                                ~
15
```

**Comment by CarterLi** [comment]
> > What is the output of `flatpak list --app | grep -c ''`?
> 
>  ```
> flatpak list --app | grep -c ''                                                ~
> 15
> ```

That's it

**Comment by mateowoetam** [comment]
> > > What is the output of `flatpak list --app | grep -c ''`?
> > 
> > 
> > ```
> > flatpak list --app | grep -c ''                                                ~
> > 15
> > ```
> 
> That's it

mabye I don't understand how it works, because I do have 47 flatpaks installed, user + system, is it not supposed to add them up?

**Comment by CarterLi** [comment]
Fastfetch detects only apps (flatpak list --app) but ignores runtimes (flatpak list --runtime)

**Comment by CarterLi** [comment]
By design
