### ISSUE TITLE
[BUG] Fastfetch 2.21.0 fails to detect WM (XMonad)

### ISSUE THREAD

**Issue by Fuxino** [fastfetch-cli/fastfetch#1172]
I'm running Arch Linux with XMonad window manager (no DE), and fastfetch fails to detect the WM since upgrading to version 2.21.0. It works fine if I downgrade to version 2.20.0

Output of `fastfetch -c ci.jsonc --format json`:

```
...
  {
    "type": "WM",
    "error": "No WM found",
    "stat": 0
  },
  {
    "type": "WMTheme",
    "error": "WM Theme needs successful WM detection",
    "stat": 0
  },
  {
    "type": "Theme",
    "error": "Theme isn't supported in TTY",
    "stat": 0
  },
  {
    "type": "Icons",
    "error": "Icons aren't supported in TTY",
    "stat": 0
  },
  {
    "type": "Font",
    "error": "Font isn't supported in TTY",
    "stat": 0
  },
  {
    "type": "Cursor",
    "error": "Cursor isn't supported in TTY",
    "stat": 0
  },
...
```

**Comment by CarterLi** [comment]
Did you manually run `startx` in TTY?

**Comment by CarterLi** [comment]
Can you test the dev build work for you?

**Comment by Fuxino** [comment]
I didn't run `startx` manually, I have this in my config.fish file (using fish as my interactive shell):
```
if test -z "$DISPLAY" -a "$XDG_VTNR" = 1
    exec startx -- -keeptty
end
```

I will try the dev build later and let you know if it works.

**Comment by Fuxino** [comment]
Okay, I tried the dev build and it seems to work again.
