### ISSUE TITLE
[BUG] Image logo does not work in tmux session

### ISSUE THREAD

**Issue by ZirixCZ** [fastfetch-cli/fastfetch#1176]
Fastfetch does not display logo when in a tmux session. This has been discussed here earlier https://github.com/fastfetch-cli/fastfetch/issues/861. A fix has been committed and released in 2.11.3, though the issue persists.

I am on MacOs and got fastfetch throught brew. I tried the 2.18 and 2.21.1 versions of fastfetch.

Fastfetch config 
```
{
  "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
  "modules": [
    "os",
    "kernel",
    "uptime",
    "separator",
    "cpu",
    "gpu",
    "memory",
    "swap",
    "separator",
    "de",
    "wm",
    "icons",
    "terminal",
    "terminalfont",
    "localip",
    "battery",
    "poweradapter",
    "locale",
    "break",
    "colors",
  ],
}
```

I tried multiple terminal emulators that all behaved the same. The following video is from WezTerm.

https://github.com/user-attachments/assets/2c900fd6-d7cb-494a-9365-b4d00be059fb

**Comment by CarterLi** [comment]
You have to use sixel image protocol

**Comment by ZirixCZ** [comment]
That solves it.
Doing `fastfetch --logo ~/Pictures/hyprchantransparent.png --logo-type sixel --logo-width 25 --logo-height 20` instead of `fastfetch --logo ~/Pictures/hyprchantransparent.png --logo-type iterm --logo-width 25 --logo-height 20` displays the image in tmux. Unfortunately it seems like to not support transparency, but that's most likely a protocol limitation than anything else. Thanks!
