### ISSUE TITLE
[LOGO] HyprOS

### ISSUE THREAD

**Issue by ElryDeveloper** [fastfetch-cli/fastfetch#1178]
Tip: A logo can be displayed by fastfetch without getting into fastfetch's official repo. For highly customized logo for personal use, it's recommended to keep it locally. Please refer to https://github.com/fastfetch-cli/fastfetch/wiki/Migrate-Neofetch-Logo-To-Fastfetch

# OS
```
NAME="HyprOS"
PRETTY_NAME="HyprOS"
ID="hypros"
ID_LIKE="arch"
BUILD_ID=rolling
HOME_URL="https://hypros.xyz"
SUPPORT_URL="https://github.com/ElryDeveloper/HyprOS/issues"
BUG_REPORT_URL="https://github.com/ElryDeveloper/HyprOS/issues"
LOGO="hypros"
```

# Ascii

An ASCII logo should not take up too much space (smaller than 50x20 characters). Please also include the color codes if not available in `os-release` 

```
                                                  
                 .::--=======---:.                
             .:-====--::::---=++==-:.             
           -+++=--:-----===---:-=++=-:.           
         -***+----====++++===---::==+=-:.         
       .****=======++++====++**+++==----:.        
      :#*#*=++===+*++=++++##%%#####*+=-:--:.      
     :###*+++=-=***+++-:--+#%%%%%%%#%#+=::-:      
     ##%#*++=-+***++=.      .+#%%%%%%%%+=:--:     
    =%#%***+==**#*+=.         -#%%%%%%%#++:=-.    
    *%%%#**+=+*##++.           =#%%%%%%#+*-==:    
    #%%%#*#*=**##*=            :*##%%%##+*=+=:    
    #%%%###*+=+##*=            :**######+*=+=.    
    +%%%####*==*%++:           =+****##***=+-     
    :%%%%####*+=*#++:         -=+++*##***++=:     
     +#%%%####**+++++=:    .:-===+*#*+**++=:      
      *#%%%######*++++==----=-=+*****#*++=:       
       *##%%#######**++=-+++******###*+=-.        
        =###%%########*++==+*#####**++=:          
         .+###%%#########*+=-+*#**++-.            
           :+###%%##########*+--=:.               
             .-*##%%########%##+=-.               
                :=*############%#*+=-.            
                   ..:=++*###*++=-:....           
                           ..                     

```

**Comment by ElryDeveloper** [comment]
png file cuz ive seen you have png files of anime characters or like arch stuff, incase you can incoorperate that
![HyprOS-Logo-v2](https://github.com/user-attachments/assets/c81d9edf-e068-4748-9049-992baefcbf4c)

**Comment by CarterLi** [comment]
Please make your logo smaller than 50x20

**Comment by CarterLi** [comment]
WxH

**Comment by ElryDeveloper** [comment]
```
               :::::.::             
          ---========+=-::.         
        +==+====++++===++=-:.       
      *+*++++++***+=-----==-:..     
     #*****++***++++*##**==:--:.    
    #*#***++*#**=#%%@@@%###==:-:    
   %#%###++##*+-    #%%@@%##+=--:   
   %#%##*+#%*+-       %%@%%%#=-=-   
   %%%%##*#%*-        #%%%%##====   
   %%%%%#+*%*-        *#%%##*+=+=   
   %%@%%%#*#*+:       +*##*#+*++-   
   %%%%%%%#***+-    -+*****+*+*=    
    %%%%%%%%#***+++++++**+****=     
     #%%%%##%%#**=**#*+*#***+=      
      #%%%%###%#%#*+*#####*+        
        #%%%%##%###%#+=+++          
          #%%%%######%#*=-          
             ###%%#######++=-       
                   #*#              
```

**Comment by Princess-Sunset-Shimmer** [comment]
logo Looks cool, and excuse me: what is hyprOS?

**Comment by CarterLi** [comment]
Colors?

**Comment by Princess-Sunset-Shimmer** [comment]
Color_Testing:
![image](https://github.com/user-attachments/assets/b74cec02-bf66-4d4c-8bfe-8a88c7432fb2)
How's your feel about this presentation?

**Comment by Princess-Sunset-Shimmer** [comment]
> Colors?

Monochrome?

**Comment by ElryDeveloper** [comment]
> Color_Testing: ![image](https://private-user-images.githubusercontent.com/102773277/356979428-b74cec02-bf66-4d4c-8bfe-8a88c7432fb2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NTIyNTcsIm5iZiI6MTcyMzQ1MTk1NywicGF0aCI6Ii8xMDI3NzMyNzcvMzU2OTc5NDI4LWI3NGNlYzAyLWJmNjYtNGQ0Yy04YmZlLThhODhjNzQzMmZiMi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTJUMDgzOTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjdjZjNmMzc1ZGJmMmZmZTZiZDBhMzI2MTA1M2FmOWE1NDIxNGZkYjMxMmFlMzUwMDkzN2U3Y2VkNjljYmMzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.67G3rVn8_XY-eJiNTYMWDbSFuvLZqCF1cCPOPlRouS0) How's your feel about this presentation?

That looks perfect.


> logo Looks cool, and excuse me: what is hyprOS?

An Arch distro that comes with Hyprland and automatically installs nvidia / amd drivers but otherwise stays minimal.

Im working on the Distro.

**Comment by Princess-Sunset-Shimmer** [comment]
Will An amazing new /\rch Distro come? Why i didn't search out hyprOS official website?

**Comment by Princess-Sunset-Shimmer** [comment]
So, if you two approve this presentation of hyprOS's Cutie-Mark (showed in above pic), then i'll push the new Pull-Request

**Comment by Princess-Sunset-Shimmer** [comment]
and Important question for new pull-request:
    Does fastfetch already collect hyprOS logo before?

**Comment by ElryDeveloper** [comment]
> So, if you two approve this presentation of hyprOS's Cutie-Mark (showed in above pic), then i'll push the new Pull-Request

Sure approve of it.


> and Important question for new pull-request: Does fastfetch already collect hyprOS logo before?

Nope

**Comment by ElryDeveloper** [comment]
@CarterLi does @Princess-Sunset-Shimmer has your ok ?

**Comment by Princess-Sunset-Shimmer** [comment]
> @CarterLi does @Princess-Sunset-Shimmer have your ok ?

i'm ready

**Comment by Princess-Sunset-Shimmer** [comment]
🎉 🎈🎊 Congratulations, the hyprOS logo has been collected into the fastfetch logo list 🥳 🎇 🎆

**Comment by ElryDeveloper** [comment]
Thanks @Princess-Sunset-Shimmer

**Comment by CarterLi** [comment]
Seems this distro is already dead 😆

**Comment by Princess-Sunset-Shimmer** [comment]
> Seems this distro is already dead 😆 

i only found hyprlinux github page.
