### ISSUE TITLE
[BUG] Doesn't detect that I have 2 GPU on my laptop

### ISSUE THREAD

**Issue by g-berthiaume** [fastfetch-cli/fastfetch#1181]
Be sure to read the [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

# General description of bug:

* What happened:

While `Winfetch` detects that my laptop has 2 GPUs
![image](https://github.com/user-attachments/assets/fee07ea5-1617-4de5-b772-5e5e95f05ac1)

fastfetch does not

![image](https://github.com/user-attachments/assets/3060ea8f-185e-461c-b45e-7b9f5e3283c5)

* What should happen:
In an ideal world, It should detect both GPU

* Fastfetch version used: 
```
λ  fastfetch -v
fastfetch 2.21.1 (x86_64)
```

* Did it work in an older version: 

I just installed it.

* Where did you get the binary: 

installed with `scoop`

---

I think fast-fetch is great. Thanks for making it!

**Comment by Kseen715** [comment]
Same issue, installed with `choco`

winfetch:
![Снимок экрана 2024-08-12 235841](https://github.com/user-attachments/assets/488ced86-01cc-45a1-b3be-87b7c2f2e3a0)

fastfetch:
![Снимок экрана 2024-08-12 235945](https://github.com/user-attachments/assets/3a15ffd9-14f4-4515-98e6-b1ac5914c764)

- Fastfetch version used:
fastfetch 2.21.1 (x86_64)

**Comment by CarterLi** [comment]
Can you try if v2.20.0 works for you?

**Comment by CarterLi** [comment]
Please also try this build: https://github.com/fastfetch-cli/fastfetch/actions/runs/10360383324/artifacts/1804101583

Paste the result of `fastfetch -s gpu --format json`

**Comment by Kseen715** [comment]
> Please also try this build: https://github.com/fastfetch-cli/fastfetch/actions/runs/10360383324/artifacts/1804101583
> 
> Paste the result of `fastfetch -s gpu --format json`

This exact build is working correctly for me! And it also shows all disk right now (now disk Z:\ is shown)

Original version:
![Снимок экрана 2024-08-13 084624](https://github.com/user-attachments/assets/46e0a1f1-645e-4b0d-8e07-0b25ac932297)

This build:
![Снимок экрана 2024-08-13 084953](https://github.com/user-attachments/assets/03d7e497-5a13-4683-bd19-1400c4a6947a)
![Снимок экрана 2024-08-13 085054](https://github.com/user-attachments/assets/c0cebe88-eb9c-48ff-a8bb-670d5e7c910d)

**Comment by CarterLi** [comment]
@Kseen715 I added some debug log. Can you try this build: https://github.com/CarterLi/fastfetch/actions/runs/10365012515/artifacts/1805206798

**Comment by Kseen715** [comment]
> try this build

Here it is:

```
PCI\VEN_8086&DEV_9BC4&SUBSYS_12F41462&REV_05
{C24A09B1-3E04-11EE-8A53-8EBD99653248}
SYSTEM\CurrentControlSet\Control\Video\{C24A09B1-3E04-11EE-8A53-8EBD99653248}\0000
SOFTWARE\Microsoft\DirectX\{C24A09B1-3E04-11EE-8A53-8EBD99653248}
PCI\VEN_10DE&DEV_25A0&SUBSYS_12F41462&REV_A1
{C24A0A03-3E04-11EE-8A53-0C9A3C4B70C1}
SYSTEM\CurrentControlSet\Control\Video\{C24A0A03-3E04-11EE-8A53-0C9A3C4B70C1}\0000
```
![Снимок экрана 2024-08-13 101514](https://github.com/user-attachments/assets/40b54ed6-f4ba-4215-8c32-5777574fa5cb)

**Comment by CarterLi** [comment]
Does the registry `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Video\{C24A0A03-3E04-11EE-8A53-0C9A3C4B70C1}` exist?

**Comment by Kseen715** [comment]
> Does the registry HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Video\{C24A0A03-3E04-11EE-8A53-0C9A3C4B70C1} exist?

Yes

PS:
![image](https://github.com/user-attachments/assets/eb79c6b4-3da8-4361-8fb6-109c01ecb097)

reg:
![image](https://github.com/user-attachments/assets/bb2fcb81-4de1-431c-9792-09662a116621)

**Comment by CarterLi** [comment]
Can you check the `{DEB039CC-XXXXX` key if it contains the information about your NVIDIA GPU.

Just in case, did you upgrade your NVIDIA GPU driver today?

**Comment by CarterLi** [comment]
Can you also check if `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\DirectX\{C24A0A03-3E04-11EE-8A53-0C9A3C4B70C1}` exists?

**Comment by Kseen715** [comment]
Nvidia driver 560.70 from 2024.07.16 ( Should I upgrade it to 560.81? They didn't change nor fix anything related afaik

Here `{DEB039CC-XXXXX` key:
![image](https://github.com/user-attachments/assets/0882cba1-7a94-4896-917d-7c7343d4c606)
![image](https://github.com/user-attachments/assets/64e59604-edd2-43d7-8ce3-876a578d0a13)

> Can you also check ...

And that key:
PS somehow tells nothing
![image](https://github.com/user-attachments/assets/08ea0a8a-7641-47aa-a3ca-c198a62372a4)
reg shows normal:
![image](https://github.com/user-attachments/assets/25f9a713-2b33-4e1a-b798-e98f3f321587)

**Comment by CarterLi** [comment]
Big thanks for your help! I will implement a fix soon.

> Should I upgrade it to 560.81?

No. I just want to check if you just upgraded the driver.

**Comment by Kseen715** [comment]
Glad to help!

> try rebooting your computer to see if the debug log changes

Nothing changed
![image](https://github.com/user-attachments/assets/35bdfd04-1c07-4407-9b1a-55eb7968c1e6)

```
PCI\VEN_8086&DEV_9BC4&SUBSYS_12F41462&REV_05
{C24A09B1-3E04-11EE-8A53-8EBD99653248}
SYSTEM\CurrentControlSet\Control\Video\{C24A09B1-3E04-11EE-8A53-8EBD99653248}\0000
SOFTWARE\Microsoft\DirectX\{C24A09B1-3E04-11EE-8A53-8EBD99653248}
PCI\VEN_10DE&DEV_25A0&SUBSYS_12F41462&REV_A1
{C24A0A03-3E04-11EE-8A53-0C9A3C4B70C1}
SYSTEM\CurrentControlSet\Control\Video\{C24A0A03-3E04-11EE-8A53-0C9A3C4B70C1}\0000
```
![image](https://github.com/user-attachments/assets/12de3885-4d1f-468a-9224-37bd95e23569)

**Comment by CarterLi** [comment]
Should be fixed in the dev build, please test: https://github.com/fastfetch-cli/fastfetch/actions/runs/10368907219/artifacts/1806184673

**Comment by g-berthiaume** [comment]
Thanks everybody!
