### ISSUE TITLE
[BUG] fastfetch: symbol lookup error: fastfetch: undefined symbol: yyjson_locate_pos

### ISSUE THREAD

**Issue by HakaishinShwet** [fastfetch-cli/fastfetch#1185]
just installed normally using yay -S fastfetch in my arch linux and when i run fastfetch in cli i get this error 

`> fastfetch: symbol lookup error: fastfetch: undefined symbol: yyjson_locate_pos`

please guide what package could be missing in my arch linux because of which i am facing this. Btw i installed fresh today only so can say its latest for me 

```
extra/fastfetch 2.21.1-1 [0 B 2.55 MiB] [Installed]
    Like Neofetch, but much faster because written in C
```

**Comment by HakaishinShwet** [comment]
Strangely i tried fastfetch-git package instead of just fastfetch and it fixed my issue so closing this for now :-))

**Comment by CarterLi** [comment]
You need to upgrade yyjson

**Comment by HakaishinShwet** [comment]
ok
