### ISSUE TITLE
[FEAT] Can You Support Ubuntu 20.04 and previous versions?

### ISSUE THREAD

**Issue by marvinwu-legmed** [fastfetch-cli/fastfetch#1196]
Be sure to read [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

## Wanted features: 

Can You Support Ubuntu 20.04 LTS and previous versions?

## Motivation: 

I think this fetch is awesome, but it can not be used in my Ubuntu 20.04 machine.

**Comment by CarterLi** [comment]
For 20.04, you may download the binaries from Github release page. For older version, you have to build it yourself.
