### ISSUE TITLE
[FEAT] Please add completion for zsh

### ISSUE THREAD

**Issue by AtifChy** [fastfetch-cli/fastfetch#1197]
Be sure to read [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

## Wanted features:
`fastfetch` has a vast number of options available, it would be much easier to traverse around these options with tab completion instead of opening the man page over and over.

## Motivation:
currently fastfetch has completion support for `fish` shell with proper description beside each option, having the same completion with zsh would be awesome.

**Comment by CarterLi** [comment]
You can try carapace-bin https://github.com/carapace-sh/carapace-bin

**Comment by AtifChy** [comment]
@CarterLi i noticed that a python script being used to generate the completions for fish shell, can't the same be done for zsh. carapace-bin looks interesting, but i would prefer native shell completion.

**Comment by CarterLi** [comment]
> i noticed that a python script being used to generate the completions for fish shell, can't the same be done for zsh

You still need to know the syntax of zsh script to generate the completions.

You can try it yourself if you have interest. `fastfetch --help-raw` prints a JSON document that contains all command line options. All you need to do is parse the JSON document [and generate zsh completion command](https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org)

**Comment by aymen-3** [comment]
Since fastfetch has a --help option, you can add this line to your .zshrc file and it will have completion: 

**compdef _gnu_generic fastfetch**

**Comment by Simon238** [comment]
For those of us using Oh-My-Zsh:

Copying [`fastfetch/completions/fastfetch.zsh`](https://github.com/fastfetch-cli/fastfetch/blob/dev/completions/fastfetch.zsh) to `~/.oh-my-zsh/cache/completions/_fastfetch` as is did not work for me. I had to change
```zsh
_fastfetch "$@"
```
into
```zsh
if [ "$funcstack[1]" = "_fastfetch" ]; then
    _fastfetch "$@"
else
    compdef _fastfetch fastfetch
fi
```
