### ISSUE TITLE
[LOGO] "Sleeper OS" Request

### ISSUE THREAD

**Issue by victinifan360** [fastfetch-cli/fastfetch#1198]
Tip: A logo can be displayed by fastfetch without getting into fastfetch's official repo. For highly customized logo for personal use, it's recommended to keep it locally. Please refer to https://github.com/fastfetch-cli/fastfetch/wiki/Migrate-Neofetch-Logo-To-Fastfetch

# OS
```
Paste content of /etc/os-release and /etc/lsb-release here. If none of these files exist, describe a way to identify the distro
```

##  /etc/os-release

PRETTY_NAME="Sleeper OS BEE V2"
NAME="Sleeper OS"
VERSION_ID="V2"
VERSION="V2"
VERSION_CODENAME=bee
ID=SleeperOS
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

## /etc/lsb-release

PRETTY_NAME="Sleeper OS V2 BEE"
DISTRIB_ID="Sleeper OS"
DISTRIB_RELEASE=V2
DISTRIB_CODENAME="BEE"
DISTRIB_DESCRIPTION="Sleeper OS V2 BEE"

# Ascii

An ASCII logo should not take up too much space (smaller than 50x20 characters). Please also include the color codes if not available in `os-release` 

```
        ;ollllllllllllllllllllllk
        .dxKKKKKKKKKKKKKKKKKKKKd;'
        .dKMMMMMMMMMMMMMMMMMMMMxl.
        .dKMMMMMMMMMMMMMMMMMMMMxl.
         dkXXXXXXXXXXXNMMMMMMMWdc
                  .,xdNMMMMMMXd'
                 o,lkMMMMMMMOo.
                d;oKMMMMMMWxc
              ;;cxWMMMMMMKo.
             d,oOMMMMMMMkl
           .l;dXMMMMMMNd;
          l,lxWMMMMMM0o.
         d,o0MMMMMMWxl.lxxxxxxdkl
        ;:dNMMMMMMMkOOOOOOOOOOOo,;
        .dKMMMMMMMMMMMMMMMMMMMMxl.
        .dKMMMMMMMMMMMMMMMMMMMMxl.
        .x0MMMMMMMMMMMMMMMMMMMMxl.
          ;lllllllllllllllllllc. 
```
## Color codes #03f1ff #ffffff

**Comment by Princess-Sunset-Shimmer** [comment]
sleeper os logo Needs 2 colors 😊

**Comment by Princess-Sunset-Shimmer** [comment]
i also assembled a small version of it\
Here is testing:
![image](https://github.com/user-attachments/assets/dfc1bba0-fa7d-4311-bc41-d01d1ff72287)
How's it?

**Comment by victinifan360** [comment]
Yes! I approve it!

**Comment by Princess-Sunset-Shimmer** [comment]
> Yes! I approve it!

Wait for CarterLi actions

**Comment by CarterLi** [comment]
Done

**Comment by Princess-Sunset-Shimmer** [comment]
Do you need small version?\
Colored sleeperos_small:
![image](https://github.com/user-attachments/assets/767a164f-b54e-4e98-ac03-18a9b8db336a)
How's this result?

**Comment by Princess-Sunset-Shimmer** [comment]
> > > Yes! I approve it!
> 
> > 
> 
> > Wait for CarterLi actions
> 
> 
> 
> You did a great work!

Thanks

**Comment by victinifan360** [comment]
> Do you need small version? Colored sleeperos_small: ![image](https://private-user-images.githubusercontent.com/102773277/359396244-767a164f-b54e-4e98-ac03-18a9b8db336a.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNTQxNjcsIm5iZiI6MTcyNDE1Mzg2NywicGF0aCI6Ii8xMDI3NzMyNzcvMzU5Mzk2MjQ0LTc2N2ExNjRmLWI1NGUtNGU5OC1hYzAzLTE4YTliOGRiMzM2YS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjBUMTEzNzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTQ2M2U5NmQ2NjQ4ZjM5MTE2YjVlNjdlOGJmNjlmMWRjNWM4ZGMwYTE2NzJhNzVjNGI1OTk1NzM4YTRiM2YzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ufn0e-xNq4g73mHkNGLgghmfc3FBt_Aehau6wQwDw0I) How's this result?

Yes, I'd appreciate it.

**Comment by Princess-Sunset-Shimmer** [comment]
now i have to do some thing As SleeperOS do --> goto sleep state 😴 💤
