### ISSUE TITLE
[BUG] macOS Sonoma Apple Silicon shows Version - fastfetch 2.21.3 (x86_64)

### ISSUE THREAD

**Issue by onefish2** [fastfetch-cli/fastfetch#1201]
macOS Sonoma on Apple Silicon shows Version - fastfetch 2.21.3 **(x86_64)**

**Comment by CarterLi** [comment]
Where did you download the binary?

**Comment by onefish2** [comment]
Homebrew

**Comment by CarterLi** [comment]
Cannot reproduce

**Comment by onefish2** [comment]
Mac Studio M1 Max running Sonoma 14.6.1. Using iterm2. Build 3.5.4beta2. Installed with Homebrew.

**Comment by CarterLi** [comment]
It doesn't matter what machine you use. As long as you use macOS 14 aarch64, you download the same bottle `https://ghcr.io/v2/homebrew/core/fastfetch/blobs/sha256:15fc995728c023c5288544b50003dc3b2953db27e25da8df04032e259a821e43`

```
❯ env -u HOMEBREW_BOTTLE_DOMAIN brew reinstall fastfetch
==> Downloading https://ghcr.io/v2/homebrew/core/fastfetch/manifests/2.21.3-1
Already downloaded: /Users/carter/Library/Caches/Homebrew/downloads/9f34137b9535e860f4348cc07a724e634ec9a3d3ef04deb319056158556b865e--fastfetch-2.21.3-1.bottle_manifest.json
==> Fetching fastfetch
==> Downloading https://ghcr.io/v2/homebrew/core/fastfetch/blobs/sha256:15fc995728c023c5288544b50003dc3b2953db27e25da8df04032e259a821e43
Already downloaded: /Users/carter/Library/Caches/Homebrew/downloads/2a8d10e52bdca96a9d1815b51b3f5866d78bcd27e6ab9fc6ee8d1861e0ddbd4a--fastfetch--2.21.3.arm64_sonoma.bottle.1.tar.gz
==> Reinstalling fastfetch
==> Verifying attestation for fastfetch
==> Pouring fastfetch--2.21.3.arm64_sonoma.bottle.1.tar.gz
==> Caveats
fish completions have been installed to:
  /opt/homebrew/share/fish/vendor_completions.d
==> Summary
🍺  /opt/homebrew/Cellar/fastfetch/2.21.3: 40 files, 2.4MB
==> Running `brew cleanup fastfetch`...
fastfetch/build on  dev [$✘!?] via C v15.0.0-clang via △ v3.30.2 took 4s
❯ /opt/homebrew/bin/fastfetch --version
fastfetch 2.21.3 (aarch64)
fastfetch/build on  dev [$✘!?] via C v15.0.0-clang via △ v3.30.2
❯ file (realpath /opt/homebrew/bin/fastfetch)
/opt/homebrew/Cellar/fastfetch/2.21.3/bin/fastfetch: Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>
fastfetch/build on  dev [$✘!?] via C v15.0.0-clang via △ v3.30.2
❯ sha256sum (realpath /opt/homebrew/bin/fastfetch)
d009b585502f8583812367e28080e28f9ea3f7604523e72a9364b939577e6f10  /opt/homebrew/Cellar/fastfetch/2.21.3/bin/fastfetch
```

**Comment by onefish2** [comment]
I made some edits. See above. MacBook Pro is using zsh. Mac Studio with the mismatch is using bash.

**Comment by CarterLi** [comment]
They all don't matter. Follow the instructions and paste the command outputs:

* env -u HOMEBREW_BOTTLE_DOMAIN brew reinstall fastfetch
* which fastfetch
* file (realpath (which fastfetch))
* sha256sum (which fastfetch)
* /opt/homebrew/bin/fastfetch --version

**Comment by onefish2** [comment]
uname -a
Darwin Mac-Studio.local 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000 x86_64

env -u HOMEBREW_BOTTLE_DOMAIN brew reinstall fastfetch
==> Downloading https://ghcr.io/v2/homebrew/core/fastfetch/manifests/2.21.3-1
Already downloaded: /Users/steve/Library/Caches/Homebrew/downloads/9f34137b9535e860f4348cc07a724e634ec9a3d3ef04deb319056158556b865e--fastfetch-2.21.3-1.bottle_manifest.json
==> Fetching fastfetch
==> Downloading https://ghcr.io/v2/homebrew/core/fastfetch/blobs/sha256:b641531e953f6614a241087b9fbe
Already downloaded: /Users/steve/Library/Caches/Homebrew/downloads/96a884b2cd8530265fb66965164bc9578ebb13085ea6a590210da7608754bba1--fastfetch--2.21.3.sonoma.bottle.1.tar.gz
==> Reinstalling fastfetch
==> Pouring fastfetch--2.21.3.sonoma.bottle.1.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/fastfetch/2.21.3: 40 files, 2.4MB
==> Running `brew cleanup fastfetch`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

which fastfetch
/usr/local/bin/fastfetch

file $(realpath $(which fastfetch))
/usr/local/Cellar/fastfetch/2.21.3/bin/fastfetch: Mach-O 64-bit executable x86_64

sha2 $(which fastfetch)
SHA-256 (/usr/local/bin/fastfetch) = d6c89cb0e8a201d363fc7e83de4dcda39a1c0dde695d1de002ebd533012c7fbe
SHA-384 (/usr/local/bin/fastfetch) = bc30b01534d4cd14325b91dae0ba0b765af427adf721d8986753989ebd12ba3a081a0c6b141f71a542176312243fb6b0
SHA-512 (/usr/local/bin/fastfetch) = dfefba14eda4f24bc0518903e8feba897cd38ad98fedd050c12fcf3dbc357d226993361dfe6bea8cdd6ab5babe4fcc3ea6e10bbdabbeb8bdae133b3d8b5ff9a7

/opt/homebrew/bin/fastfetch --version
-bash: /opt/homebrew/bin/fastfetch: No such file or directory

**Comment by CarterLi** [comment]
> Darwin Mac-Studio.local 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000 x86_64

This means you are using x86_64 of macOS
