### ISSUE TITLE
[FEAT] or maybe not. my program gets detected as shell and gets re-executed by fastfetch 

### ISSUE THREAD

**Issue by BurningPho3nix** [fastfetch-cli/fastfetch#1205]
Be sure to read [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

## Wanted features:

please make it ignore [setup-tool-cli](https://gitlab.com/setup-tooling-project/setup-tool/-/blob/main/cli/setup-tool-cli.c) and maybe [setup-tool-cli-beta](https://gitlab.com/setup-tooling-project/setup-tool/-/blob/testing/CLI/setup-tool-cli-beta.c)
in shell detection

## Motivation:

Bug in my program

**Comment by CarterLi** [comment]
This issue should have been fixed in https://github.com/fastfetch-cli/fastfetch/commit/d0b72c545781e5f4c7b5434db1ea53a2a8144e07 (released in v2.21.0). What version of fastfetch do you use?

**Comment by BurningPho3nix** [comment]
Tested it with fastfetch-2.21.2 on Fedora 40.

You can test as well. My program is available here:

https://copr.fedorainfracloud.org/coprs/burningpho3nix/Setup-Tool/

https://gitlab.com/setup-tooling-project

**Comment by CarterLi** [comment]
If `$FFTS_IGNORE_PARENT` is set to `1`, fastfetch will now ignore the parent process.

Simple test program works for me

```c
#include <stdlib.h>

int main() {
        system("FFTS_IGNORE_PARENT=1 fastfetch");
}
```

**Comment by BurningPho3nix** [comment]
So I just need to change the command I run?

When will the ignore be in a shipping version of ff?

**Comment by CarterLi** [comment]
Should be in the next week.

**Comment by BurningPho3nix** [comment]
Ok
Thanks
