### ISSUE TITLE
[BUG] loadvg_linux is wrong

### ISSUE THREAD

**Issue by Dariqq** [fastfetch-cli/fastfetch#1206]
Hi,

Looking through the loadavg code and in `loadavg_linux.c` fastfetch seems to read `/proc/uptime` instead of `/proc/loadavg`.

Also even if changing to `/proc/loadavg` (and removing the sysinfo code) the format string `sscanf` statement seems wrong:

```
cat /proc/loadavg
2.02 1.44 1.30 3/1633 102474

 ./fastfetch -s loadavg --format json
[
  {
    "type": "Loadavg",
    "result": [
      2.0,
      null,
      null
    ]
  }
]
```

**Comment by CarterLi** [comment]
That was awful

**Comment by CarterLi** [comment]
This means that every scanf(%f) is buggy
