### ISSUE TITLE
[FEAT] Font size per module

### ISSUE THREAD

**Issue by NeoFax75** [fastfetch-cli/fastfetch#1212]
## Wanted features:

Ability to set a font type and size as the colorScheme circles is so small I can barely see it.

## Motivation:

Preserving my eye sight.

**Comment by CarterLi** [comment]
I didn't get what you want.

**Comment by entitybtw** [comment]
![image](https://github.com/user-attachments/assets/9737e2c4-a415-48a0-abc6-84fbffca026d)
he mean how to make these circles bigger

**Comment by CarterLi** [comment]
> ![image](https://github.com/user-attachments/assets/9737e2c4-a415-48a0-abc6-84fbffca026d)
> he mean how to make these circles bigger

You can't.
