### ISSUE TITLE
[BUG] MacOS: Window Manager incorrectly identified when using Yabai WM

### ISSUE THREAD

**Issue by aspauldingcode** [fastfetch-cli/fastfetch#1223]
* What happened:
DE: Aqua
WM: Quartz Compositor

* What should happen:
DE: Aqua
WM: yabai

* Fastfetch version used: fastfetch 2.22.0 (aarch64)
* MacOS version used: Sonoma 14.6.1
* yabaiwm version used: yabai-v7.1.2

**Comment by aspauldingcode** [comment]
And, I know that technically Quartz Compositor is correct... but when running yabai tiling window manager it should be changed to say yabai to reflect the behavior of the Quartz Compositor after yabai hax.

**Comment by CarterLi** [comment]
Dup #1087
