### ISSUE TITLE
[FEAT] Build number in macOS

### ISSUE THREAD

**Issue by volsk** [fastfetch-cli/fastfetch#1224]
Be sure to read [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

## Wanted features:

See build number on macOS

The call for the build number is already in os_apple.m
```
    if(os->buildID.length == 0)
        ffSysctlGetString("kern.osversion", &os->buildID);
```

The proposed output is
```
OS: macOS Sequoia 15.0 (24A5331b) arm64
```
## Motivation:
Especially on beta versions the build number gives more information than the macOS version string.

**Comment by CarterLi** [comment]
You may use `--os-format`
