### ISSUE TITLE
Weird Ubuntu logo

### ISSUE THREAD

**Issue by tiagorangel2011** [fastfetch-cli/fastfetch#1226]
The Ubuntu logo looks rly weird, the neofetch one is way better.
![fastfetch ubuntu logo](https://github.com/user-attachments/assets/8e55290e-aaa5-49fb-b3d4-0907b78a899a)

![BETTER neofetch ubuntu logo](https://github.com/user-attachments/assets/efcfc9bd-2d90-43be-b0f5-eb309ca0909a)

**Comment by tiagorangel2011** [comment]
idk if it's that the neofetch one is not updated, but the fastfetch one still seems weird...

**Comment by CarterLi** [comment]
It's current design of Ubuntu logo (the white parts)

![ubuntu](https://assets.ubuntu.com/v1/a7e3c509-Canonical%20Ubuntu.svg)

> but the fastfetch one still seems weird

That's because you are familiar with neofetch. If you prefer the old one, you can use `fastfetch -l ubuntu_old`

**Comment by daevidvincent** [comment]
I also prefer the "old" one (and honestly feel that should be the default). I came here thinking something was broken as well, just like @tiagorangel2011 did.
