### ISSUE TITLE
[FEAT] 32-bit Linux build?

### ISSUE THREAD

**Issue by skipster1337** [fastfetch-cli/fastfetch#1235]
## Wanted features:

Would be nice to provide a build for 32-bit Linux systems instead of having to build it manually. I know that there are very few people still using 32-bit x86, so if it's too much to ask for, I understand.

## Motivation:

I use a 32 bit laptop with Debian and realized the only way to currently get fastfetch on it was to compile it from source. However, a ready to use .deb package would have been nice.

**Comment by BrycensRanch** [comment]
Hi! This sounds like more of a Debian issue considering fastfetch is packaged there. Now for the GitHub repository producing 32-bit builds I don’t see why they’d do it. 32 bit is only going down.

**Comment by skipster1337** [comment]
They don't have fastfetch on 12 at all yet, but they will include it in 13 as seen by the testing and sid repositories, 32-bit included.
But yeah I get the point, too much work to build for 32-bit specifically.

**Comment by Princess-Sunset-Shimmer** [comment]
isn't 32-bit an abandoned standard?

**Comment by BrycensRanch** [comment]
Well yes, but that's why Debian exists and Debian maintain their 32 bit support.

**Comment by Princess-Sunset-Shimmer** [comment]
Future, lesser and lesser will have maintenance of 32bit. More and more have abandoned maintenance of 32bit (or starting to abandon maintenance of 32bit). The need of 32bit computing standard of binary digital computer is over

**Comment by Guiorgy** [comment]
As a workaround, you can write a script that checks for updates daily, pulls the latest source archive and builds it. I have an armfh RPI that does that, and it even has a local apt repo for fastfetch, so I can update fastfetch through apt.

**Comment by barracuda156** [comment]
@Princess-Sunset-Shimmer We maintain 32-bit arch for macOS (ppc, i386) in MacPorts, `fastfetch` works at least on 32-bit PowerPC.

OpenBSD and NetBSD support 32-bit systems in current.
