### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Cardiacman13** [fastfetch-cli/fastfetch#1242]
# General description of bug:

* What happened:  
  Fastfetch incorrectly identifies the GPU as "NVIDIA GN21-X11" instead of the expected "Nvidia RTX 4090 Mobile."
  
* What should happen:  
  Fastfetch should correctly identify and display the GPU as "Nvidia RTX 4090 Mobile."

* Fastfetch version used:  
  Latest : 2.23.0

* Did it work in an older version:  
  No

* Where did you get the binary:  
PPA but i try on other distribution and it's the same

# Often helpful information:

Screenshot:  

![image](https://github.com/user-attachments/assets/1c7d7bbd-0b42-4b67-ae14-d95aacf3abaf)

**Comment by CarterLi** [comment]
`fastfetch -s gpu --format json` please

**Comment by Cardiacman13** [comment]
```  {
    "type": "GPU",
    "result": [
      {
        "coreCount": null,
        "coreUsage": null,
        "memory": {
          "dedicated": {
            "total": null,
            "used": null
          },
          "shared": {
            "total": null,
            "used": null
          }
        },
        "driver": "nvidia (proprietary) 550.107.02",
        "name": "GN21-X11",
        "temperature": null,
        "type": "Unknown",
        "vendor": "NVIDIA",
        "platformApi": "",
        "frequency": 0,
        "deviceId": 40284
      }
    ]
  },
  {
    "type": "OpenGL",
    "result": {
      "version": "4.6.0 NVIDIA 550.107.02",
      "renderer": "NVIDIA GeForce RTX 4090 Laptop GPU/PCIe/SSE2",
      "vendor": "NVIDIA Corporation",
      "slv": "4.60 NVIDIA",
      "library": "EGL 1.5"
    }
  },
  {
    "type": "Vulkan",
    "result": {
      "apiVersion": "1.3.277",
      "conformanceVersion": "1.3.2",
      "driver": "NVIDIA [550.107.02]",
      "gpus": [
        {
          "type": "Discrete",
          "vendor": "NVIDIA",
          "name": "NVIDIA GeForce RTX 4090 Laptop GPU",
          "driver": "550.107.02",
          "platformApi": "Vulkan 1.3.277",
          "deviceId": 10071,
          "memory": {
            "dedicated": {
              "total": 17171480576,
              "used": null
            },
            "shared": {
              "total": 25045416960,
              "used": null
            }
          },
          "deviceId": 10071
        }
      ]
    }
  }
]
``` 
```cat /sys/class/drm/card{0,1,2}/device/ueven
cat: /sys/class/drm/card0/device/ueven: Aucun fichier ou dossier de ce nom
```

**Comment by CarterLi** [comment]
uevent, not ueven...

**Comment by Cardiacman13** [comment]
The file does not exist

**Comment by CarterLi** [comment]
Can you please run the command **exactly**? Even if the file does not exist, the command should print the error message **three times**.

Anyway `fastfetch --gpu-detection-method vulkan` should work.

**Comment by Cardiacman13** [comment]
sorry : 

```DRIVER=simple-framebuffer
MODALIAS=platform:simple-framebuffer
DRIVER=nvidia
PCI_CLASS=30000
PCI_ID=10DE:2757
PCI_SUBSYS_ID=1028:0C9D
PCI_SLOT_NAME=0000:01:00.0
MODALIAS=pci:v000010DEd00002757sv00001028sd00000C9Dbc03sc00i00
```

**Comment by CarterLi** [comment]
So it's not a fastfetch bug. `/usr/share/hwdata/pci.ids` contains only `GN21-X11`

![image](https://github.com/user-attachments/assets/2afec6d5-513f-4789-879c-5dabcb1c3be1)

https://admin.pci-ids.ucw.cz/read/PC/10de/2757

**Comment by CarterLi** [comment]
pci.ids database got updated yesterday with 2757 fixed: https://github.com/pciutils/pciids/commit/23068846b41b155dd4b31cf3a9dcfe4d1e065125#diff-b6c061cb8891af78232378edf0bfdd0f5d4d3bafa3256f4f3cebc67d7d829f1dL13134

You can fix this issue by manually [downloading the file](https://github.com/pciutils/pciids/raw/master/pci.ids) and overwrite `/usr/share/hwdata/pci.ids`
