### ISSUE TITLE
[BUG] "dinit" init system incorrectly identified as just "init"

### ISSUE THREAD

**Issue by JamiKettunen** [fastfetch-cli/fastfetch#1245]
Be sure to read the [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

# General description of bug:

* What happened: `dinit` init system shown as just `init` without version in `fastfetch -l none -s initsystem`
* What should happen: `Init System: dinit 0.18.0` (I can get `Init System: dinit` without the version to show up if I append e.g. `init=/bin/dinit` to kernel cmdline)
* Fastfetch version used: 2.23.0
* Did it work in an older version: Don't remember it ever working since the introduction of the init system module in [2.14.0](https://github.com/fastfetch-cli/fastfetch/releases/tag/2.14.0)
* Where did you get the binary: Chimera Linux apk repository package (I'm the package maintainer)
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Yes ([2.23.0](https://github.com/fastfetch-cli/fastfetch/releases/tag/2.23.0) just released)

# Often helpful information:

Screenshot:
![image](https://github.com/user-attachments/assets/f60a1873-d270-46d6-a11e-512e1ff9bd31)

Output of `fastfetch -s initsystem --format json`:
```
[
  {
    "type": "InitSystem",
    "result": {
      "name": "init",
      "exe": "/usr/bin/dinit",
      "version": "",
      "pid": 1
    }
  }
]
```

Output of `fastfetch --list-features`:
```
threads
vulkan
wayland
xcb-randr
xcb
xrandr
x11
drm
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
egl
osmesa
opencl
libpulse
libddcutil
libelf
libzfs
System yyjson
linux/videodev2
linux/wireless
```

**Comment by JamiKettunen** [comment]
@CarterLi Thanks for the quick patches :) seems it's trying to parse the version from the second output line instead of the first as `fastfetch -l none -s initsystem` now returns `Init System: dinit supplemental-groups`

**Comment by CarterLi** [comment]
Please try it again

**Comment by JamiKettunen** [comment]
Working properly now, thanks again!
![image](https://github.com/user-attachments/assets/42721895-8887-4967-aac9-59470ee2ee20)
