### ISSUE TITLE
[BUG] When the Weather is unavailable it kills Fastfetch

### ISSUE THREAD

**Issue by mac2net** [fastfetch-cli/fastfetch#1246]
I apologise if someone else has reported this already.

Occasionally the weather is unavailable and when this happens Fastfetch hangs at that point. 

When the weather module is commented out, Fastfetch resumes working.

Since Fastfetch is dependent on an external source/provider to get the weather, it might be useful to give the module a timeout, if possible.

Cheers
Mac

**Comment by CarterLi** [comment]
`timeout` of `Weather` module is already supported in Linux, FreeBSD and Windows.

**Comment by mac2net** [comment]
Thanks. Found it. Got it working.
