### ISSUE TITLE
[ security ] Enforce "Require signed commits"

### ISSUE THREAD

**Issue by yonas** [fastfetch-cli/fastfetch#1250]
I was looking through the git history and for some reason, a few commits are not signed. Might be an avenue of attack.

**Comment by CarterLi** [comment]
I have 1 PC, 3 laptops, 1 android phone and a lot VMs. Some time I even need to test fastfetch on Live CD. I don't think I want to set up gpg on every platform / device I use.

**Comment by yonas** [comment]
@CarterLi I wouldn't setup GPG on all those devices either. I'd choose one, likely not a portable device, and designate that as the machine that does the final `git push`.

For example - you could setup a local Gitea / Forego and have your devices push there. Then from your trusted machine, run a `git pull` and `git push github`, where `github` is a remote that points to `git@github.com:fastfetch-cli/fastfetch`.
