### ISSUE TITLE
[BUG] Cant install in ish with apk add

### ISSUE THREAD

**Issue by peterge-misoft** [fastfetch-cli/fastfetch#1252]
# General description of bug:

* What happened: I cant install fastfetch in [ish](https://apps.apple.com/us/app/ish-shell/id1436902243) (Alpine)
* What should happen: It should install

# Often helpful information:

Screenshot:
![image](https://github.com/user-attachments/assets/b3833a70-0d4a-4e73-a734-0b698d00925a)

**Comment by CarterLi** [comment]
We don't support iOS.
