### ISSUE TITLE
[FEAT] Support parameters/options when running shell command

### ISSUE THREAD

**Issue by FreeHarry** [fastfetch-cli/fastfetch#1255]
## Wanted features: 

Support considering parameters/options when specifying a shell program, e.g. to run a command with Shell `pwsh`, PLUS parameter `-NoProfile`.

```
{
    "type": "command",
    "shell": "pwsh -NoProfile",
    "text": "(git --version).Substring(12)",
    "key": "Git"
},
```
Currently it seems not supported at the moment, because it is not working on my side with fastfetch 2.23.0.

## Motivation:

Shells can be started with different options/parameters, which is sometimes even required to control the behavior of the shell in specific situations.

**Comment by CarterLi** [comment]
This is 2x faster than using pwsh

```bat
@ECHO OFF
REM ~/git_version.bat
FOR /F "delims=" %%i IN ('git version') DO SET "GIT_VERSION=%%i"
ECHO %GIT_VERSION:~12%
```

```json
{
  "type": "command",
  "text": "%USERPROFILE%\\git_version.bat",
  "key": "Git"
}
```
