### ISSUE TITLE
[BUG] WSL: battery shown as 0% [AC Connected] on desktop pc

### ISSUE THREAD

**Issue by edo9300** [fastfetch-cli/fastfetch#1261]
Running fastfetch on windows under WSL 1 on a desktop pc, will show the battery as being present, with no charge and the pc being ac connected, this program seems to be reading the files from `/sys/class/power_supply/battery`, and indeed on WSL that folder is present and populated, these are the files present with their contents (I suppose they're dummy/random values):
```
capacity		0
charge_counter	128
current_now		462
health			Good
present			(empty file)
status			Full
technology		Li-ion
temp			258
type			Battery
voltage_now		4294952836000
```

**Comment by CarterLi** [comment]
> I suppose they're dummy/random values

How can fastfetch know if they are dummy/random values?
