### ISSUE TITLE
[FEAT] `-DPACKAGES_DISABLE_*` is highly unergonomic

### ISSUE THREAD

**Issue by classabbyamp** [fastfetch-cli/fastfetch#1272]
Having to specify 24 cmake arguments to only show one package manager by default is very annoying (and takes up a lot of space in the command line). It would be nice if it was one of:
```
-DPACKAGES_ENABLE=foo,bar,baz
```
```
-DPACKAGES_DISABLE=foo,bar,baz
```

**Comment by CarterLi** [comment]
The current solution is designed for cmake-gui

![image](https://github.com/user-attachments/assets/1505a1e9-6312-4d74-a356-a820d260dc8d)

Just select the package managers you want to disable. If you don't use GUI, you can use ccmake

**Comment by classabbyamp** [comment]
I don't use either cmake-gui or ccmake, I'm the Void Linux package maintainer and I'd rather not keep a large list of cmake arguments in our template

**Comment by classabbyamp** [comment]
additionally, only being able to explicitly disable and not explicitly enable means we'd have to keep adding more as fastfetch adds them, instead of the cmake arguments list being relatively stable

**Comment by CarterLi** [comment]
> additionally, only being able to explicitly disable and not explicitly enable means we'd have to keep adding more as fastfetch adds them, instead of the cmake arguments list being relatively stable

It was designed not to disable anything implicitly. You may want to enable xbps with `-DPACKAGES_ENABLE=xbps` since you are the void linux package manager, and you accidentally disabled flatpak. That's what I don't want.
