### ISSUE TITLE
[FEAT] follow symlinks

### ISSUE THREAD

**Issue by treeshateorcs** [fastfetch-cli/fastfetch#1280]
Be sure to read [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue. 
✅

## Wanted features:
I want fastfetch to support following symlinks

## Motivation:
![image](https://github.com/user-attachments/assets/2af825a3-3558-4963-a6e6-16dc5b837e86)

take a close look at "Terminal"

**Comment by CarterLi** [comment]
We can't do that because some package managers do rely on symlinks. For example, all snap commands are symlinks to `/usr/bin/snap`
