### ISSUE TITLE
[BUG] Fastfetch doesn't work with Winget packages

### ISSUE THREAD

**Issue by yesseruser** [fastfetch-cli/fastfetch#1287]
# General description of bug:

* What happened: Fastfetch doesn't show Winget packages, and shows Chocolatey packages instead. (I don't have Chocolatey installed)
* What should happen: Fastfetch should correctly count the number of packages installed with Winget (can be listed with `winget list`) and not show Chocolatey packages unless they were installed with Chocolatey (I'm not sure how to check that)
* Fastfetch version used: 2.25.0
* Did it work in an older version: Not sure, haven't used anything older
* Where did you get the binary: Installed with Winget.
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Yes

# Often helpful information:

Screenshot:
![obrazek](https://github.com/user-attachments/assets/e218611b-633f-485f-8669-648b23409771)

The content of the configuration file you use (if any):
None used

Output of `fastfetch -c ci.jsonc --format json`:
[output.json](https://github.com/user-attachments/files/17089851/output.json)

Output of `fastfetch --list-features`:
```
threads
vulkan
imagemagick7
zlib
opencl
```

**Comment by CarterLi** [comment]
What does `echo $env:ChocolateyInstall` print?

You should also try `fastfetch --packages-disabled choco`

**Comment by CarterLi** [comment]
No reply for 1 week. I assume you have resolved this issue yourself.

**Comment by tordenflesk** [comment]
> What does `echo $env:ChocolateyInstall` print?
> 
> You should also try `fastfetch --packages-disabled choco`

No way to show both?
