### ISSUE TITLE
[BUG] Hangs for TerminalFont in Kitty

### ISSUE THREAD

**Issue by howyay** [fastfetch-cli/fastfetch#1289]
# General description of bug:

* What happened: Hangs for TerminalFont and all that follows won't be shown
* What should happen: all fetch categories displayed correctly
* Fastfetch version used: 2.24.0
* Did it work in an older version: 2.23.0
* Where did you get the binary: NixOS nixpkgs
* Does this issue still occur in the latest dev build: at the time of filing, yes

# Often helpful information:

It works on Alacritty and foot

Screenshot:
![2024-09-23_02-45](https://github.com/user-attachments/assets/a7a33508-1339-40e6-aa0d-d9f53cea29c9)

- No custom configuration

- `fastfetch -c ci.jsonc --format json` hangs

Output of `fastfetch --list-features`:
```
threads
vulkan
wayland
xcb-randr
xcb
xrandr
x11
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
sqlite3
egl
glx
opencl
libpulse
libddcutil
libzfs
System yyjson
linux/videodev2
linux/wireless
```

## If fastfatch crashed or froze

```shell
strace fastfetch --multithreading false -s TerminalFont --pipe
```

Yields: [pub.microbin.eu/upload/eel-turkey-bird](https://pub.microbin.eu/upload/eel-turkey-bird)
For comparison, the following is for CPU (which works):
[pub.microbin.eu/upload/ape-falcon-snail](https://pub.microbin.eu/upload/ape-falcon-snail)

Will follow up with `git bisect` if I have time tomorrow

**Comment by CarterLi** [comment]
> Yields: https://pastebin.com/Tw7bc2LQ
> 
> For comparison, the following is for CPU (which works): https://pastebin.com/dmzaVcpf

`This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff.`

Seems you made it private

**Comment by howyay** [comment]
It appears to be auto deleted by pastebin every time I try to create it - trying some other services...

-s TerminalFont:
https://pub.microbin.eu/upload/eel-turkey-bird

-s CPU:
https://pub.microbin.eu/upload/ape-falcon-snail

**Comment by CarterLi** [comment]
What does `echo -e '\eP+q6b697474792d71756572792d666f6e745f66616d696c79;6b697474792d71756572792d666f6e745f73697a65\e\\'` print?

**Comment by ThatOneOcto** [comment]
im getting this too any help? 
![2024-09-23_17-25](https://github.com/user-attachments/assets/831e77f0-51d2-4325-81f5-b0eb665238e3)

**Comment by CarterLi** [comment]
> What does `echo -e '\eP+q6b697474792d71756572792d666f6e745f66616d696c79;6b697474792d71756572792d666f6e745f73697a65\e\\'` print?

This

**Comment by howyay** [comment]
Nothing but it puts a string into my prompt ![image](https://github.com/user-attachments/assets/c2c163ce-e827-47e4-a713-0d7535a1c437)

**Comment by CarterLi** [comment]
Can you please test if https://github.com/fastfetch-cli/fastfetch/commit/29ae56e76a8fc8258a3fb316248d737468e49db8 fixes your issue?

**Comment by howyay** [comment]
> Can you please test if [29ae56e](https://github.com/fastfetch-cli/fastfetch/commit/29ae56e76a8fc8258a3fb316248d737468e49db8) fixes your issue?

It works, godly speed, thanks!

**Comment by CarterLi** [comment]
Off topic. Can you verify if the flatpak package count matches the result of `flatpak list` (or `flatpak list --user`?

**Comment by howyay** [comment]
> Off topic. Can you verify if the flatpak package count matches the result of `flatpak list` (or `flatpak list --user`?

it matches of number of results of `flatpak list --user`, yes, in the development version. In 2.24.0, it matches the number of results of `flatpak list --user --app`

**Comment by CarterLi** [comment]
Good. If you use AMD GPUs, you may also help <https://github.com/fastfetch-cli/fastfetch/issues/1284>.

Thanks

**Comment by ThatOneOcto** [comment]
> Can you please test if [29ae56e](https://github.com/fastfetch-cli/fastfetch/commit/29ae56e76a8fc8258a3fb316248d737468e49db8) fixes your issue?

commit works tysm 🙏🙏🙏🙏🙏
