### ISSUE TITLE
[BUG] LocalIp detection is inaccurate

### ISSUE THREAD

**Issue by Aoang** [fastfetch-cli/fastfetch#1299]
Fastfetch retrieves the Local IP, it receives Surge's fake IP CIDR of 198.18.0.1/8, and the MAC address is all zeros.

Because Surge v5.8.0 deprecated the TUN takeover solution and switched to using Network Extension, adopting a VPN mode to manage network connections.

There is a problem with Fastfetch's detection method.

```shell
> fastfetch -s localip --format json
[
  {
    "type": "LocalIp",
    "result": [
      {
        "defaultRoute": true,
        "ipv4": "198.18.0.1/8",
        "ipv6": "",
        "mac": "",
        "name": "utun6",
        "mtu": -1,
        "speed": -1
      }
    ]
  }
]
```

- [Surge Release Notes](https://kb.nssurge.com/surge-knowledge-base/release-notes/surge-mac#version-5.8.0)

**Comment by CarterLi** [comment]
It's expected. Fastfetch reports default route by default. If you want to display other interface, use `fastfetch --localip-default-route-only false --localip-name-prefix <interface-name>`
