### ISSUE TITLE
[BUG] trailing newline on gpu name

### ISSUE THREAD

**Issue by Dariqq** [fastfetch-cli/fastfetch#1303]
# General description of bug:

* What happened: Updated fastfetch on a raspberry pi and there is an extra "\n" in the gpu name which breaks the formatted output
* What should happen:
* Fastfetch version used: 2.26.1
* Did it work in an older version: Previous versions had an error instead
* Where did you get the binary: Built from source with minimal dependencies.
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Yes

# Often helpful information:

```
 fastfetch --list-features
threads
zlib
linux/videodev2
linux/wireless
```

Output on `2.26.1`
```
fastfetch -s gpu --format json
[
  {
    "type": "GPU",
    "result": [
      {
        "index": null,
        "coreCount": null,
        "coreUsage": null,
        "memory": {
          "dedicated": {
            "total": null,
            "used": null
          },
          "shared": {
            "total": null,
            "used": null
          }
        },
        "driver": "vc4-drm",
        "name": "bcm2835-vc4\n",
        "temperature": null,
        "type": "Integrated",
        "vendor": "Brcm",
        "platformApi": "DRM (card0)",
        "frequency": 0,
        "deviceId": 0
      }
    ]
  }
]

```

The output on `2.25.0`
```
 ./fastfetch -s gpu --format json
[
  {
    "type": "GPU",
    "error": "GPU detection failed"
  }
]
``

**Comment by CarterLi** [comment]
Please test

**Comment by XhmikosR** [comment]
@CarterLi do you plan to cut a new patch release with this fix?

**Comment by CarterLi** [comment]
Just made some changes to `cpu` `gpu` and `board` modules. If you can test the changes if they work fine for raspberry pi, I'm happy to cut a release.
