### ISSUE TITLE
[FEAT] OpenWRT support

### ISSUE THREAD

**Issue by webysther** [fastfetch-cli/fastfetch#1306]
## Wanted features:

Add the package compiled on opkg of OpeWRT `opkg install fastfetch`

## Motivation:

No need to compile from source.

**Comment by webysther** [comment]
Sorry, for me the package maintaner that provide the compiled version in the package manager.

**Comment by APCCV** [comment]
I know this is closed and 3.5 months old... but this is what you were looking for?

```
root@TestWrt-63:~# fastfetch 
 _______                        root@TestWrt
|       |.-----.-----.-----.    ---------------
|   -   ||  _  |  -__|     |    OS: OpenWrt SNAPSHOT armv7l
|_______||   __|_____|__|__|    Host: TP-Link Archer C2600
         |__|                   Kernel: Linux 6.6.71
 ________        __             Uptime: 11 days, 6 hours, 23 mins
|  |  |  |.----.|  |_           Packages: 170 (apk)
|  |  |  ||   _||   _|          Shell: ash 1.37.0
|________||__|  |____|          Terminal: dropbear
                                CPU: Generic DT based system (2) @ 1.40 GHz
                                Memory: 93.42 MiB / 463.99 MiB (20%)
                                Swap: Disabled
                                Disk (/): 3.34 MiB / 21.12 MiB (16%) - overlay
                                Disk (/overlay): 3.34 MiB / 21.12 MiB (16%) - jffs2
                                Local IP (br-lan): 192.168.1.63/24
                                Locale: C
```

Of course it prints in colour.
Possibly one of the most pointless packages I've ever built.
I have a simple Makefile for it.

**Comment by APCCV** [comment]
Never mind... wrong forum.
If you still want this open a thread at OpenWrt forums and let's see if there is demand.

**Comment by APCCV** [comment]
Opened a topic for it at openwrt forums... let's see what reaction I get.

**Comment by KiGamji** [comment]
> I have a simple Makefile for it.

could you share it please?

**Comment by inoribea** [comment]
> I know this is closed 和 3.5 个月之前 old... but this is what you were looking for?
> 
> ```
> root@TestWrt-63:~# fastfetch 
>  _______                        root@TestWrt
> |       |.-----.-----.-----.    ---------------
> |   -   ||  _  |  -__|     |    OS: OpenWrt SNAPSHOT armv7l
> |_______||   __|_____|__|__|    Host: TP-Link Archer C2600
>          |__|                   Kernel: Linux 6.6.71
>  ________        __             Uptime: 11 days, 6 hours, 23 mins
> |  |  |  |.----.|  |_           Packages: 170 (apk)
> |  |  |  ||   _||   _|          Shell: ash 1.37.0
> |________||__|  |____|          Terminal: dropbear
>                                 CPU: Generic DT based system (2) @ 1.40 GHz
>                                 Memory: 93.42 MiB / 463.99 MiB (20%)
>                                 Swap: Disabled
>                                 Disk (/): 3.34 MiB / 21.12 MiB (16%) - overlay
>                                 Disk (/overlay): 3.34 MiB / 21.12 MiB (16%) - jffs2
>                                 Local IP (br-lan): 192.168.1.63/24
>                                 Locale: C
> ```
> 
> Of course it prints in colour. I have a simple Makefile for it.

I also using Glinet router.

could you share it please?

**Comment by KiGamji** [comment]
I think I'ma try and make it to openwrt packages/master branch

**Comment by APCCV** [comment]
> I think I'ma try and make it to openwrt packages/master branch

Sure. Good luck.
I posted the Makefile at forums.openwrt. You can find the thread over there. 
TBH I don't have the time to own this going forward, and I really don't use it. It needs a better owner than me.
I do find it interesting and that's why I made this file.
Here is the Makefile in any case.

```
PKG_VERSION:=2.35.0
PKG_RELEASE:=1

PKG_SOURCE:=$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/
PKG_HASH:=e066d84f9ca176e24f162ce99dab7fac5238b5e8c94ab4aaff5850b6cc5c6ead

PKG_BUILD_DIR:=$(BUILD_DIR)/fastfetch-$(PKG_VERSION)

PKG_MAINTAINER:=YOUR NAME HERE <your.email@goes.here>
PKG_LICENSE:=MIT
PKG_LICENSE_FILES:=LICENSE
PKG_CPE_ID:=cpe:/a:fastfetch:fastfetch

include $(INCLUDE_DIR)/package.mk
include $(INCLUDE_DIR)/cmake.mk

define Package/fastfetch
  CATEGORY:=Utilities
  TITLE:=Fetch and display system information
endef

define Package/fastfetch/description
  Fastfetch is a tool for fetching system information and displaying it prettily.
endef

define Package/fastfetch/install
        $(INSTALL_DIR) $(1)/usr/bin
        $(INSTALL_BIN) $(PKG_BUILD_DIR)/fastfetch $(1)/usr/bin/
endef

$(eval $(call BuildPackage,fastfetch))
```

What you would need to do for this mission, if you choose to accept it (apologies if I am being too obvious)...
- fork the packages repo and clone it
- make a utils/fastfetch directory
- place the contents above in a file called "Makefile" (edit PKG_MAINTAINER line with real info)
- git commit -s (commits must be signed off)
- create a PR with your fork

If you just want to try it out first, download the openwrt SDK for your platform, add it there, and follow instructions on site on how to compile as a single package for your device.

And if you get stuck, feel free to reach out here or there. Good luck!

**Comment by icyleaf** [comment]
Litte tips: needs append `CMAKE_OPTIONS += -DHAVE_STATX=0` to disable statx in musl lib.

**Comment by AlbrechtL** [comment]
There are currently two PRs open to put this great tool into the OpenWrt package repository
* https://github.com/openwrt/packages/pull/27949
* https://github.com/openwrt/packages/pull/29564
