### ISSUE TITLE
[BUG] CPU Temperature shows 0.0°C on 2.26.1 but shows correct on 2.25.0

### ISSUE THREAD

**Issue by K4r0qtuYNE5G4qgZ** [fastfetch-cli/fastfetch#1311]
Be sure to read the [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

# General description of bug:

* What happened: Shows CPU Temp 0.0°C
* What should happen: Show correct CPU Temp
* Fastfetch version used: 2.26.1
* Did it work in an older version: Yes, 2.25.0
* Where did you get the binary: Ubuntu: [ppa:zhangsongcui3371/fastfetch]
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)?  I don't know, I was not able to download it with wget

**Comment by CarterLi** [comment]
It should have been fixed in #1308 

You should try the dev build
