### ISSUE TITLE
[FEAT] Razer Headset battery indicator

### ISSUE THREAD

**Issue by konn-neko** [fastfetch-cli/fastfetch#1313]
## Wanted features:

if possible, the ability to see headset battery vis fastfetch
## Motivation:

i remembered my logitech g935 would report its battery on linux, but i dont remember if razer does, so if it does have some sort of feature, would be lovwely to see

**Comment by CarterLi** [comment]
If supported, bluetooth module will report its battery level

Tested with my Sony-1000X

![image](https://github.com/user-attachments/assets/b1d37cea-95e5-4911-be98-5399335fc264)

**Comment by konn-neko** [comment]
> If supported, bluetooth module will report its battery level
> 
> Tested with my Sony-1000X
> 
> ![image](https://private-user-images.githubusercontent.com/6134068/375660761-b1d37cea-95e5-4911-be98-5399335fc264.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2ODUwNjQsIm5iZiI6MTcyODY4NDc2NCwicGF0aCI6Ii82MTM0MDY4LzM3NTY2MDc2MS1iMWQzN2NlYS05NWU1LTQ5MTEtYmU5OC01Mzk5MzM1ZmMyNjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTFUMjIxMjQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzFmZmM1NDFjZTg1ZmFiMDgxNzhlODA5ZTNhMWU1MGI2NmY2YmQzYzM3Zjc1OWIxYmM4YTc3Zjc3ZjQyMzk2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ytFqtXfclIuGBtiwW-5toA9VbZ6yWcCBpMgGOCVZTqA)

what about through usb?

**Comment by CarterLi** [comment]
You can connect a headset through usb?

**Comment by konn-neko** [comment]
> You can connect a headset through usb?

yup, just unsure how razer reports battery as i havent looked into its usb protocol, logitec natively sends it
