### ISSUE TITLE
[BUG] tpm n\a

### ISSUE THREAD

**Issue by wincmd64** [fastfetch-cli/fastfetch#1314]
* Fastfetch version used:  2.26.1 (win10)

❯ fastfetch -s tpm --format json
[
  {
    "type": "TPM",
    "error": "Tbsi_GetDeviceInfo() failed"
  }
]

tpm does not show anything even "not installed"

PS. pls remove host from stadart **BluetoothRadio** output:
Bluetooth Radio (_host-name_): Bluetooth 5.1 (Intel)

**Comment by CarterLi** [comment]
Set `key`

**Comment by wincmd64** [comment]
wtf is "key" ?
