### ISSUE TITLE
[FEAT] print path all all logo files in fastfetch on windows installed via choco

### ISSUE THREAD

**Issue by Dxuian** [fastfetch-cli/fastfetch#1317]
Be sure to read [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

## Wanted features:
a cmd to print the file path that contains all logos 

## Motivation:
It'd be easier to edit the file just like in neofetch

**Comment by CarterLi** [comment]
fastfetch --print-logos

**Comment by Dxuian** [comment]
> fastfetch --print-logos

no what i meant was the location of the file that contains logos , similar to the neofetch file in /usr/bin

**Comment by CarterLi** [comment]
Logos were compiled in the binaries. You can't find it.
