### ISSUE TITLE
[FEAT] A switch to suppress the logo

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [fastfetch-cli/fastfetch#1322]
## Wanted features:

Command-line switch to suppress the logo.

## Motivation:

The better to paste into places where one's system specs are needed.

neofetch had that feature (in that it had `neofetch --off`).

Perhaps the user could create a custom config file in order to achieve the same result, but a command-line switch would be easier.

Thanks for your time.

**Comment by CarterLi** [comment]
fastfetch -l none

**Comment by LinuxOnTheDesktop** [comment]
Wow. That was fast. I did look in the man page; this option is not mentioned there.
