### ISSUE TITLE
[BUG] Images cant be rendered in TMUX

### ISSUE THREAD

**Issue by Sk7Str1pe** [fastfetch-cli/fastfetch#1326]
# General description of bug:

Expected behavior : render png in tmux (kitty is used)
![image](https://github.com/user-attachments/assets/f9f2eb75-c79d-47e6-a8e1-28f944d4be90)
fastfetch with kitty alone

actual behavior:
![image](https://github.com/user-attachments/assets/770f4acf-50d6-4ed8-bcd4-690e0cfdd60d)
yazi can display images tho

version used: fastfetch 2.26.1 (x86_64)
no idea if worked in older versions
installed with Nixpkgs (unstable)

image protocol : icat
term : kitty + tmux
image : 
![nixos-logo](https://github.com/user-attachments/assets/4e6ad989-d73b-4e5e-b761-af9889c04721)
nah it doesnt work with height and width

**Comment by CarterLi** [comment]
See https://github.com/fastfetch-cli/fastfetch/discussions/1039#discussioncomment-10860217
