### ISSUE TITLE
[BUG] fastfetch hangs with "kitty" and fails to display images

### ISSUE THREAD

**Issue by FyrelWhister** [fastfetch-cli/fastfetch#1329]
fastfetch hangs with "kitty" and fails to display images

Description: When using fastfetch with the "kitty" terminal, the command hangs indefinitely. In the "kitty-dyrect" terminal, fastfetch runs but does not display the image. The attached image (JPEG) works fine with icat in kitty.

Steps to reproduce:

Set the image path in ~/.config/fastfetch/config.jsonc.
Run fastfetch in "kitty" terminal — it hangs.
Run fastfetch in "kitty-dyrect" terminal — the image does not display.
Expected behavior: fastfetch should display the image.

Version: fastfetch 2.27.1 (x86_64)
OS: Linux Mint 22
Terminal: Kitty
Kernel: 6.8.0-38-generic
![CAT](https://github.com/user-attachments/assets/9d01b464-04a6-4faa-8fa0-b705d2fe4ba5)

**Comment by FyrelWhister** [comment]
// ~/.config/fastfetch/config.jsonc
// See https://github.com/fastfetch-cli/fastfetch/wiki/Configuration for more details
// See *.jsonc in https://github.com/fastfetch-cli/fastfetch/tree/dev/presets/examples for more examples
{
  "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
  //"logo": {
  //    "type": "small"
  //},
   "logo": {
       "type": "kitty",
       "source": "~/.config/fastfetch/CAT.jpeg",
       "height": 11
   },
  "display": {
      "separator": "  "
  },
  "modules": [
      {
          "type": "title",
          "color": {
              "user": "red",
              "at": "cyan",
              "host": "blue"
          }
      },
      {
          "type": "os",
          "key": "OS",
          "keyColor": "yellow",
          "format": "{2} {8}"
      },
      {
          "type": "kernel",
          "key": " ",
          "keyColor": "yellow"
      },
      {
          "type": "cpu",
          "key": "PC",
          "keyColor": "green"
      },
      {
          "type": "disk",
          "key": " ",
          "keyColor": "green"
      },
      {
          "type": "memory",
          "key": " 󰑭",
          "keyColor": "green"
      },
      {
          "type": "wmtheme",
          "key": "UI",
          "keyColor": "magenta"
      },
      {
          "type": "icons",
          "key": " 󰀻",
          "keyColor": "magenta"
      },
      {
          "type": "colors",
          "key": " ",
          "keyColor": "magenta",
          "symbol": "circle"
      }
  ]


}

**Comment by CarterLi** [comment]
Cannot reproduce

![image](https://github.com/user-attachments/assets/e962d205-3f7f-4158-a153-7c093b979c4c)

**Comment by CarterLi** [comment]
> In the "kitty-dyrect" terminal, fastfetch runs but does not display the image

It's kitty-d**i**rect. It support png images only. You have to convert your jpeg image to png before using.

**Comment by FyrelWhister** [comment]
> Cannot reproduce
> 
> ![image](https://private-user-images.githubusercontent.com/6134068/374761866-e962d205-3f7f-4158-a153-7c093b979c4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjA5NDQsIm5iZiI6MTcyODQ2MDY0NCwicGF0aCI6Ii82MTM0MDY4LzM3NDc2MTg2Ni1lOTYyZDIwNS0zZjdmLTQxNTgtYTE1My03YzA5M2I5NzljNGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDlUMDc1NzI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGE3ZmZmOTg4M2MzMzg5MDk1ZTYxYWU2N2VlNjRkMDNlZmNmYmJlMDI1Y2Y2Mjk5ZjFjZjYwMzljZWUzYTFkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.TxlYX0DIXSEfmB3d1JF-oeczZqgTMaxpFfePEVZaGBQ)

it's in kitty protocol? but why in mine kitty doesn't work? i install imagemagick

**Comment by FyrelWhister** [comment]
> > > Cannot reproduce
> > > ![image](https://private-user-images.githubusercontent.com/6134068/374761866-e962d205-3f7f-4158-a153-7c093b979c4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjA5NDQsIm5iZiI6MTcyODQ2MDY0NCwicGF0aCI6Ii82MTM0MDY4LzM3NDc2MTg2Ni1lOTYyZDIwNS0zZjdmLTQxNTgtYTE1My03YzA5M2I5NzljNGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDlUMDc1NzI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGE3ZmZmOTg4M2MzMzg5MDk1ZTYxYWU2N2VlNjRkMDNlZmNmYmJlMDI1Y2Y2Mjk5ZjFjZjYwMzljZWUzYTFkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.TxlYX0DIXSEfmB3d1JF-oeczZqgTMaxpFfePEVZaGBQ)
> > 
> > 
> > it's in kitty protocol? but why in mine type kitty doesn't work? i install imagemagick fastfetch just doesn't work when i use type:"kitty"
> 
> yes

what is your kitty version?

**Comment by FyrelWhister** [comment]
hey ayo wtf. i install fastfetch from ubuntu ppa and ayo IT WORK. WHY?  type: "kitty" doens't work in kitty from github but work from ppa? 

> > > Cannot reproduce
> > > ![image](https://private-user-images.githubusercontent.com/6134068/374761866-e962d205-3f7f-4158-a153-7c093b979c4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjA5NDQsIm5iZiI6MTcyODQ2MDY0NCwicGF0aCI6Ii82MTM0MDY4LzM3NDc2MTg2Ni1lOTYyZDIwNS0zZjdmLTQxNTgtYTE1My03YzA5M2I5NzljNGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDlUMDc1NzI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGE3ZmZmOTg4M2MzMzg5MDk1ZTYxYWU2N2VlNjRkMDNlZmNmYmJlMDI1Y2Y2Mjk5ZjFjZjYwMzljZWUzYTFkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.TxlYX0DIXSEfmB3d1JF-oeczZqgTMaxpFfePEVZaGBQ)
> > 
> > 
> > it's in kitty protocol? but why in mine type kitty doesn't work? i install imagemagick fastfetch just doesn't work when i use type:"kitty"
> 
> yes

**Comment by aishenreemo** [comment]
It also happened to me most probably because I am using Nix (home-manager) in an Arch linux environment. I fixed it by using [kitty-icat](https://github.com/fastfetch-cli/fastfetch/wiki/Json-Schema#23111-property-json-config--logo--oneof--item-2--type--oneof--item-10) as `--logo-type` instead.
