### ISSUE TITLE
[BUG] Wrong RAM Usage Statistics (OpenBSD)

### ISSUE THREAD

**Issue by time-killer-games** [fastfetch-cli/fastfetch#1331]
Here's what I'm getting on my system currently:

![Screenshot_2024-10-10_01-53-29](https://github.com/user-attachments/assets/e4f0d13b-ad45-4f53-8396-05aecbf41c42)

`totalram` can be got on OpenBSD (and NetBSD) with:
```
  long long totalram = -1;
  int mib[2];
  mib[0] = CTL_VM;
  mib[1] = VM_UVMEXP;
  struct uvmexp buf;
  std::size_t sz = sizeof(buf);
  if (!sysctl(mib, 2, &buf, &sz, nullptr, 0))
    totalram = buf.npages * sysconf(_SC_PAGESIZE);
```

`freeram` can be got on OpenBSD (and NetBSD) with:
```
  long long freeram = -1;
  int mib[2];
  mib[0] = CTL_VM;
  mib[1] = VM_UVMEXP;
  struct uvmexp buf;
  std::size_t sz = sizeof(buf);
  if (!sysctl(mib, 2, &buf, &sz, nullptr, 0))
    freeram = buf.free * sysconf(_SC_PAGESIZE);
```

`usedram` can be got on OpenBSD (and NetBSD) with:
```
  long long usedram = -1;
  if (totalram != -1 && freeram != -1)
    usedram = totalram - freeram;
```

You can see from testing yourself that this will produce values that match OpenBSD's [top(1)](https://man.openbsd.org/top).

I wrote a test program which shows the above code works, [here it is](https://github.com/time-killer-games/sysinfo).

Run `./build.sh` and compare with  [top(1)](https://man.openbsd.org/top).

![Screenshot_2024-10-10_02-08-22](https://github.com/user-attachments/assets/2e7d724c-9aff-4549-a82c-86ffff89b96b)

In the above screenshot, my test case program `sysinfo` is on the top, and OpenBSD's built-in [top(1)](https://man.openbsd.org/top) is at the bottom.

(Ignore the CPU core count feature in my test case, not only is that unrelated to this ticket, it also is not a feature even supported by OpenBSD reliably OS-level unless you care to write inline assembly and maintain it every time new hardware comes out which breaks it, which is why I have it report `(null)` on OpenBSD).

**Comment by CarterLi** [comment]
You should open a PR.

Code is here https://github.com/fastfetch-cli/fastfetch/blob/dev/src/detection/memory/memory_obsd.c
