### ISSUE TITLE
[BUG] Fastfetch displaying the wrong (deleted) images

### ISSUE THREAD

**Issue by Max7891-github** [fastfetch-cli/fastfetch#1338]
I am using Prasan Thrangan's [config](https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/fastfetch/config.jsonc), but I don't think it makes a difference here.

I wanted to display some images whenever fastfetch would run but for some reason, fastfetch uses the images that I have already deleted. 

I had 2 images - "Berserk.png" and "Guts.png"

The problem was that both of these images were not transparent so I deleted them and replaced them with transparent ones. The new names of the image files were - "Berserker.png" and "Guts.png"

Now for some reason, fastfetch displays the deleted image, rather than showing the new transparent image I downloaded with that same exact name. I even renamed "Berserker.png" to "Berserk.png" and the issue still persisted. If the file name was the same, it would only display the deleted image. The video provides a better explanation.

https://github.com/user-attachments/assets/e2e711b3-210e-4abb-a3d3-77dccd1e7000

I am running the latest version of fastfetch on Hyprland, Arch Linux (pacman).

**Comment by CarterLi** [comment]
Try add `"type": "kitty-direct"` in `"logo": { ... }`

**Comment by Max7891-github** [comment]
I tried Kitty direct but that messes up the height of the images

**Comment by CarterLi** [comment]
Remove `"height": 10`

**Comment by Max7891-github** [comment]
> Remove `"height": 10`

**Comment by Max7891-github** [comment]
> Remove `"height": 10`

I have a couple of other images as well with varying sizes so it's not applicable for me to remove "height"

**Comment by Max7891-github** [comment]
Also I noticed something strange. I renamed a completely different image to "Guts.png" and then the original image with no transparency started showing up. Strange. I've tried uninstalling Fastfetch yet nothing changes when I reinstall.

**Comment by CarterLi** [comment]
If you don't use `type: kitty-direct`, the images will be cached. You have to use `recache: true` to disable caching.

**Comment by Max7891-github** [comment]
> If you don't use `type: kitty-direct`, the images will be cached. You have to use `recache: true` to disable caching.

This solved the issue! Thank you so much friend 👍
