### ISSUE TITLE
[BUG] Git-Bash on WindowsTerminal: Unknown terminal: WindowsTerminal

### ISSUE THREAD

**Issue by FreeHarry** [fastfetch-cli/fastfetch#1345]
# General description of bug:

* What happened:
Running fastfetch on Git-Bash via WindowsTerminal in Windows 11 shows: `Unknown terminal: WindowsTerminal`
* What should happen:
The terminal font should be shown properly
* Fastfetch version used: 
2.27.1
* Did it work in an older version: 
No
* Where did you get the binary: 
scoop

# Often helpful information:

Screenshot:

![image](https://github.com/user-attachments/assets/018e5f66-e1e9-4bc5-ba63-4c6e63acc4bc)

**Comment by CarterLi** [comment]
It's expected. We dont support terminal font detection of Windows Terminal in git bash.

You may use either native shells, or mintty.
