### ISSUE TITLE
[LOGO] Make SummitOS Logo

### ISSUE THREAD

**Issue by krolmiki2011** [fastfetch-cli/fastfetch#1352]
Tip: A logo can be displayed by fastfetch without getting into fastfetch's official repo. For highly customized logo for personal use, it's recommended to keep it locally. Please refer to https://github.com/fastfetch-cli/fastfetch/wiki/Migrate-Neofetch-Logo-To-Fastfetch

# OS
```
Paste content of /etc/os-release and /etc/lsb-release here. If none of these files exist, describe a way to identify the distro
os-release:
NAME="SummitOS"
PRETTY_NAME="SummitOS"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;0;255;0"
HOME_URL="https://summitos.github.io/"
LOGO=summitos-logo
lsb-release:
DISTRIB_ID=SummitOS
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="SummitOS"

```

# Ascii

An ASCII logo should not take up too much space (smaller than 50x20 characters). Please also include the color codes if not available in `os-release` 

```
Paste ascii art here.
```
 IS really hard to place ascii but i have a image
![summitos-logo](https://github.com/user-attachments/assets/6ee93090-41de-4421-8efb-413e224744ee)

**Comment by krolmiki2011** [comment]
HEY IM STILL WATING TO APPROVE!

**Comment by CarterLi** [comment]
> Paste ascii art here.

**Comment by krolmiki2011** [comment]
[logo.txt](https://github.com/user-attachments/files/17525653/logo.txt)
Here is

**Comment by krolmiki2011** [comment]
O and color follow the image

**Comment by CarterLi** [comment]
> An ASCII logo should not take up too much space (**smaller than 50x20 characters**)

**Comment by krolmiki2011** [comment]
I made a update 
[logo.txt](https://github.com/user-attachments/files/17530171/logo.txt)
