### ISSUE TITLE
[FEAT] Windows XP/Server 2003 support

### ISSUE THREAD

**Issue by david-goliath93** [fastfetch-cli/fastfetch#1354]
Be sure to read [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

## Wanted features:

Title says it all.

## Motivation:

This would be a useful tool to have on my machines with XP, and would be an awesome gizmo for screenshots.

I am unaware of what exactly prevents fastfetch from functioning on XP/2003, but it claims it is not a valid Win32 application on XP x64 (NT 5.2 Build 3790.srv03_sp2_qfe.190711-0601 : Service Pack 2)

If you think it's ridiculous that anyone is using XP/2003 today, I get that and you can close the issue.

![image](https://github.com/user-attachments/assets/cf08bf5c-82de-49a0-aae1-28098b6b83df)

**Comment by CarterLi** [comment]
Fastfetch uses a lot WIN32 APIs that only available on Windows 7 or later. I know there are always some people stuck at ancient versions but it's just not worth the effort to support them.

**Comment by CarterLi** [comment]
Even Windows 7 is considered ancient and I plan to remove its support in newer version.
