### ISSUE TITLE
[BUG] Winget failing to install update

### ISSUE THREAD

**Issue by Mukul1127** [fastfetch-cli/fastfetch#1364]
Be sure to read the [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

# General description of bug:

* What happened: Winget failed to update fastfetch
* What should happen: It should update 
* Fastfetch version used:  N/A
* Did it work in an older version:  N/A
* Where did you get the binary:  N/A
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? N/A

![{1FC03F05-97D3-412A-8868-71BA114606DA}](https://github.com/user-attachments/assets/edcf9a79-7719-411c-9cfd-6b52f5e2b9fc)

```
$ winget remove Fastfetch-cli.Fastfetch
Found fastfetch [Fastfetch-cli.Fastfetch]
Starting package uninstall...
An unexpected error occurred while executing the command:
remove: Access is denied.: "C:\Users\Mukul\AppData\Local\Microsoft\WinGet\Packages\Fastfetch-cli.Fastfetch_Microsoft.Winget.Source_8wekyb3d8bbwe\fastfetch.exe"
Uninstall failed with exit code: 0x8a150003 : Executing command failed

$ winget install fastfetch-cli.Fastfetch --force
Found fastfetch [Fastfetch-cli.Fastfetch] Version 2.28.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
An unexpected error occurred while executing the command:
remove: Access is denied.: "C:\Users\Mukul\AppData\Local\Microsoft\WinGet\Packages\Fastfetch-cli.Fastfetch_Microsoft.Winget.Source_8wekyb3d8bbwe\fastfetch.exe"
Portable install failed; Cleaning up...
An unexpected error occurred while executing the command:
0x80070490 : Element not found.

$ fastfetch --version
fastfetch 2.27.1 (x86_64)
```

Deleted rest as N/A

**Comment by Mukul1127** [comment]
Powershell is running as administrator

**Comment by CarterLi** [comment]
This is fastfetch repo. Issues of fastfetch itself go here. Issues of package managers should be reported in their own repo.

https://github.com/microsoft/winget-pkgs/issues
