### ISSUE TITLE
[FEAT] Add TempleOS's logo

### ISSUE THREAD

**Issue by ivaaane** [fastfetch-cli/fastfetch#1366]
## Wanted features:

Add [TempleOS's](https://en.wikipedia.org/wiki/TempleOS) ASCII logo by default.

![image](https://github.com/user-attachments/assets/9a06b24e-61be-4f0c-b1f6-fbccf29dcfa0)

## Motivation:

Another operative system to support is always nice.

**Comment by CarterLi** [comment]
Please fill the [logo request template](https://github.com/fastfetch-cli/fastfetch/issues/new?assignees=&labels=logo+request&projects=&template=logo_request.md&title=%5BLOGO%5D+)
