### ISSUE TITLE
[BUG] inconsistent behavior with custom logo colors

### ISSUE THREAD

**Issue by Willow-Zero** [fastfetch-cli/fastfetch#1368]
* What happened: ive been futzing around with fastfetch getting random selection of icons on terminal start set up, thats entirely handled by my bashrc, and unrelated to fastfetch. in testing commands ive found some odd behavior that i dont think is intended, namely some weird bug with fastfetch not recognizing custom colors when a relative path is used for a text file and with it assuming a wider screen exists than actually does
* What should happen: none of that! a relative path should work fine, and the program should know how big the terminal its running in is.
* Fastfetch version used: latest arch repo (i checked and updated my system)
* Did it work in an older version: dont know
* Where did you get the binary: arch repo
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)?

# Often helpful information:

Screenshot:
![2024-10-31-124746_hyprshot](https://github.com/user-attachments/assets/bba95900-7541-43b1-bae8-778f8b86d0b9)
![2024-10-31-124758_hyprshot](https://github.com/user-attachments/assets/4e09aebd-a8ed-4d13-92e7-243bfbee0311)

The content of the configuration file you use (if any):
```
no custom config file but
commands used are:
fastfetch -l /home/wren/.config/neofetch/aperture --logo-color-1 "38;5;201" --logo-color-2 "red" --logo-color-3 "38;5;166" --logo-color-4 "38;5;226" --logo-color-5 "38;5;28" --logo-color-6 "38;5;44" --logo-color-7 "38;5;56" --logo-color-8 "38;5;90"
and 
fastfetch -l aperture --logo-color-1 "38;5;201" --logo-color-2 "red" --logo-color-3 "38;5;166" --logo-color-4 "38;5;226" --logo-color-5 "38;5;28" --logo-color-6 "38;5;44" --logo-color-7 "38;5;56" --logo-color-8 "38;5;90"
both running from inside /home/wren/.config/neofetch/
the aperture file is in this pastebin
https://pastebin.com/kyz9C2bU

```

Output of :

```
[// Paste here](https://pastebin.com/PdDEEjrP)
```

Output of `fastfetch --list-features`:
```
threads
vulkan
wayland
xcb-randr
xcb
xrandr
x11
drm
drm_amdgpu
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
egl
glx
osmesa
opencl
libpulse
libddcutil
libelf
libzfs
Directx Headers
System yyjson
linux/videodev2
linux/wireless
```

**Comment by CarterLi** [comment]
> ![1](https://private-user-images.githubusercontent.com/149698657/382040231-bba95900-7541-43b1-bae8-778f8b86d0b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MjEwODksIm5iZiI6MTczMDQyMDc4OSwicGF0aCI6Ii8xNDk2OTg2NTcvMzgyMDQwMjMxLWJiYTk1OTAwLTc1NDEtNDNiMS1iYWU4LTc3OGY4Yjg2ZDBiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQwMDI2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGI5YWU5ZWY3ZTMyNzU4OGIxNDE2OTA3OTBjZDE2ZjQ5MjgyNTE5ZTY1NjJlMjQ1ZDg5Y2FlN2FjYTRmZGIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.A-XP4hghIJls8RzFQ6SYnCNW0ZqT4OFOq6h06f-ew0k)

It's because your ascii art contains `$` characters. They must be encoded with double `$$` in order not to be confused with color placeholders. For example: `$$` should be `$$$$`

> ![2](https://private-user-images.githubusercontent.com/149698657/382040579-4e09aebd-a8ed-4d13-92e7-243bfbee0311.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MjEwODksIm5iZiI6MTczMDQyMDc4OSwicGF0aCI6Ii8xNDk2OTg2NTcvMzgyMDQwNTc5LTRlMDlhZWJkLWE4ZWQtNGQxMy05MmU3LTI0M2JmYmVlMDMxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQwMDI2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xN2E4YzFhNGMzOTc5NGZkZmE5NTU1NWZiOGQ5NDc2MTNjYWU5ZGM4MjhhNWM4ZWY2YTUzY2QyNmY1ZTc4Y2U5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nxGq3Me-UfV3AWCa7DlaTK1Pip8qlinD6H1h3DSPSB4)

It's because fastfetch includes [a builtin aperture logo](https://github.com/fastfetch-cli/fastfetch/blob/dev/src/logo/ascii/aperture.txt), but it doesn't contain custom color placeholders.

**Comment by CarterLi** [comment]
I have updated the builtin aperture logo which included in fastfetch. You may use it directly
