### ISSUE TITLE
[FEAT] Bluetooth devices battery is always at 0%

### ISSUE THREAD

**Issue by Ctrl-Alb** [fastfetch-cli/fastfetch#1375]
I really like Fastfetch: I started using it just for "ahah ASCII art is nice" but now I think it's a very good and useful piece of software. Thanks for what you're doing :)

# General description of bug: 

* What happened: The bluetooth devices' battery percentage is always displayed as 0%
* What should happen: The percentage should represent the real battery percentage as displayed in the macOS Bluetooth menu
* Fastfetch version used: 2.29
* Did it work in an older version: I only tried the 2.28 and 2.29 versions and the bug occurs in both versions
* Where did you get the binary: Homebrew for macOS
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Yes

# Often helpful information:

Screenshot:
<img width="227" alt="Screenshot" src="https://github.com/user-attachments/assets/a4ce980f-7b28-4da8-b698-c8bb37049281">

The content of the configuration file you use (if any):
```
       {
          "type": "bluetooth",
          "key": "├ BT Dev",
          "keyColor": "blue",
          "format": "{1} {4}"
       },
```

Output of `fastfetch -c ci.jsonc --format json`:
```
  {
    "type": "Bluetooth",
    "result": [
      {
        "address": "****", // here I deleted the address
        "battery": 0,
        "connected": false,
        "name": "Cuffie",
        "type": "Audio/Video"
      },
      {
        "address": "****", // here I deleted the address
        "battery": 0,
        "connected": true,
        "name": "Mouse",
        "type": "Peripheral"
      },
      {
        "address": "****", // here I deleted the address
        "battery": 0,
        "connected": false,
        "name": "iPhone",
        "type": "Miscellaneous"
      }
    ],
    "stat": 16.92700000014156
  },
```

Output of `fastfetch --list-features`:
```
threads
vulkan
imagemagick7
chafa
zlib
sqlite3
```

**Comment by CarterLi** [comment]
The battery detection is a feature of BLE (Bluetooth Low Energy). We actually only support it on Linux and detect all bluetooth devices with the classic bluetooth APIs on macOS (and Windows)

**Comment by CarterLi** [comment]
Better open it separately

**Comment by CarterLi** [comment]
> I hope this feature will be added for macOS in the future as well.

The BLE APIs are much harder to use than the classical APIs. Definitely not a easy task.

**Comment by CarterLi** [comment]
Please test the dev build: https://github.com/fastfetch-cli/fastfetch/actions/runs/11676810398
