### ISSUE TITLE
[BUG] HDR output is always set to "false"

### ISSUE THREAD

**Issue by CTRL-panino** [fastfetch-cli/fastfetch#1376]
# General description of bug:

* What happened: The HDR output in the "Display" category is always set to "false". This happens even if my computer display (MBP M1 Pro) is HDR capable. I tried to re-run Fastfetch while watching HDR content and even while forcing an HDR preset (Settings -> Displays -> Presets -> "HDR video") but the HDR output remains "false". In contrast, the HDR output in the "Monitor" category is always set to "true"
* What should happen: The "Display" HDR output should be "true", like the "Monitor" HDR output
* Fastfetch version used: 2.29
* Did it work in an older version: I only tried the 2.28 and 2.29 versions and the bug occurs in both versions
* Where did you get the binary: Homebrew for macOS
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Yes

# Often helpful information:

Screenshot:
<img width="170" alt="Screenshot" src="https://github.com/user-attachments/assets/5bfee1d3-b1db-4730-8122-ce921fb3e144">

The content of the configuration file you use (if any):
```
       {
          "type": "display",
          "key": "├ Display",
          "keyColor": "yellow",
          "format": "HDR: {15}"
       },

       {
          "type": "monitor",
          "key": "├ Monitor",
          "keyColor": "yellow",
          "format": "HDR: {12}"
       },
```

Output of `fastfetch -c ci.jsonc --format json`:

```
  {
    "type": "Display",
    "result": [
      {
        "id": 1,
        "name": "Color LCD",
        "primary": true,
        "output": {
          "width": 3456,
          "height": 2234
        },
        "scaled": {
          "width": 1728,
          "height": 1117
        },
        "physical": {
          "width": 344,
          "height": 223
        },
        "refreshRate": 120.0,
        "rotation": 0,
        "bitDepth": 10,
        "hdrStatus": "Supported",
        "type": "Builtin",
        "manufactureDate": null,
        "serial": 4251086178,
        "platformApi": "CoreGraphics"
      }
    ],
    "stat": 33.88800000026822
  },
  {
    "type": "Brightness",
    "result": [
      {
        "name": "Color LCD",
        "max": 1.0,
        "min": 0.0,
        "current": 0.4208080768585205
      }
    ],
    "stat": 1.1270000003278255
  },
  {
    "type": "Monitor",
    "error": "Monitor module is an alias of Display module",
    "stat": 0.0020000003278255463
  },
```

Output of `fastfetch --list-features`:
```
threads
vulkan
imagemagick7
chafa
zlib
sqlite3
```

**Comment by CarterLi** [comment]
Also expected. The built-in XDR display doesn't have a *HDR enabled* state.

This property is for external HDR compatible displays. If you connect it to macOS, there is an option in system settings that let you turn the display to HDR mode

![hdr](https://www.digitaltrends.com/wp-content/uploads/2022/06/MacOS-enabling-HDR-on-external-monitor.jpg)

Enable it and this display will be considerred HDR enabled.

**Comment by CarterLi** [comment]
> Settings -> Displays -> Presets -> "HDR video"

It's about tone mapping, not turn the display into HDR mode.

> In contrast, the HDR output in the "Monitor" category is always set to "true"

`HDR` in "Monitor" module means the monitor is HDR compatible. `HDR` in "Display" module means the HDR mode is enabled.

**Comment by CarterLi** [comment]
> Would it be possible to add an "HDR-compatible" module in the "Display" category?

Sure
