### ISSUE TITLE
[FEAT] Unifi ASCII

### ISSUE THREAD

**Issue by deathbybandaid** [fastfetch-cli/fastfetch#1378]
## Wanted features:

Pulled directly from a unvr motd

````

  ___ ___      .__________.__
 |   |   |____ |__\_  ____/__|
 |   |   /    \|  ||  __) |  |
 |   |  |   |  \  ||  \   |  |
 |______|___|  /__||__/   |__|
            |_/
````

Might be able to detect that the Host contains UBNT

````
Host: Annapurna Labs Alpine V2 UBNT
Kernel: Linux 4.19.152-alpine-unvr
````

## Motivation:

Old Unifi hardware, NVRs etc can be repurposed

**Comment by CarterLi** [comment]
Logo added. Can be tested with `fastfetch -l unifi`
