### ISSUE TITLE
[BUG] Unable to detect Shell version in macOS 10.15.7

### ISSUE THREAD

**Issue by pbobbenb** [fastfetch-cli/fastfetch#1388]
# General description of bug:

* What happened: Fastfetch fails to detect shell version on macOS 10.15.7 in both iTerm and Terminal. Neofetch correctly detects it as zsh 5.7.1.
* What should happen: Shell version should be displayed.
* Fastfetch version used: Tested with 2.24, 2.25 and 2.29
* Did it work in an older version: No idea, 2.24 was the first version I have used/tried.
* Where did you get the binary: Compiled myself but also tried binary from GitHub release with the same results.

# Often helpful information:

Screenshot:
![Screenshot](https://github.com/user-attachments/assets/0c046b44-dc0a-423c-9b8d-1703ebe3c01c)

## If fastfetch crashed or froze
[fastfetch_2024-11-10-crash.txt](https://github.com/user-attachments/files/17692930/fastfetch_2024-11-10-crash.txt)

**Comment by CarterLi** [comment]
Please test if the newest dev build fix your problem. You may download it here: https://github.com/fastfetch-cli/fastfetch/actions/runs/11776108502

**Comment by pbobbenb** [comment]
Yep, that works!
One minor thing, tried with compiling myself with ./run.sh and then it displays Shell as "sh" at the end of the compile, but running fastfetch from the build directory shows Shell correct as "zsh 5.7.1"

Bit off topic but downloading the file from the link above, the zip file actually contained a zip and an tar.gz inside, is it supposed to be that way? Seems a bit redundant to have two packed files (that both contain the same things) inside a packed file.

**Comment by CarterLi** [comment]
> the zip file actually contained a zip and an tar.gz inside

It's expected. They will be put in release assets
