### ISSUE TITLE
[BUG] Unable to detect the correct WM on macOS 15.1

### ISSUE THREAD

**Issue by adamajane** [fastfetch-cli/fastfetch#1389]
Be sure to read the [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

# General description of bug:

* What happened: Fastfetch doesn't detect the current window manager in use. I use Rectangle, but it outputs Quartz Compositor
* What should happen: Next to "WM", it should output Rectangle
* Fastfetch version used: 2.29.0
* Did it work in an older version: I just installed it
* Where did you get the binary: Installed with Homebrew

# Often helpful information:

Screenshot:
<img width="905" alt="Screenshot 2024-11-10 at 21 41 53" src="https://github.com/user-attachments/assets/ee8ab01b-92bf-49bb-b79c-aa12ba855a1a">

**Comment by CarterLi** [comment]
See https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#q-fastfetch-cannot-detect-my-awesome-3rd-party-macos-window-manager
