### ISSUE TITLE
[BUG] Segmentation fault in zsh on macOS 14.7.1 x86_64

### ISSUE THREAD

**Issue by jby** [fastfetch-cli/fastfetch#1393]
Be sure to read the [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

# General description of bug:

* What happened: fastfetch crashes _every_ time I try to run it on an intel-based mac 
* What should happen: It shouldn't crash
* Fastfetch version used: fastfetch 2.29.0 (x86_64)
* Did it work in an older version: No
* Where did you get the binary: Homebrew
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)?

# Often helpful information:

Screenshot:
![image](https://github.com/user-attachments/assets/14817577-fbc3-44c0-9f57-99bc6b3f5644)

Output of `fastfetch -c ci.jsonc --format json`:
```
$ fastfetch -c ci.jsonc --format json
zsh: segmentation fault  fastfetch -c ci.jsonc --format json
```

Output of `fastfetch --list-features`:
```
fastfetch --list-features
threads
vulkan
imagemagick7
chafa
zlib
sqlite3
```

## If fastfetch behaves incorrectly on shell startup

It doesn't matter if run from commandline or in .zshrc
I see this on 2 different intel-Macs, but not on my arm-Macs where it works as expected.

**Comment by CarterLi** [comment]
I do have an old Intel Macbook Pro and it works fine for me.

Please provide the stack trace for debugging.

**Comment by niu541412** [comment]
I have 4 mac machines,  macOS are  10.13.6、11.7.10、12.7.6、15.1.1 ，the first 3 are x86_64 CPU.
They all works with `fastfetch -c all` with 2.30.1. 
Version 2.29.0 should work as well because I usually keep upgrading fasfetch.

**Comment by CarterLi** [comment]
#1413 suggests fastfetch works fine in 14.7.1 x86_64. As we still got no response from @jby I will close this issue for now. One can reopen it with stack trace uploaded

**Comment by jby** [comment]
Sorry, I missed that you'd replied.
Here's the requested `lldb` output:
```
Process 49130 launched: '/usr/local/Cellar/fastfetch/2.30.1/bin/fastfetch' (x86_64)
                     ..'          root@
                 ,xNMM.           -----------------
               .OMMMMo            OS: macOS Sequoia 15.1.1 x86_64
               lMM"               Host: Mac mini (2018)
     .;loddo:.  .olloddol;.       Kernel: Darwin 24.1.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:     Uptime: 4 days, 18 hours, 38 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.     Packages: 301 (brew), 11 (brew-cask)
 XMMMMMMMMMMMMMMMMMMMMMMMX.       Shell: zsh 5.9
Process 49130 stoppedMMMM:
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00007ff80a2f571c CoreFoundation`CF_IS_OBJC + 12
CoreFoundation`CF_IS_OBJC:Wd.
->  0x7ff80a2f571c <+12>: movq   (%rsi), %rcx
    0x7ff80a2f571f <+15>: testq  %rcx, %rcx
    0x7ff80a2f5722 <+18>: je     0x7ff80a2f5742 ; <+50>
    0x7ff80a2f5724 <+20>: cmpq   $0x7, %rdi
Target 0: (fastfetch) stopped.
(lldb) bt all
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x00007ff80a2f571c CoreFoundation`CF_IS_OBJC + 12
    frame #1: 0x00007ff80a1d4b43 CoreFoundation`CFDictionaryContainsKey + 26
    frame #2: 0x000000010008819b fastfetch`ffConnectDisplayServerImpl + 1163
    frame #3: 0x00000001000116a3 fastfetch`ffConnectDisplayServer + 135
    frame #4: 0x000000010005a05a fastfetch`ffPrintDisplay + 42
    frame #5: 0x000000010000aebe fastfetch`ffPrintCommandOption + 632
    frame #6: 0x00000001000075e5 fastfetch`main + 253
    frame #7: 0x00007ff809dba2cd dyld`start + 1805
  thread #2
    frame #0: 0x00007ff80a108542 libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x00007ff80a144cd8 libsystem_pthread.dylib`_pthread_wqthread + 415
    frame #2: 0x00007ff80a143bdb libsystem_pthread.dylib`start_wqthread + 15
  thread #3
    frame #0: 0x00007ff80a108542 libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x00007ff80a144cd8 libsystem_pthread.dylib`_pthread_wqthread + 415
    frame #2: 0x00007ff80a143bdb libsystem_pthread.dylib`start_wqthread + 15
(lldb) ^D
```

**Comment by jby** [comment]
I can now report that with fastfetch 2.31.0 this seems resolved
