### ISSUE TITLE
[BUG] Logo fails to load from symlinked files

### ISSUE THREAD

**Issue by screwyprof** [fastfetch-cli/fastfetch#1395]
### What happened:
Fastfetch fails to load logo file when the source file is a symlink 

### What should happen:
Fastfetch should be able to load logo files that are symlinks

### Version Information:
- Fastfetch version: 2.29.0 (aarch64)
- Worked in older version: N/A
- Binary source: Installed via nix/home-manager
- Latest dev build: Not tested
- OS: macOS
- Terminal: iTerm2

### The content of the configuration file you use:

```json
{
    "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
    "logo": {
        "type": "file",
         "source": "~/.config/fastfetch/gopher.ascii"

    },
    // skipped for brevity as not related to the issue
    // ...
}
```
### Error output with `--show-errors`:
```
Logo: Failed to load file content from logo source: ~/.config/fastfetch/gopher.ascii
```

### FIle structure:
```bash
lrwxr-xr-x - parallels 12 Nov 18:09 /Users/parallels/.config/fastfetch/gopher.ascii -> /nix/store/xxx-home-manager-files/.config/fastfetch/gopher.ascii
```

### Steps to reproduce:
1. Create a symlink to a logo file 
2. Configure fastfetch to use this file (symlink)
3. Run fastfetch
4. The build-in distro logo will show instead of the specified one

The logo loads correctly when a regular file specified instead of a symlink

**Comment by CarterLi** [comment]
Seems a macOS kernel bug. I tested Linux & FreeBSD they both worked fine.
