### ISSUE TITLE
[FEAT] Add color customization for charElapsed and charTotal

### ISSUE THREAD

**Issue by judexgauss** [fastfetch-cli/fastfetch#1396]
## Wanted features:
Add color customization for `charElapsed` and `charTotal` from `display/bar`

## Motivation:

Just want my fastfetch to look clean and tight

**Comment by CarterLi** [comment]
Just use

```jsonc
{
  "charElapsed": "\u001b[32m-",
  "charTotal": "\u001b[35m="
}
```

**Comment by CarterLi** [comment]
`display.percent.color.*` also affects color of `charElapsed`
