### ISSUE TITLE
[FEAT] use bold for printing logos to better match neofetch output

### ISSUE THREAD

**Issue by rrotter** [fastfetch-cli/fastfetch#1399]
## Wanted features:

Print ascii logos in bold. Or provide an option to print in bold, whether this is the default or not.

This can currently be emulated with something like `fastfetch --logo-color-1 bright_green` (which works on macos since the first color of the apple logo is green, this would obviously not work correctly for other logos).

## Motivation:

`neofetch` prints logos in bold by default. This can be toggled with `neofetch --ascii_bold [on|off]`. Since most of fastfetch's logo's appear to be copy/pasted from neofetch it would make sense to replicate this behavior, or at least make it an option.

**Comment by CarterLi** [comment]
It's already in bold if your terminal is in dark mode.

There is also an option to control it: `fastfetch --bright-color {true|false}`

**Comment by rrotter** [comment]
Thank you. I was able to get this working by adding `"display": {"brightColor": true}` to my config. I missed this option because I was looking for options under `logo` rather than `display`.
