### ISSUE TITLE
[BUG] Wrong display resolution and size when using an external monitor

### ISSUE THREAD

**Issue by CTRL-panino** [fastfetch-cli/fastfetch#1406]
# General description of bug:

* What happened: 
 
While using an external monitor **in duplication mode**, the **display resolutions and sizes** reported by Fastfetch do not match the actual resolutions and sizes of the displays (both for the built-in and the external displays).

In my example, Fastfetch should report:
**Built-in**: 3456x2234 (16")
**External**: 1920x1080 (32")

When the built-in screen is the target, Fastfetch incorrectly reports the **external display** as:
Resolution: 3456x2234 (incorrect, its max resolution is 1080p)
Size: 57" (incorrect, its max size is 32")
<img width="545" alt="Screenshot 2024-11-19 alle 12 36 46" src="https://github.com/user-attachments/assets/d7edfb7a-f7eb-4a30-a277-87fbf1396e0e">

When the external display is the target, Fastfetch reports the **built-in screen** as:
Scaled Resolution: 1920x1080 (incorrect, this is the scaled resolution, not the actual resolution)
Size: 8" (incorrect)
![Screenshot 2024-11-19 alle 12 29 57](https://github.com/user-attachments/assets/2ee1cd1b-b4d6-479e-84b2-bc9073108a1f)

The issue **doesn't occur** when the external display is set as "extended display"
<img width="530" alt="Screenshot 2024-11-19 alle 12 31 42" src="https://github.com/user-attachments/assets/fcec7812-7ab7-471f-b27f-fcb87e036a07">

* What should happen: In my opinion, Fastfetch should report the actual resolutions and sizes. Then, separately, the scaled resolutions
* Fastfetch version used: 2.30.1
* Did it work in an older version: No
* Where did you get the binary: from the GitHub release page
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Yes

# Often helpful information:

Output of `fastfetch -c ci.jsonc --format json`: I didn't include the output for the three different scenarios to avoid creating a wall of text, but I can provide it if necessary.

**Comment by CarterLi** [comment]
Fastfetch always reports output resolution (the image resolution generated by GPU). That's by design. You can change the resolution in system settings.

**Comment by CarterLi** [comment]
I wonder why you want the physical resolution, as it's mostly useless unless your GPU is really working on that resolution.

A resolution supported by your monitor doesn't mean you can make use of it. For example, you have a 4K / 60 Hz monitor. If you want to use it, you must have:

1. a modern GPU support 4K output
2. a HDMI 2.0+ or a DP 1.2+ connection cable and connect it to the HDMI 2.0+ or DP 1.2+ port, both in GPU and monitor
3. set your monitor working on HDMI 2.0+ or DP 1.2+ mode, respectively.
4. enable 4K / 60 Hz in your system settings

Otherwise, the image is scaled and everything is blurred. I don't think reporting 4K resolution for a blurred display is a good idea.

**Comment by CarterLi** [comment]
> it could be misleading to present information that does not accurately reflect the display data

1. The total memory size is smaller than the physical memory size (not the case on macOS though)
2. The sum size of all disks is smaller than the physical disk size

That's by design. I don't think anyone say it's misleading.

**Comment by CarterLi** [comment]
> This is true and you're perfectly right. It's useless to present a screen as 8K 240 Hz if my GPU doesn't support it.

This is also true if you don't enable the display mode. For example, mirroring another display with different resolution.

**Comment by CarterLi** [comment]
> I noticed some new code has been added. Should I go ahead and test it?

`{preferred-width}` and `{preferred-height}` was added to partially resolve your requirement. Preferred resolution is the display mode that OS chooses by default ( usually the maximum resolution supported by your setup )

**Comment by CarterLi** [comment]
It should work when the built-in display is the target. It's known not to work when the external display is the target.

**Comment by CarterLi** [comment]
0 means the information is not available. You should use `{?inch}inch{?}` to print it conditionally

**Comment by CarterLi** [comment]
> I thought it was something unrelated to Apple since the display size (in inches) and ppi are incorrect in Fastfetch on Windows, too.

They are different. macOS and Windows are different OSes, provide different APIs. Fastfetch uses different strategies in different OS and they don't share any code.

> display size (in inches) and ppi are incorrect

This doesn't help. Please provide the result of `fastfetch -s display --format json` and the results you expect. BTW, diagonal length (in inches) is calcuated with physical screen size (pythagorean theorem); PPI is calcuated with screen width and pixel count. They both depends on screen size is detected correctly. So that you should always check if screen size is detected correctly (smaller or larger?) and that would be much more helpful.

```json
[
  {
    "type": "Display",
    "result": [
      {
        "id": 65537,
        "name": "Odyssey G7",
        "primary": true,
        "output": {
          "width": 3840,
          "height": 2160,
          "refreshRate": 165.0
        },
        "scaled": {
          "width": 1920,
          "height": 1080
        },
        "preferred": {
          "width": 3840,
          "height": 2160,
          "refreshRate": 165.0
        },
        "physical": {
          "width": 697,
          "height": 392
        },
        "rotation": 0,
        "bitDepth": 10,
        "hdrStatus": "Enabled",
        "type": "External",
        "manufactureDate": {
          "year": 2023,
          "week": 21
        },
        "serial": 810244676,
        "platformApi": "GDI"
      }
    ]
  }
]
```

This is the result of my display reported in Windows. `result.physical.{width,height}` are the values (in mm) you should check.

**Comment by CarterLi** [comment]
Fastfetch uses  [CGDisplayScreenSize](https://developer.apple.com/documentation/coregraphics/1456599-cgdisplayscreensize) to acquire the physical screen size. It reports invalid results if the display is in mirroring mode. The document says nothing about mirroring and who knows what the heck goes wrong inside this closed-source function. All you can do is waiting Apple to fix it.

**Comment by CarterLi** [comment]
```
"physical": {
   "width": 1210,
   "height": 680
}
```

This is weird. Does it happen only when the display is in mirroring mode?

**Comment by CarterLi** [comment]
> 8-bit depth color (detected wrong in macOS)

I don't know how to fix it. Let's leave as it was.

> HDR support: true (detected wrong in Windows)

This is because HDR support is disabled when the display is mirrored. You can't enable the HDR mode in Windows display settings either.

**Comment by CarterLi** [comment]
Please export Windows Registry entries for debugging.

`HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Enum\DISPLAY`

**Comment by CarterLi** [comment]
> Here it is:
> 
> ```
> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum\DISPLAY\GSM0001
> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum\DISPLAY\LGD05D0
> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum\DISPLAY\SAM0F39
> ```

To export the registry: you select the entry and click `File->Export`; save it as a `.reg` file; upload it here (you may need to rename the file to `.txt`).

**Comment by CarterLi** [comment]
> Windows doesn't detect the external display as an HDR monitor even if it is (and macOS detects it correctly).
> So, the HDR issue was a Windows issue

You need to ensure that your GPU, cable, port all support HDR mode (HDMI 2.0a+ or DP 1.4+)

**Comment by CarterLi** [comment]
Please test the latest dev build

Ref (https://people.freedesktop.org/~imirkin/edid-decode/):

```
edid-decode (hex):

00 ff ff ff ff ff ff 00 4c 2d 39 0f 00 08 00 00
04 1c 01 03 80 46 27 78 0a 23 ad a4 54 4d 99 26
0f 47 4a bd ef 80 71 4f 81 c0 81 00 81 80 95 00
a9 c0 b3 00 01 01 02 3a 80 18 71 38 2d 40 58 2c
45 00 ba a8 42 00 00 1e 66 21 56 aa 51 00 1e 30
46 8f 33 00 ba a8 42 00 00 1e 00 00 00 fd 00 18
4b 0f 51 17 00 0a 20 20 20 20 20 20 00 00 00 fc
00 53 41 4d 53 55 4e 47 0a 20 20 20 20 20 01 09

02 03 33 f1 4d 90 1f 04 13 05 14 03 12 20 21 22
07 16 29 09 07 07 15 07 50 57 07 01 83 01 00 00
e2 00 0f e3 05 c3 01 67 03 0c 00 10 00 b8 3c e3
06 0d 01 01 1d 80 d0 72 1c 16 20 10 2c 25 80 ba
a8 42 00 00 9e 01 1d 80 18 71 1c 16 20 58 2c 25
00 ba a8 42 00 00 9e 01 1d 00 bc 52 d0 1e 20 b8
28 55 40 ba a8 42 00 00 1e 01 1d 00 72 51 d0 1e
20 6e 28 55 00 ba a8 42 00 00 1e 00 00 00 00 b3

----------------

Block 0, Base EDID:
  EDID Structure Version & Revision: 1.3
  Vendor & Product Identification:
    Manufacturer: SAM
    Model: 3897
    Serial Number: 2048
    Made in: week 4 of 2018
  Basic Display Parameters & Features:
    Digital display
    Maximum image size: 70 cm x 39 cm
    Gamma: 2.20
    RGB color display
    First detailed timing is the preferred timing
  Color Characteristics:
    Red  : 0.6406, 0.3300
    Green: 0.3007, 0.6005
    Blue : 0.1503, 0.0605
    White: 0.2802, 0.2900
  Established Timings I & II:
    IBM     :   720x400    70.081663 Hz   9:5     31.467 kHz     28.320000 MHz
    DMT 0x04:   640x480    59.940476 Hz   4:3     31.469 kHz     25.175000 MHz
    Apple   :   640x480    66.666667 Hz   4:3     35.000 kHz     30.240000 MHz
    DMT 0x05:   640x480    72.808802 Hz   4:3     37.861 kHz     31.500000 MHz
    DMT 0x06:   640x480    75.000000 Hz   4:3     37.500 kHz     31.500000 MHz
    DMT 0x09:   800x600    60.316541 Hz   4:3     37.879 kHz     40.000000 MHz
    DMT 0x0a:   800x600    72.187572 Hz   4:3     48.077 kHz     50.000000 MHz
    DMT 0x0b:   800x600    75.000000 Hz   4:3     46.875 kHz     49.500000 MHz
    Apple   :   832x624    74.551266 Hz   4:3     49.726 kHz     57.284000 MHz
    DMT 0x10:  1024x768    60.003840 Hz   4:3     48.363 kHz     65.000000 MHz
    DMT 0x11:  1024x768    70.069359 Hz   4:3     56.476 kHz     75.000000 MHz
    DMT 0x12:  1024x768    75.028582 Hz   4:3     60.023 kHz     78.750000 MHz
    DMT 0x24:  1280x1024   75.024675 Hz   5:4     79.976 kHz    135.000000 MHz
    Apple   :  1152x870    75.061550 Hz 192:145   68.681 kHz    100.000000 MHz
  Standard Timings:
    DMT 0x15:  1152x864    75.000000 Hz   4:3     67.500 kHz    108.000000 MHz
    DMT 0x55:  1280x720    60.000000 Hz  16:9     45.000 kHz     74.250000 MHz
    DMT 0x1c:  1280x800    59.810326 Hz  16:10    49.702 kHz     83.500000 MHz
    DMT 0x23:  1280x1024   60.019740 Hz   5:4     63.981 kHz    108.000000 MHz
    DMT 0x2f:  1440x900    59.887445 Hz  16:10    55.935 kHz    106.500000 MHz
    DMT 0x53:  1600x900    60.000000 Hz  16:9     60.000 kHz    108.000000 MHz (RB)
    DMT 0x3a:  1680x1050   59.954250 Hz  16:10    65.290 kHz    146.250000 MHz
  Detailed Timing Descriptors:
    DTD 1:  1920x1080   60.000000 Hz  16:9     67.500 kHz    148.500000 MHz (1210 mm x 680 mm)
                 Hfront   88 Hsync  44 Hback  148 Hpol P
                 Vfront    4 Vsync   5 Vback   36 Vpol P
    DTD 2:  1366x768    59.789541 Hz 683:384   47.712 kHz     85.500000 MHz (1210 mm x 680 mm)
                 Hfront   70 Hsync 143 Hback  213 Hpol P
                 Vfront    3 Vsync   3 Vback   24 Vpol P
    Display Range Limits:
      Monitor ranges (GTF): 24-75 Hz V, 15-81 kHz H, max dotclock 230 MHz
    Display Product Name: 'SAMSUNG'
  Extension blocks: 1
Checksum: 0x09

----------------

Block 1, CTA-861 Extension Block:
  Revision: 3
  Underscans IT Video Formats by default
  Basic audio support
  Supports YCbCr 4:4:4
  Supports YCbCr 4:2:2
  Native detailed modes: 1
  Video Data Block:
    VIC  16:  1920x1080   60.000000 Hz  16:9     67.500 kHz    148.500000 MHz (native)
    VIC  31:  1920x1080   50.000000 Hz  16:9     56.250 kHz    148.500000 MHz
    VIC   4:  1280x720    60.000000 Hz  16:9     45.000 kHz     74.250000 MHz
    VIC  19:  1280x720    50.000000 Hz  16:9     37.500 kHz     74.250000 MHz
    VIC   5:  1920x1080i  60.000000 Hz  16:9     33.750 kHz     74.250000 MHz
    VIC  20:  1920x1080i  50.000000 Hz  16:9     28.125 kHz     74.250000 MHz
    VIC   3:   720x480    59.940060 Hz  16:9     31.469 kHz     27.000000 MHz
    VIC  18:   720x576    50.000000 Hz  16:9     31.250 kHz     27.000000 MHz
    VIC  32:  1920x1080   24.000000 Hz  16:9     27.000 kHz     74.250000 MHz
    VIC  33:  1920x1080   25.000000 Hz  16:9     28.125 kHz     74.250000 MHz
    VIC  34:  1920x1080   30.000000 Hz  16:9     33.750 kHz     74.250000 MHz
    VIC   7:  1440x480i   59.940060 Hz  16:9     15.734 kHz     27.000000 MHz
    VIC  22:  1440x576i   50.000000 Hz  16:9     15.625 kHz     27.000000 MHz
  Audio Data Block:
    Linear PCM:
      Max channels: 2
      Supported sample rates (kHz): 48 44.1 32
      Supported sample sizes (bits): 24 20 16
    AC-3:
      Max channels: 6
      Supported sample rates (kHz): 48 44.1 32
      Maximum bit rate: 640 kb/s
    Enhanced AC-3 (DD+):
      Max channels: 8
      Supported sample rates (kHz): 48 44.1 32
      Supports Joint Object Coding
  Speaker Allocation Data Block:
    FL/FR - Front Left/Right
  Video Capability Data Block:
    YCbCr quantization: No Data
    RGB quantization: No Data
    PT scan behavior: No Data
    IT scan behavior: Supports both over- and underscan
    CE scan behavior: Supports both over- and underscan
  Colorimetry Data Block:
    xvYCC601
    xvYCC709
    BT2020YCC
    BT2020RGB
  Vendor-Specific Data Block (HDMI), OUI 00-0C-03:
    Source physical address: 1.0.0.0
    Supports_AI
    DC_36bit
    DC_30bit
    DC_Y444
    Maximum TMDS clock: 300 MHz
  HDR Static Metadata Data Block:
    Electro optical transfer functions:
      Traditional gamma - SDR luminance range
      SMPTE ST2084
      Hybrid Log-Gamma
    Supported static metadata descriptors:
      Static metadata type 1
  Detailed Timing Descriptors:
    DTD 3:  1920x1080i  50.000000 Hz  16:9     28.125 kHz     74.250000 MHz (1210 mm x 680 mm)
                 Hfront  528 Hsync  44 Hback  148 Hpol P
                 Vfront    2 Vsync   5 Vback   15 Vpol P Vfront +0.5 Odd Field
                 Vfront    2 Vsync   5 Vback   15 Vpol P Vback  +0.5 Even Field
    DTD 4:  1920x1080i  60.000000 Hz  16:9     33.750 kHz     74.250000 MHz (1210 mm x 680 mm)
                 Hfront   88 Hsync  44 Hback  148 Hpol P
                 Vfront    2 Vsync   5 Vback   15 Vpol P Vfront +0.5 Odd Field
                 Vfront    2 Vsync   5 Vback   15 Vpol P Vback  +0.5 Even Field
    DTD 5:  1280x720    50.000000 Hz  16:9     37.500 kHz     74.250000 MHz (1210 mm x 680 mm)
                 Hfront  440 Hsync  40 Hback  220 Hpol P
                 Vfront    5 Vsync   5 Vback   20 Vpol P
    DTD 6:  1280x720    60.000000 Hz  16:9     45.000 kHz     74.250000 MHz (1210 mm x 680 mm)
                 Hfront  110 Hsync  40 Hback  220 Hpol P
                 Vfront    5 Vsync   5 Vback   20 Vpol P
Checksum: 0xb3

----------------

Preferred Video Timing if only Block 0 is parsed:
  DTD   1:  1920x1080   60.000000 Hz  16:9     67.500 kHz    148.500000 MHz (1210 mm x 680 mm)
                 Hfront   88 Hsync  44 Hback  148 Hpol P
                 Vfront    4 Vsync   5 Vback   36 Vpol P

----------------

Preferred Video Timings if Block 0 and CTA-861 Blocks are parsed:
  DTD   1:  1920x1080   60.000000 Hz  16:9     67.500 kHz    148.500000 MHz (1210 mm x 680 mm)
                 Hfront   88 Hsync  44 Hback  148 Hpol P
                 Vfront    4 Vsync   5 Vback   36 Vpol P
  VIC  16:  1920x1080   60.000000 Hz  16:9     67.500 kHz    148.500000 MHz (native)
                 Hfront   88 Hsync  44 Hback  148 Hpol P
                 Vfront    4 Vsync   5 Vback   36 Vpol P

----------------

Native Video Resolution:
  1920x1080

----------------

edid-decode SHA: 84ddf9155376 2021-10-03 10:37:45

Warnings:

Block 1, CTA-861 Extension Block:
  Video Capability Data Block: Set Selectable YCbCr Quantization to avoid interop issues.
EDID:
  CTA-861: Multiple native progressive timings are defined.

Failures:

Block 0, Base EDID:
  Detailed Timing Descriptor #1: Mismatch of image size 1210x680 mm vs display size 700x390 mm.
  Detailed Timing Descriptor #2: Mismatch of image size 1210x680 mm vs display size 700x390 mm.
Block 1, CTA-861 Extension Block:
  Video Capability Data Block: Set Selectable RGB Quantization to avoid interop issues.
  Detailed Timing Descriptor #3: Mismatch of image size 1210x680 mm vs display size 700x390 mm.
  Detailed Timing Descriptor #4: Mismatch of image size 1210x680 mm vs display size 700x390 mm.
  Detailed Timing Descriptor #5: Mismatch of image size 1210x680 mm vs display size 700x390 mm.
  Detailed Timing Descriptor #6: Mismatch of image size 1210x680 mm vs display size 700x390 mm.

EDID conformity: FAIL
```
