### ISSUE TITLE
[FEAT] dual CPU support

### ISSUE THREAD

**Issue by AzimovParviz** [fastfetch-cli/fastfetch#1413]
Be sure to read [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

## Wanted features:

I want fastfetch to differentiate if there's multiple physical CPUs on the system. 

## Motivation:

I have no hard numbers to back me up, but I assume there's plenty of people using fastfetch on their dual Xeon workstations running Windows/macOS/Linux.

I have came up with the following macOS only implementation https://github.com/AzimovParviz/fastfetch/commit/d3e8416f73f55ea40bd7dc53934d6b554f11a895 in my fork.

This is how it looks on my MacPro5,1 with dual quad core Xeons 
![fastfetch dual cpu example](https://github.com/user-attachments/assets/9cd96e2a-0955-4bf6-85cc-a48025b36374)

I also did https://github.com/AzimovParviz/fastfetch/commit/3355cd505d6c2f2a2b85aef4d0cf8f3dd807a928 to account for the "2 x" string to the output more clear, but I am not confident in whether this is the correct way to go about it

I did not find any contribution guidelines outside of line 206 of README.md so I am doing a feature request before doing a PR

**Comment by CarterLi** [comment]
Well, fastfetch shows 16 threads. Seems that it already takes dual CPU into account.

Another question: What if user installs 2 different CPU in 1 machine. Is it possible?

**Comment by AzimovParviz** [comment]
> Well, fastfetch shows 16 threads. Seems that it already takes dual CPU into account.
Yeah but wouldn't it be better if outright stated the number of CPUs like on the screenshot? 

> Another question: What if user installs 2 different CPU in 1 machine. Is it possible?
I definitely know that you need to have a matching pair on MacOS. I cannot say for sure for other systems. Cursory google search tells that most motherboards won't even post but some systems seem to work when mixing CPUs. But I never seen it and can't seem to find a video of someone doing it

**Comment by CarterLi** [comment]
If you can figger out how to detect it in Linux and Windows, I am happy to have it supported in fastfetch.

**Comment by AzimovParviz** [comment]
> If you can figger out how to detect the CPU count in Linux and Windows, I am happy to have it supported in fastfetch.

I'll take a shot at it. I never developed on Windows, I spent the entire evening yesterday trying to just build the project. It fails to find vulkan headers whenever I try building. It also won't build unless I do `cmake -G Ninja`

Here's how it looks like
```
$ cmake .. -G Ninja
-- The C compiler identification is Clang 19.1.4
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/msys64/clang64/bin/cc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Found PkgConfig: C:/msys64/clang64/bin/pkg-config.exe (found version "2.3.0")
-- Build type: RelWithDebInfo
-- Threads type: Win32 thread
-- The CXX compiler identification is Clang 19.1.4
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/msys64/clang64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Enabling LTO
-- Target dirs: ROOT="" USR="/usr" HOME="/home" ETC="/etc"
-- Could NOT find Python (missing: Python_EXECUTABLE Interpreter)
CMake Warning at CMakeLists.txt:265 (message):
  Python3 is not found, 'help.json' will not be minified


CMake Warning at CMakeLists.txt:293 (message):
  Python3 is not found, use basic 'fastfetch.1.in' instead


-- Looking for wcwidth
-- Looking for wcwidth - not found
-- Library: found VULKAN
-- Library: missing: IMAGEMAGICK7
-- Library: found ZLIB
-- Library: missing: CHAFA
-- Library: missing: EGL
-- Library: missing: OPENCL
-- Looking for C++ include winrt/Windows.Foundation.h
-- Looking for C++ include winrt/Windows.Foundation.h - not found
-- Disabled package managers: WINGET
-- Configuring done (26.4s)
-- Generating done (0.5s)
-- Build files have been written to: C:/projects/fastfetch/build
```

```
$ cmake --build . --target fastfetch --target flashfetch
[24/211] Building C object CMakeFiles/libfastfetch.dir/src/detection/vulkan/vulkan.c.obj
FAILED: CMakeFiles/libfastfetch.dir/src/detection/vulkan/vulkan.c.obj
C:\msys64\clang64\bin\cc.exe -DFF_HAVE_THREADS=1 -DFF_HAVE_VULKAN=1 -DFF_HAVE_ZLIB=1 -DFF_PACKAGES_DISABLE_LIST=FF_PACKAGES_FLAG_WINGET_BIT -DNOMINMA
X -DUNICODE -DWIN32_LEAN_AND_MEAN -D_GNU_SOURCE -D_WIN32_WINNT=0x0A00 -IC:/projects/fastfetch/build -IC:/projects/fastfetch/src -Wall -Wextra -Wconve
rsion -Werror=uninitialized -Werror=return-type -Werror=incompatible-pointer-types -Werror=implicit-function-declaration -Werror=int-conversion -O2 -
g -DNDEBUG -std=gnu11 -flto=thin -pthread -MD -MT CMakeFiles/libfastfetch.dir/src/detection/vulkan/vulkan.c.obj -MF CMakeFiles\libfastfetch.dir\src\d
etection\vulkan\vulkan.c.obj.d -o CMakeFiles/libfastfetch.dir/src/detection/vulkan/vulkan.c.obj -c C:/projects/fastfetch/src/detection/vulkan/vulkan.
c
C:/projects/fastfetch/src/detection/vulkan/vulkan.c:12:10: fatal error: 'vulkan/vulkan.h' file not found
   12 | #include <vulkan/vulkan.h>
      |          ^~~~~~~~~~~~~~~~~
1 error generated.
[41/211] Building C object CMakeFiles/libfastfetch.dir/src/common/jsonconfig.c.obj
ninja: build stopped: subcommand failed.
```

`$ which vulkan
which: no vulkan in (/clang64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)`

`$ whereis vulkan
vulkan: /usr/include/vulkan`

**Comment by CarterLi** [comment]
You need both vulkan-loader and vulkan-headers. See https://github.com/fastfetch-cli/fastfetch/wiki/Dependencies

Or you can just disable it with `-DENABLE_VULKAN=OFF`

**Comment by AzimovParviz** [comment]
> You need both vulkan-loader and vulkan-headers. See https://github.com/fastfetch-cli/fastfetch/wiki/Dependencies
> 
> Or you can just disable it with `-DENABLE_VULKAN=OFF`

both are already installed. All done from CLANG64. 

```$ pacman -Q | grep vulkan
mingw-w64-clang-x86_64-vulkan-loader 1.3.296.0-1
mingw-w64-x86_64-vulkan-headers 1.3.296.0-1
mingw-w64-x86_64-vulkan-loader 1.3.296.0-1
mingw-w64-x86_64-vulkan-utility-libraries 1.3.296.0-1
mingw-w64-x86_64-vulkan-validation-layers 1.3.296.0-1
```

**Comment by CarterLi** [comment]
You need to install `mingw-w64-clang-x86_64-*`

They are different. `mingw-w64-x86_64-*` is MINGW64

**Comment by AzimovParviz** [comment]
Thanks, instaleld $ pacman -S mingw-w64-clang-x86_64-vulkan-headers and now it builds. 

Any chance you could add these to the wiki? https://github.com/fastfetch-cli/fastfetch/wiki/Building

**Comment by CarterLi** [comment]
Done.

**Comment by xiaoran007** [comment]
> If you can figger out how to detect the CPU count in Linux and Windows, I am happy to have it supported in fastfetch.

For Linux, just read the **physical id** field in the /proc/cpuinfo file. 
For example, in my workstation, which has 2 _xeon silver 4216_ processors, you can see that the first 16 physical cores are 0 and the 17-32 physical cores are 1, indicating CPU0 and CPU1 respectively.
![WechatIMG26](https://github.com/user-attachments/assets/72ab6c44-36f5-47dc-844d-a643dfbd8194)
I can submit a PR for Linux if necessary.

**Comment by AzimovParviz** [comment]
@xiaoran007 https://github.com/fastfetch-cli/fastfetch/pull/1417 I have already started working on Linux so you don't have to. But after I make the necessary commits, I would be happy if you took a look.

**Comment by CarterLi** [comment]
> > If you can figger out how to detect the CPU count in Linux and Windows, I am happy to have it supported in fastfetch.
> 
> For Linux, just read the **physical id** field in the /proc/cpuinfo file. For example, in my workstation, which has 2 _xeon silver 4216_ processors, you can see that the first 16 physical cores are 0 and the 17-32 physical cores are 1, indicating CPU0 and CPU1 respectively. ![WechatIMG26](https://private-user-images.githubusercontent.com/52413051/389415994-72ab6c44-36f5-47dc-844d-a643dfbd8194.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDgwNjcsIm5iZiI6MTczMjU0Nzc2NywicGF0aCI6Ii81MjQxMzA1MS8zODk0MTU5OTQtNzJhYjZjNDQtMzZmNS00N2RjLTg0NGQtYTY0M2RmYmQ4MTk0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDE1MTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NGZiYjlkNjliZjk5NmIxZmYxNTMyN2NjM2ExMDUxNzhlZTcwODY1ODJjMWQ4Y2IyMWVlYTA2NTk0NjgzOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MfHxXkAxKk_bUFbZS6Ijc0kngTnxXND7JgFoXa2R-_U) I can submit a PR for Linux if necessary.

Would you mind to upload your `/proc/cpuinfo` file for testing?

**Comment by AzimovParviz** [comment]
Mine looks like this interestingly enough 
![image](https://github.com/user-attachments/assets/3201290d-44ef-497c-8eba-e280704c0a42)

**Comment by AzimovParviz** [comment]
> Here is the /proc/cpuinfo file for two Xeon Silver 4216 CPU (Hyper-Threading is enabled) [Xeon.txt](https://github.com/user-attachments/files/17905077/Xeon.txt) Because hyper-threading is enabled, cpuinfo displays information for all logical cores. That is, the first 32 cores are physical cores, and the last 32 cores are logical cores for hyper-threading. The order of the reports on macOS may be different from that on Linux, but the actual information is the same. If you need AMD epyc files, please let me know.

the screenshot and cpuinfo i provided are from Linux, but that's interesting about hyperthreading.

**Comment by CarterLi** [comment]
Please test the dev build. BTW I removed the useless white spaces in CPU name.

**Comment by AzimovParviz** [comment]
Oh yeah, that was bothering me too. I noticed that it's a thing on Macs, I saw someone on reddit with a MacBook have a similar whitespace in cpu vendor name but I didn't have it on my 2017 mbp with i5. 

I will take a look on all 3 OSs on my MP when I have a moment

**Comment by AzimovParviz** [comment]
my windows's EFI broke after installing Mint, but the dev branch builds and runs fine on MacOS and Linux. correct output, detects dual CPUs and removes the whitelines
