### ISSUE TITLE
[FEAT] Add the w3m graphics protocol for logos

### ISSUE THREAD

**Issue by TheRealOne78** [fastfetch-cli/fastfetch#1414]
## Wanted features:
Add w3m-img as a graphics protocol for showing image logos on terminal emulators like RXVT-Unicode.

## Motivation:
Neofetch has the w3m graphics protocol, but fastfetch doesn't. Although fastfetch only accepts hardware or system level software feature requests, I guess that fastfetch is also supposed to be a neofetch replacement, and right now it lacks this thing from neofetch.

**Comment by CarterLi** [comment]
w3m is NOT a **terminal image protocol**. It is a dirty hack for terminals that don't support any image protocol and it works on X11 only.

I don't think I want to support that. Switching to a modern terminal which supports real **image protocol** is a better option.
