### ISSUE TITLE
[BUG] alpine 3.19 It doesn't work properly

### ISSUE THREAD

**Issue by SDCOM-0415** [fastfetch-cli/fastfetch#1416]
Be sure to read the [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

# Please note in advance that I am from China, and my English is Microsoft Translator, please understand

# General description of bug:

* What happened: Unable to install
* What should happen: Normal installation
* Fastfetch version used: I don't know
* Did it work in an older version: 
* Where did you get the binary: alpine apk
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)?

# Often helpful information:I don't know, this is from my alpine cloud server, the service provider only gave me the installation option of 3.19, I'm not sure if 3.20 is applicable again

Screenshot:
![image](https://github.com/user-attachments/assets/73736960-cc00-4515-9e5e-daeabc5ca838)

**Comment by CarterLi** [comment]
3.20才收录fastfetch，3.19没有收录。你要用可以尝试在release页面直接下载运行 https://github.com/fastfetch-cli/fastfetch/releases/download/2.30.1/fastfetch-musl-amd64.tar.gz
