### ISSUE TITLE
[FEAT] animated logos

### ISSUE THREAD

**Issue by acxz** [fastfetch-cli/fastfetch#1423]
Be sure to read [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

## Wanted features:

Right now we support static logos of various formats. It would be wonderful to support animated logos such as `.gif` files.

## Motivation:

The motivation here is that I have a shell script, [pokeshell](https://github.com/acxz/pokeshell), which supports the output of both static and animated images to the terminal via `chafa`. I can pipe the static output just fine with `pokeshell pikachu | fastfetch --file-raw -`, but `pokeshell -a pikachu | fastfetch --file-raw -` just clears the current terminal screen. (i.e. `pikachu.gif | fastfetch --file-raw -`)

`pokeshell pikachu | fastfetch --file-raw -`:
![image](https://github.com/user-attachments/assets/8d401461-4b6f-44df-8c00-3688bfcde190)

Here is the animated file that I would like to show in fastfetch:
![pikachu.gif](https://github.com/user-attachments/assets/68a621ec-45d9-49ae-a531-4707c88a525c)

How it looks by itself:

https://github.com/user-attachments/assets/8dcf45c2-fba0-4023-864c-a83674c51199

And when trying to use the file with fastfetch:
![image](https://github.com/user-attachments/assets/be9fa546-d128-45c5-b014-152ec2f924a9)

**Comment by CarterLi** [comment]
`gif`s only work with iTerm image protocol. In WSL2, you may install Wezterm **inside Linux** and use

```jsonc
{
  "logo": {
    "padding": {
      "top": 2
    },
    "source": "/path/to/pikachu.gif",
    "type": "iterm",
    "width": 20
  }
}
```


https://github.com/user-attachments/assets/aebbdd56-612f-4662-853a-b1aa91467f92

**Comment by CarterLi** [comment]
> How it looks by itself:

I assume the program supports the animation by drawing every frame manually. This method doesn't work with fastfetch because fastfetch exits immediately after all modules are printed.

**Comment by CarterLi** [comment]
I tested your script and confirmed your script keeps running if I enables animation mode. You may take a look at [the iterm image protocol](https://iterm2.com/documentation-images.html) which provides much higher resolution and is much simpler to use.

**Comment by acxz** [comment]
I didn't think to check `iterm`... Thanks for that. Is there no plan to support other animation protocols, like kitty or with native chafa output (via redrawing fastfetch output, maybe)?

**Comment by acxz** [comment]
The script actually uses chafa or timg, both of which have support for iterm. I'm testing with a limited character set right now.

**Comment by CarterLi** [comment]
> Is there no plan to support other animation protocols, like kitty or with native chafa output (via redrawing fastfetch output, maybe)?

No plan. Fastfetch is designed to exit as fast as possible. Redrawing is not an option here.

> native chafa output

chafa is not an image protocol. It just print regular texts.

**Comment by acxz** [comment]
also side note, in the config file could I list an arbritary command that outputs a filename? i.e. say if I had a `pokeshell --filename pikachu` which outputs `~/.cache/pokeshell/pikachu.gif`.
Could I do `"source": "pokeshell --filename pikachu"`?

**Comment by acxz** [comment]
Does kitty require redrawing? I thought it was more similar to iterm in that regards?

**Comment by CarterLi** [comment]
> Could I do `"source": "pokeshell --filename pikachu"`?

You may use command substitution. For example `"source": "$(pokeshell --filename pikachu)"`

See also https://github.com/fastfetch-cli/fastfetch/wiki/Logo-options

**Comment by CarterLi** [comment]
> Does kitty require redrawing? I thought it was more similar to iterm in that regards?

Kitty has its own animation protocol that I didn't investigate. I tested this command with 0.37.0 and it works for me

`kitten icat -n --align left ~/pikachu.gif | fastfetch --raw -`

**Comment by ocueye2** [comment]
> Kitty has its own animation protocol that I didn't investigate. I tested this command with 0.37.0 and it works for me
> 
> `kitten icat -n --align left ~/pikachu.gif | fastfetch --raw -`

Here's a better version of it that has a more reasonable scale so those after me don't have to go father down the rabbit hole

kitten icat -n --place 50x50@0x0 --align left (logo path here) | fastfetch --logo-width 50 --raw -

**Comment by bowsarr** [comment]
pewwwwwwwwwwwwwwwwwwwwwwdiepie

**Comment by entropax** [comment]
This command respect fastfetch config and scale image to **box 30x30** with padding **12x6**.
`kitten icat -n --place 30x30@12x6 --scale-up --align left pika.gif | fastfetch --logo-width 50 --raw -`

I think < this is a best option 👍🏽

**Comment by jk0893** [comment]
@entropax May I ask you, how to launch Kitty and then execute this command? I tried searching for info but couldn't come up wth solution myself (skill issue, I guess).

Edit: I figured it out. Since I use Fish as a shell, all I had to do is replace `fastfetch` in `function fish_greeting` with provided command. Now my terminal looks cool B-)

**Comment by krdecadedev** [comment]
yo i want to display kamen rider decade henshin in my fastfetch that's why im here LOL
