### ISSUE TITLE
[FEAT] Add support for multiple logo sources with random selection in --logo option

### ISSUE THREAD

**Issue by jongwoo328** [fastfetch-cli/fastfetch#1426]
## Wanted features:
I'm using the --logo option with the path to the image.
Currently, it seems that only a single source can be specified in that option. 
It would be nice to be able to take multiple logo sources and show one logo at random from them.
Something like this.
It could probably look something like this
- `--logo path1 --logo path2`
- `--logo path1,path2`

Or any other way!

And if this feature is added, I think we could also accept a string array in the schema for logo.

## Motivation:
While it's possible to work around this limitation using shell scripts to randomize the source, having this feature built directly into the CLI would enhance usability and make the tool more user-friendly.

This feature would not only simplify workflows for advanced users but also enable casual users to achieve the same result without needing additional scripting knowledge.

Thank you for creating such a great tool!

**Comment by CarterLi** [comment]
I don't like this idea. I don't think it's worth the effort.

> This feature would not only simplify workflows for advanced users but also enable casual users to achieve the same result without needing additional scripting knowledge.

Comparing `fastfetch --logo ~/Desktop/1.png --logo ~/Desktop/2.png --logo ~/Desktop/3.png --logo ~/Desktop/4.png` with `fastfetch --logo $(shuf -n1 -e ~/Desktop/*.png)`, I don't think it's considered *simplifying*.

**Comment by CarterLi** [comment]
Okey, I desided to simplify it furthur. If the logo source path (with the syntax of [shell expansion](https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html)) matches multiple files, fastfetch will randomly select one. For example:

1. `fastfetch --logo '/path/to/image*.png'`
2. `fastfetch --logo '{/path/to/image1.png,/path/to/image2.png,/path/to/image3.png}'` noting the braces

**Comment by jongwoo328** [comment]
Thank you for adding feature!!
