### ISSUE TITLE
[FEAT] Display Docker containers alongside regular packages and flatpaks

### ISSUE THREAD

**Issue by loxoron218** [fastfetch-cli/fastfetch#1427]
Be sure to read [[FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq)](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

## Wanted features:

- Display Docker containers alongside regular packages (dpkg, rpm, pacman) and Flatpaks in the Fastfetch output.
- Maybe with a simple command like this?
`sudo docker ps -q | wc -l`

## Motivation:

I work with Docker containers alongside traditional package managers, and having both types of software (packages and containers) displayed in one unified overview would be incredibly useful. It think it would simplify managing and reviewing all installed applications and environments without needing to use separate commands or tools for Docker and would streamline my workflow :)

**Comment by CarterLi** [comment]
```
{
  "type": "command",
  "text": "sudo docker ps -q | wc -l",
  "key": "Docker containers"
}
```

**Comment by loxoron218** [comment]
Is it possible to add it to the default _fastfetch_ version?
