### ISSUE TITLE
[FEAT] Wrap logo on small screens

### ISSUE THREAD

**Issue by Henry-Hiles** [fastfetch-cli/fastfetch#1431]
Be sure to read [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

## Wanted features:

On small screens, all the system information gets cut off: 
![Screenshot from 2024-12-09 13-16-08](https://github.com/user-attachments/assets/92b45986-089a-450b-b7a0-db9aa20a39a2)

It would be ideal if the details would be put under the text on these small screens. Thanks!

**Comment by CarterLi** [comment]
Please try `fastfetch --logo-position top`

**Comment by Henry-Hiles** [comment]
Oh, my bad, didnt know that was a thing. Thank you!!
