### ISSUE TITLE
[FEAT] installer pkg for macOS

### ISSUE THREAD

**Issue by alsyundawy** [fastfetch-cli/fastfetch#1432]
Be sure to read [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

## Wanted features:

[FEAT] installer pkg for macOS

## Motivation:

Easy install without brew or manualy install

**Comment by CarterLi** [comment]
You don't need to *install* it. You extract the archive and you are done.

**Comment by alsyundawy** [comment]
extract with root ? can you give me example?

**Comment by CarterLi** [comment]
`curl -L https://github.com/fastfetch-cli/fastfetch/releases/download/2.31.0/fastfetch-macos-universal.tar.gz | tar zxvf - && fastfetch-macos-universal/usr/bin/fastfetch`
