### ISSUE TITLE
[BUG] Intel Xe kernel driver warning from Mesa, not suppressed

### ISSUE THREAD

**Issue by nokia8801** [fastfetch-cli/fastfetch#1435]
When using the new Xe kernel driver for Intel GPUs instead of i915, the usual Xe warning is also displayed in fastfetch when `opengl` config option is enabled.

> MESA: warning: Support for this platform is experimental with Xe KMD, bug reports may be ignored.

This warning is present everywhere when using the Xe kernel driver, but I guess it'd be nice if fastfetch could ignore it, since that kinda defeats the purpose. It cuts the logo too.

**Screenshot:**
![image](https://github.com/user-attachments/assets/64f460b1-5179-444b-b6ea-bf5154f91f7a)

**Config:**
```
{
    "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
    "logo": {
        "padding": {
            "top": 2
        }
    },
    "modules": [
        "title",
        "separator",
        "os",
        "kernel",
        "initsystem",
        "uptime",
        "packages",
        "shell",
        "editor",
        "display",
        "de",
        "wm",
        "terminal",
        {
            "type": "cpu",
            "showPeCoreCount": false,
            "temp": true
        },
        {
            "type": "gpu",
            "driverSpecific": true,
            "temp": true
        },
        "vulkan",
        "opengl",
        "opencl",
        "memory",
        "physicalmemory",
        "swap",
        "disk",
        "datetime",
        "version",
        "break",
        "colors"
    ]
}
```

`opengl` value seems to be the culprit. Doesn't happen without it.

**Comment by CarterLi** [comment]
[We already do that](https://github.com/fastfetch-cli/fastfetch/blob/dev/src/detection/opengl/opengl_shared.c#L137). Please provide the output of `fastfetch --format json` for debugging.

**Comment by nokia8801** [comment]
[debug.log](https://github.com/user-attachments/files/18122280/debug.log)

**Comment by CarterLi** [comment]
Please test the dev build

**Comment by nokia8801** [comment]
Ok, I cloned the repo and followed the building instructions and ran `./fastfetch` without installing.

No more warning. Thanks.

But I can't install the AUR version. It fails for me.
