### ISSUE TITLE
[BUG] showAllIps not showing all IPs

### ISSUE THREAD

**Issue by ronen1n** [fastfetch-cli/fastfetch#1440]
# General description of bug:

* What happened: when i connect to vpn using openvpn command i dont see my ip in localip and when i'm using the kali network manneger to connect to the vpn i do see it but every time i see only 1 ip even when i configured the showallips like:
```
        {
            "type": "localip",
            "showPrefixLen": false,
            "showAllIps": true,
            "compact": true,
            "outputColor": "cyan"
        },
```
Also tried with and without the '"compact": true,'

* What should happen: show all IPs including the vpn ip
* Fastfetch version used: Version: fastfetch 2.31.0 (x86_64)

* Where did you get the binary: GitHub release

Output of `fastfetch -c ci.jsonc --format json`:
```
...
  {
    "type": "PublicIp",
    "error": "ffNetworkingSendHttpRequest() failed",
    "stat": 623.7384109999985
  },
  {
    "type": "LocalIp",
    "result": [
      {
        "name": "tun1",
        "defaultRoute": true,
        "ipv4": "10.9.1.199/16",
        "ipv6": "fe80::7f5b:6d7:9c68:3e00/64",
        "mac": "",
        "mtu": 1500,
        "speed": 10000,
        "flags": "UP,POINTOPOINT,RUNNING,NOARP,MULTICAST,LOWER_UP"
      }
    ],
    "stat": 0.30129999993368983
  },
  {
    "type": "DNS",
    "result": [
      "10.0.0.2"
    ],
    "stat": 0.036700000055134296
  },
  {
    "type": "Wifi",
    "result": [],
    "stat": 0.16580000007525086
  },
...
```

Output of `fastfetch --list-features`:
```
threads
vulkan
wayland
xcb-randr
xrandr
drm
drm_amdgpu
gio
dconf
dbus
imagemagick7
imagemagick6
chafa
zlib
xfconf
sqlite3
rpm
egl
glx
osmesa
opencl
libpulse
libddcutil
libelf
libzfs
Directx Headers
linux/videodev2
linux/wireless
Embedded pciids
```

Didn't find anything more to try in docs
If you need more info please tell me
fastfetch showing only one ip at a time like:
        -#         Local IP: 10.9.1.199
         @         DNS: 10.0.0.2

**Comment by CarterLi** [comment]
`"defaultRouteOnly": false`
