### ISSUE TITLE
Fastfetch slow on powershell

### ISSUE THREAD

**Issue by lilnynho** [fastfetch-cli/fastfetch#1449]
Be sure to read the [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

# General description of bug:

* What happened:
* What should happen:
* Fastfetch version used: 
* Did it work in an older version: 
* Where did you get the binary: 
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)?

# Often helpful information:

Screenshot:

The content of the configuration file you use (if any):
```
// Paste here
```

Output of `fastfetch -c ci.jsonc --format json`:

```
// Paste here
```

Output of `fastfetch --list-features`:
```
// Paste here
```

## If fastfatch crashed or froze

Paste the stacktrace here. You may get it with:

```shell
# You may need Ctrl+C to stop the process if it freezes
gdb -q -ex 'set confirm off' -ex run -ex 'bt full' -ex quit --args /path/to/fastfetch
```

If you are able to identify which module crashed, the strace can be helpful too

```shell
strace /path/to/fastfetch --multithreading false -s {MODULE} --pipe
```

If you cannot do the instructions above, please upload the core dump file:

## If fastfetch is slow

Use `time fastfetch --stat` to show time usage for each module.![Screenshot_20241218_215011_spacedesk.jpg](https://github.com/user-attachments/assets/e714621d-79eb-4226-9a49-4556344b614d)

## If an image or logo didn't show 

* The image protocol you used: 
* The terminal you used: 
* Upload the image file here, or paste the image URL: 
* Does it work with `--logo-width {WIDTH} --logo-height {HEIGHT}`? 

## If fastfetch behaves incorrectly on shell startup

* The bug is reproducible with a clean shell configuration (i.e. `fastfetch` is the only line in `.zshrc` or `~/.config/fish/config.fish`): 
* Does `sleep 1` before running `fastfetch` work?

**Comment by CarterLi** [comment]
It's expected.

I suggest you use the [modern PowerShell](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4) instead of the old Windows PowerShell.

If you don't want to use a different shell, you may use `fastfetch --detect-version false` to workaround this issue.

**Comment by CarterLi** [comment]
In the dev branch, you can also add this line in `$PROFILE` to resolve the issue.

```powershell
# $PROFILE
$env:POWERSHELL_VERSION = $PSVersionTable.PSVersion.ToString()
```

**Comment by 0-BlackSpectrum-0** [comment]
same issue, it takes like 20+ seconds to load all the disc and stops halfway, at printing ASCII, I've attached the gif, I used stat and it said drives data took `21036.388ms` sometimes the profile takes 30k+ ms and sometimes it takes 60k+ which is a lot!
`fastfetch 2.67.0 (x86_64)`
`Windows 11 26220.9022`

https://github.com/user-attachments/assets/30bf8c97-8196-406a-8506-9d9271cd3f44

**Comment by CarterLi** [comment]
@0-BlackSpectrum-0 If you are here asking for help, you must provide enough information for us to investigate.

All I know about your issue is that it's not related to powershell. Please file a new issue and fill the template.
