### ISSUE TITLE
[BUG] fastfetch sees through Termux PRoot

### ISSUE THREAD

**Issue by Usinganame** [fastfetch-cli/fastfetch#1452]
# General description of bug:

* What happened: Running under Kali Linux PRoot showed the Android Logo
* What should happen: It should show the Kali logo
* Fastfetch version used: 2.32.1
* Did it work in an older version: Unknown
* Where did you get the binary: Kali Linux Apt repository
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Not Applicible, Builds are only for amd64

# Often helpful information:

Screenshot:
![Screenshot_20241219_181525_Termux](https://github.com/user-attachments/assets/31e6b6b2-7a52-4546-8dd1-48d298221d19)
Output of `fastfetch -c ci.jsonc --format json`:

[ff.log](https://github.com/user-attachments/files/18204523/ff.log)
Beware searching through this file for anything useful, Android mounts a lot of filesystems

Output of `fastfetch --list-features`:
```
threads
vulcan
freetype 
```

**Comment by CarterLi** [comment]
When compiled for Android, we don't try to detect Linux distros.

**Comment by Usinganame** [comment]
Its not compiled for android. This is the one packaged in Kali Linux, so it is compiled for Debian/Ubuntu
