### ISSUE TITLE
[BUG] ATA Interfaces

### ISSUE THREAD

**Issue by tutralex** [fastfetch-cli/fastfetch#1453]
Recently, the {3} format parameter physicaldisk for ATA interfaces has been empty, and it is added to the drive name in front, while everything is fine with the NVMe interface.

**Comment by tutralex** [comment]
{
 "type": "physicaldisk",
 "key": "├─Disk",
 "keyColor": "green",
 "format": "{1} ({?3}{3}/{?}{6})"
},

Result:
├─Disk: 223.57 GiB (SSD)
├─Disk: 931.51 GiB (HDD)
├─Disk: 931.51 GiB (HDD)
├─Disk: 894.25 GiB (SSD)
├─Disk: 931.51 GiB (NVMe/SSD)

**Comment by CarterLi** [comment]
Please provide output of `--format json`

**Comment by CarterLi** [comment]
Dev branch should fix your issue. Please test
