### ISSUE TITLE
[LOGO]  NurOS

### ISSUE THREAD

**Issue by AnmiTaliDev** [fastfetch-cli/fastfetch#1456]
Hello, I am the team leader of the NurOS project, which is a Linux distribution from Kazakhstan. And I want to add our logo.
# OS
```
These files are not available yet, but I can provide:
1. Name: NurOS
2. Version 1
3. Homepage: https://nuros.anmitali.kx
4. Version codename Juldyz (Star)
5. GitHub nuros-linux
6. Developers: AnmiTali/NurOS Team
```

# Ascii

Sorry, I do not know the color codes.

```
                     ___╓╓___
                 _▄▄▓▓▀▀╜╜╨▀▓▓▓╗_
               ╓▓▓▀²          `╙▓▓╖
              ╣▓▀   _▄▓▓▓▓▓▓W_   ╙▓▓
             ╣▓╜  ,▓▓▓▓▓▓▓▓▓▓▓▓_  ²▓▓
            ╒▓▌   ▓▓▓▓▓▓▓▓▓▓▓▓▓▓   ║▓m
            ╞▓▓  í▓▓▓▓▓▓▓▓▓▓▓▓▓▓h  ╞▓╡
            ²▓▓   ▓▓▓▓▓▓▓▓▓▓▓▓▓▓   ║▓h
             ║▓▄   ╙▓▓▓▓▓▓▓▓▓▓╜   ƒ▓▓
              ╙▓▓_   ⁿ╙╨╝╝╝╜²   _╢▓╜
                ╙▓▓╗__       _╗▓▓╜
                  `╙╝▓▓▓▓▓▓▓▓╝╙

```
![image_2024-12-21_22-37-18](https://github.com/user-attachments/assets/1bfe31bc-5bcb-47e8-aa69-959f10928879)
![nuroslogo](https://github.com/user-attachments/assets/3293133b-746a-4c47-a594-2d910f812954)

**Comment by GoldenVadim** [comment]
Hello, I'm participant of NurOS. Thank you for this.

**Comment by HOGNIG** [comment]
вау

**Comment by CosmoBlade** [comment]
I'm also developing nurOS, thanks you
