### ISSUE TITLE
[BUG] Enumerating PCI devices should not need root privileges.

### ISSUE THREAD

**Issue by time-killer-games** [fastfetch-cli/fastfetch#1457]
According to 2.32.1 Release Notes:

>Bugfixes:
>
>    Fix pci.ids file location on OpenBSD (GPU, OpenBSD)
>        It's normally unused because enumerating PCI devices on OpenBSD requires root privileges

Wouldn't it be better to download the latest version of `pci.ids` from the website, and then compile it directly into the executable?

```
curl -o pci.ids https://pci-ids.ucw.cz/pci.ids
xxd -i pci.ids > pci.ids.h
```

There should also be a way to automate only downloading a specific `pci.ids` file version relative to the current release of fastfetch, I'm pretty sure. I have code I wrote in C++ which parses device and vendor name by its ID, (and the ID can be retrieved by GLX or Vulkan, depending on the platform): [system.cpp#L433-L468](https://github.com/time-killer-games/sysinfo/blob/9639143b17b8f8999349e32be5a2ea5959e11267/system.cpp#L433-L468). 

Of course, you would need to rewrite the code in C, but the same basic code logic will stay there. I think this would be a much better approach than relying on root privileges, only issue I can see is that it requires hardware acceleration and Xorg or Wayland to work, (i.e. the `vesa` or `scfb` drivers won't cut it).  

These are just my thoughts on how this could be approached better. As a fallback, you could use the `glGetString(GL_VENDOR)` for the vendor and `glGetString(GL_RENDERER)` for the device, and whatever equivalent there is for Vulkan, where applicable. 

This would work as long as an Xorg or Wayland session is running in the current TTY. 

Edit: sorry for having no title to this ticket initially. I don't know how I missed that, honestly.

**Comment by CarterLi** [comment]
It's inrelevant. I meant querying PCI device id list requires root permission.

See also https://github.com/fastfetch-cli/fastfetch/blob/dev/scripts/gen-pciids.py

**Comment by time-killer-games** [comment]
> It's inrelevant. I meant querying PCI device id list requires root permission.
> 
> See also https://github.com/fastfetch-cli/fastfetch/blob/dev/scripts/gen-pciids.py

Unless I am deeply missing something, this is not irrelevent. You can get a PCI device ID from either GLX or Vulkan, and then use the ID to get the parsed name out of pci.ids. This does not require root permissions, not even 1%. If you think this requires root, either you are doing something horribly wrong, or there is some sort of miscommunication, and we aren't talking about the same thing when we say "PCI device ID".

**Comment by CarterLi** [comment]
GLX and Vulkan themselves report GPU names. Why do you bother getting the GPU device ids and query the PCI names manually dude?

Fastfetch supports querying GPUs via GLX and Vulkan (and OpenCL by the way) as alternates, if failed to querying PCI devices directly.

**Comment by time-killer-games** [comment]
Are you actually trying the code I just shared, or anything remotely like it? It reports GPI vendor and device names as a fallback, but as a first attempt it does actually try to get the ID and derive the the vendor and device names from that.

**Comment by CarterLi** [comment]
Did you actually try fastfetch?

![image](https://github.com/user-attachments/assets/1c8a2542-76be-442d-b991-5a8ec8120281)

**Comment by time-killer-games** [comment]
The reason is because `get_vendor_or_device_name_by_id()` takes the PCI ID spit out of GLX, and gives the actual string reported by pci.ids, which is more descriptive and exact compared to the strings given by GLX itself.

**Comment by CarterLi** [comment]
False. pci.ids is maintained by community. It may miss some devices and contain mistakes. See https://github.com/fastfetch-cli/fastfetch/issues/1282

**Comment by CarterLi** [comment]
And https://github.com/fastfetch-cli/fastfetch/issues/1242#issuecomment-2326377561

**Comment by time-killer-games** [comment]
Even if imperfect and maintained by some random community (like everything else written by programmers) I don't see where the word "False" is even being applied here. It gives the exact chipset or vendor name of an ID, and simply being willing to accept "Intel UHD Graphics" as being perfectly descriptive enough I have trouble relating to. The release notes already claim pci.ids is being used under root, so my very realistic question here is, why does it have to be limited to root users for no reason?

**Comment by CarterLi** [comment]
AGAIN. IT IS QUERYING PCI DEVICES DIRECTLY THAT REQUIRES ROOT! IN THIS CASE, PCI.IDS IS NOT USED UNLESS SOMEONE RUNNING FASTFETCH IN ROOT SO THE BUG SHOULD NOT AFFECT MOST PEOPLE!

**Comment by CarterLi** [comment]
![image](https://github.com/user-attachments/assets/bbfdece0-d15c-4357-ae06-6cf48f5ad72d)

**Comment by CarterLi** [comment]
There are flaws of GLX:
1. It requires proper GPU driver that supports OpenGL installed.
2. It requires X server. Which means, it doesn't work in TTY or SSH session.

For OpenBSD, it doesn't even support nouveau, so that my NVIDIA laptop is running entirely in software renderer. With GLX, you get llvmpipe only.

**Comment by CarterLi** [comment]
![2024-12-22-130035_1366x768_scrot](https://github.com/user-attachments/assets/74f93ed9-64e2-4477-abba-d8852cc13720)

Please get my words before talking. Thanks
