### ISSUE TITLE
[BUG] Clarification on #1457

### ISSUE THREAD

**Issue by time-killer-games** [fastfetch-cli/fastfetch#1458]
Please don't close this ticket--this is a valid bug--it is a valid discussion. A harmless, legitimate perspective. I'm terribly sorry a maintainer got so offended by something that wasn't even the slightest bit derogatory. My follow up to: https://github.com/fastfetch-cli/fastfetch/issues/1457 Their screenshot attempting to prove something, (I'm not sure what), right after preventing me to reply any further:

![Screenshot from 2024-12-21 18-54-22](https://github.com/user-attachments/assets/2c689465-e0f5-4d9b-9006-47f9c9273822)

If you want to believe it's not possible because of what you tried alone than I can't force you to believe it can still work by other means. The above screenshot proves nothing besides the person who posted it wasn't reading anything I was telling them at all, and they also yelled at me and got angry when I wasn't doing anything wrong to them, just pointing out a bug they didn't want to fix. I am very aware the solution I gave was not bullet-proof, and it will sometimes report llvmpipe or something like that, in such a case we can use some form of fallback to avoid that, just like what you already do when failing to read the PCI ID if not running fastfetch under a root user.

I can't force this bug to be fixed, if you don't want to fix it, you don't have to. But my goodness, at least let people report bugs without closing and locking their tickets, so that others who actually want to fix the problem can see it and do something about it. Locking the discussion is extremely immature and makes it look like the user cares more about being right and proving me wrong than having any real, two-sided, discussion. They wanted a monologue, not allowing me to express perfectly harmless and valid thoughts. I don't mean these things as an insult. If you want people working with you on an open source, (or any), project, it seriously pays to not be hostile.

Prerequisites:

You need Xorg installed (Xenocara). In a lot of cases you would likely need to run `fw_update` to ensure you have graphics acceleration enabled. If there are no graphics drivers available for you chipset, even after running `fw_update`, using GLX or Vulkan to get the PCI ID will fail, and this would also be the case when running without an Xorg or Wayland session, or when running under the scfb/vesa drivers.

Steps to produce and observe what I described in my previous ticket does in fact work for those who care enough to do it:

1. On OpenBSD you need the following installed: `git`, `xxd`, `pkgconfig`, `sdl2`, and `x11`.
2. Run the following in an Xorg graphical session:
```
git clone https://github.com/time-killer-games/sysinfo $HOME/sysinfo && cd sysinfo && ./build.sh
```
3. Be amazed.

If `fw_update` or the built-in kernel itself provided the graphics drivers necessary for retrieving the proper PCI ID, and pci.ids had that chipset and vendor correctly listed, you should see that information then printed to the terminal beside the "GPU MANUFACTURER" and "GPU RENDERER" fields. Again, you already have it so that there is a fallback when not run as root, why can't the same fallback be used when there is Xorg or no graphics acceleration instead? This would have a lot less failure cases to display the right information. 

The only time it wouldn't show the right information is when the pci.ids file is bugged, you don't have Xorg running in the current TTY, or no drivers exist for your graphics card, that is way less failure cases than simply failing every single time you are not running under root.

All of these things I mentioned are perfectly valid and reasonable to consider. I don't care to argue about this so I won't say anything else. I don't appreciate being treated this way just because I told you something you don't want to hear--you wrote software with bugs.

Have a nice day.

**Comment by CarterLi** [comment]
There is no xxd in OpenBSD, nor `pkg_add xxd` work

**Comment by time-killer-games** [comment]
There is, would you like me to provide video footage?

**Comment by CarterLi** [comment]
Got it working by installing vim. This is what I get
![image](https://github.com/user-attachments/assets/541a85dd-cc8b-4b4c-8bcb-808790449c72)

**Comment by CarterLi** [comment]
![2024-12-22-133159_1366x768_scrot](https://github.com/user-attachments/assets/bc407c81-1109-450c-bca6-6553063a7b92)

Just some normal stuff. To be honest I didn't get amazed...

**Comment by time-killer-games** [comment]
![Screenshot_2024-12-21_22-37-23](https://github.com/user-attachments/assets/9288a0f9-9283-4678-b295-0eca576e2204)

**Comment by CarterLi** [comment]
> Do you have graphics acceleration enabled?

No. As I have said, OpenBSD doesn't even have nouveau, nor does the proprietary nvidia driver.

**Comment by time-killer-games** [comment]
Well yeah, but forcing this feature to only work when run as root, when it could work for more than 99% of non-NVIDIA GPU's is very limiting. That's the only point I was making in my initial ticket. If you don't find that pressing enough to do anything about it, then I guess there's nothing left to discuss.

**Comment by CarterLi** [comment]
> when it could work for more than 99% of non-NVIDIA GPU's

I don't think so. AFAIK GPU manufacturers (except NVIDIA for FreeBSD I think) don't really care *BSDs. All GPU drivers of *BSDs (except NVIDIA for FreeBSD) are ported from Linux, which makes it very slow to support newest GPU devices. Even the most up-to-date BSD - FreeBSD has issues with Intel GPU. [The newest GPU driver (only i919 but xe) of FreeBSD is ported from Linux 6.1](https://www.freshports.org/graphics/drm-61-kmod/). The newest Linux version is 6.12.

I still don't know what you want me to do. If fastfetch fails to query PCI devices directly, it silently falls back to vulkan or OpenGL. That's why the GPU entry in my last screenshot is detected as llvmpipe. I have repeated myself several times.

**Comment by time-killer-games** [comment]
I've repeated myself multiple times too. This isn't getting anywhere. At this point, I would just say, don't worry about it.

Thank you for at least being willing to continue to discuss this at all. I really appreciate it.
