### ISSUE TITLE
[BUG] Media refuses to show up

### ISSUE THREAD

**Issue by ajd07** [fastfetch-cli/fastfetch#1461]
# General description of bug:

* What happened: With `fastfetch --format json` Media says "No media found", it also does not show up when running fastfetch with the module enabled.
* What should happen: It should be finding either Firefox or VLC
* Fastfetch version used: 2.32.1
* Did it work in an older version: Yes, but I don't remember which one. It was working last month though.
* Where did you get the binary: Installed by package manager (Pacman)
* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)?
Yes
# Often helpful information:
This used to work like normal, in the screenshot it should be above Sound.
Screenshot:
![image](https://github.com/user-attachments/assets/1f3f4d1e-2830-45c5-bc23-f9ef1ada50cd)

The content of the configuration file you use (if any):
```
{
  "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
  "modules": [
    "os",
    "kernel",
    "uptime",
    "separator",
    "packages",
    "shell",
    "de",
    "wm",
    "wmtheme",
    "theme",
    "icons",
    "font",
    "terminal",
    "terminalfont",
    "separator",
    "cpu",
    "gpu",
    "memory",
    "swap",
    "disk",
    "separator",
    "media",
    "sound",
    "break",
  ]
}
```

Output of `fastfetch --list-features`:
```
threads
vulkan
wayland
xcb-randr
xrandr
drm
drm_amdgpu
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
egl
glx
osmesa
opencl
libpulse
libddcutil
libelf
libzfs
Directx Headers
System yyjson
linux/videodev2
linux/wireless
```

**Comment by CarterLi** [comment]
Should be fixed in dev branch
