### ISSUE TITLE
[FEAT] Add support for detecting terminal font for Ghostty

### ISSUE THREAD

**Issue by justbispo** [fastfetch-cli/fastfetch#1466]
## Wanted features:

Currently `TerminalFont` shows the error `Unknown terminal: ghostty`. Add support for detecting the font for the [Ghostty](https://ghostty.org/) terminal.

## Motivation:

Besides me being a new user of this terminal, it's gaining popularity recently after becoming open source and having its first release.

**Comment by CarterLi** [comment]
Please test the dev build

**Comment by Red6785** [comment]
Doesn't work for me on MacOS Sequoia.
```[
  {
    "type": "TerminalFont",
    "error": "Couldn't find file `ghostty/config`"
  }
]

**Comment by moebis** [comment]
@CarterLi I built the dev version (looks exactly the same) still shows the wrong fonts, and also doesn't support kitty

<img width="1162" alt="image" src="https://github.com/user-attachments/assets/1b3f777d-0a2d-4148-8fa3-13971ff2f7a2" />

**Comment by CarterLi** [comment]
> @CarterLi I built the dev version (looks exactly the same) still shows the wrong fonts, and also doesn't support kitty
> 
> <img width="1162" alt="image" src="https://github.com/user-attachments/assets/1b3f777d-0a2d-4148-8fa3-13971ff2f7a2" />
> 

Please upload your ghostty config file
