### ISSUE TITLE
Output of "Terminal" is wrong if script is using #!/bin/sh

### ISSUE THREAD

**Issue by thingsiplay** [fastfetch-cli/fastfetch#366]
# General description of bug:

Using fastfetch within a script with `#!/bin/sh` will result the terminal as the name of the script. But changing it to `#!/bin/env bash` will result in correct terminal, kitty in my case. I consider this a bug, even if this is expected from scripting perspective. Notice this issue is present in previous versions of fastfetch too, but I just decided to make a report today.

# Often helpful questions:
* Does the issue occur across multiple terminal emulators? Y (tested with kitty and konsole)
* Does the issue occur across multiple shells? (bash, zsh, fish, etc) NA (yes, but no, tricky to answer, due to the nature of the problem)

Output of `fastfetch --version`:
```
fastfetch 1.8.0
```

Output of `fastfetch --load-config devinfo`:
```
fastfetch --load-config devinfo                        
██████████████████  ████████    tuncay@matrix
██████████████████  ████████    -------------
██████████████████  ████████    OS: Manjaro Linux x86_64
██████████████████  ████████    Host: neither product_family nor product_name is set by O.E.M.
████████            ████████    Kernel: 6.1.1-1-MANJARO
████████  ████████  ████████    Uptime: 22 hours, 54 mins
████████  ████████  ████████    Packages: 2396 (pacman)[stable], 2 (flatpak)
████████  ████████  ████████    Shell: zsh 5.9
████████  ████████  ████████    Resolution: 2560x1440 @ 144Hz
████████  ████████  ████████    DE: KDE Plasma 5.26.4
████████  ████████  ████████    WM: LG3D (X11)
████████  ████████  ████████    WM Theme: Unknown WM: LG3D
████████  ████████  ████████    Theme: breeze (GruvboxColors) [QT], Klaus [GTK2/3/4]
████████  ████████  ████████    Icons: breeze [QT], Gruvbox [GTK2/3/4]
                                Font: Noto Sans (12pt) [QT], Noto Sans (12pt) [GTK2/3/4]
                                Cursor: default (24px)
                                Terminal: kitty
                                Terminal Font: SauceCodePro Nerd Font Mono (14.0pt)
                                CPU: Intel(R) Xeon(R) E3-1230 v3 (8) @ 3.7 GHz
                                GPU: NVIDIA GeForce GTX 1070
                                Memory: 1.95 GiB / 15.57 GiB (12%)
                                Disk (/): 134 GiB / 220 GiB (61%)
                                Disk (/home/tuncay/.steam/steam_games): 430 GiB / 916 GiB (46%) [Removable]
                                Disk (/home/tuncay/Arbeitsplatz): 996 GiB / 4 TiB (27%) [Removable]
                                Disk (/home/tuncay/Backup): 264 GiB / 917 GiB (28%) [Removable]
                                Disk (/home/tuncay/Bilder): 996 GiB / 4 TiB (27%) [Removable]
                                Disk (/home/tuncay/Dokumente): 996 GiB / 4 TiB (27%) [Removable]
                                Disk (/home/tuncay/Downloads): 996 GiB / 4 TiB (27%) [Removable]
                                Disk (/home/tuncay/Emulatoren): 4 TiB / 5 TiB (78%) [Removable]
                                Disk (/home/tuncay/Musik): 996 GiB / 4 TiB (27%) [Removable]
                                Disk (/home/tuncay/Projekte): 996 GiB / 4 TiB (27%) [Removable]
                                Disk (/home/tuncay/VM): 430 GiB / 916 GiB (46%) [Removable]
                                Disk (/home/tuncay/Videos): 996 GiB / 4 TiB (27%) [Removable]
                                Disk (/media/Backup): 264 GiB / 917 GiB (28%)
                                Disk (/media/Emulation): 4 TiB / 5 TiB (78%)
                                Disk (/media/My): 996 GiB / 4 TiB (27%)
                                Disk (/media/System): 430 GiB / 916 GiB (46%)
                                Battery: batteryDir doesn't contain any battery folder
                                Power Adapter: Not supported on this platform
                                Locale: de_DE.UTF-8

                                ████████████████████████
                                ████████████████████████
```

Output of `fastfetch --load-config devinfo-verbose`:

```
Error: unknown option: --media-format
```

Output of `fastfetch --list-features`:
```
libpci
vulkan
wayland
xcb-randr
xcb
xrandr
x11
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
egl
glx
osmesa
opencl
```

**Comment by LinusDierheimer** [comment]
I cannot reproduce. If i execute [run.sh](https://github.com/LinusDierheimer/fastfetch/blob/dev/run.sh), which has `#!/usr/bin/env sh` at the top, i correctly get `konsole` as my terminal and `zsh` as my shell. In fact, i already explicitly ignore `sh` when walking up the process tree: https://github.com/LinusDierheimer/fastfetch/blob/50983f83f5c80c8241d2ce8ce697dcd5c3e6c558/src/detection/terminalshell/terminalshell_linux.c#L135

When putting `#!/usr/bin/env bash` at the top, the terminal is still `konsole`, but the shell is `bash`. I think that this is correct behaviour. Do you mean this?

**Comment by thingsiplay** [comment]
`#!/usr/bin/env sh` and `#!/bin/sh` are not the same. I have just tested it with a fresh script. While the first one (your example with env sh) will list the Terminal correctly, but when using the more common approach (/bin/sh) it does not work.

**Comment by thingsiplay** [comment]
I tested following in the interactive shell / terminal (in my zsh):

1. Run `sh` and `echo $0`, result: `sh`
2. Run `/usr/bin/env sh` and `echo $0`, result: `sh`
3. Run `/bin/sh` and `echo $0`, result: `/bin/sh`

Not sure if this is any helpful, but sharing can't hurt.

**Comment by LinusDierheimer** [comment]
I can reproduce this behaviour. Putting `#!/usr/bin/sh` at the top changes the process name from `sh` to `run.sh`.

This makes it pretty hard to fix, because how should fastfetch know if `run.sh` is just a script or a terminal? There is no difference from a process point of view. Detecting shells only work because of a hard coded list of known shell process names.

My best solution right now would be to ignore process names containing a dot, because executables usually don't have it, but this fails for scripts without an file extension (or names longer than 16). Do you have a better idea?

**Comment by LinusDierheimer** [comment]
I might switch from process name to executable name, as this should still be `sh`. Looking into this now.

**Comment by thingsiplay** [comment]
Would it make sense to check if its a text (script) or binary executable? Terminals aren't scripts usually. But on the other hand, if someone uses a script to run a Terminal...

**Comment by LinusDierheimer** [comment]
No, kitty for example is a python script.

**Comment by thingsiplay** [comment]
On my system kitty is an ELF executable. But either way, your case shows this is a bad assumption. I noticed that when the Terminal is fetched correctly, then we get also the Terminal Font. So maybe that's the way to go.

**Comment by CarterLi** [comment]
We may detect shell and terminal by env variables ($SHELL and $TERM_PROGRAM) first, which is set by shell and terminal themselves, and is more accurate.

**Comment by thingsiplay** [comment]
On my machine `$SHELL` is set, but not `$TERM_PROGRAM`. So the latter does not seem to be universally working. You probably meant `$TERM`.

**Comment by CarterLi** [comment]
It is `$TERM_PROGRAM`. Modern terminals set it, but not gnome-terminal

`$TERM` is always `xterm-*`, which is useless.

**Comment by LinusDierheimer** [comment]
> We may detect shell and terminal by env variables

```bash
> env | rg -i term                        
COLORTERM=truecolor
TERM=xterm-256color
```
Konsole can't be detected that way

**Comment by LinusDierheimer** [comment]
What if we walk up the process tree and use the shell that is the closest child to the terminal as shell. If we use executable names scripts would be seen as shell too. For example in the following tree, konsole would be the terminal, and zsh the shell:
```
konsole
- zsh
  - bash (executable name of run.sh process)
    - fastfetch
```

What wouldn't work is, when the user starts a shell from within a shell:
```
konsole
- zsh
  - bash (by typing bash)
    - fastfetch
```
Same output, but the shell should be bash. Don't know how to detect that one. Maybe look if the process name doesn't match the exe name for known shell processes?

**Comment by CarterLi** [comment]
Since this issue is not a regression. I'd like to release 1.8.1 first to [fix the build error for homebrew](https://github.com/Homebrew/homebrew-core/pull/119329#issuecomment-1367471112)

**Comment by LinusDierheimer** [comment]
Okay, lets do that. Having the fix for #364 is also good.

**Comment by thingsiplay** [comment]
Using `#!/usr/bin/env sh` will search the PATH environment for `sh`, which means the argument is `sh`. And `#!/bin/sh` is called directly without an argument. Maybe it is possible to check the arguments of the process?

AND BTW `$TERM_PROGRAM` is not only not set by gnome-terminal, but on my kitty as well.

**Comment by Dan1jel** [comment]
same for me, `#!/usr/bin/bash` gave same issue, changed to `#!/usr/bin/env bash` and now shows correcly, at least it shows if im in a tmux shell or not :)

**Comment by jumps-are-op** [comment]
Why not use `stdin`/`stdout`/`stderr` files?

Here is `tty` on my system which return the terminal pts file
```
user@host ~$ tty
/dev/pts/2
```
We could check for which PID is the owner/master/creator of `/dev/pts/2` to get
its exe name.

And if the `/dev/stdin` resolve to `/dev/tty[0-9]` then we are in a TTY.

**Comment by CarterLi** [comment]
> Why not use `stdin`/`stdout`/`stderr` files?
> 
> Here is `tty` on my system which return the terminal pts file
> 
> ```
> user@host ~$ tty
> /dev/pts/2
> ```
> 
> We could check for which PID is the owner/master/creator of `/dev/pts/2` to get its exe name.
> 
> And if the `/dev/stdin` resolve to `/dev/tty[0-9]` then we are in a TTY.

I didn't see any difference

```
~ 
❯ cat test.sh
#!/usr/bin/sh

lsof $(tty)

~ 
❯ ./test.sh
COMMAND   PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
fish     7542 carter    0u   CHR  136,2      0t0    5 /dev/pts/2
fish     7542 carter    1u   CHR  136,2      0t0    5 /dev/pts/2
fish     7542 carter    2u   CHR  136,2      0t0    5 /dev/pts/2
test.sh 16138 carter    0u   CHR  136,2      0t0    5 /dev/pts/2
test.sh 16138 carter    1u   CHR  136,2      0t0    5 /dev/pts/2
test.sh 16138 carter    2u   CHR  136,2      0t0    5 /dev/pts/2
lsof    16140 carter    0u   CHR  136,2      0t0    5 /dev/pts/2
lsof    16140 carter    1u   CHR  136,2      0t0    5 /dev/pts/2
lsof    16140 carter    2u   CHR  136,2      0t0    5 /dev/pts/2
```

**Comment by jumps-are-op** [comment]
After reading a lot of man pages, I found nothing about "Get PID of the process that is the owner of device /dev/pts/XX."
So walking up the process tree and searching for terminal process name should be the only solution.
BTW here is a [list of terminal emulators](https://en.wikipedia.org/wiki/List_of_terminal_emulators) that could help you.

**Comment by thingsiplay** [comment]
I have experimented a little bit further and don't know if that makes sense or not. With `ps` command one can get lot of information, including the commandline and its argument that was used to run the script. I tried following script 
```
pts=$(tty | grep -oE 'pts/.+')
psu=$(ps -u)
pid=$(echo "${psu}" | grep "${pts}" | grep " Sl*+ " | awk '{print $2}')
echo $pid
```
by creating different files with

_test_bin.sh_:
```
#!/bin/sh
...
```

_test_env.sh_:
```
#!/usr/bin/env sh
...
```

_test_bin.bash_:
```
#!/usr/bin/bash
...
```

_test_env.bash_:
```
#!/usr/bin/env sh
...
```

Remove the `awk` and other parts of the pipe, to see what information it delivers. One could probably use `echo "$0"` to grep the line with filename as argument. Maybe these investigations can be useful in finding a solution.
