### ISSUE TITLE
Linux: detect scaled resolution

### ISSUE THREAD

**Issue by CarterLi** [fastfetch-cli/fastfetch#414]
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/6134068/216295137-c70fc5e4-6857-476c-bf55-f81cc30f8691.png">

https://github.com/LinusDierheimer/fastfetch/blob/dev/src/detection/displayserver/linux/wayland.c#L69

The only source I can find is `~/.config/monitors.xml`. What do you think @LinusDierheimer

**Comment by LinusDierheimer** [comment]
On wayland probably using this protocol: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/143. I don't know a X11 way out of my head.

**Comment by CarterLi** [comment]
> But it only supports full numbers, e.g. 200%, 300% etc

It should be ok as there's no way that DE can set fractional scale without WM support

> I don't know a X11 way out of my head.

AFAIK X11 doesn't support scaling

**Comment by LinusDierheimer** [comment]
> It should be ok as there's no way that DE can set fractional scale without WM support

Since fractional scaling is starting to become a thing, we should use that as primary method, and the integer scale factor only as a fallback. My Wayland Compositor (KWin 5.26.90) for example already supports it.

> AFAIK X11 doesn't support scaling

I can scale a plasma x11 session, but it might be some kde specific solution.

**Comment by LinusDierheimer** [comment]
I have implemented it using the integer scale factor, but i would like to leave this open until support for fractional scaling is added.

**Comment by CarterLi** [comment]
Fixed

**Comment by CarterLi** [comment]
Ref: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2394

**Comment by CarterLi** [comment]
Did some work: https://github.com/LinusDierheimer/fastfetch/commit/498ae61afe3987f63b833d38ce679704ed7e7d86

I found it too hard for me. [Getting a fractional-scale instance requires a composer surface](https://github.com/LinusDierheimer/fastfetch/commit/498ae61afe3987f63b833d38ce679704ed7e7d86#diff-2bbc20c4a50da66295fe6a89767bca005b02e9e488578dd8932bf73fa1c0ddf6R238), which doesn't seem to fit fastfetch. Will you take over it? @LinusDierheimer 

PS: I must say that unable to use inline function from 3rd-party lib headers is annoy. Maybe this is a better solution to work around the issue: https://github.com/CarterLi/fastfetch/blob/config/src/common/json.c#L77

**Comment by LinusDierheimer** [comment]
> PS: I must say that unable to use inline function from 3rd-party lib headers is annoy. Maybe this is a better solution to work around the issue: https://github.com/CarterLi/fastfetch/blob/config/src/common/json.c#L77

I tried that, but its not really possible as far as i know. A lot of libwayland functions are variadic, and i don't know how to pass the arguments in that case. For example:
```c
struct wl_proxy* wl_proxy_marshal_constructor(struct wl_proxy *proxy, uint32_t opcode, const struct wl_interface *interface, ...)
{
    waylandLib->ffwl_proxy_marshal_constructor(proxy, opcode, interface, ???);
}
```

**Comment by CarterLi** [comment]
Found this: https://stackoverflow.com/a/61545790

**Comment by LinusDierheimer** [comment]
Besides even [gcc](https://gcc.gnu.org/onlinedocs/gcc-4.1.2/gcc/Constructing-Calls.html) saying those funcions are bad, [clang](https://lists.llvm.org/pipermail/llvm-dev/2013-October/066040.html) doesn't even support them. We would loose support for the second biggest compiler, that is standard on many platforms.

**Comment by CarterLi** [comment]
You are right. And I just found another builtin function [__builtin_va_arg_pack](https://gcc.gnu.org/onlinedocs/gcc-13.1.0/gcc/Constructing-Calls.html)

```c
FF_LIBRARY_SYMBOL(wl_proxy_marshal_flags);

extern inline __attribute__((__gnu_inline__)) __attribute__((__always_inline__))
struct wl_proxy *
wl_proxy_marshal_flags(struct wl_proxy *proxy,
    uint32_t opcode,
    const struct wl_interface *interface,
    uint32_t version,
    uint32_t flags,
    ...)
{
    return ffwl_proxy_marshal_flags(proxy, opcode, interface, version, flags, __builtin_va_arg_pack());
}
```

However it's not supported by clang too, sadly.

It's possible to implement it using `wl_proxy_marshal_array_flags`, but the implementation can be very verbose and it's not worth the effort.

**Comment by LinusDierheimer** [comment]
See https://github.com/fastfetch-cli/fastfetch/pull/564#issuecomment-1747003856
