### ISSUE TITLE
Ability to display a count of podman containers

### ISSUE THREAD

**Issue by dnkmmr69420** [fastfetch-cli/fastfetch#443]
# Current state:
Does not show anything about podman containers or docker containers.

# Wanted state:
Shows the count of total containers for both podman user, podman root, possibly docker as well and show the count of running containers for podman user, podman root, possibly docker as well.

# Why the change is sensible:
It is a good way to get info about the amount of containers there are as well as the ammount of running containers as well. This will also be the first fetch program that shows info about containers if this happens. It should be allowed to enable and disable in the config if possible as well.

**Comment by CarterLi** [comment]
Seems not many people care this feature. Containers are neither hardware related, nor preinstalled by systems. Therefore I don't think it fits fastfetch.

If you need it, you may detect it with command module yourself.
