### ISSUE TITLE
Module "Newline" and --raw and --raw-separator commands

### ISSUE THREAD

**Issue by jordantrizz** [fastfetch-cli/fastfetch#453]
# Current state:
There is no method I've found to have modules on the same line with a separator and introduce a new line.

# Wanted state:
❯ fastfetch --structure Title:OS:Newline:CPU:Newline:Shell:Kernel --raw --raw-separator "|"
```
username@host | OS: Ubuntu 20.04 x86_64
CPU: AMD Ryzen 7 3700X (16) @ 3.600022 GHz 
Shell: zsh 5.8 | Kernel: 5.10.16.3-microsoft-standard-WSL2
```

# Why the change is sensible:
More flexible formatting without of output.

**Comment by CarterLi** [comment]
You may use `--set` or `--set-keyless`

For example: https://github.com/LinusDierheimer/fastfetch/blob/dev/presets/examples/2#L9

**Comment by jordantrizz** [comment]
Thanks @CarterLi, but I couldn't figure out how to create the following.

```
Host: KVM (RHEL 7.6.0 PC (i440FX + PIIX, 1996)) | Kernel: 5.15.0-58-generic
Uptime: 91 days, 11 hours, 32 mins | Packages: 863 (dpkg), 3 (snap)
Shell: zsh 5.8.1 | Terminal: screen
CPU: Intel(R) Xeon(R) E5-2680 v2 (2) @ 2.799998 GHz | GPU: Cirrus Logic GD 5446
Memory: 430.67 MiB / 2.42 GiB (17%) | Disk (/): 15.49 GiB / 56.49 GiB (27%)
Locale: en_US.UTF-8 |
```

Am I missing something?

**Comment by CarterLi** [comment]
No, you can't do this. It's not supported.

**Comment by jordantrizz** [comment]
Thanks for the confirmation @CarterLi I've updated the issue, suggesting a --raw mode. Seems like it's a big endeavour.

**Comment by CarterLi** [comment]
No thoughts. Line merging is a long planned feature but definitely not easy to do.

**Comment by jordantrizz** [comment]
Thanks for the response @CarterLi

**Comment by jordantrizz** [comment]
@CarterLi what about --raw removing the formatting of the output?

**Comment by CarterLi** [comment]
What did you mean formatting? We have --pipe that removes colors.

**Comment by jordantrizz** [comment]
Sorry, I completely missed it, I grep'd versus RTFM. Thanks.

**Comment by CarterLi** [comment]
Closing in favor of https://github.com/fastfetch-cli/fastfetch/issues/482
