### ISSUE TITLE
2.0 release

### ISSUE THREAD

**Issue by LinusDierheimer** [fastfetch-cli/fastfetch#469]
This project has outgrown my personal hobby project, so i like to discuss a few options about what to do with the repository when we release 2.0:
* transfer to an organization
* keep everything as is under my account
* fork to an organization, archive this repository

I'd prefer option 1, but i don't know how package managers etc targeting 1.* versions would handle that.

**Comment by LinusDierheimer** [comment]
We should also think about a good name for the organization. Fastfetch is on the hand, but in the long term we might split out usefull parts as extra libraries etc, so maybe we need a common name.

**Comment by LinusDierheimer** [comment]
From the [GitHub docs](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository):
> All links to the previous repository location are automatically redirected to the new location. When you use git clone, git fetch, or git push on a transferred repository, these commands will redirect to the new repository location or URL.

I think we are fine transfering it.

**Comment by CarterLi** [comment]
What about libfastfetch, or shorter, libfetch?

**Comment by LinusDierheimer** [comment]
> What about libfastfetch, or shorter, libfetch?
> Or fastfetch-cli

Those all seem like the name of a single repository, not the name of the organization containing all of them

**Comment by CarterLi** [comment]
> Or fastfetch-cli

I actually took the idea from [Macchina-CLI](https://github.com/Macchina-CLI), which is also a neofetch like CLI tool.

```
Fastfetch-CLI ( the group name )
  |- fastfetch ( the CLI program exe file )
  |- libfastfetch ( the library behind exe. May be compiled into a so / dylib / dll in the future )

**Comment by LinusDierheimer** [comment]
I did go this way.
