### ISSUE TITLE
[RFC] Request for testing of JSON config

### ISSUE THREAD

**Issue by CarterLi** [fastfetch-cli/fastfetch#471]
There are no documentations yet ( [JSON schema](https://json-schema.org/) is planned ). Keys can mostly map to the traditional command flags. Here is an example ( when `config.jsonc` is found, `config.conf` will be ignored )

## My config file

```jsonc
// ~/.config/fastfetch/config.json
{
  "logo": { // https://github.com/fastfetch-cli/fastfetch/blob/71beb626c30c5755613d743d9349f7a95effbe6c/src/fastfetch.c#L900
    "type": "iterm",
    "source": "/home/carter/linux.png", // https://en.wikipedia.org/wiki/Linux#/media/File:Tux.svg
    "width": 30,
    "height": 14,
    "padding": {
      "top": 2,
      "left": 1,
      "right": 2
    }
  },
  "general": { // https://github.com/fastfetch-cli/fastfetch/blob/71beb626c30c5755613d743d9349f7a95effbe6c/src/fastfetch.c#L872
    "allowSlowOperations": true,
    "stat": true
  },
  "display": { // https://github.com/fastfetch-cli/fastfetch/blob/71beb626c30c5755613d743d9349f7a95effbe6c/src/fastfetch.c#L906
    "color": {
      "keys": "yellow"
    },
    "percentType": 9,
    "hideCursor": false
  },
  "modules": [
    "title",
    "separator",
    "os",
    "host",
    "kernel",
    "uptime",
    "processes",
    "packages",
    "shell",
    {
      "type": "display",
      "detectName": true
    },
    "brightness",
    "de",
    "wm",
    "wmtheme",
    "theme",
    "icons",
    "cursor",
    "terminal",
    "terminalfont",
    {
      "type": "cpu",
      "temp": true
    },
    {
      "type": "gpu",
      "forceVulkan": true
    },
    "memory",
    "swap",
    "disk",
    "media",
    "battery",
    {
      "type": "localip",
      "showIpv6": true
    },
    "cpuusage",
    "wifi",
    "locale",
    "vulkan",
    "opengl",
    "bluetooth",
    "sound",
    "datetime",
    "break",
    "colors"
  ]
}
```

## The result
![image](https://github.com/fastfetch-cli/fastfetch/assets/6134068/d74a6d39-4b28-46b3-8016-5b3c9e28bced)

**Comment by tdtooke** [comment]
Thanks.  I'll definitely give this a go when I get home.

**Comment by CarterLi** [comment]
> Mostly anything I ever used starting with --set-keyless no longer works.

Breaking change is the main reason we bump the major version of fastfetch. `--set-key` and `--set-keyless` were implemented as a hack, and will be replaced by the new `Custom` module.

> Would really like a guide on how to do other keys like host key, cpu key, etc.

Definitely yes. I just need more time.

**Comment by tdtooke** [comment]
I'm wanting to go full json so my question is for those keys would I want that to be within "display"?  Adding just under "color" something like "host-key" : "myhostkey"?

**Comment by CarterLi** [comment]
> I see where you set the color for all keys under display, was wondering if I can set custom colors for individual keys.

You can do it with

```jsonc
{
    "type": "host",
    "key": "\\e[34mhost" // note double `\`s are required
}
```

for now, but we may support it some day. Let me focus porting existing features.

> but couldn't figure out what the equivalent of --logo-color-1 and --logo-color-2 is.

```jsonc
{
    "logo": {
        "color": {
            "1": "white",
            "2": "cyan",
            // and whatever
        }
    }
}
```

You may add

```
"$schema": "https://raw.githubusercontent.com/fastfetch-cli/fastfetch/dev/src/data/json_schema.jsonc"
```

[at the beginning of the JSON config file and use vscode to get some suggestions when typing](https://code.visualstudio.com/docs/languages/json#_mapping-in-the-json)

> Also now some of my keys have an unwanted added colon.

Fixed in 184a6de1e9845e9310fd1ee3101cd668b06457d6

**Comment by CarterLi** [comment]
> Mostly anything I ever used starting with --set-keyless no longer works.

```jsonc
{
    "type": "custom",
    "format": "whatever you want"
}
```

**Comment by tdtooke** [comment]
Thanks you!!!  I actually did try that way to color a key just without the extra '\'.  I tried a variation of what you did for logo colors.  I really should have known but for some reason my brain was telling me there wouldn't be something named simply "1".  I'm beginning to suspect the colon I see after the key is hard coded in so I won't ask for that.

**Comment by tdtooke** [comment]
Just in case it would help anybody else wanting to go in the direction I tend to go theming wise I'll post my json.  Thanks to CarterLi for fixing my other post.  I guess the old bbcode tags I'm used to using don't always work.

```jsonc
// "$schema": "https://raw.githubusercontent.com/fastfetch-cli/fastfetch/dev/src/data/json_schema.jsonc"
{
  "logo": {
    "padding": {
      "top": 3,
      "left": 1
    },
    "color": {
      "1": "36",
      "2": "32"
    }
  },
  "general": {
    "allowSlowOperations": true
  },
  "display": {
    "color": {
      "title": "33"
    },
    "percentType": 9,
    "hideCursor": false,
    "separator": "   "
  },
  "modules": [
    "title",
    "separator",
    {
    "type": "host",
    "key": "\\e[36m PC"
    },
    {
    "type": "board",
    "key": "\\e[36m  ├"
    },
    {
    "type": "CPU",
    "key": "\\e[36m  ├"
    },
    {
    "type": "gpu",
    "key": "\\e[36m  ├﬙"
    },
    {
    "type": "display",
    "key": "\\e[36m  ├"
    },
    {
    "type": "memory",
    "key": "\\e[36m  ╰"
    },
    "break",
    {
    "type": "os",
    "key": "\\e[32m OS"
    },
    {
    "type": "kernel",
    "key": "\\e[32m  ├"
    },
    {
    "type": "shell",
    "key": "\\e[32m  ├"
    },
    {
    "type": "terminal",
    "key": "\\e[32m  ├"
    },
    {
    "type": "TerminalFont",
    "key": "\\e[32m  ├"
    },
    {
    "type": "Locale",
    "key": "\\e[32m  ├"
    },
    {
    "type": "Packages",
    "key": "\\e[32m  ╰"
    },
    "break",
    {
    "type": "DE",
    "key": "\\e[33m DE"
    },
    {
    "type": "WM",
    "key": "\\e[33m  ├"
    },
    {
    "type": "WMTheme",
    "key": "\\e[33m  ├"
    },
    {
    "type": "Theme",
    "key": "\\e[33m  ├"
    },
    {
    "type": "Icons",
    "key": "\\e[33m  ├"
    },
    {
    "type": "Font",
    "key": "\\e[33m  ├"
    },
    {
    "type": "Cursor",
    "key": "\\e[33m  ╰󰇀"
    },
    "break",
    {
    "type": "custom",
    "format": "   \\e[38m \\e[37m \\e[36m \\e[35m \\e[34m \\e[33m \\e[32m \\e[31m"
    }
  ]
}
```

And if you want to know what that will produce on konsole with the Mega-Konsole theme then:

https://i.postimg.cc/VkhB8zxb/fetch.png

**Comment by CarterLi** [comment]
[Added `keyColor` and `--<module>-key-color`](https://github.com/fastfetch-cli/fastfetch/commit/36a2fee9d5da84cef3fe9ad67bccc940b7e56116)

Usage:

```json
{
    "type": "Cursor",
    "keyColor": "cyan"
}
```

**Comment by tdtooke** [comment]
I would suggest you move your config into presets.  A lot of people will like that one.  I just might convert a lot of the old examples into the new format and make a pull request.  Also will there be a way to have a config file where you can choose your json theme?

**Comment by CarterLi** [comment]
What is a json theme?

**Comment by tdtooke** [comment]
The contents of config.jsonc are what I would call a theme. As is if I want to change appearance I need to rename a config I created as config.jsonc.  I was thinking of themes being stored in the presets directory and in a config file you might have something like "theme" : "mytheme"

**Comment by CarterLi** [comment]
You mean something like `--load-config`?

It's easy to support it for commandline / flag based config file. For a config file newly loaded, it just override everything set before.

However JSON config is structure based, there are trees, arrays, etc. It's not easy to do so.

**Comment by CarterLi** [comment]
I mean trees are mergeable, but arrays (eg `modules`) are not.

**Comment by tdtooke** [comment]
I see.  I hadn't really considered the difficulty of that idea.  Maybe a default config.jsonc that is installed.  Yours would be a good choice.  Then the preset directory converted to themename.jsonc files and an install script in there that you could run with ./install.sh --themename which would then copy that theme to where config.jsonc is and rename it to that.  I believe neofetch does something like that with it's themes.

**Comment by gabrielomana** [comment]
Wgen i run `fastfetch --load-config theme.jsonc` i get error. Sorry but i'm new to this

![image](https://github.com/fastfetch-cli/fastfetch/assets/36016056/3dd57269-9b22-48a1-b648-6cc2e18dfb16)

**Comment by CarterLi** [comment]
> Wgen i run `fastfetch --load-config theme.jsonc` i get error. Sorry but i'm new to this
> 
> ![image](https://user-images.githubusercontent.com/36016056/252993893-3dd57269-9b22-48a1-b648-6cc2e18dfb16.png)

Did you use the latest dev build? `fastfetch --version`?

**Comment by CarterLi** [comment]
Closing in favor of https://github.com/fastfetch-cli/fastfetch/wiki/Configuration
