### ISSUE TITLE
Fastfetch detects GNOME as a DE even tho only polkit-gnome is running

### ISSUE THREAD

**Issue by Alxhr0** [fastfetch-cli/fastfetch#480]
# General description of bug:

* What happened: Fastfetch detects GNOME as a DE when only polkit-gnome is running
* What should happen: Fastfetch shouldn't show GNOME
* Did it work in an older version: Yes
* Where did you get the binary: Installed from the chaotic-aur, same thing happens with the actual AUR package

- [ ] The issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)

# Often helpful information:
OS: Arch Linux
Installed package: fastfetch-git

Output of `fastfetch --version`:
```
fastfetch 1.11.3-224 (x86_64)
```

Output of `fastfetch --load-config devinfo-verbose --show-errors --multithreading false --disable-linewrap false`: Error: unknown option: --terminal-font-format

Output of `fastfetch --list-features`:
```
threads
libpci
vulkan
wayland
xcb-randr
xcb
xrandr
x11
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
egl
glx
osmesa
opencl
libpulse
libnm
```

**Comment by CarterLi** [comment]
Seems relate to https://github.com/fastfetch-cli/fastfetch/commit/bc7d84fea2053883f734c5cc40a50b176cd67fa1
