### ISSUE TITLE
Misidentifies Desktop Environment

### ISSUE THREAD

**Issue by tdtooke** [fastfetch-cli/fastfetch#481]
I have both KDE Plasma and Gnome installed.  I'm currently running Plasma but the latest fastfetch identifies me as Gnome.  I reverted back to rev cff95e66be47563f34db1f482e02e91ec014119d.  I don't know but I suspect the commit at 48b01c96652754125f6cb1d0a3f61244cd06ec91 is what did it.  I'm at work now but I'll test that theory when I get home.

**Comment by osalbahr** [comment]
I recommend using `git bisect` to help find (or confirm) the first commit that introduced the issue.

**Comment by CarterLi** [comment]
Seems that @LinusDierheimer is busy at study. I am trying to help with this issue. Please test

**Comment by tdtooke** [comment]
It fixes it on my end.
