### ISSUE TITLE
Utilities have exception under Windows Server 2019/2022

### ISSUE THREAD

**Issue by Zeroes1** [fastfetch-cli/fastfetch#484]
# General description of bug:
both fastfetch.exe and flashfetch.exe have exception c0000005 under Windows Server 2019/2022

* What happened:
* run
fastfetch.exe
process show info
```
                                        s.dindikov@sapsrv1
/////////////////  /////////////////    -------------------
/////////////////  /////////////////    OS: Windows Server 2022 (Datacenter) x86_64
/////////////////  /////////////////    Host: VMware7,1
/////////////////  /////////////////    Kernel: 10.0.20348.1787 (21H2)
/////////////////  /////////////////    Uptime: 15 days, 18 hours, 49 mins
/////////////////  /////////////////    Shell: Far
/////////////////  /////////////////    Display: 1676x936 @ 32Hz
/////////////////  /////////////////    DE: Fluent
                                        WM: Desktop Window Manager
/////////////////  /////////////////    WM Theme: Aero - #0078D7 (System: Dark, Apps: Light)
/////////////////  /////////////////    Font: Segoe UI (12pt) [Caption / Menu / Message / Status]
/////////////////  /////////////////    Cursor: По умолчанию (32px)
/////////////////  /////////////////    Terminal: Console Window Host 10.0.20348.1787
/////////////////  /////////////////    Terminal Font: Consolas (20pt)
/////////////////  /////////////////    CPU: Intel(R) Xeon(R) E5-2660 v3 (2) @ 2,6 GHz
```
after proccess is ended (but no exit to shell) need press ctrl-c

run 
flashfetch.exe
and nothing....
need press ctrl-c
to show info
after this auto exit to console

* What should happen:
* normal work, show info and exit proccess
* 
* 
* Where did you get the binary: 
 Github Release
 
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)?
YES

# Often helpful information:
trouble 100% reproduced

Output of `fastfetch --version`:
```
fastfetch 1.11.3 (x86_64)
```

**Comment by Zeroes1** [comment]
[bug.zip](https://github.com/fastfetch-cli/fastfetch/files/11916232/bug.zip)

**Comment by CarterLi** [comment]
Does registry path `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Video\` exist? If yes, please paste the screenshot of `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Video\{*}\0000` here. Like this

![image](https://github.com/fastfetch-cli/fastfetch/assets/6134068/e86ad473-bc83-44c9-b595-280610c8bcef)

**Comment by Zeroes1** [comment]
![image](https://github.com/fastfetch-cli/fastfetch/assets/11919060/99243ac8-63aa-4446-a109-6b42cc541ef8)

**Comment by Zeroes1** [comment]
![image](https://github.com/fastfetch-cli/fastfetch/assets/11919060/a8a0291a-f89e-49f6-846b-b6628a08b9d4)

**Comment by Zeroes1** [comment]
both 2019 and 2022 servers are virtual based VMware vSphere

**Comment by CarterLi** [comment]
> ![image](https://user-images.githubusercontent.com/11919060/250191464-a8a0291a-f89e-49f6-846b-b6628a08b9d4.png)

I don't see much difference from mine

I can't do much without getting a stack trace. I have added some debug log in the latest dev build. Please try it with `fastfetch -s gpu --pipe`

**Comment by Zeroes1** [comment]
1) run fastfetch.exe or flashfetch.exe from (CMake (Windows): remove an unused dependency #1346) build crashed under 2019/2022

2) now run fastfetch.exe or flashfetch.exe without any options  from (GPU (Windows): add debug logs for #484 #1348) build  work fine! not crashed under 2019/2022

3)
D:\install\dindikov\test>fastfetch -s gpu --pipe
ffPrintGPU start
ffDetectGPU start
ffDetectGPUImpl: start
ffDetectGPUImpl EnumDisplayDevicesW
ffDetectGPUImpl deviceKeyLength 0
ffDetectGPUImpl EnumDisplayDevicesW
ffDetectGPUImpl deviceKeyLength 0
ffDetectGPUImpl EnumDisplayDevicesW
ffDetectGPUImpl deviceKeyLength 0
ffDetectGPUImpl EnumDisplayDevicesW
ffDetectGPUImpl deviceKeyLength 0
ffDetectGPUImpl EnumDisplayDevicesW
ffDetectGPUImpl deviceKeyLength 0
ffDetectGPUImpl EnumDisplayDevicesW
ffDetectGPUImpl deviceKeyLength 0
ffDetectGPUImpl EnumDisplayDevicesW
ffDetectGPUImpl deviceKeyLength 0
ffDetectGPUImpl EnumDisplayDevicesW
ffDetectGPUImpl deviceKeyLength 0
ffDetectGPUImpl EnumDisplayDevicesW
ffDetectGPUImpl deviceKeyLength 0
ffDetectGPUImpl EnumDisplayDevicesW
ffDetectGPUImpl deviceKeyLength 0
ffDetectGPUImpl EnumDisplayDevicesW
ffDetectGPUImpl deviceKeyLength 0
ffDetectGPUImpl EnumDisplayDevicesW
ffDetectGPUImpl deviceKeyLength 0
ffDetectGPUImpl EnumDisplayDevicesW
ffDetectGPUImpl deviceKeyLength 0
ffDetectGPUImpl EnumDisplayDevicesW
ffDetectGPUImpl deviceKeyLength 0
ffDetectGPUImpl EnumDisplayDevicesW
ffDetectGPUImpl deviceKeyLength 0
ffDetectGPUImpl EnumDisplayDevicesW
ffDetectGPUImpl deviceKeyLength 0
ffDetectGPUImpl end
ffDetectGPU end 1
ffPrintGPU 1
ffPrintGPU 2
ffPrintGPU 3
ffPrintGPU 4

**Comment by CarterLi** [comment]
> ffDetectGPUImpl deviceKeyLength 0

That's not expected. Anyway, I have pushed a work around for this. Please test the latest dev build

**Comment by Zeroes1** [comment]
Under 2019/2022 work fine, thanks!
May be to release 1.14?
