### ISSUE TITLE
No logo when starting via .zshrc

### ISSUE THREAD

**Issue by sepperlot** [fastfetch-cli/fastfetch#485]
# General description of bug:

* What happened: starting fastfetch in `.zshrc` produces output without OS icon and colors i.e. same if I were to use `--pipe true`
running `fastfetch` once the terminal is running it shows properly
* What should happen: it should print the logo and colors
* Did it work in an older version:  yes worked on 1.11.3
* Where did you get the binary:  AUR, updated via yay
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? not tested

# Often helpful information:

Output of `fastfetch --version`:
```
$ fastfetch --version         
fastfetch 1.12.0 (x86_64)
```
shell is zsh
```
$ zsh --version
zsh 5.9 (x86_64-pc-linux-gnu)
```
terminal terminator or xfce4-terminal
```
$ terminator -v     
terminator 2.1.3

$ xfce4-terminal --version
xfce4-terminal 1.0.4 (Xfce 4.18)
```
Currently fixed by adding `fastfetch --pipe false` to my `.zshrc`

**Comment by CarterLi** [comment]
I can't reproduce with both konsole and terminator

![image](https://github.com/fastfetch-cli/fastfetch/assets/6134068/c99e304e-1f5b-46ae-9280-bf991b9c515d)

**Comment by CarterLi** [comment]
We are using [isatty](https://github.com/fastfetch-cli/fastfetch/blob/master/src/common/init.c#L63) to detect if stdout is a tty, which should not be problematic. Can you backup your `.zshrc` and reproduce the issue with only `fastfetch` in the file?

**Comment by sepperlot** [comment]
Used a blank `.zshrc` and it worked with just `fastfetch`
I'm using [Powerlevel10k](https://github.com/romkatv/powerlevel10k) and narrowed it down to the instant prompt feature
```zsh
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
```
When I comment above lines it works.

**Comment by CarterLi** [comment]
Does moving `fastfetch` before `p10k` work?

**Comment by sepperlot** [comment]
It does work if I move it before the instant prompt call i.e. at the very beginning of my `.zshrc`
