### ISSUE TITLE
Detect number of pkgtool (Slackware) packages

### ISSUE THREAD

**Issue by 1-1sam** [fastfetch-cli/fastfetch#486]
# Current state:
Fastfetch does not detect the number of pkgtool packages installed.
# Wanted state:
Fastfetch detects and displays the number of pkgtool packages installed.
# Why the change is sensible:
Would provide more accurate system information for Slackware systems. pkgtool packages are also detected in many other *fetch programs.

**Comment by CarterLi** [comment]
@1-1sam Please use the newest CI build to test it

**Comment by 1-1sam** [comment]
pkgtool packages are still not being displayed. However, flatpaks are being displayed properly.

**Comment by CarterLi** [comment]
Please paste a screenshot of `ls -l /var/log/packages`

**Comment by 1-1sam** [comment]
![Screenshot_2023-07-03_10-57-32](https://github.com/fastfetch-cli/fastfetch/assets/128822641/8111a6aa-1e41-4f35-8c82-b6f38c6b6f87)

**Comment by 1-1sam** [comment]
/var/log/packages is a symlink to a directory (/var/lib/pkgtool/packages).

**Comment by CarterLi** [comment]
then `ls -l /var/lib/pkgtool/packages`

**Comment by 1-1sam** [comment]
![Screenshot_2023-07-03_11-08-03](https://github.com/fastfetch-cli/fastfetch/assets/128822641/406418ab-5ed1-4fae-b78f-bee07fb708ef)
I can post the entire text output if you'd like me to.

**Comment by CarterLi** [comment]
Are they files or directories?

**Comment by 1-1sam** [comment]
They are all files. Also it's /var/lib/pkgtools/packages, not /var/lib/pkgtool/packages, sorry about that.

**Comment by CarterLi** [comment]
I wonder how a file can be a package. But whatever

**Comment by CarterLi** [comment]
Please test it again

**Comment by 1-1sam** [comment]
It works now.
