### ISSUE TITLE
need fix: readme.md

### ISSUE THREAD

**Issue by Zeroes1** [fastfetch-cli/fastfetch#487]
* What happened:
* need fix: readme.md
* Terminal fonts -> Terminal 

![image](https://github.com/fastfetch-cli/fastfetch/assets/11919060/c57c3135-5ee2-49da-a528-f7eafe51f853)

**Comment by CarterLi** [comment]
That's expected, which means we support detecting current fonts of those terminals.

**Comment by Zeroes1** [comment]
Hmm, strange situation:
no information about ALL supported terminals, but exist info about support detecting current fonts of those terminals?

**Comment by CarterLi** [comment]
All terminals should just work, thus no information.
