### ISSUE TITLE
one case wrong info about terminal/shell

### ISSUE THREAD

**Issue by Zeroes1** [fastfetch-cli/fastfetch#488]
may be can fix one case wrong info about terminal/shell ?
# General description of bug:

I make some test flashfetch.exe 1.12.1.0 under win 10:

far under cmd
Terminal: Console Window Host 10.0.19041.3031
Shell: Far

Terminal: WezTerm 20230622-212134-f21dcb96
Shell: Command Prompt 10.0.19041.746

Terminal: Windows Terminal 1.18.2305.26002
Shell: Far

under conemu
Terminal: ConEmu 221218
Shell: PowerShell 7.3.5

Terminal: ConEmu 221218
Shell: Windows PowerShell 5.1.19041.3031

Terminal: ConEmu 221218
Shell: Command Prompt 10.0.19041.746

![image](https://github.com/fastfetch-cli/fastfetch/assets/11919060/512984e3-17a8-4b58-aa3d-9821ae592c2d)
but last test is WRONG? (under ConEmu I run FAR):
Terminal: Far 3.0.6171.0
Shell: ConEmuC64

need show like:
Terminal: ConEmu 221218
Shell: Far 3.0.6171.0

reproduced 100%

**Comment by CarterLi** [comment]
<img width="610" alt="image" src="https://github.com/fastfetch-cli/fastfetch/assets/6134068/2271b4c3-40dc-4bc4-99e6-bfacca555d81">

For some reason, `Far` calls `ConEmuC64` to run `fastfetch`. Will fix it.

**Comment by CarterLi** [comment]
Please test it with the newest CI build

**Comment by Zeroes1** [comment]
now, good!
thnx! :)
