### ISSUE TITLE
DE report with Solus Budgie reports as "Gnome" instead of Budgie

### ISSUE THREAD

**Issue by carlberger** [fastfetch-cli/fastfetch#489]
# General description of bug:

* What happened:

fastfetch reports DE as "Gnome" instead of "Budgie" with Solus Budgie 4.4 ( not yet released at this moment ) 

* What should happen:

DE should be "Budgie 10.7.2"

* Did it work in an older version: 

idk

* Where did you get the binary: 

Built from source myself

* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)?

yes

# Often helpful information:

I patched the source with 

```
diff --git a/src/detection/displayserver/linux/wmde.c b/src/detection/displayserver/linux/wmde.c
index 3022f873..abdff51a 100644
--- a/src/detection/displayserver/linux/wmde.c
+++ b/src/detection/displayserver/linux/wmde.c
@@ -286,6 +286,8 @@ static void applyPrettyNameIfDE(FFDisplayServerResult* result, const char* name)
         return;
     else if(strcasestr(name, "plasma") != NULL || strcasecmp(name, "KDE") == 0)
         getKDE(result);
+    else if(strcasestr(name, "budgie:gnome") != NULL)
+        getBudgie(result);
     else if(
         strcasecmp(name, "polkit-gnome") != 0 &&
         strcasecmp(name, "gnome-keyring") != 0 &&
```

and this fixed it.

**Comment by CarterLi** [comment]
Please test if it works for you
