### ISSUE TITLE
Not working with lolcat.

### ISSUE THREAD

**Issue by pragit-raj-sharma** [fastfetch-cli/fastfetch#502]
Fastfetch is not working with lolcat. I just updated fastfetch from version 1.11.0 to 1.12.2.  

Command `(fastfetch|lolcat)` should work fine and produce output like this
![image](https://github.com/fastfetch-cli/fastfetch/assets/65211497/83056f7e-1a1f-4489-b006-c8215246d9d4)

But, it is not showing any logo after update to version 1.12.2.
![image](https://github.com/fastfetch-cli/fastfetch/assets/65211497/11eee561-51a7-4071-897f-d50105400edb)

**Comment by CarterLi** [comment]
In 1.12, we enable `--pipe` automatically when we detect fastfetch is being piped. Specify `--pipe false` if you don't want the behavior.

**Comment by pragit-raj-sharma** [comment]
Thanks.
