### ISSUE TITLE
deepin v23 will support fastfetch

### ISSUE THREAD

**Issue by xzl01** [fastfetch-cli/fastfetch#506]
see： https://github.com/linuxdeepin/developer-center/issues/4728 

Because the neofetch maintainer has not been updated for a long time, we decided to replace neofetch with fastfetch

**Comment by CarterLi** [comment]
可以可以

**Comment by CarterLi** [comment]
有什么我可以帮忙的？

**Comment by xzl01** [comment]
https://github.com/deepin-community/fastfetch/pull/1 可以审阅下此pr 同时我们会试图向debian提交一份维护

**Comment by CarterLi** [comment]
有问题开新issue吧
