### ISSUE TITLE
NixOS terminal detection

### ISSUE THREAD

**Issue by ErrorNoInternet** [fastfetch-cli/fastfetch#510]
# General description of bug:

* What happened: I am using NixOS with the kitty terminal emulator. The TerminalFont module isn't working correctly on NixOS because the terminal is `.kitty-wrapped` instead of `kitty`. Running the command:
```
fastfetch --structure terminalfont --terminal-font-format "hello world" --show-errors
```
displays
```
Terminal Font: Unknown terminal: .kitty-wrapped
```

* What should happen: fastfetch should acknowledge that `.kitty-wrapped` is the same as `kitty`, which would result in terminal font detection working correctly.
+ * What should maybe also happen: Specifying `--terminal-font-format` should override the errors and display what I want? Or maybe manually setting `--terminal-format` to `kitty` would override the terminal and make font detection work?
* Where did you get the binary: nixpkgs unstable (23.11)
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/): yes

# Often helpful information:

Output of `fastfetch --version`: `fastfetch 1.12.2 (x86_64)`

**Comment by CarterLi** [comment]
Please test the dev build

**Comment by CarterLi** [comment]
> * What should maybe also happen: Specifying `--terminal-font-format` should override the errors and display what I want? Or maybe manually setting `--terminal-format` to `kitty` would override the terminal and make font detection work?

That's not how `--*-format` works. If you want to display some custom text, use `--set` ( or `Custom` module if you use the unreleased dev build ) instead

**Comment by ErrorNoInternet** [comment]
> > * What should maybe also happen: Specifying `--terminal-font-format` should override the errors and display what I want? Or maybe manually setting `--terminal-format` to `kitty` would override the terminal and make font detection work?
> 
> That's not how `--*-format` works. If you want to display some custom text, use `--set` ( or `Custom` module if you use the unreleased dev build ) instead

Ah I see. Thanks for letting me know.

As for the dev build, it doesn't seem to work.

**Comment by CarterLi** [comment]
My bad. Please try again

**Comment by ErrorNoInternet** [comment]
Almost there, now the Terminal field shows "kitty" instead of ".kitty-wrapped", but Terminal Font still thinks it's ".kitty-wrapped" and errors out.

**Comment by ErrorNoInternet** [comment]
Works now! Thanks :)
