### ISSUE TITLE
Feature Request: Allow users to pick the location for the Weather Module 

### ISSUE THREAD

**Issue by anoraktrend** [fastfetch-cli/fastfetch#511]
# Current state:
The current Weather module relies on potentially inaccurate ip data in order pick the location.

# Wanted state:
to optionally let the user pick the their location via a config option

# Why the change is sensible:
To provide more accurate weather data for the user

**Comment by CarterLi** [comment]
It has been supported in the dev branch.

https://github.com/fastfetch-cli/fastfetch/blob/dev/src/data/help.txt#L144

**Comment by anoraktrend** [comment]
woo thanks

**Comment by exstntlmsnthrp** [comment]
I have been searching for hours, trying to figure out the correct URI encoding to use for the ```--weather-location:``` and I cannot figure it out. I've tried using ```geo:lat,long```, but that just fails. Can anyone help and or point me in a useful direction? Cheers.
