### ISSUE TITLE
Fastfetch doesn't load custom ASCII logo, segmentation fault.

### ISSUE THREAD

**Issue by EliasLucky** [fastfetch-cli/fastfetch#518]
Thank you for fixing previous issue that I've reported to you and answering me. Now everything works fine. I can finally load custom config file without config.conf/config.jsonc file being loaded. But now there is another issue.

# General description of bug:

I've noticed that, after new update with the fix of the issue that I've reported to you, now I can't load any my custom ascii logo's by passing argument `--logo <path-to-logo>`, I am getting errors, but with only one difference in error message, between when I am trying to load custom ascii logo by passing argument `--logo <path-to-logo>` and though config file.

What errors I am getting:

Error, If I try to load custom ascii logo for fastfetch **from config file** by passing argument `--load-config "$HOME/.config/fastfetch/small.conf"` with `--logo "$HOME/aperture-small.txt"` inside config file:

`[1]    365646 segmentation fault (core dumped)  fastfetch --load-config /home/user/.config/fastfetch/small.conf`

Error, If I try to load custom ascii logo for fastfetch **without config file**, by just passing argument `--logo "$HOME/aperture-small.txt"` without config file:

`[1]    367970 segmentation fault (core dumped)  fastfetch --logo $HOME/aperture-small.txt`

But If I try to load default ascii logo's such as "arch", "arch_small", "ubuntu", and etc. everything is fine, so the problem is only when user tries to load custom config by passing argument `--logo <path-to-logo>` in and not in config file.

* What happened: Fastfetch doesn't load custom ascii-logo by passing argument `--logo <path-to-logo>` in and without config file.
* What should happen: Fastfetch should load custom ascii-logo by passing argument `--logo <path-to-logo>` without any errors.
* Did it work in an older version: yes, it worked when I last used fastfetch 1.12.2-457 (x86_64)
* Where did you get the binary: Github dev branch
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? yes

# Often helpful information:

Output of `fastfetch --version`:
```
fastfetch 1.12.2-490 (x86_64)
```

The content of the configuration file you use (if any)
(small.conf)
```
--logo $HOME/aperture-small.txt
--logo-color-1 blue

--color blue
--separator ": "

--set-keyless Start=┌───────────────────────────────┐
--set-keyless End=└───────────────────────────────┘

--os-key "|  OS"
--host-key "|  Host"
--kernel-key "|  Kernel"
--uptime-key "|  Uptime"
--packages-key "|  Packages"
--shell-key "|  Shell"
--wm-key "|  WM"

--structure Title:Start:OS:Host:Kernel:Uptime:Packages:Shell:WM:End
```

Output of `env NO_CONFIG=1 fastfetch --load-config all --show-errors --stat --multithreading false --disable-linewrap false --hide-cursor false`: It just works, no issues.

Output of `fastfetch --list-features`:
```
threads
libpci
vulkan
wayland
xcb-randr
xcb
xrandr
x11
gio
dconf
dbus
zlib
xfconf
sqlite3
egl
glx
osmesa
libpulse
libnm
```

## If fastfatch crashed

Stracktrace:

```
$ gdb /usr/local/bin/fastfetch
$ run --logo $HOME/aperture-small.txt
Starting program: /usr/local/bin/fastfetch --logo $HOME/aperture-small.txt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff79396c0 (LWP 840108)]
[New Thread 0x7ffff71386c0 (LWP 840109)]
[New Thread 0x7ffff691a6c0 (LWP 840110)]
[New Thread 0x7ffff61196c0 (LWP 840111)]
[New Thread 0x7ffff59186c0 (LWP 840112)]

Thread 1 "fastfetch" received signal SIGSEGV, Segmentation fault.
0x00007ffff7e4980b in ?? () from /usr/lib/libc.so.6
$ bt
#0  0x00007ffff7e4980b in ?? () from /usr/lib/libc.so.6
#1  0x0000555555574073 in ffStrbufIgnCaseCompS (comp=0xc6bf225ffffff <error: Cannot access memory at address 0xc6bf225ffffff>,
    strbuf=<optimized out>) at /home/user/Downloads/git/fastfetch/src/util/FFstrbuf.h:320
#2  ffStrbufIgnCaseEqualS (comp=0xc6bf225ffffff <error: Cannot access memory at address 0xc6bf225ffffff>, strbuf=<optimized out>)
    at /home/user/Downloads/git/fastfetch/src/util/FFstrbuf.h:325
#3  logoHasName (small=<optimized out>, name=<optimized out>, logo=<optimized out>)
    at /home/user/Downloads/git/fastfetch/src/logo/logo.c:205
#4  logoGetBuiltin (name=<optimized out>, size=size@entry=FF_LOGO_SIZE_UNKNOWN) at /home/user/Downloads/git/fastfetch/src/logo/logo.c:232
#5  0x0000555555574778 in logoPrintBuiltinIfExists (size=size@entry=FF_LOGO_SIZE_UNKNOWN, name=<optimized out>)
    at /home/user/Downloads/git/fastfetch/src/logo/logo.c:302
#6  0x0000555555574967 in ffLogoPrint () at /home/user/Downloads/git/fastfetch/src/logo/logo.c:466
#7  0x000055555556aa9f in ffStart () at /home/user/Downloads/git/fastfetch/src/common/init.c:257
#8  0x00005555555649ab in main (argc=3, argv=0x7fffffffe178) at /home/user/Downloads/git/fastfetch/src/fastfetch.c:1399
```

`strace fastfetch --logo $HOME/aperture-small.txt` output:

I've posted it on pastebin because output log is too big. (expires after 1 year)
https://pastebin.com/Xh79LiFd

* Does `sleep 1` before running `fastfetch` work? no

PS: Hope the information that I've provided will be helpful to solve this issue! Ask me if you need anything else.

**Comment by CarterLi** [comment]
> I've posted it on pastebin because output log is too big. (expires after 1 year)
> https://pastebin.com/Xh79LiFd

This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff.

**Comment by CarterLi** [comment]
Supported. See <https://github.com/fastfetch-cli/fastfetch/wiki/Logo-options#general> for detail

**Comment by CarterLi** [comment]
Great! Thanks for testing.
