### ISSUE TITLE
[Feature Request] CMake option to use system-provided yyjson

### ISSUE THREAD

**Issue by FedericoSchonborn** [fastfetch-cli/fastfetch#525]
# Current state:

`yyjson` is downloaded during the build step (and vendored as of cd4a5122918aeb3f3dd34c4463d3f6f19a882851), and there's no option to use the system-provided version of the library. Gentoo has [a patch](https://gitweb.gentoo.org/repo/gentoo.git/tree/app-misc/fastfetch/files/fastfetch-2.0.0-dont-fetch-yyjson.patch?id=f6d44ba7a68e831f498e0aa166fc80aed78a41b8) that removes the download step to use the system-provided `yyjson` instead.

# Wanted state:

An option to use the system-provided `yyjson` should be available in CMake or the download/vendoring should be disabled if a system-provided version of `yyjson` is found.

# Why the change is sensible:

Many Linux distributions would benefit from this feature, as they usually want to avoid enabling networking during builds and vendored libraries.

**Comment by CarterLi** [comment]
Hello.

Fastfetch v2.0.1 has been released, with `-DENABLE_SYSTEM_YYJSON` support. Please check it.

Also please check if the terminal detection is correctly fixed.
