### ISSUE TITLE
Wrong formatting for percentages

### ISSUE THREAD

**Issue by IanManske** [fastfetch-cli/fastfetch#535]
# General description of bug:
Certain percentages/`double`s are being formatted with `FF_FORMAT_ARG_TYPE_UINT8` which does not format the value properly. 

* What happened:
    `--memory-format {3}`, `--swap-format {3}`, and `--disk-format {3}` (and maybe more?) are not being formatted as `double`s/percentages. Using the example config below, fastfetch may report over 100% usage :fearful:
    ```
    Memory: 5.80 GiB / 15.41 GiB (209%)
    Disk (/): 558.16 GiB / 898.83 GiB (187%)
    ```
* What should happen:
    The correct percentages are shown when using the default config even though the format is (roughly) the same:
    ```
    Memory: 5.79 GiB / 15.41 GiB (38%)
    Disk (/): 558.16 GiB / 898.83 GiB (62%) - ext4
    ```
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Yes

# Often helpful information:

The content of the configuration file you use (if any)
```
--memory-format {1} / {2} ({3}%)
--swap-format {1} / {2} ({3}%)
--disk-format {1} / {2} ({3}%)
```

**Comment by CarterLi** [comment]
Should be fix in dev branch, and `--*-format` will honor `--percent-type 9`. Please test it.

**Comment by IanManske** [comment]
Looks good, thanks!
