### ISSUE TITLE
Disk module won't show the root path `/`

### ISSUE THREAD

**Issue by CarterLi** [fastfetch-cli/fastfetch#541]
Ref: https://github.com/fastfetch-cli/fastfetch/issues/537#issuecomment-1692687687

```
/dev/mapper/luks-ecdf3111-d8f8-4148-a323-53da903d831f on /sysroot type btrfs (ro,relatime,seclabel,compress=zstd:1,ssd,space_cache=v2,subvolid=258,subvol=/root)
/dev/mapper/luks-ecdf3111-d8f8-4148-a323-53da903d831f on / type btrfs (rw,relatime,seclabel,compress=zstd:1,ssd,space_cache=v2,subvolid=258,subvol=/root)
```

`/` comes after `/sysroot`, so that `/` is detected as a subvolume of `/sysroot`. This is unexpected.

**Comment by CarterLi** [comment]
CC @osalbahr @LinusDierheimer

**Comment by LinusDierheimer** [comment]
Is it possible, that this is an installation on a partition-less disk, for example btrfs on `/dev/sda` instead of `/dev/sda1`?

**Comment by CarterLi** [comment]
Wow! @LinusDierheimer you came back!

**Comment by CarterLi** [comment]
I find [`/proc/self/mountinfo`](https://www.[kernel.org/doc/Documentation/filesystems/proc.txt](https://www.kernel.org/doc/Documentation/filesystems/proc.txt))

```
3.5	/proc/<pid>/mountinfo - Information about mounts
--------------------------------------------------------

This file contains lines of the form:

36 35 98:0 /mnt1 /mnt2 rw,noatime master:1 - ext3 /dev/root rw,errors=continue
(1)(2)(3)   (4)   (5)      (6)      (7)   (8) (9)   (10)         (11)

(1) mount ID:  unique identifier of the mount (may be reused after umount)
(2) parent ID:  ID of parent (or of self for the top of the mount tree)
(3) major:minor:  value of st_dev for files on filesystem
(4) root:  root of the mount within the filesystem
(5) mount point:  mount point relative to the process's root
(6) mount options:  per mount options
(7) optional fields:  zero or more fields of the form "tag[:value]"
(8) separator:  marks the end of the optional fields
(9) filesystem type:  name of filesystem of the form "type[.subtype]"
(10) mount source:  filesystem specific information or "none"
(11) super options:  per super block options
```

There is `mount ID` and `parent ID`. I checked fedora (in VM) and it shows

```
77 1 0:38 /root / rw,relatime shared:1 - btrfs /dev/sda3 rw,seclabel,compress=zstd:1,ssd,discard=async,space_cache=v2,subvolid=257,subvol=/root
48 77 0:38 /home /home rw,relatime shared:51 - btrfs /dev/sda3 rw,seclabel,compress=zstd:1,ssd,discard=async,space_cache=v2,subvolid=256,subvol=/home
```

So that `/home` is a child of `/`. Don't know if it's useful

**Comment by CarterLi** [comment]
@osalbahr Can you paste the content of `/proc/self/mountinfo` here?

**Comment by CarterLi** [comment]
> Is it possible, that this is an installation on a partition-less disk, for example btrfs on `/dev/sda` instead of `/dev/sda1`?

Seems he is using LVM

**Comment by osalbahr** [comment]
> @osalbahr Can you paste the content of `/proc/self/mountinfo` here?

Sure.

```console
$ cat /proc/self/mountinfo
22 72 0:21 / /proc rw,nosuid,nodev,noexec,relatime shared:19 - proc proc rw
23 72 0:22 / /sys rw,nosuid,nodev,noexec,relatime shared:6 - sysfs sysfs rw,seclabel
24 72 0:5 / /dev rw,nosuid shared:14 - devtmpfs devtmpfs rw,seclabel,size=4096k,nr_inodes=986111,mode=755,inode64
25 23 0:6 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime shared:7 - securityfs securityfs rw
26 24 0:23 / /dev/shm rw,nosuid,nodev shared:15 - tmpfs tmpfs rw,seclabel,inode64
27 24 0:24 / /dev/pts rw,nosuid,noexec,relatime shared:16 - devpts devpts rw,seclabel,gid=5,mode=620,ptmxmode=000
28 72 0:25 / /run rw,nosuid,nodev shared:17 - tmpfs tmpfs rw,seclabel,size=1596012k,nr_inodes=819200,mode=755,inode64
29 23 0:26 / /sys/fs/cgroup rw,nosuid,nodev,noexec,relatime shared:8 - cgroup2 cgroup2 rw,seclabel,nsdelegate,memory_recursiveprot
30 23 0:27 / /sys/fs/pstore rw,nosuid,nodev,noexec,relatime shared:9 - pstore pstore rw,seclabel
31 23 0:28 / /sys/firmware/efi/efivars rw,nosuid,nodev,noexec,relatime shared:10 - efivarfs efivarfs rw
32 23 0:29 / /sys/fs/bpf rw,nosuid,nodev,noexec,relatime shared:11 - bpf bpf rw,mode=700
46 28 0:30 / /run/credentials/systemd-vconsole-setup.service ro,nosuid,nodev,noexec,relatime shared:18 - ramfs ramfs rw,seclabel,mode=700
67 23 0:34 / /sys/kernel/config rw,nosuid,nodev,noexec,relatime shared:12 - configfs configfs rw
73 72 0:35 /root /sysroot ro,relatime - btrfs /dev/mapper/luks-ecdf3111-d8f8-4148-a323-53da903d831f rw,seclabel,compress=zstd:1,ssd,space_cache=v2,subvolid=258,subvol=/root
72 1 0:35 /root/ostree/deploy/fedora/deploy/94c063e370f6891eae991480e040906a3430fa1ec8ee3deb384a14be3719988d.0 / rw,relatime shared:1 - btrfs /dev/mapper/luks-ecdf3111-d8f8-4148-a323-53da903d831f rw,seclabel,compress=zstd:1,ssd,space_cache=v2,subvolid=258,subvol=/root
76 72 0:35 /root/ostree/deploy/fedora/deploy/94c063e370f6891eae991480e040906a3430fa1ec8ee3deb384a14be3719988d.0/etc /etc rw,relatime shared:2 - btrfs /dev/mapper/luks-ecdf3111-d8f8-4148-a323-53da903d831f rw,seclabel,compress=zstd:1,ssd,space_cache=v2,subvolid=258,subvol=/root
77 72 0:35 /root/ostree/deploy/fedora/deploy/94c063e370f6891eae991480e040906a3430fa1ec8ee3deb384a14be3719988d.0/usr /usr ro,relatime shared:3 - btrfs /dev/mapper/luks-ecdf3111-d8f8-4148-a323-53da903d831f rw,seclabel,compress=zstd:1,ssd,space_cache=v2,subvolid=258,subvol=/root
78 73 0:35 /root/ostree/deploy/fedora/var /sysroot/ostree/deploy/fedora/var rw,relatime - btrfs /dev/mapper/luks-ecdf3111-d8f8-4148-a323-53da903d831f rw,seclabel,compress=zstd:1,ssd,space_cache=v2,subvolid=258,subvol=/root
34 23 0:19 / /sys/fs/selinux rw,nosuid,noexec,relatime shared:13 - selinuxfs selinuxfs rw
33 22 0:31 / /proc/sys/fs/binfmt_misc rw,relatime shared:20 - autofs systemd-1 rw,fd=33,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=20541
35 24 0:32 / /dev/hugepages rw,relatime shared:21 - hugetlbfs hugetlbfs rw,seclabel,pagesize=2M
36 24 0:18 / /dev/mqueue rw,nosuid,nodev,noexec,relatime shared:22 - mqueue mqueue rw,seclabel
37 23 0:7 / /sys/kernel/debug rw,nosuid,nodev,noexec,relatime shared:23 - debugfs debugfs rw,seclabel
38 23 0:12 / /sys/kernel/tracing rw,nosuid,nodev,noexec,relatime shared:24 - tracefs tracefs rw,seclabel
39 23 0:33 / /sys/fs/fuse/connections rw,nosuid,nodev,noexec,relatime shared:25 - fusectl fusectl rw
101 28 0:38 / /run/credentials/systemd-sysctl.service ro,nosuid,nodev,noexec,relatime shared:26 - ramfs ramfs rw,seclabel,mode=700
40 28 0:39 / /run/credentials/systemd-tmpfiles-setup-dev.service ro,nosuid,nodev,noexec,relatime shared:27 - ramfs ramfs rw,seclabel,mode=700
42 72 0:35 /var /var rw,relatime shared:28 - btrfs /dev/mapper/luks-ecdf3111-d8f8-4148-a323-53da903d831f rw,seclabel,compress=zstd:1,ssd,space_cache=v2,subvolid=256,subvol=/var
44 72 0:43 / /tmp rw,nosuid,nodev shared:74 - tmpfs tmpfs rw,seclabel,nr_inodes=1048576,inode64
48 72 259:4 / /boot rw,relatime shared:90 - ext4 /dev/nvme0n1p4 rw,seclabel
52 42 0:35 /home /var/home rw,relatime shared:93 - btrfs /dev/mapper/luks-ecdf3111-d8f8-4148-a323-53da903d831f rw,seclabel,compress=zstd:1,ssd,space_cache=v2,subvolid=257,subvol=/home
51 48 259:3 / /boot/efi rw,relatime shared:96 - hfsplus /dev/nvme0n1p3 rw,umask=22,uid=0,gid=0,nls=utf8
160 28 0:45 / /run/credentials/systemd-tmpfiles-setup.service ro,nosuid,nodev,noexec,relatime shared:99 - ramfs ramfs rw,seclabel,mode=700
57 33 0:46 / /proc/sys/fs/binfmt_misc rw,nosuid,nodev,noexec,relatime shared:102 - binfmt_misc binfmt_misc rw
202 28 0:47 / /run/credentials/systemd-resolved.service ro,nosuid,nodev,noexec,relatime shared:128 - ramfs ramfs rw,seclabel,mode=700
326 28 0:71 / /run/user/1000 rw,nosuid,nodev,relatime shared:981 - tmpfs tmpfs rw,seclabel,size=798004k,nr_inodes=199501,mode=700,uid=1000,gid=1000,inode64
924 326 0:72 / /run/user/1000/gvfs rw,nosuid,nodev,relatime shared:1033 - fuse.gvfsd-fuse gvfsd-fuse rw,user_id=1000,group_id=1000
1133 326 0:73 / /run/user/1000/doc rw,nosuid,nodev,relatime shared:1061 - fuse.portal portal rw,user_id=1000,group_id=1000
```

> > Is it possible, that this is an installation on a partition-less disk, for example btrfs on `/dev/sda` instead of `/dev/sda1`?
> 
> Seems he is using LVM

Not sure. I followed https://fedoraproject.org/wiki/QA:Testcase_dualboot_with_macOS.

**Comment by osalbahr** [comment]
> There is `mount ID` and `parent ID`. I checked fedora (in VM) and it shows
> 
> ```
> 77 1 0:38 /root / rw,relatime shared:1 - btrfs /dev/sda3 rw,seclabel,compress=zstd:1,ssd,discard=async,space_cache=v2,subvolid=257,subvol=/root
> 48 77 0:38 /home /home rw,relatime shared:51 - btrfs /dev/sda3 rw,seclabel,compress=zstd:1,ssd,discard=async,space_cache=v2,subvolid=256,subvol=/home
> ```
> 
> So that `/home` is a child of `/`. Don't know if it's useful

It might be worth noting that I'm using Fedora Silverblue. If your VM was a Fedora Workstation, some discrepancy in the mounts is expected. For example, as per the [Fedora Silverblue filesystem layout](https://docs.fedoraproject.org/en-US/fedora-silverblue/technical-information/):
```console
$ ls -l /home
lrwxrwxrwx. 4 root root 8 Jun 29 22:29 /home -> var/home
```

Or, more specifically, I am using an image based on Fedora Silverblue provided by [Universal Blue (uBlue)](https://universal-blue.org/). I highly doubt this affects the mounts but I can rebase back to vanilla Silverblue and double-check if it might be helpfu.

```console
$ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 6min ago
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/silverblue-main
                   Digest: sha256:6efc58f4bd8367c81df2551f92d5beb0f6c064509673418446f86d8d7838a98c
                  Version: 38.20230825.0 (2023-08-25T07:10:59Z)
                     Diff: 3 upgraded

● ostree-image-signed:docker://ghcr.io/ublue-os/silverblue-main
                   Digest: sha256:b1dae5d6f166cf8cf3f54cccd77ab699e89d44c2d75a071483298ecdede20642
                  Version: 38.20230824.0 (2023-08-24T17:24:04Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/silverblue-main
                   Digest: sha256:ae95a5e3108d5bc4b66216086a252c85312238ce1907a79967c66e9c16e93832
                  Version: 38.20230821.0 (2023-08-22T01:44:12Z)
```

**Comment by CarterLi** [comment]
> > @osalbahr Can you paste the content of `/proc/self/mountinfo` here?
> 
> Sure.
> 
> ```console
> $ cat /proc/self/mountinfo
> 22 72 0:21 / /proc rw,nosuid,nodev,noexec,relatime shared:19 - proc proc rw
> 23 72 0:22 / /sys rw,nosuid,nodev,noexec,relatime shared:6 - sysfs sysfs rw,seclabel
> 24 72 0:5 / /dev rw,nosuid shared:14 - devtmpfs devtmpfs rw,seclabel,size=4096k,nr_inodes=986111,mode=755,inode64
> 25 23 0:6 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime shared:7 - securityfs securityfs rw
> 26 24 0:23 / /dev/shm rw,nosuid,nodev shared:15 - tmpfs tmpfs rw,seclabel,inode64
> 27 24 0:24 / /dev/pts rw,nosuid,noexec,relatime shared:16 - devpts devpts rw,seclabel,gid=5,mode=620,ptmxmode=000
> 28 72 0:25 / /run rw,nosuid,nodev shared:17 - tmpfs tmpfs rw,seclabel,size=1596012k,nr_inodes=819200,mode=755,inode64
> 29 23 0:26 / /sys/fs/cgroup rw,nosuid,nodev,noexec,relatime shared:8 - cgroup2 cgroup2 rw,seclabel,nsdelegate,memory_recursiveprot
> 30 23 0:27 / /sys/fs/pstore rw,nosuid,nodev,noexec,relatime shared:9 - pstore pstore rw,seclabel
> 31 23 0:28 / /sys/firmware/efi/efivars rw,nosuid,nodev,noexec,relatime shared:10 - efivarfs efivarfs rw
> 32 23 0:29 / /sys/fs/bpf rw,nosuid,nodev,noexec,relatime shared:11 - bpf bpf rw,mode=700
> 46 28 0:30 / /run/credentials/systemd-vconsole-setup.service ro,nosuid,nodev,noexec,relatime shared:18 - ramfs ramfs rw,seclabel,mode=700
> 67 23 0:34 / /sys/kernel/config rw,nosuid,nodev,noexec,relatime shared:12 - configfs configfs rw
> 73 72 0:35 /root /sysroot ro,relatime - btrfs /dev/mapper/luks-ecdf3111-d8f8-4148-a323-53da903d831f rw,seclabel,compress=zstd:1,ssd,space_cache=v2,subvolid=258,subvol=/root
> 72 1 0:35 /root/ostree/deploy/fedora/deploy/94c063e370f6891eae991480e040906a3430fa1ec8ee3deb384a14be3719988d.0 / rw,relatime shared:1 - btrfs /dev/mapper/luks-ecdf3111-d8f8-4148-a323-53da903d831f rw,seclabel,compress=zstd:1,ssd,space_cache=v2,subvolid=258,subvol=/root
> 76 72 0:35 /root/ostree/deploy/fedora/deploy/94c063e370f6891eae991480e040906a3430fa1ec8ee3deb384a14be3719988d.0/etc /etc rw,relatime shared:2 - btrfs /dev/mapper/luks-ecdf3111-d8f8-4148-a323-53da903d831f rw,seclabel,compress=zstd:1,ssd,space_cache=v2,subvolid=258,subvol=/root
> 77 72 0:35 /root/ostree/deploy/fedora/deploy/94c063e370f6891eae991480e040906a3430fa1ec8ee3deb384a14be3719988d.0/usr /usr ro,relatime shared:3 - btrfs /dev/mapper/luks-ecdf3111-d8f8-4148-a323-53da903d831f rw,seclabel,compress=zstd:1,ssd,space_cache=v2,subvolid=258,subvol=/root
> 78 73 0:35 /root/ostree/deploy/fedora/var /sysroot/ostree/deploy/fedora/var rw,relatime - btrfs /dev/mapper/luks-ecdf3111-d8f8-4148-a323-53da903d831f rw,seclabel,compress=zstd:1,ssd,space_cache=v2,subvolid=258,subvol=/root
> 34 23 0:19 / /sys/fs/selinux rw,nosuid,noexec,relatime shared:13 - selinuxfs selinuxfs rw
> 33 22 0:31 / /proc/sys/fs/binfmt_misc rw,relatime shared:20 - autofs systemd-1 rw,fd=33,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=20541
> 35 24 0:32 / /dev/hugepages rw,relatime shared:21 - hugetlbfs hugetlbfs rw,seclabel,pagesize=2M
> 36 24 0:18 / /dev/mqueue rw,nosuid,nodev,noexec,relatime shared:22 - mqueue mqueue rw,seclabel
> 37 23 0:7 / /sys/kernel/debug rw,nosuid,nodev,noexec,relatime shared:23 - debugfs debugfs rw,seclabel
> 38 23 0:12 / /sys/kernel/tracing rw,nosuid,nodev,noexec,relatime shared:24 - tracefs tracefs rw,seclabel
> 39 23 0:33 / /sys/fs/fuse/connections rw,nosuid,nodev,noexec,relatime shared:25 - fusectl fusectl rw
> 101 28 0:38 / /run/credentials/systemd-sysctl.service ro,nosuid,nodev,noexec,relatime shared:26 - ramfs ramfs rw,seclabel,mode=700
> 40 28 0:39 / /run/credentials/systemd-tmpfiles-setup-dev.service ro,nosuid,nodev,noexec,relatime shared:27 - ramfs ramfs rw,seclabel,mode=700
> 42 72 0:35 /var /var rw,relatime shared:28 - btrfs /dev/mapper/luks-ecdf3111-d8f8-4148-a323-53da903d831f rw,seclabel,compress=zstd:1,ssd,space_cache=v2,subvolid=256,subvol=/var
> 44 72 0:43 / /tmp rw,nosuid,nodev shared:74 - tmpfs tmpfs rw,seclabel,nr_inodes=1048576,inode64
> 48 72 259:4 / /boot rw,relatime shared:90 - ext4 /dev/nvme0n1p4 rw,seclabel
> 52 42 0:35 /home /var/home rw,relatime shared:93 - btrfs /dev/mapper/luks-ecdf3111-d8f8-4148-a323-53da903d831f rw,seclabel,compress=zstd:1,ssd,space_cache=v2,subvolid=257,subvol=/home
> 51 48 259:3 / /boot/efi rw,relatime shared:96 - hfsplus /dev/nvme0n1p3 rw,umask=22,uid=0,gid=0,nls=utf8
> 160 28 0:45 / /run/credentials/systemd-tmpfiles-setup.service ro,nosuid,nodev,noexec,relatime shared:99 - ramfs ramfs rw,seclabel,mode=700
> 57 33 0:46 / /proc/sys/fs/binfmt_misc rw,nosuid,nodev,noexec,relatime shared:102 - binfmt_misc binfmt_misc rw
> 202 28 0:47 / /run/credentials/systemd-resolved.service ro,nosuid,nodev,noexec,relatime shared:128 - ramfs ramfs rw,seclabel,mode=700
> 326 28 0:71 / /run/user/1000 rw,nosuid,nodev,relatime shared:981 - tmpfs tmpfs rw,seclabel,size=798004k,nr_inodes=199501,mode=700,uid=1000,gid=1000,inode64
> 924 326 0:72 / /run/user/1000/gvfs rw,nosuid,nodev,relatime shared:1033 - fuse.gvfsd-fuse gvfsd-fuse rw,user_id=1000,group_id=1000
> 1133 326 0:73 / /run/user/1000/doc rw,nosuid,nodev,relatime shared:1061 - fuse.portal portal rw,user_id=1000,group_id=1000
> ```
> 
> > > Is it possible, that this is an installation on a partition-less disk, for example btrfs on `/dev/sda` instead of `/dev/sda1`?
> > 
> > Seems he is using LVM
> 
> Not sure. I followed https://fedoraproject.org/wiki/QA:Testcase_dualboot_with_macOS.

Thanks. It is very useful.

**Comment by CarterLi** [comment]
> Remember, because by default the system is booted into a chroot equivalent, there has to be some way to refer to the actual physical root filesystem. Therefore, your operating system tree should contain an empty /sysroot directory; at boot time, OSTree will make this a bind mount to the physical / root directory. There is precedent for this name in the initramfs context. You should furthermore make a toplevel symbolic link /ostree which points to /sysroot/ostree, so that the OSTree tool at runtime can consistently find the system data regardless of whether it’s operating on a physical root or inside a deployment.

So that /sysroot is the true fs root?

**Comment by CarterLi** [comment]
According to <https://stackoverflow.com/questions/5426818/ordering-of-proc-mounts-and-etc-mtab>, items in /proc/mounts are in mounted order.

I decide not to change the current behavior. If one want to display / instead of /sysroot or something, use `--disk-folders` option
