### ISSUE TITLE
Network

### ISSUE THREAD

**Issue by iomari** [fastfetch-cli/fastfetch#546]
Greetings,
the only module that archey has over this is the network.
Archey shows me my network interfaces and ip addresses attached to them.
Are there any places on adding httis to fastfetch?

**Comment by CarterLi** [comment]
`fastfetch -s localip`

https://github.com/fastfetch-cli/fastfetch/blob/dev/src/data/help.txt#L146-L152

**Comment by iomari** [comment]
thanks for the quick response
