### ISSUE TITLE
presets

### ISSUE THREAD

**Issue by iomari** [fastfetch-cli/fastfetch#547]
Greetings,
In your presets folder, how do I use the files that are not .jsonc?

**Comment by CarterLi** [comment]
`fastfetch --config /path/to/the/presets/file`

**Comment by iomari** [comment]
thanks. They all worked except:
fastfetch --config ./verbose                                                                                                                                                                                               
Error: unknown option: --cpu-usage-format

**Comment by CarterLi** [comment]
Good. I'll fix that

**Comment by iomari** [comment]
cool. BTW,this is an excellent tool. I've tried them all and this is definitely the best of the lot.

**Comment by CarterLi** [comment]
Thanks.

Have fun!
