### ISSUE TITLE
Battery life percentage reports a number higher than 100 on a Windows laptop

### ISSUE THREAD

**Issue by 1ivyatan** [fastfetch-cli/fastfetch#549]
Hi! After downloading latest release (2.0.5) for Windows x64, I ran `fastfetch` with `cmd.exe` without configuring anything, just running it right after downloading. Output is fast and is without layout issues, but battery percentage reporting is above 100% (reports 117% and should be 100%). The image below shall tell a lot about hardware used to run fastfetch.
![the screenshot](https://files.catbox.moe/9vfadb.PNG)
I guess it has to do with this file responsible for getting battery status `src/detection/battery/battery_windows.c` (how do you reference files with md?)

### Reproducing the bug
- Hardware should be a laptop and battery should be full and connected to AC
- Download latest release binary (2.0.5) for Windows x64
- Extract the archive and run it with `cmd.exe` without configuring anything

If battery level report does not exceed 100%, there are likely more factors that leads to battery level report being above 100%

**Comment by CarterLi** [comment]
Try `fastfetch --allow-slow-operations`

**Comment by 1ivyatan** [comment]
AC ON
![screencap](https://files.catbox.moe/ipn8lz.PNG)

AC off right after disconnecting it (no change as of taking second screenshot)
![no ac](https://files.catbox.moe/cviwzn.PNG)

AC off for some time
![no ac after some time](https://files.catbox.moe/rheagw.PNG)

AC on after that and charging to 100%
![finale](https://files.catbox.moe/tlvgd2.PNG)

I think battery life reporting outputs wrong information when battery is fully charged

**Comment by 1ivyatan** [comment]
> When you disconnected the AC, did it drop to 97% directly or slowly? Did it show other values above 100% ( eg 110% )?

Drop to 97% was not instant but gradual and i have yet to see values that are `100 > n < 117` but now there's this problem of hardware not charging battery that is above 90%, so I will let that laptop use battery more and recharge it to completion to make sure i have not seen values like you said, for that I will come back in a while to report it.


> The percentage value is calcuated with `remainingCapacity / maxCapacity * 100%`. It seems that the OS was reporting remaining capacity larger than max capacity.

Might get into this, which I will put it to window sill for a while

**Comment by 1ivyatan** [comment]
Came back with results! Two outputs show past and current battery level but even when it reports 100%, it still says `Charging`, so what is likely is the formula or how kernel reports battery levels.
![ff3](https://github.com/fastfetch-cli/fastfetch/assets/143333830/e03cf428-d333-43be-b262-44db3b612fcf)

So I disconnected the charger and reconnected it and reran `fastfetch`  and no longer it reports `Charging` but just `AC Connected`, but after not running it for a minute and then running the program again, `Charging` is reported again.
![ff4](https://github.com/fastfetch-cli/fastfetch/assets/143333830/e0bdefd1-4972-4162-81a1-351df8227a77)

But Windows mobility centre says it's fully charged.
![ff5](https://github.com/fastfetch-cli/fastfetch/assets/143333830/eed44401-a818-4fa7-9e8f-21f69a4ea54a)

**Comment by CarterLi** [comment]
Maybe your laptop supports [trickle charging](https://en.wikipedia.org/wiki/Trickle_charging).

Anyway, I don't think there are any bugs in detection logic. The only thing I can do is clamping the result to 100% if it exceeds 100%, but I don't think I want to to that.
