### ISSUE TITLE
[BUG] Graphical Image Resize Changes Imager Resolution

### ISSUE THREAD

**Issue by VehementHam** [fastfetch-cli/fastfetch#550]
# General description of bug:

* What happened:

- I ran the command `fastfetch --logo-type kitty --logo Pictures/OpenSuse.png --logo-width 36 --logo-height 18`. The image was resized, but the resolution was lowered. In neofetch teh resolution retains.

* What should happen:

- The resolution of the image should be the same regardless of the size flags or arguments. 

* Where did you get the binary: 
I installed the `fastfetch` binary with Zypper. 

# Often helpful information:

Output of `fastfetch --list-features`:
```
fastfetch --list-features
threads
libpci
vulkan
wayland
xcb-randr
xcb
xrandr
x11
gio
dbus
imagemagick7
chafa
zlib
xfconf
sqlite3
rpm
egl
glx
osmesa
openc
```

## If my image logo didn't show / work

* The image protocol you used: Kitty
* The terminal you used: Kitty
* Upload the image file here, or paste the image URL: 

-  https://media.discordapp.net/attachments/877406812566069299/1146179709412057088/OpenSuse.png?width=702&height=702

  
  https://media.discordapp.net/attachments/1092527545758527549/1146865721779966002/20230831_12h54m42s_grim.png?width=1248&height=702

**Comment by CarterLi** [comment]
It is intentional. If you don't want the image to be resized, you should use `--logo-type kitty-direct` instead

**Comment by VehementHam** [comment]
> It is intentional. If you don't want the image to be resized, you should use `--logo-type kitty-direct` instead

`Error: unknown --logo-type value: kitty-direct`

**Comment by CarterLi** [comment]
What fastfetch version are you using?

**Comment by VehementHam** [comment]
> What fastfetch version are you using?

fastfetch 1.12.2 (x86_64)

**Comment by CarterLi** [comment]
Ok, it was the terminal that lowers the resolution, if you specifies logo width and height.

![image](https://github.com/fastfetch-cli/fastfetch/assets/6134068/cc7635fc-eadc-459b-8139-3f314cc72508)

You may test it yourself. Just change `L2hvbWUvY2FydGVyL09wZW5TdXNlLnBuZw==` to base64 encoded path to the image file.

**Comment by VehementHam** [comment]
Sorry, how do I find the base64 encoded path of the image file?

**Comment by CarterLi** [comment]
Support of `--logo-type kitty-direct` without specifying `--logo-width` and `--logo-height` was added in dev branch
