### ISSUE TITLE
Small image size borks text rendering

### ISSUE THREAD

**Issue by Pandaalifter** [fastfetch-cli/fastfetch#553]
# General description of bug:

* What happened: When an image is rendered with a size that makes it small enough to go under the user@hostname line, it causes the fastfetch output to overlay on the previous text line of the terminal. This issue doesn't occur on a clear or new terminal in contour, but always occurs on Wezterm. @kojq also said I should write this.
* What should happen: FastFetch should not intersect with the text of previous lines.
* Where did you get the binary: Installed 2.0.5 Deb from GitHub with `apt install`

# Often helpful information:

* The image protocol you used: Sixel 
* The terminal you used: Wezterm (Deb and Flatpak) and Contour (Flatpak)
* Screenshots:
![image](https://github.com/fastfetch-cli/fastfetch/assets/96748487/2d1df8ca-5086-4f93-8da4-17383bf601e6)
![image](https://github.com/fastfetch-cli/fastfetch/assets/96748487/6c30678d-e7b2-4623-a7ac-3128993e0a35)

**Comment by CarterLi** [comment]
It is a known issue. See https://github.com/fastfetch-cli/fastfetch/issues/529#issuecomment-1687596116.

**Comment by CarterLi** [comment]
I won't fix this. @LinusDierheimer please have a check when you have time
