### ISSUE TITLE
fastfetch 2.0.5-8 (x86_64) kitty-direct

### ISSUE THREAD

**Issue by VehementHam** [fastfetch-cli/fastfetch#554]
When I run `./build/fastfetch --logo-type kitty-direct --logo ~/Pictures/OpenSuse.png`, the logo shows up a large size.  
Also I get this error message: `Logo (kitty-direct): fail to query cursor position: poll() timeout or failed`.

I filled the whole thing out earlier, and then I accidentally when back in my browser and lost it. I am not doing all of that again. But I think one of the commands said that fastfetch was not compiled with a bunch of stuff.

Next time I will use me freaking text editor to do this.

**Comment by CarterLi** [comment]
What terminal were you using?

**Comment by CarterLi** [comment]
I reproduced this issue with a very large image. Then I resized the image to a smaller size, fastfetch worked fine.
