### ISSUE TITLE
Incorrect Snap package number

### ISSUE THREAD

**Issue by iamrasel** [fastfetch-cli/fastfetch#562]
* What happened:
It shows that I have no **Snap** package installed, though I have some. I have also tested with `--packages-format {16}`, it also outputs `0`. **Neofetch** can detect and show the exact number.

* What should happen:
It should detect and print the number of installed Snap packages.

* Did it work in an older version:
I don't know. I just installed **Fastfetch** for the first time, thinking I would permanently shift from Neofetch as it has much more customization options.

* Where did you get the binary: 
Installed through this AUR package - [https://aur.archlinux.org/packages/fastfetch](https://aur.archlinux.org/packages/fastfetch)

* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)?
Any of the recent builds doesn't contain any term that could be related to this issue, so I haven't tried.

![2023-09-20--1695193708_236x55_scrot](https://github.com/fastfetch-cli/fastfetch/assets/77199897/50e59772-0878-4a83-a1fa-9379fe6b2a35)

**System Information:**
OS - EndeavourOS x86_64
Kernel - 6.5.3-arch1-1
Shell - zsh
Terminal - Terminator 3.11.5

**Comment by CarterLi** [comment]
Are snap packages installed in `/snap`? What's output of `ls /snap`?

**Comment by CarterLi** [comment]
Fastfetch also counts `/var/lib/snapd/snap` in now, which seems to be the bin path of systems other than Ubuntu. Please have a test.

**Comment by iamrasel** [comment]
> What's output of `ls /snap` ?
- ls: cannot access '/snap': No such file or directory

> Does `/var/lib/snapd/snaps` exist?
- Yes. `/var/lib/snapd/snap` also exists, which contains the dedicated folders for installed Snap packages along with some other directories.

**Comment by CarterLi** [comment]
Can you test it? If it works for you, please close this issue.

**Comment by CarterLi** [comment]
You may get the latest binary here: https://github.com/fastfetch-cli/fastfetch/actions/runs/6245881128

**Comment by iamrasel** [comment]
It works now, thanks for fixing this.
