### ISSUE TITLE
[linux] Can't recognize the cpu name correctly on arm64.

### ISSUE THREAD

**Issue by xzl01** [fastfetch-cli/fastfetch#567]
Sorry I didn't follow your feedback format. I noticed that on Huawei Pangu ARM machines the CPU name is output as unknown:
![image](https://github.com/fastfetch-cli/fastfetch/assets/31403725/f727d559-1c50-4355-8521-bb26d69e66a9)
But the name output on the lscpu is correct, After looking at the code I realized that the lscpu does something special for arm64 cpus  <https://github.com/util-linux/util-linux/blob/87f491671efb920ddd1c45c70dc8016f072851bb/sys-utils/lscpu-arm.c> 

Hopefully fastfetch will also support recognizing

**Comment by CarterLi** [comment]
I will just call lscpu and fetch its output

**Comment by daniejstriata** [comment]
I have output from the AWS g4 lscpu in this ticket: https://github.com/fastfetch-cli/fastfetch/issues/566

**Comment by CarterLi** [comment]
What's `lscpu -p=MODELNAME`?

**Comment by CarterLi** [comment]
![Screenshot_2023-09-27-14-16-19-753_com.termux.jpg](https://github.com/fastfetch-cli/fastfetch/assets/6134068/b8f0daa2-06bd-47ae-bc35-8c061cd31f44)

Tested on Android, lscpu prints different model names for different cores. In this case should fastfetch use only the first name, or print them all?

**Comment by daniejstriata** [comment]
`lscpu | awk '/Model name:/ { print $3 }'`
Neoverse-N1

**Comment by CarterLi** [comment]
What's `lscpu -h`?

> lscpu | awk '/Model name:/ { print $3 }'

I can't use that, because the `Model name` is localized.

**Comment by CarterLi** [comment]
Seems that `CPU part` is `id_part::id` in `lscpu-arm.c`. I decided to use it.

**Comment by xzl01** [comment]
This is the output of my lscpu:
```
deepin@deepin-pc-52:~$ lscpu
Architecture:           aarch64
  CPU op-mode(s):       64-bit
  Byte Order:           Little Endian
CPU(s):                 24
  On-line CPU(s) list:  0-23
Vendor ID:              HiSilicon
  Model name:           Kunpeng-920
    Model:              0
    Thread(s) per core: 1
    Core(s) per socket: 24
    Socket(s):          1
    Stepping:           0x1
    BogoMIPS:           200.00
    Flags:              fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm
Caches (sum of all):    
  L1d:                  1.5 MiB (24 instances)
  L1i:                  1.5 MiB (24 instances)
  L2:                   12 MiB (24 instances)
  L3:                   24 MiB (1 instance)
Vulnerabilities:        
  Itlb multihit:        Not affected
  L1tf:                 Not affected
  Mds:                  Not affected
  Meltdown:             Not affected
  Spec store bypass:    Not affected
  Spectre v1:           Mitigation; __user pointer sanitization
  Spectre v2:           Not affected
  Srbds:                Not affected
  Tsx async abort:      Not affected
```

**Comment by CarterLi** [comment]
Does `lscpu -p=MODELNAME` work?

**Comment by xzl01** [comment]
> Does `lscpu -p=MODELNAME` work?  `lscpu -p=MODELNAME` 有效吗？

no
```
lscpu: unknown column: MODELNAME
```

**Comment by CarterLi** [comment]
Strange. Maybe you are using an old lscpu version

**Comment by xzl01** [comment]
> Strange. Maybe you are using an old lscpu version strange. Maybe you are using an old lscpu version

It's possible, the version I'm using is 2.38-5 but I'll update it soon when I realize

**Comment by daniejstriata** [comment]
`lscpu --version`
lscpu from util-linux 2.37.4

**Comment by CarterLi** [comment]
Please test it

**Comment by daniejstriata** [comment]
Working for me:
![image](https://github.com/fastfetch-cli/fastfetch/assets/13314239/c9b215f8-6233-456a-95c2-48bdd7fe1317)

**Comment by theofficialgman** [comment]
@CarterLi please re-open. this issue is still present

fastfetch 2.16.0
```
                                            CPU: ARMv8 rev 1 (v8l) (4) @ 2.09 GHz
```
`lscpu -p=MODELNAME`
```
# The following is the parsable format, which can be fed to other
# programs. Each different item in every column has an unique ID
# starting usually from zero.
# Modelname
Cortex-A57
Cortex-A57
Cortex-A57
Cortex-A57
```
`cat /proc/cpuinfo`
```
processor       : 0
model name      : ARMv8 Processor rev 1 (v8l)
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 1

processor       : 1
model name      : ARMv8 Processor rev 1 (v8l)
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 1

processor       : 2
model name      : ARMv8 Processor rev 1 (v8l)
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 1

processor       : 3
model name      : ARMv8 Processor rev 1 (v8l)
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 1
```

I would prefer that `lscpu` output always be default on arm (armv6/7/8/9)

**Comment by NitroNils** [comment]
> We can't use code of lscpu because of the GPL license issue.

There is a BSD clause 3 licensed [version](https://github.com/NanXiao/lscpu) of lscpu too.

**Comment by CarterLi** [comment]
> > We can't use code of lscpu because of the GPL license issue.
> 
> There is a BSD clause 3 licensed [version](https://github.com/NanXiao/lscpu) of lscpu too.
> 
> EDIT: Not sure whether it would work on Linux, though.

It's for x86 only

**Comment by theofficialgman** [comment]
> > We can't use code of lscpu because of the GPL license issue.
> 
> There is a BSD clause 3 licensed [version](https://github.com/NanXiao/lscpu) of lscpu too.
> 
> EDIT: Not sure whether it would work on Linux, though.

mapping tables matching the variant/part to a friendly name are not code and are not subject to licenses. these variant/part to friendly name tables all come from public license free resources.
