### ISSUE TITLE
[Feature request] opkg (OpenWRT package manager) support

### ISSUE THREAD

**Issue by Kamillaova** [fastfetch-cli/fastfetch#574]

**Comment by CarterLi** [comment]
Please test it. If there's anything wrong, please upload the file `/usr/lib/opkg/status` for me to debugging.

**Comment by Kamillaova** [comment]
It works, thanks!

![image](https://github.com/fastfetch-cli/fastfetch/assets/54859825/798d37a5-7fe9-4220-88ed-6f50ce39d67c)
![image](https://github.com/fastfetch-cli/fastfetch/assets/54859825/b4470aa4-5f2c-484a-920f-1bb1d83a972c)

**Comment by CarterLi** [comment]
Is there a terminal on your openwrt (router?) device?

**Comment by Kamillaova** [comment]
> Is there a terminal on your openwrt (router?) device?

No

**Comment by CarterLi** [comment]
Can you pull the newest code and try it again with `--format json`?

**Comment by Kamillaova** [comment]
> Can you pull the newest code and try it again with `--format json`?

![image](https://github.com/fastfetch-cli/fastfetch/assets/54859825/dd649171-4d0a-4c3c-9918-57ac7f0265dc)

https://gist.github.com/Kamillaova/8fcbd53ee5eed02007be3f33b29d020d

**Comment by CarterLi** [comment]
Google said that dropbear is a SSH server implementation. I think it is okey to be detected as a terminal.
