### ISSUE TITLE
Detecting runtime libc version

### ISSUE THREAD

**Issue by JamiKettunen** [fastfetch-cli/fastfetch#575]
I see https://github.com/fastfetch-cli/fastfetch/commit/23d2cc3fdc1d1531174a67b0dd708b05a5cba43c was very recently commited and was wondering if there would be hope for running e.g. `/lib/ld-musl-x86_64.so.1` (which would be the dynamic linker for `fastfetch` under relevant systems) which outputs for example:
```
musl libc (x86_64)
Version 1.2.4
Dynamic Program Loader
Usage: /lib/ld-musl-x86_64.so.1 [options] [--] pathname [args]
```
And parsing its output for the `Version`?

I can get the path to the linker via e.g. `ldd /usr/bin/fastfetch` (first line) but there's probably a smarter way to do that as well.

**Comment by JamiKettunen** [comment]
I'm also wondering if it makes sense to even hardcode the shown glibc version either, there may be cases where the program is compiled against, say glibc 2.36 and distro updates to 2.38 without the program requiring a recompile to keep running. In that case it would show a mostly irrelevant detail imho

**Comment by CarterLi** [comment]
The `Version` module was designed to print compile flags used / compiler used / libc used when fastfetch was compiling, because there were several issues filed before that running fastfetch in systems with old glibc version.

Detecting libc version that fastfetch running on, while should be possible, is a different topic.

**Comment by JamiKettunen** [comment]
Ah ok, thanks for explaining. I'll rename the issue accordingly

**Comment by CarterLi** [comment]
Why do you want that?

**Comment by JamiKettunen** [comment]
Now that I think of it the `glibc`/`musl` version for example are really just core things people don't really care about, they update in the background and whatever; now just knowing which one the distro is using is more interesting as https://voidlinux.org/ for example ships both `glibc` and `musl` images of the distribution (of course for most distribution this would be `glibc` similar to most having `systemd` while `dinit`, `openrc` etc also exists for init systems).
