### ISSUE TITLE
Topic suggestion for the repo

### ISSUE THREAD

**Issue by neoroot** [fastfetch-cli/fastfetch#585]
Please consider adding the `hacktoberfest` topic to the repository, so that it might get much more visibility. And more people will be attracted to contribute new stuffs.

**Comment by LinusDierheimer** [comment]
Done.

**Comment by CarterLi** [comment]
@LinusDierheimer Can you grant me the permission to change project settings? I have something want to change (for example the project description), but I am only allowed to push code.
