### ISSUE TITLE
Add steam games to packages

### ISSUE THREAD

**Issue by Lutitious** [fastfetch-cli/fastfetch#588]
# Current state: 
Not implemented

# Wanted state: 
Implemented

# Why the change is sensible:
Hyfetch has added support for this and it would be cool. Here is the code they use for it specifically
```bash
# Steam games
STEAM_P=".local/share/Steam/steamapps/common"
if [[ -d "$HOME/$STEAM_P" ]]; then
    manager=steam && dir "$HOME/$STEAM_P/*/"
elif [[ -d "$HOME/.var/app/com.valvesoftware.Steam/$STEAM_P" ]]; then
    manager=steam && dir "$HOME/.var/app/com.valvesoftware.Steam/$STEAM_P/*/"
elif [[ -d "$HOME/.steam/steam/steamapps/common" ]]; then
    manager=steam && dir "$HOME/.steam/steam/steamapps/common/*/"
fi
```

**Comment by xbt573** [comment]
`$STEAM_P` also can contain compatibility tools like Proton or libraries like Steamworks Shared or SteamLinuxRuntime
Plus, user can install games to other location by choosing it in Steam client, so this is useless in this case

**Comment by CarterLi** [comment]
I don't think that steam fits for fastfetch. Package module in fastfetch detects general purpose and system level package managers. Steam is neither general purpose nor system level.

You may use `Command` module to fit your personal requirements.

```
--command-key Steam --command-text "Whatever shell script"
```
