### ISSUE TITLE
The number of dpkg packages is incorrect

### ISSUE THREAD

**Issue by og900aero** [fastfetch-cli/fastfetch#593]
The number of dpkg packages is incorrect in Debian 12 with fastfetch 2.1.2 (x86_64).

Fastfetch show: 1534 (dpkg)
When I Run dpkg --list | wc --lines, then show 1560
Also run neofetch, that show 1555

What is the truth? How do you count packages?

The content of the configuration file you use (if any)
```
--structure "Title:Separator:OS:Host:Kernel:Uptime:Packages:Shell:Display:WM:WMTheme:Theme:Terminal:TerminalFont:Font:CPU:GPU:Memory:Break:Colors"
--host-format "{/2}{-}{/}{2}{?3} {3}{?}"
--os-format "{3}"
--display-key Resolution
--display-compact-type original
--wm-format "{2}"
--theme-format "{?1}{1}"
--terminalfont-format "{/2}{-}{/}{2}{?3} {3}{?}"
--memory-format "{1} / {2}"
--cpu-freq-ndigits 2
--size-max-prefix MB
--size-ndigits 0
```
Output of `fastfetch --list-features`:
```
threads
libpci
vulkan
wayland
xcb-randr
xcb
xrandr
x11
gio
dconf
dbus
imagemagick6
zlib
xfconf
sqlite3
rpm
egl
glx
osmesa
opencl
libpulse
libnm
Directx Headers
```

**Comment by CarterLi** [comment]
The logic of fastfetch is like `grep 'Status: install ok installed' /var/lib/dpkg/status | wc -l`

Which should matches `apt list --installed | wc -l # - 1`

**Comment by og900aero** [comment]
> The logic of fastfetch is like `grep 'Status: install ok installed' /var/lib/dpkg/status | wc -l`
> 
> Which should matches `apt list --installed | wc -l # - 1`

Thx.
Or maybe work this too: dpkg --list | grep -c '^ii'
This show 1534 too.
