### ISSUE TITLE
Fastfetch does not recognize a few popular terminals

### ISSUE THREAD

**Issue by og900aero** [fastfetch-cli/fastfetch#594]
Fastfetch does not recognize a few popular terminals: like st and urxvt.
I get error message when I run: env NO_CONFIG=1 fastfetch --show-errors --stat --multithreading false --disable-linewrap false --hide-cursor false && fastfetch --version:
- Terminal Font: Unknown terminal: st
- Terminal Font: Unknown terminal: urxvt

**Comment by CarterLi** [comment]
Are they rxvt-unicode and stterm?

**Comment by og900aero** [comment]
I installed rxvt-unicode package from Debian 12 repo, and run rxvt-unicode
and I downloaded st from https://dl.suckless.org/st/st-0.9.tar.gz and compile with make clean install. In the config.def.h is contains char *termname = "st-256color", if that helps.

**Comment by og900aero** [comment]
> The terminals were recognized. The errors were to indicate the terminal font detection were not supported

Is there anything else I need to do then, or will this be fixed later?

**Comment by CarterLi** [comment]
It is not supported means that someone must implement it. Any contributions are welcome.

**Comment by og900aero** [comment]
> May I ask: are they really popular? I never heard them before.

st -t is developed by the same developer as dwm tilling window manager. Accordingly, it is fast, requires few resources, and can be customized with various patches.
Urxvt is an improved version of plain rxvt, which is a usable alternative to xterm.
urxvt and st are mostly used by those who use the tilling window manager, like dwm, bspwm, i3, xmonad, qtile etc.

Of course, if you don't want it, you don't need to develop it, I just thought that if one of the guidelines is fast and simple, then you should also support those terminals that also follow the fast and simple principles.

**Comment by CarterLi** [comment]
Yeah, make sence.

As I said before, st has been supported. You should try it.

As for urxvt, if you tell me how can I implment it, I'll do it. Otherwise, you have to wait for others.

**Comment by CarterLi** [comment]
And before you try it, please make sure that you know what `Terminal Font: Unknown terminal: st` stands for.

**Comment by og900aero** [comment]
> And before you try it, please make sure that you know what `Terminal Font: Unknown terminal: st` stands for.

Yeah. terminal Font: Unknown terminal: st
So unknown terminal: st does not mean that for unknown terminal st. OK...
No comments. Then I'll close the ticket, because I can see that only confusion is going on.

**Comment by CarterLi** [comment]
Let me clarify: `Terminal Font` module is used to detect what font are you currently using for the terminal. Basically it's used for show casing your terminal configuration for others.

`Unknown terminal: st` means that fastfetch doesn't know how to detect the font that st is using.
