### ISSUE TITLE
Impressive!  Not sure if its feasible but thought I would ask: as you show version numbers it would be nice to see what Nividia driver version is in use.  Thanks!

### ISSUE THREAD

**Issue by EarBiteR** [fastfetch-cli/fastfetch#597]
# Current state: Shows GPU type

# Wanted state: Next to GPU type please show the Version of video driver in use for Nvidia users, possibly others

# Why the change is sensible:  It would save time having to load the Nvidia X server settings apps to find this detail

**Comment by CarterLi** [comment]
`fastfetch -s gpu --gpu-format {3}`

See `fastfetch --help gpu-format` for all available params

**Comment by CarterLi** [comment]
Driver version detection on Linux has been added in https://github.com/fastfetch-cli/fastfetch/commit/9d664e2b61ffada4c96aa7ecc2419c2e52f63541

**Comment by CarterLi** [comment]
Try `./fastfetch -s gpu --gpu-format {3}`

**Comment by EarBiteR** [comment]
Yes, that works - thank you.  Is there a way for it to show it next to the GPU type? Like:

GPU: NVIDIA GeForce GTX 750 Ti (2.24 GiB)  535.113.01

Do I need to modify a preset and recompile?

**Comment by CarterLi** [comment]
See `./fastfetch --help gpu-format`

**Comment by EarBiteR** [comment]
I gen-config and set the options so now works exactly as expected.  Sorry to bother you! Thanks for your time. 

GPU: NVIDIA GeForce GTX 750 Ti 535.113.01
