### ISSUE TITLE
Display information cut off when flashfetch in /etc/bash.bashrc

### ISSUE THREAD

**Issue by kojq** [fastfetch-cli/fastfetch#605]
Using the `2.2.0` release.

Shows:

`Display (NCP005E): 1920x1080 @ 144Hz (as 960x540) [Built-i]`

instead of:

`Display (NCP005E): 1920x1080 @ 144Hz (as 960x540) [Built-in]`

When:

Opening `foot` terminal with `flashfetch` in `/etc/bash.bashrc`.

This does not occur with general use, meaning when manually typed.

FYI: I didn't try with `fastfetch` or with the `.bashrc` in the user home dir.

**Comment by CarterLi** [comment]
Screenshots?

**Comment by CarterLi** [comment]
I can't reproduce it with foot 1.15.3

**Comment by kojq** [comment]
It is like this most of the time:

![image](https://github.com/fastfetch-cli/fastfetch/assets/106934605/5e760a2d-7913-4931-91ea-895ccb648303)


However, it is like this on rare occasion:

![image](https://github.com/fastfetch-cli/fastfetch/assets/106934605/95118ad4-139e-4684-97aa-4c40a7a14c35)

**Comment by CarterLi** [comment]
Please put this line before running fastfetch and make a screenshot again

```shell
echo -e "\e[?7lThis should not be trancated at middle! This should not be trancated at middle! This should not be trancated at middle! This should not be trancated at middle! This should not be trancated at middle! This should not be trancated at middle!\e[?7h"
```

Also you may try `fastfetch --disable-linewrap false` and see if it makes a difference

**Comment by kojq** [comment]
![image](https://github.com/fastfetch-cli/fastfetch/assets/106934605/99e13bbc-dca1-4a8a-897e-78b1116c9cd1)

With `fastfetch --disable-linewrap false`:

![image](https://github.com/fastfetch-cli/fastfetch/assets/106934605/8b0ed072-28b0-46e9-b028-90c2c82020c4)

**Comment by CarterLi** [comment]
> ![image](https://user-images.githubusercontent.com/106934605/280200861-99e13bbc-dca1-4a8a-897e-78b1116c9cd1.png)
> 

This can confirm a terminal bug. You may report it to the author of foot.

**Comment by kojq** [comment]
Closing.

**Comment by kojq** [comment]
https://codeberg.org/dnkl/foot/issues/1541
