### ISSUE TITLE
Error JsonConfig Error: Property `display.percentX` has been changed to `display.percent.x`

### ISSUE THREAD

**Issue by manhhieu2909** [fastfetch-cli/fastfetch#606]
I use the following code in the zshrc config file to launch fastfetch. 
`if [[ -o interactive ]]; then
    fastfetch --load-config examples/11.jsonc
fi`
After updating version 2.2.0, I encountered an error. 
`JsonConfig Error: Property `display.percentX` has been changed to `display.percent.x`
`
Can someone help me fix the error?

**Comment by CarterLi** [comment]
Oops, I forgot to change the presets

A hot fix release will be cut in a few days if no other issues found. But before that, you have to modify the file manually. `:%s/"percentType": 9/"percent": { "type": 9 }/g` in vim should work
