### ISSUE TITLE
--allow-slow-operations no longer works.

### ISSUE THREAD

**Issue by Samueru-sama** [fastfetch-cli/fastfetch#610]
OS: Arch Linux
Source: Fastfetch from the Aur. 

I have a polybar script that uses fastfetch with the--allow-slow-operations variable to get the gpu vram usage, after updating fastfetch it no longer works with error: unknown option: --allow-slow-operations

I also tested removing option just in case now fastfetch doesn't need it and that didn't work either, it results with missing info from the scripts output.

Downgrading to version 2.1.2 fixes the issue.

**Comment by CarterLi** [comment]
--allow-slow-operations was replaced by several other flags. See release note of 2.2.0

**Comment by Samueru-sama** [comment]
> --allow-slow-operations was replaced by several other flags. See release note of 2.2.0
> 
> Note that used vram detection using --gpu-force-vulkan was also removed, due to incorrect results. Instead, we added used vram detection for NVIDIA cards with --gpu-use-nvml. Other type of graphic cards are not supported yet.

Well I guess I will stick with the older version in the meantime since I have an amd gpu.

**Comment by CarterLi** [comment]
Alright. However, vmem usage is significantly smaller than what GPU driver reports, at least for NV cards.

**Comment by Samueru-sama** [comment]
> Alright. However, vmem usage is significantly smaller than what GPU driver reports, at least for NV cards.

Not an issue with AMD, if anything the vram usage is slightly higher than what mangohub reports (5.1 vs 5.33 GiB). 

![image](https://github.com/fastfetch-cli/fastfetch/assets/36420837/3838263e-d408-4d65-a7a5-411e1408115c)
