### ISSUE TITLE
IP local address show by default?

### ISSUE THREAD

**Issue by DoTheEvo** [fastfetch-cli/fastfetch#611]
There is probably some reason why others also dont show it by default
but I feel like its one of the major info you want

but at least in neofetch all I have to do is uncomment one line `info "Local IP" local_ip`
while it seems more hands on with fastfetch
seems like I would have to redo the defaul json to just have it there, not sure

**Comment by CarterLi** [comment]
It's explictly forbidden by the project author @LinusDierheimer. See https://github.com/fastfetch-cli/fastfetch/pull/92#discussion_r730408469

> seems like I would have to redo the defaul json to just have it there, not sure

What do you mean *redo*? You can either generate the default json file with `fastfetch --migrate-config` and add `localip` into it, or copy / download the [`presets/all.json`](https://github.com/fastfetch-cli/fastfetch/tree/dev/presets) and disable things you don't need.

**Comment by LinusDierheimer** [comment]
> It's explictly forbidden by the project author @LinusDierheimer. See https://github.com/fastfetch-cli/fastfetch/pull/92#discussion_r730408469

I think i mixed up public and local IP there. @CarterLi Do as you think.

**Comment by DoTheEvo** [comment]
Awesome, thanks!

I use fastfetch when posting submissions on /r/homeserver about power consumption, [like this one](https://www.reddit.com/r/HomeServer/comments/16ys32a/guess_the_power_consumption_of_ryzen57600x/) and I love that it works it works in windows and linux the same.

**Comment by CarterLi** [comment]
Which fastfetch version were you using? `(Default string)` printed in `Host` module was unexpected. Really strange...

**Comment by realroot2185** [comment]
When I use it from SSH it shows public ip instead of local ip.

And sorry to say this but showing local ip and locale by default does not look a sane default.

**Comment by realroot2185** [comment]
Right I was one of those person, it's local ip sorry.
