### ISSUE TITLE
[CI] Install ImageMagick 7 alongside ImageMagick 6

### ISSUE THREAD

**Issue by Mukul1127** [fastfetch-cli/fastfetch#612]
# Current state:
Ubuntu Repos only package ImageMagick 6 thus not allowing distros like Fedora with updated ImageMagick 7 to use sixel or kitty graphics protocol.

# Wanted state:
We use Homebrew to install imagemagick 7 alongside 6 on the CI so builds will have ImageMagick 7 support.
[formulae.brew.sh/formula/imagemagick](https://formulae.brew.sh/formula/imagemagick#default)

# Why the change is sensible:
Seems like a Win Win as older distros will still have ImageMagick 6 support while newer distros will now have ImageMagick 7 support.

**Comment by CarterLi** [comment]
Builds of linuxbrew has glibc version issues, and seems can only load so libraries of linuxbrew packages themselves.

See: https://github.com/fastfetch-cli/fastfetch/issues/476

**Comment by CarterLi** [comment]
Done
