### ISSUE TITLE
Could you please put it on Ubuntu apt repository,  or drop the following script somewhere

### ISSUE THREAD

**Issue by AwesomeDog** [fastfetch-cli/fastfetch#619]
# Current state:

Fastfetch has brought up many conveniences to me, I want it on all my machines.

# Wanted state:

So could you please put it on Ubuntu apt repository,  or drop the following script somewhere

install.sh
```shell
sudo apt install jq

project_name="fastfetch-cli/fastfetch"

tag_name="`wget -qO- -t1 -T2 "https://api.github.com/repos/${project_name}/releases/latest" | jq -r '.tag_name'`"
release_name="`wget -qO- -t1 -T2 "https://api.github.com/repos/${project_name}/releases/latest" | jq -r '.assets[].name' | grep ".deb"`"
release_url="https://github.com/${project_name}/releases/download/${tag_name}/${release_name}"

wget -c ${release_url} -q --show-progress
sudo dpkg -i ${release_name}

rm ${release_name}
```

# Why the change is sensible:

so that I can install on every instance of Ubuntu via a simple command:

```
curl https://raw.githubusercontent.com/fastfetch-cli/fastfetch/master/install.sh | bash
```

**Comment by CarterLi** [comment]
> Could you please put it on Ubuntu apt repository

See #533. There's nothing I can do.

> drop the following script somewhere

[Github Gist](https://gist.github.com/) is your friend.

**Comment by CarterLi** [comment]
Alternatively, linuxbrew works fine for me.
