### ISSUE TITLE
Shows wrong uptime & swap in LXC-container

### ISSUE THREAD

**Issue by borestad** [fastfetch-cli/fastfetch#620]
Hi!

FYI:
Inside an lxc-container (almalinux) with proxmox 8.04, it shows the parent (proxmox) uptime & swap, not the container stats.

**Comment by CarterLi** [comment]
Since it's a container, shouldn't these stats be contained too? Fastfetch doesn't try to query the stats of its parent.

What does neofetch print?

CC @LinusDierheimer

**Comment by borestad** [comment]
Hi! :)

neofetch prints the correct uptime & swap
