### ISSUE TITLE
The packages section still shows the number of flatpak packages installed, even after uninstalling all flatpaks (and even flatpak entirely)

### ISSUE THREAD

**Issue by pearmypie** [fastfetch-cli/fastfetch#621]
I'm using 2.2.3, upgraded from a previous version. I tried uninstalling and reinstalling.
I'm using Debian Testing.

**Comment by CarterLi** [comment]
fastfetch searchs for installed app folders directly. This issue could happen if you uninstalled flatpak but didn't remove the app folders.

Try removing `/var/lib/flatpak` and `~/.local/share/flatpak`

**Comment by pearmypie** [comment]
Thank you, I didn't consider that.
