### ISSUE TITLE
Output Blank on Windows Server Core

### ISSUE THREAD

**Issue by DanAE111** [fastfetch-cli/fastfetch#623]
# General description of bug:

* What happened: Running fastfetch.exe produced no output.
* What should happen: Output should be written to the console when runnig fastfetch.exe
* Did it work in an older version: N/A
* Where did you get the binary: Github Release
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Unsure

# Often helpful information:

Output of `fastfetch --list-features`:
```
//None
```

**Comment by CarterLi** [comment]
I guess it's because Windows Server Core lacks some system dlls required by fastfetch, so fastfetch crashes at start. Although fastfetch is a CLI program, it does require some dlls to fetch desktop / GUI related information

**Comment by CarterLi** [comment]
Please check if these dlls exist in `C:\Windows\System32`

```
    bthprops.cpl
    dwmapi.dll
    GDI32.dll
    IPHLPAPI.DLL
    ole32.dll
    OLEAUT32.dll
    OPENGL32.dll
    WS2_32.dll
    ntdll.dll
    VERSION.dll
    SETUPAPI.dll
    HID.DLL
    WTSAPI32.dll
    dxva2.dll
    KERNEL32.dll
    USER32.dll
    SHELL32.dll
    ADVAPI32.dll
    ucrtbase.dll
```

**Comment by CarterLi** [comment]
We now have full support for Windows Server 2022 Core edition

![image](https://github.com/fastfetch-cli/fastfetch/assets/6134068/5072876c-92b1-48bf-bada-2025c1b071bf)
