### ISSUE TITLE
First Arrange Logo Not Displayed

### ISSUE THREAD

**Issue by firu82** [fastfetch-cli/fastfetch#635]
Hello I've completed the code on cmake in a Asustor nas and everything perfect The problem is that at the first start everything goes out of phase to the left and you can't see the logo Then when you run it again it looks perfect What is the problem?

**Comment by firu82** [comment]
Hello I've completed the code on cmake in a scary nas and everything perfect The problem is that at the first start everything goes out of phase to the left and you can't see the logo Then when you run it again it looks perfect What is the problem?

**Comment by CarterLi** [comment]
I don't understand what you mean, but it seems the issue disappear. Please report it ( and filling the issue template ) if it happens again
