### ISSUE TITLE
Handling pipe timeout is incorrect

### ISSUE THREAD

**Issue by apocelipes** [fastfetch-cli/fastfetch#639]
As argued in #638 , set `O_NONBLOCK` at a pipe which will be dupped to stdout/stderr is unsafe, and has some potential problems. 

Since the code only handle pipes, we can safely use blocking-pipes with `poll` -- There is only one reader, so it couldn't happen that the fd is ready and there is no data to read. (e.g. read by another reader or reported as ready like a socket because of protocol notifications, etc.)

The correct way to do timeout is insteading of using non-blocking io, to use a big enough buff (as big as the buffer inside the pipe) to read data from pipes, and call `poll` again no matter how much data is read. When `read` returns EOF or error, break out the loop. A big enough buffer is to reduce `read` calls, a 4096 length buffer works too but may be encounter some performance impacts.

`O_NONBLOCK` problems should be fixed.

Additionally pipe needs to set the O_CLOEXEC flag for the most important reason, besides performance and preventing file descriptor leaks, for security. We have no control over the external programs that are called, so it is important to minimize the amount of information that is exposed.

**Comment by CarterLi** [comment]
> Additionally pipe needs to set the O_CLOEXEC flag for the most important reason, besides performance and preventing file descriptor leaks, for security.

[They were closed](https://github.com/fastfetch-cli/fastfetch/blob/dev/src/common/processing_linux.c#L40-L41). However, you are right, `O_CLOEXEC` is a better option. In addition, we should check every `open(2)` syscall to have `O_CLOEXEC` used.

> `O_NONBLOCK` problems should be fixed.

[If timeout is not enabled, `O_NONBLOCK` won't be used.](https://github.com/fastfetch-cli/fastfetch/blob/dev/src/common/processing_linux.c#L52-L54) I don't see any problems here.

**Comment by apocelipes** [comment]
> [If timeout is not enabled, `O_NONBLOCK` won't be used.](https://github.com/fastfetch-cli/fastfetch/blob/dev/src/common/processing_linux.c#L52-L54) I don't see any problems here.

If timeout set, fcntl will also change child process's pipe flags, this can be privode by this:

```c
#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>

int main()
{
        int fds[2] = {-1, -1};
        pipe(fds);
        int pid = fork();
        if (pid) {
                usleep(10000000);
                printf("before: %d\n", fcntl(fds[1], F_GETFL));
                fcntl(fds[1], F_SETFL, fcntl(fds[1], F_GETFL) | O_NONBLOCK);
                printf("after: %d\n", fcntl(fds[1], F_GETFL));
                waitpid(pid, NULL, 0);
        } else {
                while(1) {
                dup2(fds[1], 0);
                printf("child: %d\n", fcntl(0, F_GETFL));
                usleep(1000000);
                }
        }
}
```

![image](https://github.com/fastfetch-cli/fastfetch/assets/21255940/b74a9889-2bfb-46d7-a020-4652d144eb37)

**Comment by apocelipes** [comment]
As the output, even after dupped, the flags also been changed.

Since two process share the same pipes, it might be a correct behavior, but i cannot found documents that doucmented this.

A more serious problem, we can't control whether `fcntl` is executed before or after `exec`, and there might be a problem if it is executed after `exec`.

**Comment by CarterLi** [comment]
I didnt get it. Please speak Chinese

**Comment by apocelipes** [comment]
使用`fcntl`给父进程的pipefd添加non-block标志，子进程里的pipe一样会被影响，被添加上non-block，即使已经使用dup进行重定向。

所以设置timeout后execve调用的进程一样有概率遇到EAGAIN的错误。

以及fork不保证父子进程运行顺序，因此很可能父进程fcntl添加non-block会发生在子进程execve之后，这很可能会意外影响被execve调用的程序的行为。

**Comment by apocelipes** [comment]
解决上面问题的办法有两个：
1. fork之前添加non-block，子进程里再把non-block去除
2. 使用issue的方案，不使用非阻塞io

方案1不够简洁而且预想了第三方程序会如何处理输出；方案2本地环境测试几乎没有性能影响，能在不关心第三方程序怎么处理输出的同时解决fcntl跨进程产生影响以及fcntl和execve的时序问题。

**Comment by CarterLi** [comment]
* In parent, we add O_NONBLOCK to pipes[0]
* In child, we dup pipes[1] to stdout, while pipes[0] is closed directly

Why is it a problem?

**Comment by CarterLi** [comment]
If fcntl is called before closing, the fd will be closed. If fcntl is called after closing, it just do nothing. Why unsafe?

It is about 1 am, lets stop arguing and go to bed.

**Comment by apocelipes** [comment]
> If fcntl is called before closing, the fd will be closed. If fcntl is called after closing, it just do nothing. Why unsafe?

First, the situation where a process is unaware that its own data can be modified by other processes is inherently insecure.
Second, fcntl on a closed fd is not  a nop, the call will failed and errno set to EBADF, errno will be contaminated.

In my timezone it is 2am, i will push a PR for this issue. Good night and we'll continue tomorrow.

**Comment by apocelipes** [comment]
Close this since #640 has been merged.
Checking other `open` calls and adding necessary `O_CLOEXEC` flag should be another issue.
If any bug or performance regression caused by #640 is found, please reopen this issue.
