### ISSUE TITLE
Incorrect display resolution after scaling on wayland

### ISSUE THREAD

**Issue by spikespaz** [fastfetch-cli/fastfetch#650]
I apologize for removing the issue template. I read through it and most parts are irrelevant.

The only thing missing from fastfetch's output is the version of fastfetch itself: `2.2.3`.

I have not (and will not) updated fastfetch as Nixpkgs always lags behind releases for this repo. You're very quick, and Nixpkgs is slow.

I use no configuration for fastfetch. The output of the command `fastfetch | wl-copy`:

```
jacob@odyssey
-------------
OS: NixOS 23.11.20231117.c757e9b (Tapir) x86_64
Host: 21K5001JUS (ThinkPad P14s Gen 4)
Kernel: 6.5.11
Uptime: 13 hours, 40 mins
Packages: 1146 (nix-system), 1641 (nix-user)
Shell: zsh 5.9
Display (GP01): 2560x1440 @ 165Hz
Display (ARZOPA): 1920x1080 @ 60Hz
Display (SDC4193): 2880x1800 @ 90Hz (as 1440x900) [Built-in]
WM: Hyprland (Wayland)
Theme: Materia-dark-compact [GTK2/3/4]
Icons: Papirus-Dark [GTK2/3/4]
Font: Ubuntu [GTK2/3/4]
Cursor: Quintom_Ink (24px)
Terminal: alacritty 0.13.0-dev
Terminal Font: alacritty (11pt)
CPU: AMD Ryzen 7 PRO 7840U w/ Radeon 780M Graphics (16) @ 5.13 GHz
GPU: AMD Phoenix1
Memory: 11.48 GiB / 61.52 GiB (19%)
Swap: 0 B / 63.53 GiB (0%)
Disk (/): 35.50 MiB / 546.14 GiB (0%) - zfs
Local IP (wlan0): 192.168.4.65/22 *
Battery: 100% [Full]
Locale: en_US.UTF-8
```

The issue here is the built-in display, which reports it is running in 1440x900 mode.

I use Hyprland on Wayland, and my config for the monitors looks like this:

```
monitor = DP-5,2560x1440@165,1600x0,1.000000,bitdepth,10,transform,0
monitor = HDMI-A-1,preferred,3840x1440,1.000000,bitdepth,8,transform,0
monitor = eDP-1,2880x1800@90,1920x1440,1.500000,bitdepth,10,transform,0
monitor = DP-6,1920x1080,0x1440,1.000000,bitdepth,10,transform,0
monitor = , preferred, auto, 1
```

As you can see, the "built-in" display is native `2880x1800`, and scale is `1.5`.

```
2880 / 1.5 = 1920
1800 / 1.5 = 1200
```

So, fastfetch should say for that line:
```
Display (SDC4193): 2880x1800 @ 90Hz (as 1920x1080) [Built-in]
```

**Comment by CarterLi** [comment]
It's a known limitation of fastfetch. We haven't found a way to detecting fractional scale factor, and it seems to be impossible to do in a CLI program.

Previous try: https://github.com/fastfetch-cli/fastfetch/pull/564

If you don't want the incorrect information displayed, you may use this flag `--display-format '{1}x{2} @ {3}Hz {?7}[{7}]{?}'`

**Comment by spikespaz** [comment]
Why is incorrect information displayed at all?

**Comment by CarterLi** [comment]
Integral scaling is supported, and fastfetch doesn't know if fractional scaling is enabled because the detection method that fastfetch uses always reports integral values.

We decided to report it because we thought fractional scaling wasn't widely used. Actually we have report the scaled resolution for about one year and you are the first person reports this issue.

If we get more complains, we will disable it.

**Comment by theofficialgman** [comment]
I would like it disabled as well
