### ISSUE TITLE
Show version number for the Desktop Environment (DE)

### ISSUE THREAD

**Issue by sid-the-sloth** [fastfetch-cli/fastfetch#655]
# Current state:
DE: Xfce4
WM: Xfwm4 (X11)

# Wanted state:
DE: Xfce4 4.18
WM: Xfwm4 4.18 (X11)

# Why the change is sensible:
`fastfetch` is all about showing details and versions for software and hardware.
BTW: `neofetch` shows the XFCE version...
It's easy to find with: `xfwm4 --version` and also `xfdesktop --version`.

Thank you! We appreciate your work!

**Comment by CarterLi** [comment]
Can you try `--de-slow-version-detection`?
