### ISSUE TITLE
No transparent background in sixel

### ISSUE THREAD

**Issue by niksingh710** [fastfetch-cli/fastfetch#656]
# General description of bug:

* What happened: if using sixel to show image then it is rendering a black background instead of transparent one
* What should happen: should render a transparent background
* Where did you get the binary:  Arch linux (Aur)

![image](https://github.com/fastfetch-cli/fastfetch/assets/60490474/689d3828-b032-406d-84f0-51ffed574da0)
in the image the first one is with `--logo` that is using symbols.

I can confirm that rendering sixel using chafa renders transparent background in terminal but in fastfetch it renders black bg.

**Comment by CarterLi** [comment]
[sixel doesn't seem to support transparent pixels](https://github.com/saitoha/libsixel/issues/149). There are opening PRs in the fork repo but never got merged.

<img width="970" alt="image" src="https://github.com/fastfetch-cli/fastfetch/assets/6134068/d4640f22-d928-4749-b990-226ad11c855a">

You should try other image protocols

**Comment by niksingh710** [comment]
don't know why but for me 
![image](https://github.com/fastfetch-cli/fastfetch/assets/60490474/05252a8c-8aa7-4eee-9bce-904c71ed8fb7)
if using chafa with sixel the bg is transparent. terminal i am using is foot and tmux as multiplexer and Arch linux is the distro.

**Comment by CarterLi** [comment]
Try changing the terminal background now?

**Comment by niksingh710** [comment]
@CarterLi 
![image](https://github.com/fastfetch-cli/fastfetch/assets/60490474/8bfb4124-1dcb-45db-81d9-51d6c4ba8fa6)

**Comment by CarterLi** [comment]
Please paste the result of `chafa -f sixels out.png > out.sixel` here

**Comment by niksingh710** [comment]
> ~Please paste the result of `chafa -f sixels out.png > out.sixel` here~
> 
> I can confirm the behavior with foot, but not konsole and iterm...

yep maybe the foot implementation of sixel includes patches for the bg transparency.
i am just unsure why fastfetch is rendering background is there any way that can be avoided?

**Comment by CarterLi** [comment]
Chafa uses its own sixel image convertion implementation, while fastfetch uses imagemagick. Imagemagick doesn't support transparent background for sixel and simply convert transparent pixels to black.

It's possible for fastfetch to use chafa for sixel image generation, but it seems that a lot of terminals don't support transparent backgrounds for sixel image and render a weird bg color. I think it's not the time of switching.

It's still possible to use transparent background logos:

```bash
$ chafa -s WxH out.png > out.sixel
$ fastfetch --raw out.sixel --logo-width W --logo-height H --logo-padding-top 2 # There is a bug that makes fastfetch crash if --logo-padding-top is not set
```

<img width="954" alt="image" src="https://github.com/fastfetch-cli/fastfetch/assets/6134068/f446b59d-eb95-4d8f-b6e8-1310b6292c08">

**Comment by niksingh710** [comment]
this hack works......

**Comment by nyawox** [comment]
btw, TIL you can generate sixel with higher quality than chafa using [notcurses](https://github.com/dankamongmen/notcurses)
`ncplayer -s hires -q -k distrologo.png > distrologo.sixel`

**Comment by emilrueh** [comment]
no matter what I do. the command `$ fastfetch --raw out.sixel --logo-width W --logo-height H --logo-padding-top 2 # There is a bug that makes fastfetch crash if --logo-padding-top is not set` does set the logo and it is in-fact transparent but alway in a size that essentially covers the entire terminal.

Neither setting the width and height in the command, nor in the config changes anything about it.

Also changing the image size to something smaller and re-running it through chafa changes anything, except for it now being massive and in rendered in terrible resolution.

**Comment by Bloody-Omen** [comment]
> no matter what I do. the command `$ fastfetch --raw out.sixel --logo-width W --logo-height H --logo-padding-top 2 # There is a bug that makes fastfetch crash if --logo-padding-top is not set` does set the logo and it is in-fact transparent but alway in a size that essentially covers the entire terminal.
> 
> Neither setting the width and height in the command, nor in the config changes anything about it.
> 
> Also changing the image size to something smaller and re-running it through chafa changes anything, except for it now being massive and in rendered in terrible resolution.

did you find any solution for it later on? having the same issue

**Comment by emilrueh** [comment]
I don't think I have and just went with ascii instead :)

**Comment by j4james** [comment]
If you're using `--raw out.sixel`, note that the size of the image is controlled entirely by the tool that created that `out.sixel` file. For example `chafa -f sixel -s 40x20 out.png > out.sixel` should create an image no wider than 40 columns, and no taller than 20 rows. If you leave off the `> out.sixel` you can see exactly what it's going to look like before trying to integrate it in `fastfetch`.

Once you've got `chafa` producing the image at the right size, you'll also then need to pass the image dimensions to `fastfetch` so it can correctly position the text relative to that image. For example, if your image is exactly 40x20, then you'd use something like `fastfetch --raw out.sixel --logo-width 40 --logo-height 20`.

However, be aware that the image produced by `chafa` may not exactly match the dimensions you requested in the `-s` parameter, since it tries to to maintain the aspect ratio. So you may still need to tweak the `--logo-width` and `--logo-height` parameters if the text ends up in the wrong place.

If you can't even get `chafa` to produce an image at the right size, then that's not a `fastfetch` problem. That may be an issue with your terminal or OS. Also make sure you're using the most recent version of `chafa`.

**Comment by Bloody-Omen** [comment]
> If you're using `--raw out.sixel`, note that the size of the image is controlled entirely by the tool that created that `out.sixel` file. For example `chafa -f sixel -s 40x20 out.png > out.sixel` should create an image no wider than 40 columns, and no taller than 20 rows. If you leave off the `> out.sixel` you can see exactly what it's going to look like before trying to integrate it in `fastfetch`.
> 
> Once you've got `chafa` producing the image at the right size, you'll also then need to pass the image dimensions to `fastfetch` so it can correctly position the text relative to that image. For example, if your image is exactly 40x20, then you'd use something like `fastfetch --raw out.sixel --logo-width 40 --logo-height 20`.
> 
> However, be aware that the image produced by `chafa` may not exactly match the dimensions you requested in the `-s` parameter, since it tries to to maintain the aspect ratio. So you may still need to tweak the `--logo-width` and `--logo-height` parameters if the text ends up in the wrong place.
> 
> If you can't even get `chafa` to produce an image at the right size, then that's not a `fastfetch` problem. That may be an issue with your terminal or OS. Also make sure you're using the most recent version of `chafa`.

oh i did try all of it. im not blaming fastfetch its a `chafa` issue for sure. I posted one there.

![Image](https://github.com/user-attachments/assets/0ff8496c-da9c-4fc0-9990-fc4950971bc4)

I'm pretty fine with what I have. hopefully someone might have a better solution.

**Comment by Bloody-Omen** [comment]
> [@Bloody-Omen](https://github.com/Bloody-Omen) Note that if you're using Windows Terminal, you need version 1.22 or later for sixel support. You also must use the `-f sixel` parameter with `chafa`, because it doesn't autodetect sixel otherwise. If you're getting an ASCII art rendition like the one in your screenshot above, that suggests you haven't set the `-f sixel` parameter (if you had set it, and the terminal didn't support sixel, you'd see no output at all, or possible a bunch of random characters).

im a dumbass. I was so tired customizing it and doing other things at the same time. I missed the the obvious command you wrote there. thanks man you're genius.
