### ISSUE TITLE
[BUG] Fastfetch displays Btrfs subvolumes as partitions.

### ISSUE THREAD

**Issue by Samueru-sama** [fastfetch-cli/fastfetch#674]
![image](https://github.com/fastfetch-cli/fastfetch/assets/36420837/f7742c02-cdbd-43e4-a4a4-35dc659d3fab)

fstab: 
![image](https://github.com/fastfetch-cli/fastfetch/assets/36420837/54d2af0c-411b-4727-ae27-b03e811a94af)

Worth mentioning that this only happens with Artix, I had this issue with Arch before, reported it and got fixed. No idea if I'm missing a dependency or it is just the lack of systemd. 

Tried both fastfetch from the extra repo and fastfetch-git from the aur.

**Comment by CarterLi** [comment]
Please paste the comtent of /proc/mounts here

**Comment by Samueru-sama** [comment]
> Please paste the comtent of /proc/mounts here

```
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
sys /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
dev /dev devtmpfs rw,nosuid,noexec,relatime,size=10240k,nr_inodes=2032819,mode=755,inode64 0 0
run /run tmpfs rw,nosuid,nodev,relatime,mode=755,inode64 0 0
efivarfs /sys/firmware/efi/efivars efivarfs rw,nosuid,nodev,noexec,relatime 0 0
/dev/sda2 / btrfs rw,noatime,compress-force=zstd:1,ssd,discard=async,space_cache=v2,subvolid=256,subvol=/@ 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,nosuid,nodev,noexec,relatime 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
configfs /sys/kernel/config configfs rw,nosuid,nodev,noexec,relatime 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
shm /dev/shm tmpfs rw,nosuid,nodev,noexec,relatime,inode64 0 0
none /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,nosuid,nodev,noexec,relatime 0 0
/dev/sda1 /boot/efi vfat rw,noatime,fmask=0077,dmask=0077,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro 0 0
/dev/sda2 /home btrfs rw,noatime,compress-force=zstd:1,ssd,discard=async,space_cache=v2,subvolid=257,subvol=/@home 0 0
/dev/sda2 /var/cache btrfs rw,noatime,compress-force=zstd:1,ssd,discard=async,space_cache=v2,subvolid=258,subvol=/@cache 0 0
/dev/sda2 /var/log btrfs rw,noatime,compress-force=zstd:1,ssd,discard=async,space_cache=v2,subvolid=259,subvol=/@log 0 0
tmpfs /tmp tmpfs rw,nosuid,nodev,noatime,size=4194304k,inode64 0 0
/dev/nvme0n1p3 /mnt/MEDIA btrfs rw,nosuid,nodev,noatime,compress-force=zstd:1,ssd,discard=async,space_cache=v2,subvolid=5,subvol=/ 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=1627640k,nr_inodes=406910,mode=700,uid=1000,gid=1001,inode64 0 0
portal /run/user/1000/doc fuse.portal rw,nosuid,nodev,relatime,user_id=1000,group_id=1001 0 0
gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1001 0 0

```

**Comment by CarterLi** [comment]
Should be fixed in the dev branch.

BTW did you install the system in an external device? A usb drive or some thing?

**Comment by Samueru-sama** [comment]
> Should be fixed in the dev branch.
> 
> BTW did you install the system in an external device? A usb drive or some thing?

I can confirm that it works now, that was quite fast! 

![image](https://github.com/fastfetch-cli/fastfetch/assets/36420837/f3088298-2cad-4c84-b4a1-3ac03ab14e22)

Artix was installed on the adata sata ssd you see in the pic, to a 20GiB partition.

**Comment by CarterLi** [comment]
Can you try the latest dev branch and paste the result of `fastfetch -c all --format json` here?

**Comment by Samueru-sama** [comment]
> Can you try the latest dev branch and paste the result of `fastfetch -c all --format json` here?

I updated fastfetch and the issue is gone, I should have tested it before updating my bad. 

![image](https://github.com/fastfetch-cli/fastfetch/assets/36420837/37f5f3eb-7d3a-4a24-8487-d3193dba76e0)

Either way here is the output of `fastfetch -c all --format json` just in case

https://pastebin.com/R5hBzNQ8
