### ISSUE TITLE
[BUG] Custom logo does not seem to be working

### ISSUE THREAD

**Issue by oresttokovenko** [fastfetch-cli/fastfetch#685]
# General description of bug:

* What happened:
Basically if I call `fastfetch --logo ~/file/path`, it doesn't output the logo in ASCII. I also created a config.jsonc to see if different image interpreters would help, as well as different file types (jpg, png) but none of them output anything. I'm trying to use my company logo as my custom image but for the purpose of this issue I'm using Meta's logo

<img width="715" alt="Screenshot 2024-01-16 at 08 38 52" src="https://github.com/fastfetch-cli/fastfetch/assets/51058259/b5f24216-1ce5-4652-b21e-eb82c8583ef5">

* What should happen:

A custom logo should be printed

* Did it work in an older version: 

I'm not sure, I'm using `fastfetch 2.5.0 (aarch64)`

* Where did you get the binary: 

via Homebrew

# Often helpful information:

The content of the configuration file you use (if any)

I tried both variants

```
fastfetch --logo ~/Downloads/logo-Meta.png
```

```
{
  "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
  "logo": {
      "type": "iterm",
      "source": "~/.config/fastfetch/logo-Meta.png"
      // "width": 28,
      // "height": 12
  },
  "modules": [
    {
      "type": "custom",
      "key": "┌──────────── Test ────────────┐",
      "keyColor": "blue",
      "format": " "
      // "separator": " "
    },
    "break",
    "os",
    "uptime",
    "host",
    "packages",
    "shell",
    "display",
    "terminalfont",
    "cpu",
    "break",
    "colors",
    "break",
    "break",
    "break",
    "break"
  ]
}

```

## If my image logo didn't show / work

* The image protocol you used: Auto, and then every one explicitly to test
* The terminal you used: Alacritty
* Upload the image file here, or paste the image URL: https://1000logos.net/wp-content/uploads/2021/10/logo-Meta.png
* Does it work with `--logo-width {WIDTH} --logo-height {HEIGHT}`? No

**Comment by CarterLi** [comment]
Alacritty doesnt seem to support any image protocols.

https://github.com/alacritty/alacritty/issues/910

You may try other terminals

**Comment by oresttokovenko** [comment]
@CarterLi thank you for the quick response! I tried iTerm2, same thing:

<img width="652" alt="Screenshot 2024-01-16 at 09 12 16" src="https://github.com/fastfetch-cli/fastfetch/assets/51058259/ffb819e7-1ae4-43ab-b42c-7dbad2a3c64f">

**Comment by CarterLi** [comment]
Please try change --logo to --iterm

**Comment by oresttokovenko** [comment]
> Please try change --logo to --iterm

That works on iterm2! Thank you very much! If I want to convert a png to ASCII to have it run in Alacritty (due to lack of image protocols) how would my config.jsonc look like? What file type would I be pointing to?

**Comment by CarterLi** [comment]
You may use [--chafa](https://github.com/fastfetch-cli/fastfetch/wiki/Logo-options#chafa)
