### ISSUE TITLE
[FEAT] Winget installation

### ISSUE THREAD

**Issue by JGMelon22** [fastfetch-cli/fastfetch#693]
# Current state:
Currently it is only possible to officially install on Windows trough the zip files here in GitHub and manually setting up ambient variables

# Wanted state:
Include the project at Winget repository to easily install trough package manager and updates

# Why the change is sensible:
Easy to upgrade and install, Plus feels like a Linux experience on Windows (as a power user perspective)

**Comment by CarterLi** [comment]
See https://github.com/microsoft/winget-pkgs/pull/94697

You may use scoop
