### ISSUE TITLE
[FEAT] Upload to winget

### ISSUE THREAD

**Issue by Gauley123** [fastfetch-cli/fastfetch#703]
# Current state:
fastfetch is not on winget, a manual install is required
# Wanted state:
The possibility to use `winget install fastfetch` to install it
# Why the change is sensible:
Winget is built-in to recent versions of windows unlike scoop

**Comment by CarterLi** [comment]
See https://github.com/microsoft/winget-pkgs/pull/94697

Give it a +1 to support us
