### ISSUE TITLE
arm64

### ISSUE THREAD

**Issue by KellieOwczarczak** [fastfetch-cli/fastfetch#708]
# Current state: cannot install fastfetch-2.7.1-Linux.deb on arm64 architecture. package architecture (amd64) does not match system (arm64)

# Wanted state: arm64 compatibility

# Why the change is sensible: I figure that it seems most people are stuck with some Debian based distro on arm based devices that are not RPi. At least on RPi, I can install Fedora and then use fastfetch, but my NanoPi unit only works with Debian or Ubuntu. Same goes for Jetson devices.

**Comment by CarterLi** [comment]
You may download it here: https://github.com/fastfetch-cli/fastfetch/actions/runs/7738007836

**Comment by Makeshift** [comment]
That's good timing, I just came here to check if there was ARM64 support! Is there plans to add the additional architectures to GitHub releases?

**Comment by CarterLi** [comment]
aarch64 support will be added to GitHub releases. Other arches can be added too if someone can test them on real hardware.
