### ISSUE TITLE
[BUG] fastfetch shows different battery states when on Ubuntu WSL vs Windows

### ISSUE THREAD

**Issue by ykhan21** [fastfetch-cli/fastfetch#711]
# General description of bug:

* What happened: Battery on WSL says Not charging. Battery on Windows says AC Connected.
* What should happen: The Battery for both should say charging.
* Did it work in an older version: 
* Where did you get the binary: WSL: `dpkg` installed the latest fastfetch. Windows: `scoop` installed the latest fastfetch.
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Will check if necessary.

# Often helpful information:

Screenshot:
WSL Ubuntu (see Battery state):
![image](https://github.com/fastfetch-cli/fastfetch/assets/51864191/2a90521a-7131-4f05-92a6-5793fd4dff61)

Windows (see Battery state):
![image](https://github.com/fastfetch-cli/fastfetch/assets/51864191/ab424ce7-9e33-4dbe-a58a-236e4906643b)

The content of the configuration file you use (if any):
(none)

Output of `fastfetch -c ci.jsonc --format json`:
(Will add if required.)

Output of `fastfetch --list-features`:
WSL:
```
threads
libpci
vulkan
wayland
xcb-randr
xcb
xrandr
x11
drm
gio
dconf
dbus
imagemagick7
imagemagick6
zlib
xfconf
sqlite3
egl
glx
osmesa
opencl
libpulse
libnm
libddcutil
Directx Headers
Proprietary GPU driver API
```
Windows:
```
threads
vulkan
zlib
opencl
Proprietary GPU driver API
```

## If fastfatch crashed

Paste the stacktrace here. You may get it with:

```
$ gdb /path/to/fastfetch
$ run
$ bt
```

If you are able to identify which module crashed, the strace can be helpful too

```
$ strace /path/to/fastfetch --multithreading false --structure {MODULE} --pipe
```

If you cannot do the instructions above, please upload the core dump file:

## If my image logo didn't show / work

* The image protocol you used: 
* The terminal you used: 
* Upload the image file here, or paste the image URL: 
* Does it work with `--logo-width {WIDTH} --logo-height {HEIGHT}`? 

## If fastfetch behaves incorrectly on shell starting

* The bug is reproduceable with fresh / clean shell configuration (i.e. `fastfetch` is the single line of `.zshrc` or `~/.config/fish/config.fish`): 
* Does `sleep 1` before running `fastfetch` work?

**Comment by CarterLi** [comment]
AC connected and Not charging both means that your battery is not charging. How can you be sure it's charging?

What does Windows report natively?

**Comment by ykhan21** [comment]
I had assumed AC Connected meant charging.

Windows reports it to be charging.

![image](https://github.com/fastfetch-cli/fastfetch/assets/51864191/7a00ffa1-89aa-4ca5-87f9-9f4f1a74d95a)

**Comment by CarterLi** [comment]
Your assumption was not right. `Plugged in` means `AC connected`, but not `charging`. The evidence is that your battery capacity did not grow.
