### ISSUE TITLE
[BUG] Wrongly GPU detection?

### ISSUE THREAD

**Issue by AngryPenguinPL** [fastfetch-cli/fastfetch#713]
# General description of bug:

* What happened: After upgrade to 2.8.2 my GPU is not detected correctly but instead it it detect whole series.
As example before 2.8.2 my GPU was detected as: AMD Radeon RX580 (that correct) and now is: MD Radeon RX 470/480/570/570X/580/580X/590 - so right now whole Polaris series.
* What should happen: GPU should be detected correctly.
* Did it work in an older version:  Yes, 2.7.1
* Where did you get the binary:  Compiled by myself.
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Not tested.

# Often helpful information:

Screenshot:

![Screenshot_20240210_171953](https://github.com/fastfetch-cli/fastfetch/assets/3121142/86f816a0-d816-494c-8979-aa9f1f46baf5)
On left side old fastfetch 2.7.1 and on right side new fastfetcg 2.8.2

The content of the configuration file you use (if any):
```
//paste here
```

Output of `fastfetch -c ci.jsonc --format json`:

```
// https://gist.github.com/AngryPenguinPL/1a444cc553b5acf7468e0a80e51a02ed
```

Output of `fastfetch --list-features`:
```
//fastfetch --list-features
threads
vulkan
wayland
xcb-randr
xcb
xrandr
x11
drm
gio
dconf
dbus
imagemagick7
zlib
sqlite3
rpm
egl
glx
osmesa
opencl
libpulse
libnm
videodev2
Proprietary GPU driver API

```

## If fastfatch crashed

Paste the stacktrace here. You may get it with:

```
$ gdb /path/to/fastfetch
$ run
$ bt
```

If you are able to identify which module crashed, the strace can be helpful too

```
$ strace /path/to/fastfetch --multithreading false --structure {MODULE} --pipe
```

If you cannot do the instructions above, please upload the core dump file:

## If my image logo didn't show / work

* The image protocol you used: 
* The terminal you used: 
* Upload the image file here, or paste the image URL: 
* Does it work with `--logo-width {WIDTH} --logo-height {HEIGHT}`? 

## If fastfetch behaves incorrectly on shell starting

* The bug is reproduceable with fresh / clean shell configuration (i.e. `fastfetch` is the single line of `.zshrc` or `~/.config/fish/config.fish`): 
* Does `sleep 1` before running `fastfetch` work?

**Comment by CarterLi** [comment]
Thanks for reporting. What does `cat /sys/class/drm/card{0,1,2}/device/uevent` print?

**Comment by AngryPenguinPL** [comment]
```
cat /sys/class/drm/card{0,1,2}/device/uevent
DRIVER=amdgpu
PCI_CLASS=30000
PCI_ID=1002:67DF
PCI_SUBSYS_ID=1DA2:E353
PCI_SLOT_NAME=0000:01:00.0
MODALIAS=pci:v00001002d000067DFsv00001DA2sd0000E353bc03sc00i00
cat: /sys/class/drm/card1/device/uevent: No such file or directory
cat: /sys/class/drm/card2/device/uevent: No such file or directory
```

**Comment by SuperMewio** [comment]
I have come here with the same issue.

My RX 6800 XT now states "GPU: AMD Radeon RX 6800/6800 XT / 6900 XT" instead of it being an RX 6800 XT.

I do not use a config but a line in my fish configuration file and bashrc.

```
#Fastfetch
fastfetch --color green -s Seperator:Kernel:Packages:CPU:GPU:Memory:Seperator --logo Arch_small  --cpu-format "{1} ({5}) @ 4.15GHz"  --packages-format "{2} (P), {15} (F-U)"  --set-keyless Seperator=❰·───────────────────────────────────·❱

```

My output of `cat /sys/class/drm/card{0,1,2}/device/uevent`
```
❯ cat /sys/class/drm/card{0,1,2}/device/uevent
DRIVER=amdgpu
PCI_CLASS=30000
PCI_ID=1002:73BF
PCI_SUBSYS_ID=1EAE:6701
PCI_SLOT_NAME=0000:09:00.0
MODALIAS=pci:v00001002d000073BFsv00001EAEsd00006701bc03sc00i00
cat: /sys/class/drm/card1/device/uevent: No such file or directory
cat: /sys/class/drm/card2/device/uevent: No such file or directory
```

**Comment by CarterLi** [comment]
Please test if the latest dev build works for you

**Comment by AngryPenguinPL** [comment]
> Please test if the latest dev build works for you

Almost. Now my GPU is visible as Radeon RX 570 4GB, while my GPU is RX580 and 8GB.
![obraz](https://github.com/fastfetch-cli/fastfetch/assets/3121142/26c7b737-4721-4309-98a7-f14856ce3e95)

**Comment by CarterLi** [comment]
Seems that RX570 and RX580 use the same device ID and sub device ID. The only difference is the revision number.

**Comment by CarterLi** [comment]
Please pull the dev branch and test it again

**Comment by AngryPenguinPL** [comment]
Yes, looks like it is fixed. Thanks.

![obraz](https://github.com/fastfetch-cli/fastfetch/assets/3121142/d5e50f10-1935-4b43-9c02-530dd9d245b9)

**Comment by SuperMewio** [comment]
The dev build looks like it fixed it for me as well 
![Screenshot_20240211_152321](https://github.com/fastfetch-cli/fastfetch/assets/54662623/3eb8546b-e7ca-4947-8559-7b98abd0305b)

**Comment by CarterLi** [comment]
Thanks for testing
