### ISSUE TITLE
[BUG] Terminal Font not shown in Scoop's Windows Terminal

### ISSUE THREAD

**Issue by gchait** [fastfetch-cli/fastfetch#720]
If I remember correctly, there was a `Terminal Font` field when I used the Microsoft Store version of Windows Terminal.
Seeking a portable and easily configured solution I switched to the installation offered by `scoop install windows-terminal`.
In both the native PowerShell terminal and Git Bash's mintty the field is shown.

![image](https://github.com/fastfetch-cli/fastfetch/assets/53366531/80be8908-a23d-4c3c-b7a8-bb411583bc99)

Thank you!

**Comment by CarterLi** [comment]
Should have been fixed in the latest dev build. Please test it.
