### ISSUE TITLE
[FEAT] Make an option to print only specific colors (equivalentr to block_range)

### ISSUE THREAD

**Issue by TadoTheMiner** [fastfetch-cli/fastfetch#721]
# Current state:
You can only print all the color blocks
# Wanted state:
A range option which will specify which color blocks the user wants
# Why the change is sensible:
Some people use terminal themes that have only 8 colors (including me). I also dislike white and black being printed so I print only 1 to 6

**Comment by CarterLi** [comment]
Different person has different preferences. Fastfetch prints color blocks like that because fastfetch was designed to be a neofetch replacement. As these blocks are static text, you may use `Custom` module to print them. You may take `presets/example/*.jsonc` as an example.

**Comment by TadoTheMiner** [comment]
> Fastfetch prints color blocks like that because fastfetch was designed to be a neofetch replacement. 
That's why I ask for the option because neofetch has it aswell. @CarterLi 
![image](https://github.com/fastfetch-cli/fastfetch/assets/100917739/1a10e2ef-1db9-4ce5-9aab-0aaa98da30a3)

**Comment by TadoTheMiner** [comment]
I mean as its an replacement of neofetchit should have its options

**Comment by CarterLi** [comment]
You may try it with

```jsonc
{
    "type": "colors",
    "block": {
        "range": [9, 14],
        "width": 4
    }
}
```

**Comment by TadoTheMiner** [comment]
@CarterLi Nobody ever resolved my issue this fast thank you
