### ISSUE TITLE
[BUG] fastfetch caused core dumped on vmware virtual machine

### ISSUE THREAD

**Issue by 9Bakabaka** [fastfetch-cli/fastfetch#725]
# General description of bug:

* What happened: I am trying to use the fastfetch on my virtual machine(host: esxi 8.0 u1)However, fastfetch didnt work and caused the Segmentation fault (core dumped)
* What should happen: Run fastfetch
* Did it work in an older version: Unknown
* Where did you get the binary: Installed with a package manager(RockyLinux 9.3 dnf)
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Unknow

# Often helpful information:

Screenshot:
![image](https://github.com/fastfetch-cli/fastfetch/assets/140469824/c3270724-b6cc-4bc8-8f05-711d2cb236e7)
![image](https://github.com/fastfetch-cli/fastfetch/assets/140469824/cac91403-6544-4c3b-a780-549df7fc8d51)

**Comment by CarterLi** [comment]
Please provide the stack trace when crashng. You should follow the instructions of `if fastfetch crashed` section in the bug report template
