### ISSUE TITLE
[FEAT] Get the total disk writes for the current session.

### ISSUE THREAD

**Issue by Samueru-sama** [fastfetch-cli/fastfetch#727]
# Current state:

Fastfetch already supports useful information about the disk, like the space usage and temperature.

# Wanted state:
# Why the change is sensible:

It would be nice to get the total amount of bytes written in a human readable format along the other information, this is specially useful as it helps catch up any potential issue that might require active monitoring with iostat or iotop otherwise.

I personally didn't know what NetworkManager was writing 100MB of data to my ssd every hour in errors for months until very recently lol.

**Comment by CarterLi** [comment]
There is `DiskIO`. You may try it with `fastfetch -s diskio`

**Comment by Samueru-sama** [comment]
> There is `DiskIO`. You may try it with `fastfetch -s diskio`

That's great, but I see that only prints the the current B/s instead of total Bytes.

Iostat does report the total kB_wrtn without needing sudo rights, I don't know how difficult it would be to implement that feature into fastfetch.

**Comment by CarterLi** [comment]
`DiskIO` was implemented by calcuating total-bytes growth rate
. I think I can implement an option for `DiskIO` to let it report total bytes.

**Comment by Samueru-sama** [comment]
> `DiskIO` was implemented by calcuating total-bytes growth rate . I think I can implement an option for `DiskIO` to let it report total bytes.

Thank you, in the meantime I'm using iostat with this: 

    iostat -m -d | awk 'NR==4 { print $7" MiB Written" }

Which does print exactly that info.

**Comment by CarterLi** [comment]
You can embed this command into fastfetch

```jsonc
{
    "key": "Whatever"
    "type": "command",
    "text": "iostat -m -d | awk 'NR==4 { print $7\" MiB Written\" }'"
}
```

**Comment by Samueru-sama** [comment]
> ```js
> {
>     "key": "Whatever",
>     "type": "command",
>     "text": "iostat -m -d | awk 'NR==4 { print $7\" MiB Written\" }'"
> }
> ```

This also totally works for me, thank you so much for that!

I will leave the decision on whether to close this issue and not implement the feature to you, I'm very happy either way.

**Comment by CarterLi** [comment]
A new flag `--diskio-detect-total` has been added to support the required feature.

```shell
$ ./fastfetch -s diskio --diskio-detect-total --pipe
Disk IO (APPLE SSD AP1024R Media): 64.17 GiB (R) - 15.35 GiB (W)
```

Worth noting that the result applies to physical disks, not partitions.

**Comment by Samueru-sama** [comment]
> ```shell
> fastfetch -s diskio --diskio-detect-total
> ``

> A new flag `--diskio-detect-total` has been added to support the required feature.
> 
> ```shell
> $ ./fastfetch -s diskio --diskio-detect-total --pipe
> Disk IO (APPLE SSD AP1024R Media): 64.17 GiB (R) - 15.35 GiB (W)
> ```
> 
> Worth noting that the result applies to physical disks, not partitions.

Great, but is it possible to add it to the json config? I tried` "diskio-detect-total",` and that did not work.

If I use the flag it gets printed at the end of everything.
