### ISSUE TITLE
[FEAT] Multidevice bcachefs filesystem for disk module

### ISSUE THREAD

**Issue by boomshroom** [fastfetch-cli/fastfetch#731]
# Current state:

Bcachefs uses a shell-like list syntax to denote the device(s) for multi-device filesystems, as in `/dev/sda:/dev/sdb:/dev/sdc`. This is a list of files, but not a file. As such fastfetch trying to use `stat` to detect it fails and fastfetch mistakenly believes it's not a physical device unless it's mounted on `/` (meanwhile in my system, `/` is reported as physical despite being `tmpfs` due to special treatment).

```
> fastfetch -l none -s disk --disk-folders /persist

> grep "/persist" /proc/mounts
/dev/nvme0n1p3:/dev/sda:/dev/sdb:/dev/sdc /persist bcachefs ...[irrelevant]
```

# Wanted state:

The filesystem gets properly detected as a physical(ish) filesystem so its usage can be printed by the disk module.

```
> fastfetch -l none -s disk --disk-folders /persist
Disk (/persist): 1.9 TiB / 3.3 GiB (56%) - bcachefs
```

# Why the change is sensible:

It's a filesystem that physically stores data, but is mistaken for a non-physical filesystem. For a utility trying to show disk usage, I would expect it to show the disk usage. Bcachefs's syntax is non-standard, even if it's based on a standard syntax in a different domain, so special handling would likely be required.

**Comment by CarterLi** [comment]
Does https://github.com/fastfetch-cli/fastfetch/commit/6a0c7ca788e3ec11304799a1a900771b99761074 work for you?

**Comment by boomshroom** [comment]
It does. Frankly, it's a rather crude solution, but it gets the job done. False-positives are easier to resolve with command-line flags than false-negatives.

A more robust solution would probably be to split the "device" by the path separator, and then check if devices are physical individually, probably if any of them are. Or, of course, just skip the physicality check, among others, when provided with `--disk-folders`

**Comment by CarterLi** [comment]
> False-positives

Any examples?

**Comment by boomshroom** [comment]
> > False-positives
> 
> Any examples?

Mounting bcachefs on a normal file? I just created a small test file, formatted it with bcachefs, and then mounted it through a loop device, and fastfetch with this change reported it as though it was a normal filesystem. It's possible this is intended behavior, but that wasn't quite my impression reading the source file. I was however able to pass `--disk-folders` and it hid the mount as expected.

**Comment by CarterLi** [comment]
> Mounting bcachefs on a normal file?

That was an unexpected operation, and would  result in inconsistent behaviors between different filesystems. However it was definitely a valid use case and should be detected by fastfetch.

Therefore we should not assume that block *device* files are in /dev.
