### ISSUE TITLE
[BUG] Wrong GPU detection on latest version

### ISSUE THREAD

**Issue by cassiofb-dev** [fastfetch-cli/fastfetch#736]
# General description of bug:

* What happened: GPU output is wrong
* What should happen: GPU should be intel graphics
* Did it work in an older version: Yes, 2.8.2
* Where did you get the binary: Build myself
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Yes

# Often helpful information:

Screenshot:
![image](https://github.com/fastfetch-cli/fastfetch/assets/61878987/355f89db-e961-49d2-a0e5-3249a5dfa3a4)

Output of `fastfetch --list-features`:
```
fastfetch --list-features
threads
vulkan
wayland
xcb-randr
xcb
x11
drm
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
sqlite3
rpm
egl
osmesa
opencl
libpulse
libnm
libddcutil
videodev2
Proprietary GPU driver API
```

**Comment by CarterLi** [comment]
What's output of `cat /sys/class/drm/card{0,1,2}/device/uevent`?

**Comment by CarterLi** [comment]
Can you check if https://github.com/fastfetch-cli/fastfetch/commit/42b756e703ab14477e043a2f2031c1d23fa5d09a fix your issue?

**Comment by cassiofb-dev** [comment]
Thanks, the latest commit fixed the issue 🙏

---

> What's output of `cat /sys/class/drm/card{0,1,2}/device/uevent`?

![image](https://github.com/fastfetch-cli/fastfetch/assets/61878987/5c136d35-5798-43da-8b71-44c7fea42947)

---

> Can you check if https://github.com/fastfetch-cli/fastfetch/commit/42b756e703ab14477e043a2f2031c1d23fa5d09a fix your issue?

![image](https://github.com/fastfetch-cli/fastfetch/assets/61878987/6c53d5cd-aa65-484c-98a6-afcc6406a8d6)

**Comment by nonetrix** [comment]
Having similar issue somewhat, but kinda different. For some reason my AMD RX 6800 comes up as `AMD Device 73BF (VGA compatible)` which is true but very verbose and not what I would expect
![image](https://github.com/fastfetch-cli/fastfetch/assets/45698918/713ce642-19e5-46b8-bb6a-37dc235ee9de)

**Comment by CarterLi** [comment]
cat /sys/class/drm/card${0,1,2}/device/uevent

**Comment by nonetrix** [comment]
> `cat /sys/class/drm/card${0,1,2}/device/uevent`?

```
cat: /sys/class/drm/cardbash/device/uevent: No such file or directory
```
I am using NixOS so it's not HFS compliant, but seems like something that would stay the same

**Comment by CarterLi** [comment]
Does /usr/share/hwdata/pci.ids exist? If not, can you find where the file pci.ids is?

**Comment by nonetrix** [comment]
> Does /usr/share/hwdata/pci.ids exist? If not, can you find where the file pci.ids is?

Nope, also searched my filesystem

**Comment by CarterLi** [comment]
What does `strace lspci 2>&1 | grep 'pci.ids'` print?

**Comment by cassiofb-dev** [comment]
> Having similar issue somewhat, but kinda different. For some reason my AMD RX 6800 comes up as `AMD Device 73BF (VGA compatible)` which is true but very verbose and not what I would expect I didn't even know of this name before ![image](https://private-user-images.githubusercontent.com/45698918/307622070-713ce642-19e5-46b8-bb6a-37dc235ee9de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTYxMTIsIm5iZiI6MTcwODkxNTgxMiwicGF0aCI6Ii80NTY5ODkxOC8zMDc2MjIwNzAtNzEzY2U2NDItMTllNS00NmI4LWJiNmEtMzdkYzIzNWVlOWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDAyNTAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NDYwOTFkNzc2MGQ0YTMxYTdkMjQ0YzE2MGFkNjY3ZGFhYzg5NjIyODVkMWM0N2RkNWZhNTkxNmJhMTc1YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p6_sj_T0aIbRjHTHyKZ5r8dEX_aiMXmxwSMwGnMcX6M) Is this the same issue or should I make a new one? Also what color scheme? I like it

@nonetrix , the color pallete is catppuccin mocha from here: https://github.com/catppuccin/catppuccin
For wezterm I edited the config a bit, you can check them on my profile.
Also, did you check if the commit fixed your issue?

**Comment by CarterLi** [comment]
@nonetrix Installing package hwdata should install file `pci.ids`, which is used for fastfetch to match device ids to product names. Then [you may configure fastfetch with `-DCUSTOM_PCI_IDS_PATH=/path/to/pci.ids` to make fastfetch find the file](https://github.com/fastfetch-cli/fastfetch/commit/111f7111b28162ee056e81aeb03377e689214a4f).
