### ISSUE TITLE
[BUG] Display of Terminal being used changed from older versions

### ISSUE THREAD

**Issue by daniejstriata** [fastfetch-cli/fastfetch#738]
# General description of bug:

* What happened:
I noticed that when I login to a host the Terminal is shown as tmux. This change came in later. I checked on a host with 2.4.0 and there the Terminal is (in my view Correct) as`/dev/pts/1` and when sudo the termninal is `xterm-256color`. 

in 2.8.5, when I login the terminal is tmux and when I sudo to root the Terminal changes to sudo. 

![image](https://github.com/fastfetch-cli/fastfetch/assets/13314239/7cc3ece1-5a9e-4d04-add6-2441da586c75)
vs as root
![image](https://github.com/fastfetch-cli/fastfetch/assets/13314239/2efcbef5-36ea-44c0-aec9-9a243691c2f7)

On older version:
![image](https://github.com/fastfetch-cli/fastfetch/assets/13314239/f3e6711b-ffea-4bd2-beed-664f642625fa)
as root:
![image](https://github.com/fastfetch-cli/fastfetch/assets/13314239/72ad2d1e-3856-4a15-a96e-017cb9cece42)

Output of `fastfetch -c ci.jsonc --format json`:
```
  {
    "type": "Version",
    "result": {
      "projectName": "fastfetch",
      "architecture": "aarch64",
      "version": "2.8.5",
      "versionTweak": "",
      "cmakeBuiltType": "RelWithDebInfo",
      "compileTime": "Feb 25 2024, 00:00:00",
      "compiler": "gcc 11.4.1",
      "debugMode": false,
      "libc": "glibc 2.34"
    },
    "stat": 0
  },
```

```
//paste here
```

Output of `fastfetch --list-features`:
```
threads
gio
dconf
dbus
zlib
sqlite3
rpm
opencl
videodev2
Proprietary GPU driver API

```

**Comment by CarterLi** [comment]
> I login to a host the Terminal is shown as tmux

It's expected when you run fastfetch inside tmux

> I sudo to root the Terminal changes to sudo

I can't reproduce it. I got `Terminal: tmux` when I ran `sudo fastfetch` inside tmux. The tmux version was lost because you lost environment variables when running fastfetch with sudo, which is also expected.

**Comment by daniejstriata** [comment]
I realise what I'm saying is that the terminal id being used by the session is lost. Which is also the output of `tty`:
![image](https://github.com/fastfetch-cli/fastfetch/assets/13314239/cc1c4e60-6edc-4954-ab5f-2091698575fb)
Can the Terminal output not be:
`tty` + `sudo`
or
``tty` + `tmux`

It could be presented as:
```
Terminal: sudo on /dev/pts/2
```
if not in sudo or tmux
```
Terminal: /dev/pts/2
```
if in tmux
```
Terminal: tmux on /dev/pts/2
```

**Comment by CarterLi** [comment]
You may use `fastfetch -s terminal --terminal-format '{5} {6} on {8}'`

**Comment by daniejstriata** [comment]
@CarterLi Can this display not be the default as both are correct together and either are less correct on their own?

**Comment by CarterLi** [comment]
I don't get it. Please file a new feature request and describe what you want.
