### ISSUE TITLE
[BUG] Completely blocked and unable to be fully displayed in the latest version of WSL

### ISSUE THREAD

**Issue by Parsifa1** [fastfetch-cli/fastfetch#746]
# General description of bug:

* What happened: freezed
* What should happen: show directly
* Did it work in an older version: no
* Where did you get the binary: from pacman
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/):  yes

Screenshot:

![image](https://github.com/fastfetch-cli/fastfetch/assets/31800073/830b0d5a-e328-4b98-bc21-15e9a4c80b1b)

![image](https://github.com/fastfetch-cli/fastfetch/assets/31800073/084ae5bd-9796-4476-8e54-6adaad97d978)

![image](https://github.com/fastfetch-cli/fastfetch/assets/31800073/ad14f107-72bb-4521-83f3-2c1b26119039)

Output of `fastfetch -c ci.jsonc --format json`:

this freezed.

Output of `fastfetch --list-features`:
```
threads
vulkan
wayland
xcb-randr
xcb
xrandr
x11
drm
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
egl
glx
osmesa
opencl
libpulse
libnm
libddcutil
videodev2
Directx Headers
Proprietary GPU driver API
//paste here
```

## If fastfatch crashed

Paste the stacktrace here. You may get it with:

```
Reading symbols from /usr/bin/fastfetch...
(No debugging symbols found in /usr/bin/fastfetch)
Starting program: /usr/bin/fastfetch
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
                  -`                     parsifa1@LAPTOP-ALDRIC
                 .o+`                    ----------------------
                `ooo/                    OS: Arch Linux x86_64
               `+oooo:                   Kernel: 5.15.146.1-microsoft-standard-WSL2
              `+oooooo:                  Uptime: 12 mins
              -+oooooo+:                 Packages: 951 (pacman)
[Detaching after fork from child process 2067]
```
and it freezed

WSL version
```
2.1.4.0
```

**Comment by Parsifa1** [comment]
I rolled back the wsl version to 2.0.11.0 and everything worked fine, this might be an upstream issue

**Comment by CarterLi** [comment]
Seems it freezed in `Display` module. However I can't reproduce this issue in my PC with the same WSL version 2.1.4.0

Try this:
1. `$ gdb /path/to/fastfetch`
2. `run`
3. When fastfetch freeses, `Ctrl+C` to kill it
4. `bt --full`

**Comment by Parsifa1** [comment]
https://github.com/microsoft/wslg/issues/1156?notification_referrer_id=NT_kwDOAeU7CbM4NTg5MzMxMDQ4OjMxODAwMDcz#issuecomment-1975679118
This seems to be the cause of the problem. After I repaired $DISPLAY, everything went fine. Thank you!
