### ISSUE TITLE
adding repo is failing on ubuntu 20.04

### ISSUE THREAD

**Issue by devSajan** [fastfetch-cli/fastfetch#747]
![image](https://github.com/fastfetch-cli/fastfetch/assets/95337022/1c043ae2-b96f-4ee7-841d-0d0501f19a39)
![image](https://github.com/fastfetch-cli/fastfetch/assets/95337022/4d9b8c6a-a212-401c-a70b-0fbc3e30aa5e)

**Comment by CarterLi** [comment]
Binaries in PPA were built with Ubuntu 22.04 and copied to newer distros. I haven't found a way to deal with the different version in PPA, but 20.04 is not supported for now.
