### ISSUE TITLE
[BUG]Resizing the terminal window causes a glitch!

### ISSUE THREAD

**Issue by ChrompyCoder** [fastfetch-cli/fastfetch#754]
# General description of bug:

When you execute `fastfetch` in small sized window, some text disappears( refer screenshot 01.).

# What should happen:
text should be displayed in the following line instead of disappearing like displayed in screenshot 02.
Screenshot 02 was taken by resizing terminal window after running `fastfetch --pipe false'.

- Did it work in an older version: I don't know
# Where did you get the binary: 
I used `brew install fastfetch` on WSL2 running ubuntu 22.04 with zsh along with ohmyzsh! framework.

# Often helpful information:
This happens even when i run `fastfetch --pipe false`.
NOTE:- This DOES NOT happen when you resize a terminal window.
Screenshot:
screenshot 01-
![image](https://github.com/fastfetch-cli/fastfetch/assets/153909062/d634d87d-4263-42c2-9e9b-097454f901ed)
screenshot 02-
![image](https://github.com/fastfetch-cli/fastfetch/assets/153909062/4070161b-a146-4e94-830a-6c59084662e8)

The content of the configuration file you use (if any):
```
export PATH=$HOME/bin:/usr/local/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=( "strug" )
zstyle ':omz:update' mode reminder  # just remind me to update when it's time
DISABLE_LS_COLORS="true"
plugins=( vi-mode git macos)
source $ZSH/oh-my-zsh.sh
HIST_IGNORE_SPACE=true
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
export PATH=$HOME/.local/bin:$PATH
```

Output of `fastfetch --list-features`:
```
threads
vulkan
wayland
xcb-randr
xcb
xrandr
x11
drm
gio
dbus
imagemagick7
chafa
zlib
sqlite3
rpm
egl
osmesa
libpulse
libddcutil
videodev2
Proprietary GPU driver API
```

* Does `sleep 1` before running `fastfetch` work?  Yes

**Comment by CarterLi** [comment]
`--disable-linewrap false`
