### ISSUE TITLE
[LOGO] PVE

### ISSUE THREAD

**Issue by 9Bakabaka** [fastfetch-cli/fastfetch#756]
I notice that the proxmox ve did not have a system logo. I notice that the logo was instead of with the Debian logo.
# OS
```
https://www.proxmox.com/en/proxmox-virtual-environment/overview
```

(Notice: The logo was in the pr)

**Comment by CarterLi** [comment]
Try it with `fastfetch -l proxmox`

**Comment by 9Bakabaka** [comment]
Sir, there still not have the proxmox logo.
![image](https://github.com/fastfetch-cli/fastfetch/assets/140469824/d8ab703d-7390-4d75-8830-365191d3b3eb)

**Comment by CarterLi** [comment]
You need to use the dev build
