### ISSUE TITLE
Termux error[BUG] 

### ISSUE THREAD

**Issue by wowlikon** [fastfetch-cli/fastfetch#760]
# General description of bug:

* What happened:
* Error: "Pointer tag for 0x2020200a20202020 was truncated"
* pkg fastfetch 2.8.9 (aarch64)

Screenshot:
![image](https://github.com/fastfetch-cli/fastfetch/assets/73490630/ebf6e008-9299-40cb-bc0f-b7546cb45495)

Output of `fastfetch -c ci.jsonc --format json`:
[error.json](https://github.com/fastfetch-cli/fastfetch/files/14618669/error.json)

Output of `fastfetch --list-features`:
```
threads
vulkan
freetype
videodev2
```

**Comment by CarterLi** [comment]
Thanks for reporting, bug unfortunately I cannot reproduce this issue on my cell phone. Can you provide the output of the following command?

```bash
for structure in localip battery poweradapter locale break colors; do ./fastfetch -l none --show-errors -s $structure; done
```

**Comment by wowlikon** [comment]
`❯ fastfetch
         -o          o-             u0_a309@localhost
          +hydNNNNdyh+              -----------------
        +mMMMMMMMMMMMMm+            OS: Android REL 14 aarch64
      `dMMm:NMMMMMMN:mMMd`          Host: Xiaomi Redmi Note 12 (23021RAA2Y)
      hMMMMMMMMMMMMMMMMMMh          Kernel: 5.15.94-android13-8-00001-g171753a15b59-ab11001737
  ..  yyyyyyyyyyyyyyyyyyyy  ..      Uptime: 24 days, 6 hours, 51 mins
.mMMm`MMMMMMMMMMMMMMMMMMMM`mMMm.    Packages: 157 (dpkg)
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:    Shell: zsh 5.9
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:    WM: Window Manager
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:    Terminal: /dev/pts/1
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:    CPU: SM6225 (8) @ 2.80 GHz
-MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM-    Memory: 3.16 GiB / 5.51 GiB (57%)
 +yy+ MMMMMMMMMMMMMMMMMMMM +yy+     Swap: 1.70 GiB / 4.00 GiB (42%)
      mMMMMMMMMMMMMMMMMMMm          Disk (/): 697.13 MiB / 697.13 MiB (100%) - erofs [Read-only]
      `/++MMMMh++hMMMM++/`          Disk (/storage/emulated): 88.44 GiB / 107.31 GiB (82%) - fuse
          MMMMo  oMMMM              Local IP (rmnet_data6): 12.34.67.90/24
          MMMMo  oMMMM              Local IP (wlan0): 192.168.0.164/24
          oNMm-  -mMNs              Battery: 50% [DISCHARGING]
Pointer tag for 0x2020200a20202020 was truncated, see 'https://source.android.com/devices/tech/debug/tagged-pointers'.
[1]    3817 abort      fastfetch
❯ for structure in localip battery poweradapter locale break colors; do fastfetch -l none --show-errors -s $structure; done
Local IP (rmnet_data6): 12.34.67.90/24
Local IP (wlan0): 192.168.0.164/24
Battery: 50% [DISCHARGING]
Power Adapter: Not supported on this platform
Locale: en_US.UTF-8

████████████████████████
████████████████████████
`

**Comment by wowlikon** [comment]
> Thanks for reporting. Unfortunately I cannot reproduce this issue on my cell phone. Can you provide the output of the following command?
> 
> ```shell
> for structure in localip battery poweradapter locale break colors; do ./fastfetch -l none --show-errors -s $structure; done
> ```

❯ fastfetch
         -o          o-             u0_a309@localhost
          +hydNNNNdyh+              -----------------
        +mMMMMMMMMMMMMm+            OS: Android REL 14 aarch64
      `dMMm:NMMMMMMN:mMMd`          Host: Xiaomi Redmi Note 12 (23021RAA2Y)
      hMMMMMMMMMMMMMMMMMMh          Kernel: 5.15.94-android13-8-00001-g171753a15b59-ab11001737
  ..  yyyyyyyyyyyyyyyyyyyy  ..      Uptime: 24 days, 6 hours, 51 mins
.mMMm`MMMMMMMMMMMMMMMMMMMM`mMMm.    Packages: 157 (dpkg)
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:    Shell: zsh 5.9
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:    WM: Window Manager
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:    Terminal: /dev/pts/1
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:    CPU: SM6225 (8) @ 2.80 GHz
-MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM-    Memory: 3.16 GiB / 5.51 GiB (57%)
 +yy+ MMMMMMMMMMMMMMMMMMMM +yy+     Swap: 1.70 GiB / 4.00 GiB (42%)
      mMMMMMMMMMMMMMMMMMMm          Disk (/): 697.13 MiB / 697.13 MiB (100%) - erofs [Read-only]
      `/++MMMMh++hMMMM++/`          Disk (/storage/emulated): 88.44 GiB / 107.31 GiB (82%) - fuse
          MMMMo  oMMMM              Local IP (rmnet_data6): 12.34.67.90/24
          MMMMo  oMMMM              Local IP (wlan0): 192.168.0.164/24
          oNMm-  -mMNs              Battery: 50% [DISCHARGING]
Pointer tag for 0x2020200a20202020 was truncated, see 'https://source.android.com/devices/tech/debug/tagged-pointers'.
[1]    3817 abort      fastfetch
❯ for structure in localip battery poweradapter locale break colors; do fastfetch -l none --show-errors -s $structure; done
Local IP (rmnet_data6): 12.34.67.90/24
Local IP (wlan0): 192.168.0.164/24
Battery: 50% [DISCHARGING]
Power Adapter: Not supported on this platform
Locale: en_US.UTF-8

████████████████████████
████████████████████████

**Comment by CarterLi** [comment]
Well, is the bug consistantly reproduceable?

**Comment by wowlikon** [comment]
> Well, is the bug consistantly reproduceable?

The error is probably related to termux-api. because without it, the battery status is not displayed and an error does not occur

**Comment by CarterLi** [comment]
However it didn't occur here:

> Battery: 50% [DISCHARGING]

**Comment by wowlikon** [comment]
Perhaps some other termux-api commands are causing errors, or do not return the expected response

**Comment by CarterLi** [comment]
Can you please try this?

```
$ for structure in Title Separator OS Host Kernel Uptime Packages Shell Display DE WM WMTheme Theme Icons Font Cursor Terminal TerminalFont CPU GPU Memory Swap Disk LocalIp Battery PowerAdapter Locale Break Colors; do fastfetch -l none --show-errors -s $structure; done
```

**Comment by wowlikon** [comment]
> Can you please try this?
> 
> ```shell
> for structure in Title Separator OS Host Kernel Uptime Packages Shell Display DE WM WMTheme Theme Icons Font Cursor Terminal TerminalFont CPU GPU Memory Swap Disk LocalIp Battery PowerAdapter Locale Break Colors; do fastfetch -l none --show-errors -s $structure; done
> ```

![WindowsTerminal_rMicxOJTh6](https://github.com/fastfetch-cli/fastfetch/assets/73490630/0ebcea1d-82c3-4ef5-b381-33c03ac9875f)

**Comment by CarterLi** [comment]
The crash seems to be random. Let's wait and see if it occurs to others.

**Comment by CarterLi** [comment]
Anyway, you can always disable the battery module with `fastfetch -s Title:Separator:OS:Host:Kernel:Uptime:Packages:Shell:Display:DE:WM:WMTheme:Theme:Icons:Font:Cursor:Terminal:TerminalFont:CPU:GPU:Memory:Swap:Disk:LocalIp:Locale:Break:Colors`

**Comment by Efreak** [comment]
I'm getting this as well, though I'm not sure if it's for the same reason. It goes away when I disable battery, however the battery report is correct. It also goes away if I set `--pipe`, oddly.

<details>
<summary>detailed info and fastfetch output</summary>

[`fastfetch -c ci.jsonc --format json`](https://gist.github.com/Efreak/ea14bfd983558c5c00e5babad8046d0e)

Output from fastfetch `--list-features`:
```
threads
vulkan
freetype
linux/videodev2
linux/wireless
```

![SmartSelect_20240501_070345_Termux](https://github.com/fastfetch-cli/fastfetch/assets/749751/b10a990f-1bca-4f09-b475-bcf80cd7aa70)

</details>
