### ISSUE TITLE
[BUG] Terminal field has wrong content

### ISSUE THREAD

**Issue by Bios-Marcel** [fastfetch-cli/fastfetch#762]
# General description of bug:

* I had two terminals open
* In the left one I ran `chezmoi cd` (Changes dir to chezmoi directory in a subshell)
* Running `fastfetch` in the left one says the `Terminal` is `chezmoi`
* Running `fastfetch` in the right one correctly recognised `alacritty`

I got fastfetch via nixos-channel-23.11. The version is 2.2.3.

# Often helpful information:

Screenshot:

![image](https://github.com/fastfetch-cli/fastfetch/assets/19377618/b72f7a61-91e2-4311-b0e7-9c433024778f)

Output of `fastfetch --format json`:

```json
{
  {
    "type": "Terminal",
    "result": {
      "processName": "chezmoi",
      "exe": "chezmoi",
      "exeName": "chezmoi",
      "pid": 15680,
      "prettyName": "chezmoi",
      "version": ""
    }
  },
  {
    "type": "TerminalFont",
    "error": "Unknown terminal: chezmoi"
  }
}
```

Note my term variable though:

```bash
[marcel@nixthinkpad:~]$ echo $TERM
alacritty
```

**Comment by CarterLi** [comment]
Should be fixed in the latest dev build. Please have a test
