### ISSUE TITLE
Display of fonts when not the default font

### ISSUE THREAD

**Issue by tdtooke** [fastfetch-cli/fastfetch#764]
If I use the standard default font I will get this:
Noto Sans (10pt) [QT], Noto Sans (10pt) [GTK2/3/4]

but if I change it then it reports something really long like:
Fira Sans Medium (10pt, 0,0,0,0,0,1) [QT], Fira Sans Medium (10pt) [GTK2/3/4]

Not a bug or anything, just trying to understand why it does this.  I'm on the latest release.  I can try it out on the latest from git if you'd like.

**Comment by CarterLi** [comment]
Can I have the full screenshot and the replicate steps?

**Comment by tdtooke** [comment]
It's from running fastfetch when I have changed my system fonts to something other than Noto Sans.

[url=https://postimg.cc/phRtQZZ1][img]https://i.postimg.cc/phRtQZZ1/fetch.png[/img][/url]

**Comment by CarterLi** [comment]
May be caused by the incompatibility of KDE version 5 and 6. Can you please upload the content of `~/.config/kdeglobals`?

**Comment by LinusDierheimer** [comment]
Some examples from my system:
```
Times New Roman,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Standard    //QT 6, regular style
Times New Roman,10,-1,5,50,0,0,0,0,0                          //QT 5, regular style
Times New Roman,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Fett Kursiv //QT 6, bold italic style
Times New Roman,10,-1,5,50,0,0,0,0,0,Fett,Kursiv              //QT 5, bold italic style

**Comment by tdtooke** [comment]
That fixed it for me.  I tested with Fira Sans Medium and Times New Roman.

**Comment by CarterLi** [comment]
> That fixed it for me. I tested with Fira Sans Medium and Times New Roman.

Great!
