### ISSUE TITLE
[BUG] dpkg-build package can not run in this debian dir

### ISSUE THREAD

**Issue by xzl01** [fastfetch-cli/fastfetch#767]
我发现项目里面的debian目录似乎不能正常使用debian打包脚本运行，我们在deepin那维护了一份，如果需要的话，我可以迁移过来

**Comment by CarterLi** [comment]
这个目录是发Ubuntu的PPA用的。我们需要的是debian的官方仓库，自己维护个debian打包脚本也没什么用

**Comment by xzl01** [comment]
你可以把这个debian脚本放在 debian的git上维护  然后申请进入debian 软件源。事实上现在这一份脚本如果使用`dpkg-buildpackage -us -uc -b` 进行打包操作是无法实现的

**Comment by xzl01** [comment]
也许你需要在https://salsa.debian.org/public 维护一份debian 打包的fork。我对于debian软件包的引入也不太清楚，容我先去问问。

**Comment by xzl01** [comment]
根据我找到的信息 debian 对于包的引入需要走ITP： https://wiki.debian.org/ITP，请问是否允许我在此仓库创建一个用于打包的分支，维护一个可以被debian发行版接受的debian目录？

**Comment by CarterLi** [comment]
发过了，没人管

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1053995

**Comment by CarterLi** [comment]
Duplicate of https://github.com/fastfetch-cli/fastfetch/issues/533

**Comment by xzl01** [comment]
我关闭这个issue,后续打包问题我们在 #533 讨论吧
