### ISSUE TITLE
[FEAT] Add AM package manager.

### ISSUE THREAD

**Issue by Samueru-sama** [fastfetch-cli/fastfetch#771]
AM is a package manager for appimages and other portable applications. 

https://github.com/ivan-hc/AM

AM prints the number of packages installed by running `am -f --less`.

**Comment by CarterLi** [comment]
Does `ls /opt/*/AM-updater | wc -l` correctly print the number of packages installed by `AM`?

**Comment by Samueru-sama** [comment]
> ls /opt/*/AM-updater | wc -l

Maybe, but if it works it will only work when AM is used as AM, it also has a portable mode (AppMan) which makes it a bit more complicated. 

You can get the packages directory by reading the path in `$XDG_CONFIG_HOME/appman/appman-config` or `~/.config/appman/appman-config` and then to get the number of packages it does this: 

```
cd /path/to/packages/dir &&
find . -type f -name 'remove' 2>/dev/null | sed -r 's|/[^/]+$||' | sort | uniq | wc -l
```

And that prints the total number of packages installed. That is what AM itself does.

**Comment by CarterLi** [comment]
Can you paste the content of `$XDG_CONFIG_HOME/appman/appman-config` here?

**Comment by CarterLi** [comment]
I installed AM myself. The file `$XDG_CONFIG_HOME/appman/appman-config` doesn't exist

**Comment by ivan-hc** [comment]
hi @CarterLi I'm the developer of AM, thank you for adding my package manager in your project.

> I installed AM myself. The file `$XDG_CONFIG_HOME/appman/appman-config` doesn't exist

the file is created when AM installs programs locally with the flag `--user`, AppMan is AM but in local use, and has `appman` as command name.

Normally to have the number of installed programs is enough to run the command with option `-f --less`, with the difference that AppMan only lists local programs, AM lists both system and local programs.

In this example I have just one app installed locally and 9 system wide

![Istantanea_2025-01-07_06-25-00](https://github.com/user-attachments/assets/65f8d6db-e6ed-4ee9-9ff5-ebe7967eeb53)

I don't know how the language of your program works, in SHELL you can have a total number of apps in AM like this
```
am -f --less | awk '{ SUM += $1} END { print SUM }'
```
in AppMan is enough to run only
```
appman -f --less
```

![Istantanea_2025-01-07_06-26-15](https://github.com/user-attachments/assets/0b33862d-897a-4aa5-86de-40357a519477)

I hope this helps you understand the way AM works.

If you have any other questions, please feel free to contact me. Thank you.

**Comment by ivan-hc** [comment]
> Does `ls /opt/*/AM-updater | wc -l` correctly print the number of packages installed by `AM`?

@CarterLi This command only takes into account applications with an AM-updater script, which means that standalone programs that update themselves like Firefox and Thunderbird will not be detected.

I recommend using the `am` (combined with `awk`) and `appman` commands directly, as I suggested in the previous comment.

> I don't know how the language of your program works, in SHELL you can have a total number of apps in AM like this
> 
> ```
> am -f --less | awk '{ SUM += $1} END { print SUM }'
> ```
> 
> in AppMan is enough to run only
> 
> ```
> appman -f --less
> ```

**Comment by CarterLi** [comment]
No. Fastfetch spawns 3rd party processes as less as possible. That's why fastfetch is called **fast**.

**Comment by ivan-hc** [comment]
> No. Fastfetch spawns 3rd party processes as less as possible. That's why fastfetch is called **fast**.

Got it. What do you need to know then?

**Comment by CarterLi** [comment]
I want to know how `am` counts packages internally. Fastfetch usually counts the number of files / directories in a path, or counts the number of strings in a text file, so I want some commands like `ls /opt/*/AM-updater | wc -l` or `grep some_string /path/to/am_packages.txt | wc -l`

**Comment by ivan-hc** [comment]
For system apps only it's simple, just count the number of `remove` scripts in /opt/*/

The problem remains for locally installed apps. The path there is variable, and is indicated in the file ~/.config/appman/appman-config, if present.

**Comment by CarterLi** [comment]
What is `~/.config/appman/appman-config` and how can I use it?

**Comment by ivan-hc** [comment]
If you have AM, enter the appman mode like this
```
am --user
```
to exit the AppMan mode use the `--system` option instead.

Alternativelly, in normal mode, install an application locally, for example
```
am -i --user fastfetch
```

-----------------------------

SPOILER, according with your workflow, for AM (only system)

```
ls /opt/*/remove | wc -l
```

for AppMan

```
ls $(sort $XDG_CONFIG_HOME/appman/appman-config)/*/remove | wc -l
```

for all local and system apps via AM

```
ls $(sort $XDG_CONFIG_HOME/appman/appman-config)/*/remove /opt/*/remove | wc -l
```

NOTE that if locally you have no apps, you may get an error. System wide AM is always installed in /opt, so you have at least one `remove` script there if you only have AM installed

**Comment by ivan-hc** [comment]
> NOTE that if locally you have no apps, you may get an error. System wide AM is always installed in /opt, so you have at least one `remove` script there if you only have AM installed

without local apps

![Istantanea_2025-01-07_07-36-38](https://github.com/user-attachments/assets/fd0509e6-0f2f-4171-a5b0-ed29ecb4e385)

with local apps (here one)

![Istantanea_2025-01-07_07-37-26](https://github.com/user-attachments/assets/266c6522-cfef-4f84-9e66-3f71f2ca035d)

**Comment by CarterLi** [comment]
I'm in macOS and have no am installed.

Please upload content of `appman-config`. I will check how I can use it.

**Comment by ivan-hc** [comment]
> Please upload content of `appman-config`. I will check how I can use it.

The content of an appman-config is custom. Any usr can set a different location, according to its tastes.

At first start of AppMan or AM in appman mode or when you install an app locally with AM, this will be the message that will appear

https://github.com/user-attachments/assets/4fde8338-2a1b-484b-8440-90c210b7f6ed

while AM only installs apps in /opt, local installations can be done anywhere, also on a USB media (with rootless access, of course, AppMan mode does not accept sudo/doas permissions)

**Comment by ivan-hc** [comment]
> I'm in macOS and have no am installed.

AM can be used also on FreeBSD, I'm not sure if it works on macOS... I've not enough money for that XD

**Comment by CarterLi** [comment]
> The content of an appman-config is custom. Any usr can set a different location, according to its tastes.

I know. I want to know the format of this file.

**Comment by ivan-hc** [comment]
> > The content of an appman-config is custom. Any usr can set a different location, according to its tastes.
> 
> I knew it. I want to know the format of this file.

it is a simple txt file containing the path

![Istantanea_2025-01-07_07-55-03](https://github.com/user-attachments/assets/b8614150-d97e-46f8-a97c-027d03569760)

**Comment by CarterLi** [comment]
What does `ls -l (cat ~/.config/appman/appman-config)` print?

**Comment by ivan-hc** [comment]
> What does `ls -l (cat ~/.config/appman/appman-config)` print?

I answered here https://github.com/fastfetch-cli/fastfetch/issues/771#issuecomment-2574495632

btw ~/ is too generic, we base our workflow on XDG specifications

![Istantanea_2025-01-07_08-00-31](https://github.com/user-attachments/assets/e51efcee-6f84-4abc-837e-095b26c0442c)

**Comment by ivan-hc** [comment]
@CarterLi also, we set this in the main CLI
```
export CONFIGDIR="${XDG_CONFIG_HOME:-$HOME/.config}"
```
in case XDG is not supported.

**Comment by ivan-hc** [comment]
> What does `ls -l (cat ~/.config/appman/appman-config)` print?

@CarterLi the `ls -l` command returns this

![Istantanea_2025-01-07_08-17-28](https://github.com/user-attachments/assets/7bfc5c87-d79e-40fd-b331-ae201129f46b)

and right now I have no local apps installed, only an appman/modules/database.am file (created when I switched to AppMan mode, before).

**Comment by ivan-hc** [comment]
I have to go, thanks for your time.

**Comment by CarterLi** [comment]
Please test the dev build @ivan-hc. Thanks.

**Comment by ivan-hc** [comment]
> Please test the dev build @ivan-hc. Thanks.

@CarterLi I just built it using your instructions here https://github.com/fastfetch-cli/fastfetch/wiki/Building and I'm able to see the correct number of the system applications.

However, I can't see local apps. I don't think it's a problem... but it could be a benefit if you implemented it.

**Comment by CarterLi** [comment]
I did implement local app detection though...

**Comment by ivan-hc** [comment]
> I did implement local app detection though...

![Istantanea_2025-01-08_03-13-01](https://github.com/user-attachments/assets/36eb74d9-83ab-4613-b5e7-03257d2fc802)

**Comment by ivan-hc** [comment]
> I did implement local app detection though...

Two local apps are missing

![Istantanea_2025-01-08_03-13-01](https://github.com/user-attachments/assets/03a431a6-a101-4416-baa5-28f9dc907a7b)

**Comment by CarterLi** [comment]
Please take a screenshot of the installation path of these 2 local apps.

**Comment by CarterLi** [comment]
Does the file content of `~/.config/appman/appman-config` contain a final newline?

**Comment by ivan-hc** [comment]
> Please take a screenshot of the installation path of these 2 local apps.

The path may vary from user to user, I'll give you the screenshot anyway

> Does the file content of `~/.config/appman/appman-config` contain a final newline?

Nope, I opened the file in Mousepad, it is just one line I added when was prompted for this kind of setup, and I choosed /home/ivan/.local/share/appman ...

![Istantanea_2025-01-08_03-28-36](https://github.com/user-attachments/assets/7b41c670-7b56-46a7-b459-f45ac377f26d)

...as @Samueru-sama added a completelly different path using a total different XDG_CONFIG_DIR than mine or other's.

**Comment by ivan-hc** [comment]
> Please pull and try again.

I'm compiling the program, just one minute.

**Comment by ivan-hc** [comment]
@CarterLi man, this is perfection

![Istantanea_2025-01-08_03-37-26](https://github.com/user-attachments/assets/d1871b48-7a89-4c0b-905a-14468c195efd)

thank you!

@Samueru-sama run
```
git clone https://github.com/fastfetch-cli/fastfetch.git
cd fastfetch
mkdir -p build
cd build
cmake ..
cmake --build . --target fastfetch --target flashfetch
```
and then
```
./fastfetch
```
...let us know if it works for you too.

**Comment by ivan-hc** [comment]
@CarterLi you can also briefly call the first "am" and the seconds "appman", no need to add -user and -system

**Comment by CarterLi** [comment]
It's up to you. Which one do you prefer?

**Comment by ivan-hc** [comment]
> It's up to you. Which one do you prefer?

"am" and "appman", it's also shorter to read, actually... fast, since it's `fastfetch` ;)

**Comment by ivan-hc** [comment]
@CarterLi I have a question, how these are activated to be shown in Fastfetch?

I mean, if someone uses AppMan, what Fastfetch looks at? If the command `appman` exists or the appman-config file?

**Comment by CarterLi** [comment]
It will look up `appman-config` file

**Comment by ivan-hc** [comment]
> It will look up `appman-config` file

Thank you.

Also, when this release will be "stable". I mean, in Debian Testing the so called "freeze" is near, it would be great to include these changes in the next Debian Stable, via APT

**Comment by ivan-hc** [comment]
> Updated. Try again please.

Thank you @CarterLi 

![Istantanea_2025-01-08_04-04-00](https://github.com/user-attachments/assets/86976395-91ef-4629-b215-7758ad87b246)

**Comment by CarterLi** [comment]
I actually plan to release it today.

However, It's unknown when this version will be included in Debian, because I don't have control to the debian package repo.

**Comment by ivan-hc** [comment]
> However, It's unknown when this version will be included in Debian, because I don't have control to the debian package repo.

Don't worry, they are the ones that track you https://tracker.debian.org/pkg/fastfetch

**Comment by Samueru-sama** [comment]
> Does the file content of `~/.config/appman/appman-config` contain a final newline?
> 
> Please pull and try again.

Yes it does, the file is made [here](https://github.com/ivan-hc/AM/blob/main/APP-MANAGER#L141) and `echo` always adds a final newline unlike `printf`.

**Comment by Samueru-sama** [comment]
All working fine here. Thank you @CarterLi 

![image](https://github.com/user-attachments/assets/f7a03c3a-c8e9-4679-8bf4-d27de30f1a01)

**Comment by ivan-hc** [comment]
@CarterLi I'm proud to say that the new version is in Debian Unstable

![Istantanea_2025-01-12_23-25-17](https://github.com/user-attachments/assets/dbbca062-1fda-41f0-9183-453ebc16e18e)
