### ISSUE TITLE
[BUG] localip doesn't show the correct network prefix on Fedora Linux 39

### ISSUE THREAD

**Issue by C-512L** [fastfetch-cli/fastfetch#773]
# General description of bug:
fastfech shows the correct local ipv4 address, but an incorrect network prefix. 
* What happened:
It showed the IPv4 address from the wlp5s0 iface, but with what I suspect is the network prefix from the enp6s0 iface.
* What should happen:  Show the correct prefix
* Did it work in an older version: unsure
* Where did you get the binary: package manager
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Yes
# Often helpful information: 
[interfaces.log](https://github.com/fastfetch-cli/fastfetch/files/14856107/interfaces.log)

Output of `fastfetch -c ci.jsonc --format json`:

```
[
  ...
  {
    "type": "LocalIp",
    "result": [
      {
        "defaultRoute": true,
        "ipv4": "192.168.1.125/24",
        "ipv6": "",  // Note: I didn't remove anything from this fields.
        "mac": "",
        "name": "wlp5s0"
      }
    ]
  },
  ...
]
```
Output of `fastfetch --list-features`:
```
threads
libpci
vulkan
wayland
xcb-randr
xcb
xrandr
x11
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
sqlite3
rpm
egl
glx
osmesa
opencl
libddcutil
```

**Comment by CarterLi** [comment]
You should use `fastfetch -s localip --format json --localip-default-route-only false --localip-show-loop --localip-show-ipv6 --localip-show-mac` to show everything

**Comment by CarterLi** [comment]
It turns out that `inet_netof` doesn't support network prefix value greater than 24. I will fix that.

**Comment by CarterLi** [comment]
Should have been fixed in the dev build
