### ISSUE TITLE
[FEAT] Linux cursor detection

### ISSUE THREAD

**Issue by kojq** [fastfetch-cli/fastfetch#776]
`hyprcursor` is a new cursor format we could detect.

**Comment by CarterLi** [comment]
I found very little information about hyprcursor. How can I use that in my DE (plasma)?

**Comment by CarterLi** [comment]
[The official doc](https://wiki.hyprland.org/Hypr-Ecosystem/hyprcursor/#hyprcursor-themes) suggests setting `$HYPRCURSOR_THEME` and `$HYPRCURSOR_SIZE`. However it didn't work for me. While `hyprctl setcursor` did work, but it didn't set the environment variables.

For now I just read the env vars. Let me know if you have a better idea.
