### ISSUE TITLE
[BUG]  fastfetch --gen-config raises SIGSEGV when ~/.config/fastfetch doesn't exist

### ISSUE THREAD

**Issue by BamgoeSN** [fastfetch-cli/fastfetch#778]
# General description of bug:
`fastfetch --gen-config` raises SIGSEGV when `~/.config/fastfetch` directory doesn't exist

* What happened: When `.config/fastfetch` doesn't exist, `fastfetch --gen-config` raises SIGSEGV. Works fine if it exists. I'm aware that https://github.com/fastfetch-cli/fastfetch/issues/690 exists.
* What should happen: Probably create the directory automatically and put a default config file there
* Did it work in an older version:  untested
* Where did you get the binary:  Arch Linux package repository https://archlinux.org/packages/extra/x86_64/fastfetch/
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? untested

# Often helpful information: Was on version 2.9.0 (x86_64)

Screenshot:

![20240407_21h12m43s_grim](https://github.com/fastfetch-cli/fastfetch/assets/60645387/a1a5ac22-cabd-4531-816f-19faa9dd5222)

The content of the configuration file you use (if any): None

Output of `fastfetch -c ci.jsonc --format json`:
 
[output.json](https://github.com/fastfetch-cli/fastfetch/files/14897129/output.json)

Output of `fastfetch --list-features`:
```
threads
vulkan
wayland
xcb-randr
xcb
xrandr
x11
drm
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
egl
glx
osmesa
opencl
libpulse
libnm
libddcutil
videodev2
Directx Headers
Proprietary GPU driver API
```

## If fastfatch crashed

Paste the stacktrace here. You may get it with:

```
$ gdb -q -ex 'set confirm off' -ex run -ex 'bt full' -ex quit --args /path/to/fastfetch
```
[output.txt](https://github.com/fastfetch-cli/fastfetch/files/14897141/output.txt)

**Comment by CarterLi** [comment]
Seems a regression from 4430b7145ebca48a6607133ebf58f3d8a7285211 @apocelipes

**Comment by CarterLi** [comment]
For now I will just revert the commit. The original code can be improved later.

**Comment by cd-CreepArghhh** [comment]
Wow that was fast. I was just typing up an issue report (since about 3 hours ago)...

**Comment by apocelipes** [comment]
@CarterLi @cd-CreepArghhh 
This issue can be fixed by checking the config path whether exists. I will send a PR for this.
