### ISSUE TITLE
[FEAT] Improving Linux cursor detection

### ISSUE THREAD

**Issue by kojq** [fastfetch-cli/fastfetch#783]
continuing #776, the most accurate way to get the `hyprcursor` name would be to use the env var to find the manifest and read the `name` from it. linking with `libhyprcursor` could also work. 

I will leave this here for reference:

https://github.com/hyprwm/hyprcursor/issues/20

**Comment by CarterLi** [comment]
ENV var being set doesn't necessarily mean that you WM/DE use it. Also, it doesn't play well with `hyprctl setcursor`

> linking with libhyprcursor could also work.

I didn't find a function that returns cursor theme name.

Before a solid method is found, I don't want to complicate the logic.
