### ISSUE TITLE
[win] flashfetch.exe v2.9.1.0 say about wrong font terminal?

### ISSUE THREAD

**Issue by Zeroes1** [fastfetch-cli/fastfetch#784]
it's bug or not? :)

Far Manger 3 x64/CMD ran in Windows Terminal  (**portative mode**)
i run under FAR/cmd flashfetch.exe after fastfetch.exe

flashfetch.exe say:

Terminal: Windows Terminal 1.21.2404.5001
Terminal Font: Cascadia Mono (12pt)
it's like default font for WT. wrong info
it's data from` "%LOCALAPPDATA%\Microsoft\Windows Terminal\settings.json"` 
it's right path if WT runned not portative mode

in **portative mode** setting here: `<folder where WindowsTerminal.exe>\settings\settings.json `

fastfetch.exe say:
Terminal Font: Fira Code (16pt)
right info

**Comment by CarterLi** [comment]
> Terminal: Windows Terminal 1.21.2404.5001
> Terminal Font: Cascadia Mono (12pt)
> it's like default font for WT. wrong info
> it's data from` "%LOCALAPPDATA%\Microsoft\Windows Terminal\settings.json"`

Fastfetch / Flashfetch assumes `Cascadia Mono` if it fails to find `settings.json`. Can you change the font configuration in `settings.json` to something else and see if flashfetch can detect the change?

**Comment by Zeroes1** [comment]
1) cmd under conhost;

fastfech:
Terminal: Windows Terminal Preview
Terminal Font: Cascadia Mono (12pt)

flashfetch:
Terminal: Windows Terminal Preview
Terminal Font: Cascadia Mono (12pt)

it's WT from
`"%LOCALAPPDATA%\Microsoft\WindowsApps\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe"`
i dont use this.

2) cmd under WT
same resut as FAR manager topic#1

3) if i rename `"%LOCALAPPDATA%\Microsoft\Windows Terminal\settings.json"`
to _settings.json
flashfetch.exe dont show info about font (skip the line :)
if i copy my portable `C:\UTILITY\Terminal\settings\settings.json `
to
`"%LOCALAPPDATA%\Microsoft\Windows Terminal\settings.json"`
flashfetch.exe show my font: Terminal Font: Fira Code (16pt)

**Comment by CarterLi** [comment]
Do you use WT preview version or standard version?

What does `fastfetch -s terminal --format json` print?

**Comment by CarterLi** [comment]
> 3\. flashfetch.exe dont show info about font (skip the line :)

Yeah, `settings.json` is expected to be created by WT. However, the font section will only be generated when users change the setting.

**Comment by CarterLi** [comment]
Okey. [The offical doc](https://learn.microsoft.com/en-us/windows/terminal/distributions#enabling-portable-mode) requires `.portable` to be a file. However WT does support `.portable` being a folder.

Will fix it. For now, you may change `.portable` to an empty file. Then fastfetch should work.

**Comment by Zeroes1** [comment]
1) I use portable version WT run from here:
C:\UTILITY\Terminal\

fastfetch -s terminal:terminalfont --format json 
`[
  {
    "type": "Terminal",
    "result": {
      "processName": "WindowsTerminal.exe",
      "exe": "C:\\UTILITY\\Terminal\\WindowsTerminal.exe",
      "exeName": "WindowsTerminal.exe",
      "exePath": "C:\\UTILITY\\Terminal\\WindowsTerminal.exe",
      "pid": 9524,
      "ppid": 7772,
      "prettyName": "Windows Terminal",
      "version": "1.21.2404.5001",
      "tty": ""
    }
  },
  {
    "type": "TerminalFont",
    "result": {
      "font": {
        "name": "Fira Code",
        "size": "16",
        "styles": [],
        "pretty": "Fira Code (16pt)"
      },
      "fallback": {
        "name": "",
        "size": "",
        "styles": [],
        "pretty": ""
      }
    }
  }
]
` 
it same result if make (under cmd over WT)
fastfetch -s terminal:terminalfont --format json > config.txt

but if make (under Far Manager over WT)
fastfetch -s terminal:terminalfont --format json > config.txt
i got wrong info:

`[
  {
    "type": "Terminal",
    "result": {
      "processName": "Far.exe",
      "exe": "C:\\Far4\\Far.exe",
      "exeName": "Far.exe",
      "exePath": "C:\\Far4\\Far.exe",
      "pid": 11200,
      "ppid": 9524,
      "prettyName": "Far",
      "version": "3.0.6302.0",
      "tty": ""
    }
  },
  {
    "type": "TerminalFont",
    "error": "Unknown terminal: Far.exe"
  }
]
`
Another BUG?

if run under ( Far Manager over WT)
fastfetch -s terminal:terminalfont --format json 
on screen out right information (like cmd)

**Comment by Zeroes1** [comment]
trouble only if i redirecting output to file (under FAR under WT)
if i out to screen to all OK

**Comment by CarterLi** [comment]
far.exe will be ignored when detecting terminal. Please try the latest dev build.

**Comment by Zeroes1** [comment]
lol
at home 
i no have trouble #2 with 2.9.1.0 relis

about #1 
i download latest dev
https://github.com/fastfetch-cli/fastfetch/actions/runs/8602897045/artifacts/1394775325

but flashfetch.exe skip line with font, fastfetch.exe show rght info

![image](https://github.com/fastfetch-cli/fastfetch/assets/11919060/9f146d40-f343-4745-9b66-6fd69419afe7)

**Comment by Zeroes1** [comment]
![image](https://github.com/fastfetch-cli/fastfetch/assets/11919060/e6afcead-6e4a-4f07-ae9a-2bfdd2d95e8d)

**Comment by CarterLi** [comment]
I can't reproduce it. fastfetch and flashfetch share the same code for terminal font detection.  It should work.

**Comment by Zeroes1** [comment]
i check situation atwork (first found problem area)
№2 trouble is gone

but №1 anyway LATEST DEV build flashfetch.exe try get info about terminal font  wrong path `"%LOCALAPPDATA%\Microsoft\Windows Terminal\settings.json"` - it's not current setting 
fastfetch.exe get from right path - `C:\UTILITY\Terminal\settings\settings.json`

may be later i check code himself...

**Comment by Zeroes1** [comment]
may be help info for found trouble:

latest DEV
fastfetch.exe -c ci.jsonc
say:
Terminal Font: Cascadia Mono (12pt)

fastfetch.exe -c  software.jsonc 
say
Terminal Font: Fira Code (16pt)

=)

**Comment by CarterLi** [comment]
Still make no difference for me.

Please make sure that fastfetch succeeded in finding the full path of terminal process.

That is to say, `fastfetch -c ci.jsonc --format json` should print something like

```jsonc
  {
    "type": "Terminal",
    "result": {
      "processName": "WindowsTerminal.exe",
      "exe": "C:\\Users\\zhang\\Desktop\\terminal-1.19.10821.0\\WindowsTerminal.exe",
      "exeName": "WindowsTerminal.exe",
      "exePath": "C:\\Users\\zhang\\Desktop\\terminal-1.19.10821.0\\WindowsTerminal.exe", // full, absolute path; not relative path or file name only.
      "pid": 10768,
      "ppid": 5608,
      "prettyName": "Windows Terminal",
      "version": "1.19.2403.22001",
      "tty": ""
    }
  }
```
