### ISSUE TITLE
[BUG] Shell & Terminal detection broken with /bin/sh as login shell

### ISSUE THREAD

**Issue by JamiKettunen** [fastfetch-cli/fastfetch#798]
https://github.com/fastfetch-cli/fastfetch/blob/2.9.2/src/detection/terminalshell/terminalshell_linux.c#L222 is a problem on [Chimera Linux](https://chimera-linux.org) for example where `/bin/sh` is the default shell unless you install and start using something else.

Since `fastfetch` is [packaged in the `contrib` repo](https://pkgs.chimera-linux.org/packages?name=fastfetch) one could simply run this post-install and see broken `Shell: kgx` & `Terminal: dinit`
```
doas apk add chimera-repo-contrib
doas apk add fastfetch
fastfetch
```
Regarding the comment shouldn't pipes/redirects be detected with something similar to [`test -t 1`](https://man.archlinux.org/man/test.1.en#t) in shellscript or are there other cases this also happens to catch? Maybe some smarter heuristic could be done anyway :)

**Comment by CarterLi** [comment]
Please check the latest dev build works for you
