### ISSUE TITLE
About removal of AUR from readme

### ISSUE THREAD

**Issue by FabioLolix** [fastfetch-cli/fastfetch#804]
Hello, I have casually seen the changelog

https://github.com/fastfetch-cli/fastfetch/pull/801/commits/7c2c631807b5262c09885063d0ff36788ea2ec22

AUR `-git` pkgbuilds pull the latest commit, in this case from the `dev` branch, at build time

those pkgbuild aren't outdated and updating for every new version is unwanted FYI

**Comment by CarterLi** [comment]
It's outdated. Something no longer exists ( eg. `/etc/fastfetch/config.conf` ) and it doesn't seem to get maintained any more.

Fastfetch releases new versions often. Normal users should use the Archlinux official build

**Comment by FabioLolix** [comment]
I have adopted and updated the pkgbuild https://aur.archlinux.org/cgit/aur.git/commit/?h=fastfetch-git&id=bd4539211ff284db2176fba821acf66ca718e8b9
