### ISSUE TITLE
[FEAT] glibc version compatibility & statically linked builds

### ISSUE THREAD

**Issue by hykilpikonna** [fastfetch-cli/fastfetch#808]
## Wanted features:

Add some statically linked builds on github release.

## Motivation:

The github release for linux amd64 is not runnable on older versions of ubuntu 20 LTS.

![image](https://github.com/fastfetch-cli/fastfetch/assets/22280294/c35a0c2d-3d2c-4591-b5a1-64b3eacd2733)

![image](https://github.com/fastfetch-cli/fastfetch/assets/22280294/838509b6-2150-4071-8906-d4e26c4cee8e)

**Comment by CarterLi** [comment]
If you don't trust me, you may try it yourself.

**Comment by hykilpikonna** [comment]
> It won't work even for MUSL build. Otherwise it has been done years ago.

Okay, that's fair. Would it be possible to change the build target to lower glibc versions? (e.g. 2.12)? Afaik the latest glibc should be compatible with any version after 2.0.

**Comment by CarterLi** [comment]
Fastfetch uses Github Action to build binaries, which supports only ubuntu 20.04 and newer.

The binaries released by fastfetch were built with 22.04. If you need old glibc version support, you may download the artifacts named [fastfetch-linux-old-amd64](https://github.com/fastfetch-cli/fastfetch/actions/runs/8796585816/artifacts/1438469592)

**Comment by hykilpikonna** [comment]
> The binaries released by fastfetch were built with 22.04. If you need old glibc version support, you may download the artifacts named [fastfetch-linux-old-amd64](https://github.com/fastfetch-cli/fastfetch/actions/runs/8796585816/artifacts/1438469592)

Thanks! Do you want to maybe publish the linux-old build on GitHub releases as well? Or change the default to Ubuntu 20.04? It's a little bit strange to abandon support for 20.04 LTS since it's still being supported and hasn't reached EOL yet.

**Comment by Azathothas** [comment]
> > The github release for linux amd64 is not runnable on older versions of ubuntu 20 LTS.
> 
> It was documented in the [README](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#linux)
> 
> > Add some statically linked builds on github release
> 
> It won't work even for MUSL build. Otherwise it has been done years ago.

Actually, it is possible to build statically linked musl binaries by changing a few cmake flags.
This is how I do it: 
- https://github.com/Azathothas/Toolpacks/blob/main/.github/scripts/x86_64_Linux/bins/fastfetch.sh
- https://github.com/Azathothas/Toolpacks/blob/main/.github/scripts/aarch64_Linux/bins/fastfetch.sh
```bash
---snip---
git clone --filter "blob:none" --quiet "https://github.com/fastfetch-cli/fastfetch" && cd "./fastfetch"
         mkdir -p "./STATIC_BUILD"
         cmake -DCMAKE_C_FLAGS="-O2 -flto=auto -static -w -pipe" \
         -DCMAKE_EXE_LINKER_FLAGS="-static -s -Wl,-S -Wl,--build-id=none" \
         -DCMAKE_BUILD_TYPE="Release" \
         -DCMAKE_INSTALL_PREFIX="/usr" \
         -DIS_MUSL="ON" \
         -DBUILD_SHARED_LIBS="Off" \
         -DBUILD_TESTS="Off" \
         -DSET_TWEAK="Off" \
         -GNinja \
         -B "./STATIC_BUILD"
         cmake --build "./STATIC_BUILD" --target package -j"$(($(nproc)+1))"
---snip---

!# Verify 
# You can run the binary in a minimal alpne docker image and it works perfectly
# The (ldd | file | du -sh) output are:
./fastfetch: not a dynamic executable | ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped | 1.5M
./flashfetch: not a dynamic executable | ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped | 1.3M
```

You can test the binaries yourself:
- https://bin.ajam.dev/x86_64_Linux/fastfetch
- https://bin.ajam.dev/x86_64_Linux/flashfetch

**Comment by hykilpikonna** [comment]
> Actually, it is possible to build statically linked musl binaries by changing a few cmake flags. This is how I do it:

Oh great! This helps a lot in terms of building compatible binaries. Thanks!

**Comment by CarterLi** [comment]
> > > The github release for linux amd64 is not runnable on older versions of ubuntu 20 LTS.
> > 
> > 
> > It was documented in the [README](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#linux)
> > > Add some statically linked builds on github release
> > 
> > 
> > It won't work even for MUSL build. Otherwise it has been done years ago.
> 
> Actually, it is possible to build statically linked musl binaries by changing a few cmake flags. This is how I do it:
> 
> * https://github.com/Azathothas/Toolpacks/blob/main/.github/scripts/x86_64_Linux/bins/fastfetch.sh
> * https://github.com/Azathothas/Toolpacks/blob/main/.github/scripts/aarch64_Linux/bins/fastfetch.sh
> 
> ```shell
> ---snip---
> git clone --filter "blob:none" --quiet "https://github.com/fastfetch-cli/fastfetch" && cd "./fastfetch"
>          mkdir -p "./STATIC_BUILD"
>          cmake -DCMAKE_C_FLAGS="-O2 -flto=auto -static -w -pipe" \
>          -DCMAKE_EXE_LINKER_FLAGS="-static -s -Wl,-S -Wl,--build-id=none" \
>          -DCMAKE_BUILD_TYPE="Release" \
>          -DCMAKE_INSTALL_PREFIX="/usr" \
>          -DIS_MUSL="ON" \
>          -DBUILD_SHARED_LIBS="Off" \
>          -DBUILD_TESTS="Off" \
>          -DSET_TWEAK="Off" \
>          -GNinja \
>          -B "./STATIC_BUILD"
>          cmake --build "./STATIC_BUILD" --target package -j"$(($(nproc)+1))"
> ---snip---
> 
> !# Verify 
> # You can run the binary in a minimal alpne docker image and it works perfectly
> # The (ldd | file | du -sh) output are:
> ./fastfetch: not a dynamic executable | ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped | 1.5M
> ./flashfetch: not a dynamic executable | ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped | 1.3M
> 
> !# Features
> ❯ fastfetch --list-features
> Proprietary GPU driver API
> chafa
> dbus
> dconf
> drm
> egl
> gio
> imagemagick7
> libddcutil
> libnm
> libpulse
> linux/videodev2
> linux/wireless
> opencl
> osmesa
> sqlite3
> threads
> vulkan
> wayland
> x11
> xcb
> xcb-randr
> xfconf
> xrandr
> zlib
> ```
> 
> You can test the binaries yourself:
> 
> * https://bin.ajam.dev/x86_64_Linux/fastfetch
> * https://bin.ajam.dev/x86_64_Linux/flashfetch

This doesn't **actually** work. Fastfetch makes heavy uses of `dlopen`, and an statically linked binary can't use that.

![image](https://github.com/fastfetch-cli/fastfetch/assets/6134068/0f299100-3c9e-4e78-9990-ee251ba70ac8)

Take `Packages` module as an example. `RPM` uses `libsqlite` to read `rpmdb.sqlite`. However `dlopen` in a statically linked binary always fails.

A program runs doesn't mean it works. I'm the author, trust me.

**Comment by Azathothas** [comment]
> > > > The github release for linux amd64 is not runnable on older versions of ubuntu 20 LTS.
> > > 
> > > 
> > > It was documented in the [README](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#linux)
> > > > Add some statically linked builds on github release
> > > 
> > > 
> > > It won't work even for MUSL build. Otherwise it has been done years ago.
> > 
> > 
> > Actually, it is possible to build statically linked musl binaries by changing a few cmake flags. This is how I do it:
> > 
> > * https://github.com/Azathothas/Toolpacks/blob/main/.github/scripts/x86_64_Linux/bins/fastfetch.sh
> > * https://github.com/Azathothas/Toolpacks/blob/main/.github/scripts/aarch64_Linux/bins/fastfetch.sh
> > 
> > ```shell
> > ---snip---
> > git clone --filter "blob:none" --quiet "https://github.com/fastfetch-cli/fastfetch" && cd "./fastfetch"
> >          mkdir -p "./STATIC_BUILD"
> >          cmake -DCMAKE_C_FLAGS="-O2 -flto=auto -static -w -pipe" \
> >          -DCMAKE_EXE_LINKER_FLAGS="-static -s -Wl,-S -Wl,--build-id=none" \
> >          -DCMAKE_BUILD_TYPE="Release" \
> >          -DCMAKE_INSTALL_PREFIX="/usr" \
> >          -DIS_MUSL="ON" \
> >          -DBUILD_SHARED_LIBS="Off" \
> >          -DBUILD_TESTS="Off" \
> >          -DSET_TWEAK="Off" \
> >          -GNinja \
> >          -B "./STATIC_BUILD"
> >          cmake --build "./STATIC_BUILD" --target package -j"$(($(nproc)+1))"
> > ---snip---
> > 
> > !# Verify 
> > # You can run the binary in a minimal alpne docker image and it works perfectly
> > # The (ldd | file | du -sh) output are:
> > ./fastfetch: not a dynamic executable | ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped | 1.5M
> > ./flashfetch: not a dynamic executable | ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped | 1.3M
> > 
> > !# Features
> > ❯ fastfetch --list-features
> > Proprietary GPU driver API
> > chafa
> > dbus
> > dconf
> > drm
> > egl
> > gio
> > imagemagick7
> > libddcutil
> > libnm
> > libpulse
> > linux/videodev2
> > linux/wireless
> > opencl
> > osmesa
> > sqlite3
> > threads
> > vulkan
> > wayland
> > x11
> > xcb
> > xcb-randr
> > xfconf
> > xrandr
> > zlib
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can test the binaries yourself:
> > 
> > * https://bin.ajam.dev/x86_64_Linux/fastfetch
> > * https://bin.ajam.dev/x86_64_Linux/flashfetch
> 
> This doesn't **actually** work. Fastfetch makes heavy uses of `dlopen`, but an statically linked binary can't use that.
> 
> ![image](https://private-user-images.githubusercontent.com/6134068/326263569-0f299100-3c9e-4e78-9990-ee251ba70ac8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMTQ3MzksIm5iZiI6MTcxNDMxNDQzOSwicGF0aCI6Ii82MTM0MDY4LzMyNjI2MzU2OS0wZjI5OTEwMC0zYzllLTRlNzgtOTk5MC1lZTI1MWJhNzBhYzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjhUMTQyNzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWJkZGM4NjFiYTc3N2M5MGViMGY5NGE5NGUxNzQ5YzY5MWZkYTU1MzNjOGQ5ZTRjYTdhZGNlZWM4Njc5MDdiMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FYMzaeGOfX-3NneDMuhdTxtS5xTBG7lDvHNpBW62wjE)
> 
> Take `Packages` module as an example. `RPM` uses `libsqlite` to read `rpmdb.sqlite`. However `dlopen` in a statically linked binary always fails.
> 
> A program runs doesn't mean it works. I'm the author, trust me.

Ah I see.
I use fastfetch similar to how I use neofetch. Nothing like you have showed in the screenshot. So some features that can't be built statically is okay for me.
Though it might be possible to convert the dynamically linked full featured binary using https://github.com/JonathonReinhart/staticx

**Comment by CarterLi** [comment]
> # Try the binary yourself: https://bin.ajam.dev/x86_64_Linux/fastfetch-staticx

It crashes.

It's easy to check whether the binary work or not. You should try `fastfetch -s sound`

**Comment by Azathothas** [comment]
> > Try the binary yourself: https://bin.ajam.dev/x86_64_Linux/fastfetch-staticx
> 
> It crashes.
> 
> It's easy to check whether the binary work or not. You should try `fastfetch -s sound --show-errors` and it should not print `Sound: Failed to load libpulse.so`

That's because I used the precompiled binary that are released here (https://github.com/fastfetch-cli/fastfetch/releases/download/2.10.2/fastfetch-linux-amd64.tar.gz) , which also crashes
![image](https://github.com/fastfetch-cli/fastfetch/assets/58171889/f405dd44-415c-42b0-88f3-1b0a4636a895)

If you have `libpulse.so` on your system (I am using the default GH Runner Ubuntu Image which doesn't) and then you create it, that will be included in the staticx version.

**Comment by CarterLi** [comment]
![image](https://github.com/fastfetch-cli/fastfetch/assets/6134068/547d9647-cd5a-413c-8dec-a2a638392a41)

This is what I meant **crash**

**Comment by CarterLi** [comment]
This is what I meant *test`

![image](https://github.com/fastfetch-cli/fastfetch/assets/6134068/91b854e9-0c4d-4886-92a3-945a6cc73b88)

**Comment by Azathothas** [comment]
Hmm, interesting.
I always test all my binaries on the absolute most minimal containers,
and thus far these all work and function (except for the `libpulse.so`).
staticx isn't true static anyways, so crash is expected. But if you can, please link/upload the fastfetch binary you have on your system here, so I can take a look.
Regardless, there should be a static release which has few features removed, so people can use it anywhere. 
At the very least, this issue should provide reference to people who want to tinker with this in the future.

**Comment by CarterLi** [comment]
If you don't have `libpulse` installed, you may also try opengl, vulkan, media, song...

![image](https://github.com/fastfetch-cli/fastfetch/assets/6134068/091894e4-e1c4-4b10-8613-74602f6dc25b)

**Comment by Azathothas** [comment]
> If you don't have `libpulse` installed, you may also try opengl, vulkan, media, song...
> 
> ![image](https://private-user-images.githubusercontent.com/6134068/326268094-091894e4-e1c4-4b10-8613-74602f6dc25b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMTc2MjcsIm5iZiI6MTcxNDMxNzMyNywicGF0aCI6Ii82MTM0MDY4LzMyNjI2ODA5NC0wOTE4OTRlNC1lMWM0LTRiMTAtODYxMy03NDYwMmY2ZGMyNWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjhUMTUxNTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmJiNTg0YWM4NWQ5MTg0OTIwYTU3Y2ZiNGMzODUwYTc1Yzk1MDM2NWQ0ZDQ4MmFhMTNkNjZiM2VkYzY1NzZhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xqvB5E3072S6sgFiKgdZWnqcTs9-ykeyaJLZrnEWf6c)

If we are talking in terms of regular distros and "real-systems" instead of containers, the very same container GH Actions uses to release the binaries of fastfetch, then sure.
But the problem is that the official GH Actions doesn't have a display or `opengl, vulkan, media, song` so I can't build a staticx binary with those libs included.
I had really appreciate it if you could provide the fastfetch binary from your system.

**Comment by CarterLi** [comment]
> > If you don't have `libpulse` installed, you may also try opengl, vulkan, media, song...
> > ![image](https://private-user-images.githubusercontent.com/6134068/326268094-091894e4-e1c4-4b10-8613-74602f6dc25b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMTc2MjcsIm5iZiI6MTcxNDMxNzMyNywicGF0aCI6Ii82MTM0MDY4LzMyNjI2ODA5NC0wOTE4OTRlNC1lMWM0LTRiMTAtODYxMy03NDYwMmY2ZGMyNWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjhUMTUxNTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmJiNTg0YWM4NWQ5MTg0OTIwYTU3Y2ZiNGMzODUwYTc1Yzk1MDM2NWQ0ZDQ4MmFhMTNkNjZiM2VkYzY1NzZhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xqvB5E3072S6sgFiKgdZWnqcTs9-ykeyaJLZrnEWf6c)
> 
> If we are talking in terms of regular distros and "real-systems" instead of containers, the very same container GH Actions uses to release the binaries of fastfetch, then sure. But the problem is that the official GH Actions doesn't have a display or `opengl, vulkan, media, song` so I can't build a staticx binary with those libs included. I had really appreciate it if you could provide the fastfetch binary from your system.

I downloaded the binary **from Github releases**

**Comment by CarterLi** [comment]
> But the problem is that the official GH Actions doesn't have a display or opengl, vulkan, media, song so I can't build a staticx binary with those libs included.

A container doesn't have a display or opengl, vulkan, media, song, doesn't mean it can't build a binary that uses so libs that connect a display or opengl, vulkan, media, song.

**Comment by Azathothas** [comment]
Ah yes, my bad.
staticx finds and links from your own system, so ofc it won't build on actions. It finds and packs libs at runtime.
if you really want to tinker:
```bash
!# Install : https://staticx.readthedocs.io/en/latest/installation.html
# Make sure you also have: ldd , readelf, objcopy, patchelf (https://github.com/NixOS/patchelf) & scons

!# After you have installed those, you can create a staticx binary using:
staticx --loglevel DEBUG "./fastfetch-dynamic" --strip "./fastfetch-staticx"

!# Try the staticx build now it should mostly work
```

**Comment by CarterLi** [comment]
> staticx finds and links from your own system, so ofc it won't build on actions. It finds and packs libs at runtime.

So I have to build in my machine? Then what's the point of static link?

Talk is cheap. Unless you provide the binary, your words is meaningless.

**Comment by Azathothas** [comment]
> > staticx finds and links from your own system, so ofc it won't build on actions. It finds and packs libs at runtime.
> 
> So I have to build in my machine? Then what's the point of static link?
> 
> Talk is cheap. Unless you provide the binary, your words is meaningless.

Once you build the binary from a machine where staticx can find and pack as much features/runtime deps as possible, you can then release those binaries here on your repo.
Those binaries will work anywhere.

**Comment by CarterLi** [comment]
Talk is cheap.
