### ISSUE TITLE
[FEAT] Ability to add other package managers via config files

### ISSUE THREAD

**Issue by dnkmmr69420** [fastfetch-cli/fastfetch#813]
## Before requesting a new feature

* A lot of features are not enabled by default. Please try `fastfetch --list-modules` and `fastfetch -c all.jsonc` to see if it has been supported
* Fastfetch supports `Command` module, which can be used to grab output from a custom shell script. Please check if it fits your needs

## Wanted features:

I would like to add other package managers using configs. There would be at least these two parts for the config, the command that is ran and the display name (what it displays in the fastfetch)

## Motivation:

I would find it useful for it to count packages in containers. I have a very specific use for my own project [Brew Container](https://github.com/dnkmmr69420/brew-container) where it would run `cbrew` to count the packages in my homebrew container

If you are unable to get this implemwnted, can you at least add `cbrew` with the option to disable it?

**Comment by CarterLi** [comment]
I'm not sure I get it correctly. Do you want to display the package count for your project cbrew in fastfetch? In this case I think `Command` module is enough to use.

**Comment by dnkmmr69420** [comment]
Will I need to modify source code?

**Comment by dnkmmr69420** [comment]
> I'm not sure I get it correctly. Do you want to display the package count for your project cbrew in fastfetch? In this case I think `Command` module is enough to use.

and how would I do that?

**Comment by CarterLi** [comment]
![image](https://github.com/fastfetch-cli/fastfetch/assets/6134068/9779c5a2-4541-4687-99ab-9b7d819cefdf)

**Comment by dnkmmr69420** [comment]
it didn't work

```

{
    "modules": [
        {
            "type": "command",
            "text": "/usr/bin/env brew list",
            "key": "Packages"
        }
    ]
}
```
just got the os logo with no stats at all

![image](https://github.com/fastfetch-cli/fastfetch/assets/104856296/ffbecb76-a198-47ce-b406-fe752b217137)
