### ISSUE TITLE
[BUG] Reported processor speeds are incorrect on some machines.

### ISSUE THREAD

**Issue by AcatXIo** [fastfetch-cli/fastfetch#815]
# General description of the bug:

* What happened:
I noticed that Fastfetch shows either the turbo or the regular processor speed depending on which machine I run it on; in one case, the reported speed was totally incorrect.
Tested machines (first 3 run Windows 11, and number 4 runs Windows 10):
  1. Toshiba Satellite P755 with Intel Core i7-2670QM:
      - shown speed: 3.8 GHz **(♦️totally incorrect)**
      - processor turbo speed: 3.1 GHz
      - processor regular speed: 2.2 GHz
   2. Dell Latitude 5490 with Intel Core i5-7300U:
      - shown speed: 3.5 GHz **(🔷correct turbo)**
      - processor turbo speed: 3.5 GHz
      - processor regular speed: 2.6 GHz
   3. HP OMEN 15-ce0xx with Intel Core i7-7700HQ:
      - shown speed: 2.81 GHz **(🔶correct regular)**
      - processor turbo speed: 3.8 GHz
      - processor regular speed: 2.8 GHz
   4. HP ProBook 6460b with Intel Core i5-2410M:
      - shown speed: 2.3 GHz **(🔶correct regular)**
      - processor turbo speed: 2.9 GHz
      - processor regular speed: 2.3 GHz
* What should happen:
Fastfetch should tell the user which processor speed it is showing: the regular one or the turbo, and the speed should be correct.
* Fastfetch version used: 2.10.2 (x86_64).
* Did it work in an older version: No.
* Where did you get the binary: From Scoop package manager for Windows.
* Does this issue still occur in the latest dev build: Yes.

# Often helpful information:

Screenshots:

![image](https://github.com/fastfetch-cli/fastfetch/assets/141344817/557e73bf-84d5-4cfc-bac6-3acd8c799272)
![image](https://github.com/fastfetch-cli/fastfetch/assets/141344817/e4300938-603f-440d-a6b4-36acd8a636c9)
![image](https://github.com/fastfetch-cli/fastfetch/assets/141344817/b9961751-5f1a-4831-b6e8-965b7d0def9f)
![image](https://github.com/fastfetch-cli/fastfetch/assets/141344817/7a9b1e1d-a101-4d3f-ad1a-1dff88093860)

The content of the configuration file you use (if any): Not used.

Outputs of `fastfetch -c ci.jsonc --format json` (I only included the processors; feel free to ask for the rest if needed.):
```json
{
  "type": "CPU",
  "result": {
    "cpu": "Intel(R) Core(TM) i7-2670QM",
    "vendor": "GenuineIntel",
    "cores": {
      "physical": 4,
      "logical": 8,
      "online": 8
    },
    "frequency": {
      "base": 2.195,
      "max": 3.8,
      "min": null
    },
    "temperature": null
  },
  "stat": 0
},
{
  "type": "CPUUsage",
  "result": [
    0.0,
    0.0,
    0.0,
    75.0,
    0.0,
    0.0,
    7.6923076923076925,
    0.0
  ],
  "stat": 207
}
```
```json
{
  "type": "CPU",
  "result": {
    "cpu": "Intel(R) Core(TM) i5-7300U",
    "vendor": "GenuineIntel",
    "cores": {
      "physical": 2,
      "logical": 4,
      "online": 4
    },
    "frequency": {
      "base": 2.712,
      "max": 3.5,
      "min": null
    },
    "temperature": null
  },
  "stat": 0
},
{
  "type": "CPUUsage",
  "result": [
    0.0,
    7.142857142857142,
    42.857142857142854,
    0.0
  ],
  "stat": 213
}
```
```json
{
  "type": "CPU",
  "result": {
    "cpu": "Intel(R) Core(TM) i7-7700HQ",
    "vendor": "GenuineIntel",
    "cores": {
      "physical": 4,
      "logical": 8,
      "online": 8
    },
    "frequency": {
      "base": 2.808,
      "max": null,
      "min": null
    },
    "temperature": null
  },
  "stat": 1
},
{
  "type": "CPUUsage",
  "result": [
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0
  ],
  "stat": 206
}
```
```json
{
  "type": "CPU",
  "result": {
    "cpu": "Intel(R) Core(TM) i5-2410M",
    "vendor": "GenuineIntel",
    "cores": {
      "physical": 2,
      "logical": 4,
      "online": 4
    },
    "frequency": {
      "base": 2.295,
      "max": 2.3,
      "min": null
    },
    "temperature": null
  },
  "stat": 0
},
{
  "type": "CPUUsage",
  "result": [
    21.428571428571427,
    14.285714285714285,
    14.285714285714285,
    50.0
  ],
  "stat": 205
}
```
Output of `fastfetch --list-features` (for all machines):
```
threads
vulkan
zlib
opencl
Proprietary GPU driver API
```

**Comment by CarterLi** [comment]
SMBIOS sometimes report incorrect max CPU freq. Please try this: https://github.com/fastfetch-cli/fastfetch/issues/800#issuecomment-2067510772

**Comment by AcatXIo** [comment]
Here are the processor values (in the same order as above), I also added comments:
```
Length: 0x2A
Socket Designation: CPU 1
Processor Type: Central Processor
Processor Family:
Processor ID:
Processor Manufacturer: Intel
Processor Version: Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz
External Clock: 400MHz, 0MHz is unknown clock
Max Speed: 3800MHz <- wrong, should be 3100 MHz
Current Speed: 2200MHz <- correct
Status: 0x41
```
```
Length: 0x30
Socket Designation: U3E1
Processor Type: Central Processor
Processor Family:
Processor ID:
Processor Manufacturer: Intel(R) Corporation
Processor Version: Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
External Clock: 100MHz, 0MHz is unknown clock
Max Speed: 3500MHz <- correct
Current Speed: 2300MHz <- wrong, should be 2600 MHz
Status: 0x41
```
```
Length: 0x30
Socket Designation: U3E1
Processor Type: Central Processor
Processor Family:
Processor ID:
Processor Manufacturer: Intel(R) Corporation
Processor Version: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
External Clock: 100MHz, 0MHz is unknown clock
Max Speed: 8300MHz <- very wrong, should be 3800 MHz
Current Speed: 2700MHz <- slightly wrong, should be 2800 MHz
Status: 0x41
```
```
Length: 0x2A
Socket Designation: CPU 1
Processor Type: Central Processor
Processor Family:
Processor ID:
Processor Manufacturer: Intel(R) Corporation
Processor Version: Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz
External Clock: 100MHz, 0MHz is unknown clock
Max Speed: 2300MHz <- wrong, should be 2900 MHz
Current Speed: 2300MHz <- correct
Status: 0x41
```

**Comment by CarterLi** [comment]
Can you try this ( assume Hyper-V / WSL2 is not enabled in your laptop ): https://github.com/fastfetch-cli/fastfetch/actions/runs/8860739281/artifacts/1453433558

**Comment by AcatXIo** [comment]
With new one (first is the CPU line from `fastfetch.exe`, second is frequency part from `fastfetch.exe -c ci.jsonc --format json`):
```
CPU: Intel(R) Core(TM) i7-2670QM (8) @ 3,80 GHz
"frequency": {
	"base": 2.195, <- correct
	"max": 3.8, <- wrong, should be 3.1
	"min": null
}
```
```
CPU: Intel(R) Core(TM) i5-7300U (4) @ 3,50 GHz
"frequency": {
	"base": 2.7, <- correct
	"max": 3.5, <- correct
	"min": null
}
```
```
CPU: Intel(R) Core(TM) i7-7700HQ (8) @ 2.81 GHz
"frequency": {
	"base": 2.808, <- correct
	"max": null, <- should be 3.8
	"min": null
}
```
```
CPU: Intel(R) Core(TM) i5-2410M (4) @ 2,30 GHz
"frequency": {
	"base": 2.295, <- correct
	"max": 2.3, <- wrong, should be 2.9
	"min": null
}
```
Apparently the only change is 2.712 being rounded to 2.7 for i5-7300U?
I double-checked to use the new version, but I'm not 100% sure if I'm doing everything correctly.
Does Fastfetch have some caching or something?

**Comment by CarterLi** [comment]
You didnt have WSL2 / virtual machine platform enabled right?

**Comment by CarterLi** [comment]
According to https://stackoverflow.com/a/39620056, the method is only supported in Skylake (6th gen) and later. Its expected no change for old cpus

**Comment by AcatXIo** [comment]
> You didnt have WSL2 / virtual machine platform enabled right?

The laptop with i7-7700HQ is not a VM; but I had virtualization enabled in BIOS, after I disabled it, Fastfetch now shows:
```
CPU: Intel(R) Core(TM) i7-7700HQ (8) @ 3.8 GHz
"frequency": {
	"base": 2.8, <- correct
	"max": 3.8, <- correct
	"min": null
}
```
So it now works correctly, but why does it depend on disabling virtualization in BIOS?
I had it on because I sometimes use Android emulators.
Is it possible to make the speed be detected correctly regardless of this setting?

**Comment by Null-Ping** [comment]
> @Null-Ping @lostdusty Can you also test it?

Sure!
The results are as follows:
```
CPU: 11th Gen Intel(R) Core(TM) i3-1125G4 (8) @ 3,7 GHz
```
```json
  "frequency": {
  "base": 1.2,
  "max": 3.7,
  "min": null
}
```
Everything is correct, but I also had to disable virtualization like **AcatXIo** did, apparently my laptop had it on by default.
Before I turned it off the results were:
```json
  "frequency": {
  "base": 1.19,
  "max": null,
  "min": null
}
```

**Comment by lostdusty** [comment]
> @lostdusty Can you also test it?
Nope, sorry (I'll be away from my pc for about ~2 weeks, or maybe even more). But I have both virtualization and VT-x enabled. Also my processor is from the 7th gen, just like the i7-7700HQ.

**Comment by AcatXIo** [comment]
> I guess virtualization features makes the smbios report the wrong frequency, even if it shows the right one in bios.

I tested, and the SMBIOS for i7-7700HQ with virtualization off is still the same:
```
Max Speed: 8300MHz <- should be 3800 MHz
Current Speed: 2700MHz <- should be 2800 MHz
```
So the virtualization setting likely doesn't affect the SMBIOS data.

**Comment by CarterLi** [comment]
You don't need to disable VT-x / AMD-v in BIOS, and it's recommanded to enable it to get better VM performance.

You need to disable Virtual Machine Platform in Windows Features ( note WSL2 and WSA use that )

https://support.microsoft.com/en-us/windows/options-to-optimize-gaming-performance-in-windows-11-a255f612-2949-4373-a566-ff6f3f474613#ID0EDD

![img](https://support.content.office.net/en-us/media/cbbf67fd-9ace-45fd-a72f-10ff3f9b5e02.png)

**Comment by CarterLi** [comment]
I think this is the best result that fastfetch can get as for now. SMBIOS still seems ok for people uses WSL2 on newer CPUs ( like me ) so I want to keep it.
