### ISSUE TITLE
Request testing of AMD card users

### ISSUE THREAD

**Issue by yai-dev** [fastfetch-cli/fastfetch#816]
# General description of bug:

* What happened: I had 2 gpus on my laptop: AMD integrated GPU and NVIDIA 3060 Mobile (discrete gpu), fastfetch detected AMD as dGPU but no NVIDIA 3060 Mobile
* What should happen: NVIDIA 3060 Mobile should be detected to dGPU but not AMD integrated GPU
* Fastfetch version used: fastfetch 2.10.2-debug (x86_64)
* Did it work in an older version: IDK
* Where did you get the binary: ArchLinux Offcial Repository
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)?

# Often helpful information:

Screenshot:
![image](https://github.com/fastfetch-cli/fastfetch/assets/20114873/3e6f3d89-280f-4b06-a4c1-fbc21fc4f7fe)

The content of the configuration file you use (if any):
There has no configuration file i used

Output of `fastfetch --list-features`:
```
threads
vulkan
wayland
xcb-randr
xcb
xrandr
x11
drm
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
egl
glx
osmesa
opencl
libpulse
libnm
libddcutil
videodev2
Directx Headers
Proprietary GPU driver API
System yyjson
```

**Comment by yai-dev** [comment]
FYI: when i run fastfetch with flag `--gpu-force-vulkan`, outputs is correct:

![image](https://github.com/fastfetch-cli/fastfetch/assets/20114873/23635d71-2a9f-41aa-a4dc-f088389961aa)

**Comment by yai-dev** [comment]
I think is these codes cause wrong detection: https://github.com/fastfetch-cli/fastfetch/blob/bdd2908e6ae152bf011797230ec40881c89f9623/src/detection/gpu/gpu_linux.c#L67

**Comment by CarterLi** [comment]
I actually don't have an AMD GPU. Can you paste the result of following command here?

```
cat /sys/class/drm/card{0,1,2}/device/{mem_info_vram_total,mem_info_vram_used,mem_info_vis_vram_total,mem_info_vis_vram_used,mem_info_gtt_total,mem_info_gtt_used,smartshift_apu_power,smartshift_dgpu_power,smartshift_bias}
```

**Comment by yai-dev** [comment]
> I actually don't have an AMD GPU. Can you paste the result of following command here?
> 
> ```
> cat /sys/class/drm/card{0,1,2}/device/{mem_info_vram_total,mem_info_vram_used,mem_info_vis_vram_total,mem_info_vis_vram_used,mem_info_gtt_total,mem_info_gtt_used,smartshift_apu_power,smartshift_dgpu_power,smartshift_bias}
> ```

Here is what you need:

```
4294967296
1009135616
4294967296
1009135616
31523540992
201281536
```

**Comment by CarterLi** [comment]
你别把报错信息删了，我分不清哪个数据对应哪个文件。。。

**Comment by CarterLi** [comment]
或者你看下官方文档，对照一下你系统的文件，看看有没有能区分是独显和集显的。

https://docs.kernel.org/gpu/amdgpu/driver-misc.html

**Comment by CarterLi** [comment]
Seems no one can be used to identify the GPU type.

Let's disable the GPU type detection

**Comment by CarterLi** [comment]
hwmon interface seems contain interesting data. Notably

> * Northbridge voltage (APUs only)
> * GPU memory clock (dGPU only)

https://www.kernel.org/doc/html/v5.10/gpu/amdgpu.html#hwmon-interfaces

What do `ls -l /sys/class/drm/card?/device/hwmon?/{freq1_input, in1_input}` and `cat /sys/class/drm/card?/device/hwmon?/{freq1_input, in1_input}` print?

**Comment by yai-dev** [comment]
> hwmon interface seems contain interesting data. Notably
> 
> > * Northbridge voltage (APUs only)
> > * GPU memory clock (dGPU only)
> 
> https://www.kernel.org/doc/html/v5.10/gpu/amdgpu.html#hwmon-interfaces
> 
> What do `ls -l /sys/class/drm/card?/device/hwmon/hwmon?/{freq1_input, in1_input}` and `cat /sys/class/drm/card?/device/hwmon?/{freq1_input, in1_input}` print?

FYI:

#### Output for `ls -l /sys/class/drm/card0/device/hwmon/hwmon2/freq1_input`

```text

.r--r--r-- 4.1k root 29 4月  15:01 /sys/class/drm/card0/device/hwmon/hwmon2/freq1_input

```

#### Output for `ls -l /sys/class/drm/card0/device/hwmon/hwmon2/in1_input`

```text

.r--r--r-- 4.1k root 29 4月  15:01 /sys/class/drm/card0/device/hwmon/hwmon2/in1_input

```

#### Output for `cat /sys/class/drm/card0/device/hwmon/hwmon2/freq1_input`

```text

400000000

```

#### Output for `cat /sys/class/drm/card0/device/hwmon/hwmon2/in1_input`

```text

943

```

It seems card1 doesn't has files or symlinks as you said but only card0 (a.k.a amdgpu)

**Comment by CarterLi** [comment]
I'm sorry. It should be `cat /sys/class/drm/card0/device/hwmon/hwmon2/freq2_input`

**Comment by yai-dev** [comment]
> I'm sorry. It should be `cat /sys/class/drm/card0/device/hwmon/hwmon2/freq2_input`
> 
> And what does `ls -l /sys/class/drm/card0/device/hwmon/hwmon?` print?
> 
> > It seems card1 doesn't has files or symlinks as you said but only card0 (a.k.a amdgpu)
> 
> It was expected. All these files are amdgpu only

FYI:

#### Output for `ls -l /sys/class/drm/card0/device/hwmon/hwmon?`:

```text
lrwxrwxrwx 1 root root    0  4月29日 15:01 device -> ../../../0000:05:00.0
-r--r--r-- 1 root root 4096  4月29日 15:01 freq1_input
-r--r--r-- 1 root root 4096  4月29日 15:01 freq1_label
-r--r--r-- 1 root root 4096  4月29日 15:01 in0_input
-r--r--r-- 1 root root 4096  4月29日 15:01 in0_label
-r--r--r-- 1 root root 4096  4月29日 15:01 in1_input
-r--r--r-- 1 root root 4096  4月29日 15:01 in1_label
-r--r--r-- 1 root root 4096  4月29日 15:01 name
drwxr-xr-x 2 root root    0  4月29日 09:57 power
-r--r--r-- 1 root root 4096  4月29日 15:01 power1_input
-r--r--r-- 1 root root 4096  4月29日 15:01 power1_label
lrwxrwxrwx 1 root root    0  4月29日 09:57 subsystem -> ../../../../../../class/hwmon
-r--r--r-- 1 root root 4096  4月29日 15:01 temp1_input
-r--r--r-- 1 root root 4096  4月29日 15:01 temp1_label
-rw-r--r-- 1 root root 4096  4月29日 09:57 uevent
```

### Output for `cat /sys/class/drm/card0/device/hwmon/hwmon2/freq2_input`:

NO SUCH FILE OR DIRECTORY

**Comment by CarterLi** [comment]
I have implemented a version. It should correctly detect the GPU type of your AMD iGPU and NV dGPU. It should also print the GPU frequency for the AMD iGPU (in your case, 0.4GHz should be printed)

https://github.com/fastfetch-cli/fastfetch/actions/runs/8878225530/artifacts/1456489814

**Comment by CarterLi** [comment]
> Output for cat /sys/class/drm/card0/device/hwmon/hwmon2/freq2_input:
> NO SUCH FILE OR DIRECTORY

Cool!

**Comment by yai-dev** [comment]
> I have implemented a version. It should correctly detect the GPU type of your AMD iGPU and NV dGPU. It should also print the GPU frequency for the AMD iGPU (in your case, 0.4GHz should be printed)

cool, i will test it.

**Comment by CarterLi** [comment]
If you specify `--gpu-driver-specific`, fastfetch should print more information for both iGPU and dGPU.

**Comment by yai-dev** [comment]
![image](https://github.com/fastfetch-cli/fastfetch/assets/20114873/2396a2a3-1462-47b9-8333-2d18dc53824f)

seems not working, emmm

**Comment by CarterLi** [comment]
https://github.com/fastfetch-cli/fastfetch/actions/runs/8878546945/artifacts/1456557467

This one please.

**Comment by yai-dev** [comment]
> https://github.com/fastfetch-cli/fastfetch/actions/runs/8878546945/artifacts/1456557467
> 
> This one please.

![image](https://github.com/fastfetch-cli/fastfetch/assets/20114873/79d53fd7-c843-4ae4-a5da-1e8a0166228d)

It seems working right now, cool.

**Comment by CarterLi** [comment]
This one: https://github.com/fastfetch-cli/fastfetch/actions/runs/8878762801/artifacts/1456601026

**Comment by CarterLi** [comment]
AMD driver only reports current GPU frequency, while fastfetch reports max frequency for both CPU and non-AMD GPUs. I wonder if I should remove it.

**Comment by yai-dev** [comment]
@CarterLi  i think i need to test new gpu detection is working on Wayland, wait plz

**Comment by CarterLi** [comment]
What does `/sys/class/drm/card0/device/uevent` print?

**Comment by yai-dev** [comment]
> @CarterLi i think i need to test new gpu detection is working on Wayland, wait plz

![image](https://github.com/fastfetch-cli/fastfetch/assets/20114873/051b4486-fb29-46d2-a0fa-450f3da921a5)

![image](https://github.com/fastfetch-cli/fastfetch/assets/20114873/adb7ec6d-70f5-404b-9451-6cabc8a845b9)

![image](https://github.com/fastfetch-cli/fastfetch/assets/20114873/af88c0e7-ced7-4aa0-8ce1-44788ce7538f)

seems to working on Wayland.


> What does `/sys/class/drm/card0/device/uevent` print?

![image](https://github.com/fastfetch-cli/fastfetch/assets/20114873/de36278d-3659-4d24-84ed-2a73cc20187f)

**Comment by CarterLi** [comment]
What about `/sys/class/drm/card0/device/revision`

**Comment by yai-dev** [comment]
card1 if you needed:

![image](https://github.com/fastfetch-cli/fastfetch/assets/20114873/67ed03b1-b1b5-444e-a179-0615ba6d9d41)

**Comment by CarterLi** [comment]
I think it's enough to close this issue. Thanks for your help.
