### ISSUE TITLE
[FEAT]  Expand logo source input to allow folders

### ISSUE THREAD

**Issue by NatVIII** [fastfetch-cli/fastfetch#829]
## Wanted features:

Allow the logo source to include directories, which when specified will have a random file inside selected to be the logo to be rendered

## Motivation:

Neofetch had implemented a system in it's config which allowed one to specify a folder of images or files which would be loaded as the image_source, and it was part of my config. As an example, here's what my backend settings for neofetch looked like below

```
 # Backend Settings


 # Image backend.
 #
 # Default:  'ascii'
 # Values:   'ascii', 'caca', 'jp2a', 'iterm2', 'off', 'termpix', 'pixterm', 'tycat', 'w3m'
 # Flag:     --backend
 image_backend="kitty"
 #image_backend="off"

 # Image Source
 #
 # Which image or ascii file to display.
 #
 # Default:  'auto'
 # Values:   'auto', 'ascii', 'wallpaper', '/path/to/img', '/path/to/ascii', '/path/to/dir/'
 # Flag:     --source
 #
 # NOTE: 'auto' will pick the best image source for whatever image backend is used.
 #       In ascii mode, distro ascii art will be used and in an image mode, your
 #       wallpaper will be used.
 image_source="/path/to/dir/"
```
This would make it so that neofetch would display a logo which was a randomly selected image inside `/path/to/dir/`. I haven't found another issue related to this feature which was present in neofetch(the closest could perhaps be the discussion of wildcards in the config like in issue #375). Would this be difficult to accomplish, or is there a script workaround that can be accomplished?

Thanks

**Comment by CarterLi** [comment]
https://github.com/fastfetch-cli/fastfetch/blob/8af88a33763200e62c59eaa82705d6af5977e92c/CHANGELOG.md?plain=1#L235

**Comment by NatVIII** [comment]
Thank you :pray: I missed that completely
