### ISSUE TITLE
[FEAT] More documentation in the Manpage

### ISSUE THREAD

**Issue by ValdezFOmar** [fastfetch-cli/fastfetch#830]
## Wanted features:

- Include all the available options, currently only a subset (compared to `fastfetch --help`) is actually listed.
- Include the information from running `fastfetch -h <option>` for all options.
- Explain/give examples of the structure of the config file, accepted values for options, how to change common things, etc.
- Include the JSON Schema found in the github wiki.

## Motivation:

When I want to read thorough documentation for a tool I look at the manpage (as many others might do). I expect to find more information in `man foo` than running `foo --help`. Right now, some of the info is available in the manpage, more is in `fastfetch --help` and other is in the github wiki.

Having all the documentation in the manpage would be beneficial because:

1. There would be a centralized place to look for the documentation, without needing to look at external resources or having to run multiple commands (running `fastfetch -h <option>` constantly is not very ergonomic).
2. Users can leverage the features of the program they use to read manpages to search for specific topics of their interest more easily.

**Comment by CarterLi** [comment]
The man page file was contributed by community, but I'm not familiar the man page file syntax.

Any contribution is welcome.

**Comment by ValdezFOmar** [comment]
Neofetch used [`help2man`](https://www.gnu.org/software/help2man/) to generate a manpage using output from `--help`. Another option is to use [`pandoc`](https://pandoc.org/) to convert from any format (eg. markdown) to a manpage.

I think that pandoc would be best because then you can convert the JSON schema to a manpage too.

**Comment by mac2net** [comment]
Any documentation is better than none and is the Man page really the best place to document what really should end up in the config.jsonc file? As such, I suggest just keeping the current release version and the JSON Schema pages in sync. Right now the latest version of Fastfetch is v25, released 5 days ago while the JSON Schema document was last edited two weeks ago, Cheers Mac

**Comment by darwincereska** [comment]
I fixed the man page I will send a pull request

**Comment by CarterLi** [comment]
To someone wants to fix this

1. We don't need the generated `.1` file. We need a (python?) script to generate it, in order to regenerate it in future release.
2. It should be generated directly from <https://github.com/fastfetch-cli/fastfetch/blob/dev/src/data/help.json>, not `fastfetch --help`

**Comment by ValdezFOmar** [comment]
I'll see if I can have a go at it this weekend or next week. I've studied a bit of the format used for manpages (roff) to be familiar with it and I've seen other projects generate their manpage using a python script as you mentioned (also thanks for mentioning that `help.json` file, that really makes things easier).

**Comment by darwincereska** [comment]
I see that my pull request was outdated and not in the way that was requested, I will take a try at making a script to fix this issue

**Comment by thynus** [comment]
Hello!
I have created a python script (**man_page.py**) that generates a new man page for fastfetch.  It requires help2man, any improvements would be welcome. Thanks.

https://github.com/thynus/man_page.git

Usage:
 ./man_page.py > fastfetch.1.in

**Comment by ValdezFOmar** [comment]
@thynus please read carefully the suggestions made by CarterLi about how to resolve this issue. Your low effort script literally just runs an external tool that ends up using `fasfetch --help` (which is not what was requested).

**Comment by CarterLi** [comment]
The script should print the content of generated `.1` file to stdout.
