### ISSUE TITLE
[BUG] Normal color is applied instead of bright color

### ISSUE THREAD

**Issue by ValdezFOmar** [fastfetch-cli/fastfetch#831]
# General description of bug:

* What happened: I'm setting bright colors for the logo but they are not being apply, instead the 'normal' version of the color used
* What should happen: The bright color should be applied
* Fastfetch version used: `fastfetch 2.11.0-debug (x86_64)`
* Did it work in an older version: didn't tried
* Where did you get the binary: `pacman -S fastfetch`
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? yes

Notice that in my setup
- `yellow` is an orange color
- `bright_yellow` is yellow

It doesn't matter if I set `yellow` or `bright_yellow` it just applies `yellow` (the orange color). I also have `brightColor` set to true. The behavior was the same with all other color. 

Screenshot:
![image](https://github.com/fastfetch-cli/fastfetch/assets/80359343/1d1204b7-1dde-4608-9302-af0dfbbb881d)

The content of the configuration file you use (if any):
```jsonc
{
    "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
    "display": {
        "showErrors": true,
        "color": {
            "keys": "blue",
            "title": "magenta"
        },
        "separator": "\u001b[90m: ",
        "brightColor": true
    },
    "logo": {
        "color": {
            "1": "blue",
            "2": "bright_yellow" // <<-- important part
        }
    },
    "modules": [
        {
            "type": "title",
            "color": {
                "at": "magenta"
            }
        },
        "separator",
        "os",
        "uptime",
        "packages",
        "de",
        "theme",
        "icons",
        "shell",
        "terminal",
        "break",
        "cpu",
        "gpu",
        "memory",
        "disk",
        "break",
        "colors"
    ]
}
```

**Comment by CarterLi** [comment]
`brightColor` defaults to `true` ( see `fastfetch -h bright-color` ), so that the logo in your screenshot were bright. You may set `brightColor` to `false` to get the difference

**Comment by ValdezFOmar** [comment]
Thanks, that fixed it. But then, isn't the name confusing? I expected `"brightColor": true` to enable the use of bright colors and `"brightColor": false` to disable it. Or is it that `brightColor` means to **only** use bright colors?

**Comment by CarterLi** [comment]
> Or is it that brightColor means to only use bright colors?

Yes, which matches the behavior of neofetch

**Comment by PowerMeep** [comment]
I thought I was having this issue as well, but it turned out that I was confused about the names of the colors. It turns out, I just needed to use `light_` instead of `bright_`.

Just leaving this here for anybody else who might find it helpful.
