### ISSUE TITLE
What does the asterisk sign mean?

### ISSUE THREAD

**Issue by dcelasun** [fastfetch-cli/fastfetch#832]
I looked at the man page, `fastfetch --help`, and searched on Github but couldn't find any mention of this. What does it mean when a line in the fastfetch output has a `*` sign?

For example, I have three monitors but only one has the sign:
```
Display (ASUS MG279): 2560x1440 @ 60Hz *
Display (2369M): 1920x1080 @ 60Hz
Display (2369M): 1920x1080 @ 60Hz
```

Likewise, my local IP has it too:
```
Local IP (wlp2s0): 192.168.30.103/24 *
```

**Comment by CarterLi** [comment]
> Display (ASUS MG279): 2560x1440 @ 60Hz *
> Display (2369M): 1920x1080 @ 60Hz
> Display (2369M): 1920x1080 @ 60Hz

Means `ASUS MG279` is your primary monitor.

> Local IP (wlp2s0): 192.168.30.103/24 *

Means it's used as the default route.

**Comment by dcelasun** [comment]
Ah, thanks! I'll send a PR to update the help text :)
