### ISSUE TITLE
[Help Wanted]

### ISSUE THREAD

**Issue by JimGlass** [fastfetch-cli/fastfetch#833]
I just install fastfetch on Fedora 40 and everyone is correct, it is much faster!  I did however want to save a config file but I am getting an error.  The command I used to create the config file was:

`fastfetch --gen-config .jim/conf/fastfetch.conf`

but when I run it using:

`fastfetch -c .jim/conf/fastfetch.conf`

I am getting the error:

`Error: unknown option: {`

Can you please let me know what I am doing wrong??

**Comment by kojq** [comment]
`.jsonc` instead of `.conf`

**Comment by CarterLi** [comment]
The file extension must be jsonc. `.conf` has special meaning in fastfetch but dont use that.

**Comment by JimGlass** [comment]
Thank you both kojq and CarterLi!

It works like a charm now...  I missed that in the configuration page...  Duh!
