### ISSUE TITLE
[FEAT] support picking a random image from a directory

### ISSUE THREAD

**Issue by pmonks** [fastfetch-cli/fastfetch#834]
## Wanted features:

**As a** user who collects image files in a directory, **I want to** be able to configure `fastfetch` to randomly select and display a supported image file from that directory, **so that** each time `fastfetch` is run I (usually) see a different image.

## Motivation:

Being reminded of past places, people, and objects each time I start a new terminal session has value to me.  `neofetch` provided this feature.

**Comment by CarterLi** [comment]
See https://github.com/fastfetch-cli/fastfetch/issues/829

**Comment by pmonks** [comment]
Apologies - I guess my search-fu today was especially weak.
