### ISSUE TITLE
ipv4 address not displayed correctly

### ISSUE THREAD

**Issue by debug400** [fastfetch-cli/fastfetch#835]
First time user of fastfetch. Installed is several VMs.
IPV4 address not displayed correctly in new version of Ubuntu 2404.

Shown as 192.168.0.13*     Should be 192.168.0.133/24 *

<img width="740" alt="Ubuntu 2404" src="https://github.com/fastfetch-cli/fastfetch/assets/168670832/c19abde2-3fde-4e44-882b-2d2af3684960">

**Comment by kojq** [comment]
I suspect the window is small, causing truncation and not displaying complete information. try to use the full screen to display all text.

**Comment by CarterLi** [comment]
@kojq was correct
