### ISSUE TITLE
[FEAT] support --logo-width / --logo-height options for image files

### ISSUE THREAD

**Issue by pmonks** [fastfetch-cli/fastfetch#836]
## Wanted features:

**As a** user who is providing a random image file from a directory (currently via scripting, until ~~#834~~ #829 is addressed), **I want to** be able to control the maximum width of the image via the `--logo-width` and/or `--logo-height` options, **so that** large images are scaled down in size, leaving enough room for the system information to be displayed.

## Motivation:

Currently `--logo-width` appears to be ignored for images, so large images can consume up to the entire width of the terminal window, leaving no room for the textual system information to be displayed.

**Comment by CarterLi** [comment]
> Currently `--logo-width` appears to be ignored for images

It should work with `--sixel` and `--kitty`. You may notice text collapse, prefix fastfetch command with `clear &&` can be used as a workaround.

**Comment by pmonks** [comment]
I'm using `--iterm`, which may explain why images aren't resized.

**Comment by CarterLi** [comment]
if you use --iterm, both logo-width and logo-height need to be specified to make it work

**Comment by pmonks** [comment]
Oh interesting. Is there a way to get proportional scaling by width alone when in `--iterm` mode, without resorting to calculating width and height externally?

**Comment by pmonks** [comment]
Love it! Thank you for working on this!
