### ISSUE TITLE
[FEAT] Improve detection for images when running in sudo or ssh

### ISSUE THREAD

**Issue by Thelvaen** [fastfetch-cli/fastfetch#839]
## Wanted features:

When accessing a computer through ssh or changing user through sudo, png logos are not displayed properly.

## Motivation:

having the fallback to the ASCII version of the logo would be nicer than just having `PNG` written at the top of the output.

**Comment by 1ivyatan** [comment]
So, like a PNG turns into ASCII art as a fallback?

**Comment by Thelvaen** [comment]
probably easier to understand what I mean through screenshots.
in `sudo`
![image](https://github.com/fastfetch-cli/fastfetch/assets/19350574/dcb74f5a-06d4-4bce-a282-3dee34f99f31)
in `ssh`
![image](https://github.com/fastfetch-cli/fastfetch/assets/19350574/65207004-fefe-46fa-93db-3d2fb512520b)

**Comment by CarterLi** [comment]
Does neofetch work in this case?

**Comment by CarterLi** [comment]
Should be fixed in https://github.com/fastfetch-cli/fastfetch/commit/71cba2451a13fdb56bbbdca943a3fb8fd194d901

**Comment by CarterLi** [comment]
Commit reverted.

Image logos in SSH session do work for me

![image](https://github.com/fastfetch-cli/fastfetch/assets/6134068/1946bc9e-7e54-41b0-9ab5-c43b78f34506)

**Comment by CarterLi** [comment]
sudo works too

![image](https://github.com/fastfetch-cli/fastfetch/assets/6134068/e3df126e-04b0-4119-9938-8d6b45fd8a1d)

**Comment by matrix543** [comment]
this is still a issue in fedora 42 with fastfetch 2.44 when you connect over ssh or open sudo or a screen it dont load the png file over ssh it load fastfetch 2 times to
