### ISSUE TITLE
[LOGO] Armbian OS

### ISSUE THREAD

**Issue by pablo-cabrera** [fastfetch-cli/fastfetch#842]
# OS
```
PRETTY_NAME="Armbian 24.2.1 bookworm"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.armbian.com"
SUPPORT_URL="https://forum.armbian.com"
BUG_REPORT_URL="https://www.armbian.com/bugs"
ARMBIAN_PRETTY_NAME="Armbian 24.2.1 bookworm"
```

**Comment by CarterLi** [comment]
What does `cat /etc/lsb-release` print?

**Comment by CarterLi** [comment]
Also where can I find the ASCII art?

**Comment by Null-Ping** [comment]
Here are 2 ASCII arts for Armbian OS, extracted from https://github.com/HorlogeSkynet/archey4:
Sadly, I have not been able to make their colors work with fastfetch, so they need to be re-colored to match the screenshots below.
```
                ..
            `:]x**j-,'
       .,+t***********z\<"
       ?******************;
      '*n` .'`^,;;,^`'. ,cc.
      -<.                .[l
     //     ^^      ^^    \\
     !^         ^^         ":
    'tt}`     !~]rj_     ")t/.
    Itttt?'   ~~]rr]   `{tttt,
    \tttttt!""I_]r("""~tttttt1
  '_tttttttttttt)ftttttttttttti.
 \*ztttttttttttttttttttttttttf**[
l**c)tttttttttttttttttttttttt(z**,
.z*x.`tttttttttttttttttttttttt.`u*n
>`   (tttttttttttttttttttttt]   "I
     ,tttttttttttttttttttttt`
     ./tttttfttttttttfttttt(
      'I)))(\()(tt))|\()({;'
        .~~~~~~~|)~~~~~~~<
        '[)))))1|()))))))?
          ",,,"    ",,,^
```
```
   █ █ █ █ █ █ █ █ █ █ █
  ███████████████████████
▄▄██                   ██▄▄
▄▄██    ███████████    ██▄▄
▄▄██   ██         ██   ██▄▄
▄▄██   ██         ██   ██▄▄
▄▄██   ██         ██   ██▄▄
▄▄██   █████████████   ██▄▄
▄▄██   ██         ██   ██▄▄
▄▄██   ██         ██   ██▄▄
▄▄██   ██         ██   ██▄▄
▄▄██                   ██▄▄
  ███████████████████████
   █ █ █ █ █ █ █ █ █ █ █
```
Here's what they should look like with colors, on screenshots:

![image](https://github.com/fastfetch-cli/fastfetch/assets/141347595/60f9b642-8cff-4b32-b7a5-04c4c128b898)

![image](https://github.com/fastfetch-cli/fastfetch/assets/141347595/60f293d7-dffc-4aae-b497-cbd6309bb47e)

**Comment by CarterLi** [comment]
Logos were added. However because of the `ID=debian` line in `os-release`, it will be detected as Debian. If you want fastfetch to show armbian, use `fastfetch -l armbian --os-format '{3}'`

**Comment by CarterLi** [comment]
Seems Debian based distros (Proxmox, MX and Armbian, but Ubuntu) tend to identify themselves as Debian. Fixing this issue requires various hacks, which is what I don't like.

**Comment by CarterLi** [comment]
Distro detection was added
