### ISSUE TITLE
[LOGO] MX Linux Logo?

### ISSUE THREAD

**Issue by dagleykd** [fastfetch-cli/fastfetch#847]
# OS
```
MX Linux is currently the most popular distro on DistroWatch and is also an incredibly popular distro. Would love to see the logo added to fastfetch! Currently it only comes up as Debian. Yes, it is Debian-based, but it is not Debian :)
```

# Ascii
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@%*+--:------=+*%@@@@@@@@@@@@
@@@@@@@@@#=. .-+#%@@@@@%#*+--=#@@@@@@@@@
@@@@@@@+. .=%@@@@@@@@@@@@@@@@*-:+@@@@@@@
@@@@@*.  *@@@@@@@@@@@@@@@@@@@@@%-.*@@@@@
@@@@-  -@@@@@@@@@@@@@@@@@@@@@@@#:  -@@@@
@@@:  -@@@@@@@=.*@@@@@@@@@@@@%-   = :@@@
@@=  .@@@@@@@@%- :%@@@@@@@@@+   -%@# =@@
@%   +@@@@@@@@@@#. =@@@@@@*.  .*@@@@. %@
@+   *@@@@@@*..*@@+  *@@%-   =@@@@@@- +@
@=   *@@@@%-    -%@@- :=   -%@@@@@@@: +@
@+   :@@@=        +@@=   .#@@@@@@@@%  *@
@%    +*.          .:     *@@#: +@@:  @@
@@+                   :%@- :-    ::  +@@
@@@-                  .=@@=         -@@@
@@+.                     .           +@@
%=..:.................::...........:..-%
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

**Comment by CarterLi** [comment]
It should have been supported

https://github.com/fastfetch-cli/fastfetch/blob/dev/src/logo/ascii/mx.txt

You may test it with `fastfetch -l mx`

**Comment by dagleykd** [comment]
> It should have been supported
> 
> https://github.com/fastfetch-cli/fastfetch/blob/dev/src/logo/ascii/mx.txt
> 
> You may test it with `fastfetch -l mx`

It's not working automatically for me as it should be then? Running a standard install of MX 23.2 with the latest version of fastfetch?
![Screenshot_2024-05-02_22-10-55](https://github.com/fastfetch-cli/fastfetch/assets/20607462/7c82cb6a-c9f1-4922-a3f8-30357ffeefb8)

**Comment by CarterLi** [comment]
What does `cat /etc/os-release` or `cat /etc/lsb-release` say?

**Comment by dagleykd** [comment]
> cat /etc/lsb-release

os-release:
`PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
`

lsb-release:
`PRETTY_NAME="MX 23.2 Libretto"
DISTRIB_ID=MX
DISTRIB_RELEASE=23.2
DISTRIB_CODENAME="Libretto"
DISTRIB_DESCRIPTION="MX 23.2 Libretto"
`

**Comment by CarterLi** [comment]
Can you try this build?

https://github.com/fastfetch-cli/fastfetch/actions/runs/8933075710/artifacts/1469258998

**Comment by dagleykd** [comment]
> Can you try this build?
> 
> https://github.com/fastfetch-cli/fastfetch/actions/runs/8933075710/artifacts/1469258998

That did the trick with the logo, though the OS still identifies as "Debian GNU/Linux bookworm 12 x86_64"

I posted on the MX Linux forums a bit ago about it and one of the devs replied and said they are keeping the Debian-style os-release file as it is. Where MX is Debian-based, they need to leave it alone for the apt tool.
https://forum.mxlinux.org/viewtopic.php?p=774701#p774701

Would there be a way to modify fastfetch to take some data from the lsb-release file instead specifically for fastfetch's 'OS' line at the top regarding MX (considering the MX devs are not going to modify the os-release file from it's Debian origins)...?

The rest of the fastfetch details seem fine, but maybe it could pull the 'OS' line from the 'Pretty Name' line in the lsb-release file instead?

**Comment by CarterLi** [comment]
What does `/etc/initrd-release` print?

**Comment by CarterLi** [comment]
Tested in VM

![image](https://github.com/fastfetch-cli/fastfetch/assets/6134068/06268958-d2b0-4d0e-a003-11f7c7af9157)

**Comment by dagleykd** [comment]
> Tested in VM
> 
> ![image](https://private-user-images.githubusercontent.com/6134068/327649671-06268958-d2b0-4d0e-a003-11f7c7af9157.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MzIwMjgsIm5iZiI6MTcxNDczMTcyOCwicGF0aCI6Ii82MTM0MDY4LzMyNzY0OTY3MS0wNjI2ODk1OC1kMmIwLTRkMGUtYTAwMy0xMWY3YzdhZjkxNTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDNUMTAyMjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGRlYzllOWU4ZDgwMDYyNjA1YjJiNzE1OGFiYzdkMmY3YTZkOWRkYThkMjM3ZDhhZDQyNjljZmNjY2UwNTc1ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EzltPTb1NwkHspBgxJwd4cM0oDiMrgx78j35ZxMyeUg)

Good morning!

My apologies for now answering last night - I had gone to bed :)

Up before work now. Just tested the new build and yes, it works perfectly now...kudos to you, and thanks very much for the quick replies / quick efforts and all the hard work that goes into fastfetch! :)
