### ISSUE TITLE
way to add images instead of the logo

### ISSUE THREAD

**Issue by Sarthak950** [fastfetch-cli/fastfetch#853]
![240503_18-20-41](https://github.com/fastfetch-cli/fastfetch/assets/93645760/d3ff7659-7a40-4d8e-a8c9-22dd2d9a956d)

config from the neofetch
image_source=$(pokeget random --hide-name)

program used neowofetch

**Comment by CarterLi** [comment]
What is pokeget?

**Comment by CarterLi** [comment]
Untested. I assume you need `fastfetch --data-raw "${pokeget random --hide-name}"`

**Comment by Sarthak950** [comment]
pokefetch is a tool that display images of pokemon in the terminal 

also this error pops up 
![240503_18-33-34](https://github.com/fastfetch-cli/fastfetch/assets/93645760/8886a838-df5a-42fd-b35c-46dd55cc6be6)
i use fish shell

**Comment by CarterLi** [comment]
`pokeget random --hide-name | fastfetch --file-raw`

![image](https://github.com/fastfetch-cli/fastfetch/assets/6134068/bf8a1ab6-6caa-4ef9-947c-2b940088603b)

**Comment by Sarthak950** [comment]
u forget to add a dash at the end 
`pokeget random --hide-name | fastfetch --file-raw -`
but yeah it works now thanks for replying so fast
