### ISSUE TITLE
[BUG] Don't disable image logos when running inside tmux

### ISSUE THREAD

**Issue by heather7283** [fastfetch-cli/fastfetch#861]
This commit https://github.com/fastfetch-cli/fastfetch/commit/71cba2451a13fdb56bbbdca943a3fb8fd194d901 disables image logos if fastfetch is running inside a tmux session, however it seems unnecessary, for me sixel logos work perfectly fine inside tmux (see screenshot).
![image](https://github.com/fastfetch-cli/fastfetch/assets/142042427/693587a4-8b4e-4038-9fb5-a00baf62e094)
 It is possible to work around this by just unsetting TMUX envvar, but is it really necessary? I can't say anything about GNU screen and zellij since I don't use them, but I think that TMUX check should be removed

**Comment by Sk7Str1pe** [comment]
May you tell me how you made tmux render png?

**Comment by heather7283** [comment]
> May you tell me how you made tmux render png?

You need to tell tmux that your terminal emulator supports sixel, for example I use foot terminal emulator so I put this in my tmux.conf:
`set -a terminal-features 'foot*:sixel'`
This will tell tmux that if TERM value starts with foot, then terminal emulator supports sixel. You should replace foot with value of TERM inside your terminal emulator
This is described in more detail in tmux man page
