### ISSUE TITLE
[FEAT] Add FastFetch to Winget Repo

### ISSUE THREAD

**Issue by CrazyWolf13** [fastfetch-cli/fastfetch#863]
## Before requesting a new feature

Instead of using third-party tools an installation via the official Windows Package Manager winget would be much better in my eyes.
Are there any plans to integrate fastfetch into winget repo?

## Motivation:

Winget grows and grows, having fastfetch there would be awesome!

Even neofetch was there!!

**Comment by CarterLi** [comment]
See https://github.com/microsoft/winget-pkgs/pull/94697
