### ISSUE TITLE
[FEAT] Install on Ubuntu / Debian

### ISSUE THREAD

**Issue by CrazyWolf13** [fastfetch-cli/fastfetch#864]
Hi

Is it possible to get this into the default repo on ubuntu / debian?
So not everyone has to add a ppa or even download from GH ?
Now as neofetch is archived?

## Wanted features:

Install directly on ubuntu / debian based systems without adding any ppa or repos.

## Motivation:

THis would make the installation process much more straightforward and more similar to the one as neofetch.

**Comment by CrazyWolf13** [comment]
Closed as duplicate.

**Comment by CarterLi** [comment]
We need someone that actually knows how debian packaging works
