### ISSUE TITLE
[FEAT] Secondary key in modules

### ISSUE THREAD

**Issue by Sigmanificient** [fastfetch-cli/fastfetch#866]
## Wanted features:

The ability to set a secondary key in every module list.

```jsonc
{
  "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
  "logo": {
    "padding": {
      "top": 2
    }
  },
  "display": { "separator": " ➜ " },
  "modules": [
    { "type": "title",  "keyWidth": 10 },
    "break",
    { "type": "os",       "key": "OS",          "keyColor": "white" },
    { "type": "kernel",   "key": "├ Kernel",    "keyColor": "white" },
    { "type": "packages", "key": "├ Packages",  "keyColor": "white" },
    { "type": "uptime",   "key": "└ Uptime",    "keyColor": "white" }
  ]
}

```

### Example

```jsonc
  "display": {
    "separator": " ➜ "
  },
  "modules": [
    {
      "type": "kernel",
      "key": "├",
      "keyColor": "white",
      "secondary": "kernel",
      "keyColor": "blue"
    },
  ],
```

## Motivation:

I would like to migrate my old neofetch config, but i cannot reproduce it using the current configuration.

#### Currently, with available module settings

![image](https://github.com/fastfetch-cli/fastfetch/assets/53050011/033a46cf-71d6-4d18-afeb-0e07f34bc098)

#### What i would like to reproduce

![image](https://github.com/fastfetch-cli/fastfetch/assets/53050011/06ed21c4-1935-46b9-b4b3-eabaaf46b9ef)

**Comment by CarterLi** [comment]
You may insert ANSI escape code directly in `key`

eg:

```json
    {
      "type": "kernel",
      "key": "├ \u001b[34mkernel"
    }
```

Seems ugly though.

**Comment by Sigmanificient** [comment]
> ```json
>     {
>       "type": "kernel",
>       "key": "├ \u001b[34mkernel"
>     }
> ```


Error: failed to parse JSON config file `/home/sigmanificient/.config/fastfetch/config.jsonc` at pos 513: unexpected character

**Comment by Sigmanificient** [comment]
It also does it on the latest vresion i just built (`fastfetch 2.11.3 (x86_64)`)

**Comment by CarterLi** [comment]
It was weird. Can you upload your config file for investigation?

**Comment by Sigmanificient** [comment]
```
{
    "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
    "logo": {
        "padding": {
            "top": 2
        }
    },
    "display": {
        "separator": " ➜ "
    },
    "modules": [
        {
            "type": "title",
            "keyWidth": 10
        },
        "break",
        {
            "type": "os",
            "key": "OS",
            "keyColor": "white"
        },
    {
      "type": "kernel",
      "key": "├ \u001b[34mkernel"
    }
        {
            "type": "packages",
            "key": "├ Packages",
            "keyColor": "white"
        },
        {
            "type": "uptime",
            "key": "└ Uptime",
            "keyColor": "white"
        }
    ]
}
```

**Comment by CarterLi** [comment]
You missed a comma after `    {
      "type": "kernel",
      "key": "├ \u001b[34mkernel"
    }`

**Comment by Sigmanificient** [comment]
> You missed a comma after ` { "type": "kernel", "key": "├ \u001b[34mkernel" }`

Oops my bad
