### ISSUE TITLE
Change the Ubuntu logo to look more like the modern official design

### ISSUE THREAD

**Issue by vadimk1337** [fastfetch-cli/fastfetch#870]
![image](https://github.com/fastfetch-cli/fastfetch/assets/36221770/f9fe85f5-cf02-44a2-80f5-6ab65aa9274f)

**Comment by vadimk1337** [comment]
![image](https://github.com/fastfetch-cli/fastfetch/assets/36221770/0364f93c-7291-4190-a2df-f8d3b052e30f)
Why does it display the picture first and then the text?

**Comment by vadimk1337** [comment]
![image](https://github.com/fastfetch-cli/fastfetch/assets/36221770/1c654359-4eeb-4ebb-a662-b5a624e03ff0)
there's a lot of free space here

**Comment by vadimk1337** [comment]
I'll just reduce the size to the original size, here's the final version: 
![image](https://github.com/fastfetch-cli/fastfetch/assets/36221770/479b264d-dae9-44c3-8bb9-8e2f2731bc4d)
[ubuntu.txt](https://github.com/fastfetch-cli/fastfetch/files/15210701/ubuntu.txt)

**Comment by CarterLi** [comment]
Let's see if other people prefer this one.

**Comment by vadimk1337** [comment]
And how to do this?  They will not come to GitHub and vote. They will simply use neofetch.

**Comment by pesaventofilippo** [comment]
<img width="384" alt="image" src="https://github.com/fastfetch-cli/fastfetch/assets/32228386/28887d51-c7d0-42ed-a99a-be466486440a">

Isn't this logo already the new one? It's just inverted, so instead of having a square block, only the circle is actually colored, which I think is better.

**Comment by vadimk1337** [comment]
@pesaventofilippo 
Screenfetch replicates the Ubuntu 2004 logo 1 to 1. Neofetch replicates the Ubuntu 2010 logo 1 to 1, it doesn't just draw the Ubuntu logo like in 2004, but places it specifically inside a circle. Starting from 2022, the Ubuntu logo is inside a rectangle. Perhaps this won't be liked by nostalgic people, but it's the new reality. The fact that it's inside a rectangle is noticeable in many places in the system:

On the Ubuntu website
![image](https://github.com/fastfetch-cli/fastfetch/assets/36221770/dd720cbe-e19e-4ae1-89f1-545e07faac0e)

During startup/shutdown
![image](https://github.com/fastfetch-cli/fastfetch/assets/36221770/a1ea1fe1-7b1a-4fb1-b0f8-0c569318d0de)

At login
![image](https://github.com/fastfetch-cli/fastfetch/assets/36221770/a893a2bd-67b4-42de-b6eb-62350e0d99d7)

In system->About
![Screenshot from 2024-05-05 14-06-29](https://github.com/fastfetch-cli/fastfetch/assets/36221770/40087c4f-02f9-4465-836f-b13847e4e902)


The only reason why this isn't in Dash to Dock is because they are very lazy. They would have to write new code, synchronize this color with the accent color, not just change the image. Why isn't this in Dash to Dock? The answer is simple: they're lazy. They didn't even make accent colors for the app store, even though they were asked to, and they were also asked for a yellow accent.

**Comment by CrazyWolf13** [comment]
> Let's see if other people prefer this one.

I don't think changing the whole logo to fill out a rectangle would look good in any way, however changing the ubuntu logo to a more neofetch way (or a config switch for this) would be really nice, so the logo still has some white color inside.

To me the ubuntu logo looks also a bit squished in height:
![image](https://github.com/fastfetch-cli/fastfetch/assets/96661824/599f5458-a670-444e-9e57-16a9d329633e)

**Comment by vadimk1337** [comment]
Either way I don't like this lonely point
In any case, I don’t like this lonely point, I need to add 3 more points to create symmetry
![image](https://github.com/fastfetch-cli/fastfetch/assets/36221770/a8be998c-9924-40f0-b49e-fdfa36698912)

**Comment by CarterLi** [comment]
> Either way I don't like this lonely point In any case, I don’t like this lonely point, I need to add 3 more points to create symmetry ![image](https://private-user-images.githubusercontent.com/36221770/328027561-a8be998c-9924-40f0-b49e-fdfa36698912.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MjI3NDMsIm5iZiI6MTcxNDkyMjQ0MywicGF0aCI6Ii8zNjIyMTc3MC8zMjgwMjc1NjEtYThiZTk5OGMtOTkyNC00MGYwLWI0OWUtZmRmYTM2Njk4OTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDE1MjA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiZGNhMzVjMmY0ODYxMTE3NDlkZDJkNTk5YzUzMDMwOTM4MzM2ZDg3NDhkZDFlZmUxM2ZjNzg2OTIyOWU5MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rcACIHi3_TktEq6dWcWgcnO07U_xqz4kPFGo_RKDsfk)

Let's just remove it.

**Comment by bgiesing** [comment]
> replicates the Ubuntu 2004 logo 1 to 1

@vadimk1337 Except it isn't? This IS the current logo, notice how the circles are fully embedded inside the lines, not only partially like the 2004 logo. It's just missing the rectangle background but it is the current correct redesigned logo since the 2004 one had a completely different shape 
![image](https://github.com/fastfetch-cli/fastfetch/assets/7895463/00e199c3-9c98-4eb3-9646-5d18724cf717)

The actual 2004 logo is under `ubuntu2_old` in the repo, you can see how the circles only partially jut into the lines
![image](https://github.com/fastfetch-cli/fastfetch/assets/7895463/e2102a45-efb7-4967-bae2-0e10666b6cd2)

**Comment by CarterLi** [comment]
The lonely point has been removed.
