### ISSUE TITLE
[BUG] Windows + Wezterm: `fastfetch --logo .\Pictures\image.png --logo-type iterm` puts fastfetch text over image

### ISSUE THREAD

**Issue by ykhan21** [fastfetch-cli/fastfetch#873]
# General description of bug:

* What happened: `fastfetch --logo .\Pictures\image.png --logo-type iterm` puts fastfetch text over image
* What should happen: `fastfetch --logo .\Pictures\image.png --logo-type iterm` should puts fastfetch text beside the image
* Fastfetch version used: fastfetch 2.11.2 (x86_64)
* Did it work in an older version: 
* Where did you get the binary: scoop
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)?

# Often helpful information:

Screenshot:
![image](https://github.com/fastfetch-cli/fastfetch/assets/51864191/4c13378e-a39d-47f8-9582-49395ec9c6b4)

The content of the configuration file you use (if any):
<no config>

Output of `fastfetch -c ci.jsonc --format json`:

```
//paste here
```

Output of `fastfetch --list-features`:
```
threads
vulkan
zlib
opencl
Proprietary GPU driver API
```

## If fastfatch crashed or freezed

Paste the stacktrace here. You may get it with:

```shell
# You may need Ctrl+C to stop the process if it freezes
gdb -q -ex 'set confirm off' -ex run -ex 'bt full' -ex quit --args /path/to/fastfetch
```

If you are able to identify which module crashed, the strace can be helpful too

```shell
strace /path/to/fastfetch --multithreading false -s {MODULE} --pipe
```

If you cannot do the instructions above, please upload the core dump file:

## If fastfetch is slow

Use `time fastfetch --stat` to show time usage for each module.

## If my image logo didn't show / work

* The image protocol you used: iterm
* The terminal you used: Wezterm
* Upload the image file here, or paste the image URL: ![image](https://github.com/fastfetch-cli/fastfetch/assets/51864191/10e2f06e-8efb-4b79-95da-3bbfcc883558)
* Does it work with `--logo-width {WIDTH} --logo-height {HEIGHT}`?  yes

## If fastfetch behaves incorrectly on shell starting

* The bug is reproduceable with fresh / clean shell configuration (i.e. `fastfetch` is the single line of `.zshrc` or `~/.config/fish/config.fish`): 
* Does `sleep 1` before running `fastfetch` work?

**Comment by CarterLi** [comment]
It was an known issue of conpty. See https://github.com/wez/wezterm/issues/4240#issuecomment-1704341624

The workaround is specifying `--logo-width {WIDTH} --logo-height {HEIGHT}` so that fastfetch can know the image size and move the cursor accordingly before printing texts.
