### ISSUE TITLE
[BUG] Brief delay on Wezterm when outputting the Terminal Font

### ISSUE THREAD

**Issue by ykhan21** [fastfetch-cli/fastfetch#875]
# General description of bug:
Slight delay on Wezterm when outputting the Terminal Font. On Windows Terminal and Git Bash, fastfetch runs instantly.
On Wezterm, `fastfetch --stat` shows 155ms for the Terminal Font.
Windows Terminal and Git Bash show 1ms and 0ms respectively.

I am using the default Wezterm font (JetBrains Mono).

* What happened: fastfetch hangs briefly when it comes to outputting the Terminal Font. 
* What should happen:
* Fastfetch version used: fastfetch 2.11.3 (x86_64)
* Did it work in an older version: 
* Where did you get the binary: scoop
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)?

# Often helpful information:

Screenshot:

The content of the configuration file you use (if any):
```
<no config>
```

Output of `fastfetch -c ci.jsonc --format json`:

```
//paste here
```

Output of `fastfetch --list-features`:
```
threads
vulkan
zlib
opencl
Proprietary GPU driver API
```

## If fastfatch crashed or freezed

Paste the stacktrace here. You may get it with:

```shell
# You may need Ctrl+C to stop the process if it freezes
gdb -q -ex 'set confirm off' -ex run -ex 'bt full' -ex quit --args /path/to/fastfetch
```

If you are able to identify which module crashed, the strace can be helpful too

```shell
strace /path/to/fastfetch --multithreading false -s {MODULE} --pipe
```

If you cannot do the instructions above, please upload the core dump file:

## If fastfetch is slow

Use `time fastfetch --stat` to show time usage for each module.

## If my image logo didn't show / work

* The image protocol you used: 
* The terminal you used: 
* Upload the image file here, or paste the image URL: 
* Does it work with `--logo-width {WIDTH} --logo-height {HEIGHT}`? 

## If fastfetch behaves incorrectly on shell starting

* The bug is reproduceable with fresh / clean shell configuration (i.e. `fastfetch` is the single line of `.zshrc` or `~/.config/fish/config.fish`): 
* Does `sleep 1` before running `fastfetch` work?

**Comment by CarterLi** [comment]
It was expected. Wezterm uses lua script to define the terminal font it uses, which is not something easy to parse. Instead, fastfetch runs `wezterm ls-fonts` to get terminal font. It is cheap to start processes for Linux but it is not the case for Windows
