### ISSUE TITLE
[BUG] Fastfetch cannot output logo properly in lolcat pipe

### ISSUE THREAD

**Issue by Avenger-285714** [fastfetch-cli/fastfetch#876]
`sudo dnf install fastfetch lolcat -v -y`

`fastfetch | lolcat`

What happened: Fastfetch cannot output logo properly in lolcat pipe
![image](https://github.com/fastfetch-cli/fastfetch/assets/60058876/ad417107-311e-46fb-907e-300e570ab8ed)

What should happen: It works on neofetch
![image](https://github.com/fastfetch-cli/fastfetch/assets/60058876/6ea79b98-df1c-44ca-8081-dfc049c79ba1)

Fastfetch version: fastfetch 2.9.1 (x86_64)

Where did I get the binary: dnf-4.19.2 on Fedora40

In fact, this bug can be found on deepin23, Debian and Ubuntu also. We can even get it under tty3.

**Comment by CarterLi** [comment]
See https://github.com/fastfetch-cli/fastfetch/wiki/Logo-options#troubleshooting

**Comment by Avenger-285714** [comment]
> See https://github.com/fastfetch-cli/fastfetch/wiki/Logo-options#troubleshooting

Even so, it does not output the bottom color block properly.
![image](https://github.com/fastfetch-cli/fastfetch/assets/60058876/e7bd75ff-4466-4f04-bb1e-f84e43350637)

**Comment by Avenger-285714** [comment]
> > See https://github.com/fastfetch-cli/fastfetch/wiki/Logo-options#troubleshooting
> 
> Even so, it does not output the bottom color block properly. ![image](https://private-user-images.githubusercontent.com/60058876/327986231-e7bd75ff-4466-4f04-bb1e-f84e43350637.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4Nzg3ODAsIm5iZiI6MTcxNDg3ODQ4MCwicGF0aCI6Ii82MDA1ODg3Ni8zMjc5ODYyMzEtZTdiZDc1ZmYtNDQ2Ni00ZjA0LWJiMWUtZjg0ZTQzMzUwNjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDAzMDgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4M2Q2YzA3OTFlYjdjYTY4MDc3ZmI3MDYzZjI1NGI3MzFmMmY0NWNkYzljOTE5MTNhNGVhMWY1N2NiYzc2YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pBaiqa3tzNSgafw4kaxvX1Pl0CEH9pNpl91OWhEPU8E)

Is any useage here that I'm not aware of that could solve this problem?
If not, I could bring up another issue after.

**Comment by CarterLi** [comment]
I think you should ask lolcat?

**Comment by Avenger-285714** [comment]
> I think you should ask lolcat?

Maybe. But it just works on neofetch...

**Comment by CarterLi** [comment]
This lolcat replace all text colors, except **neofetch's colos block**? PY交易？
