### ISSUE TITLE
[BUG] Wrong terminal reported on macOS

### ISSUE THREAD

**Issue by MVS** [fastfetch-cli/fastfetch#878]
# General description of bug:

* What happened: Terminal.app on macOS Ventura (M2 Mac mini) is reported as "Terminal", which breaks the terminal font detection (as seen in the screenshot below). I'm using bash, but the same happens using zsh.
* What should happen: Terminal.app should be reported as "Apple_Terminal":
```
$ echo $TERM_PROGRAM
Apple_Terminal
```
* Fastfetch version used: 2.11.3
* Did it work in an older version: No
* Where did you get the binary: Homebrew
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Not tested yet

# Often helpful information:

Screenshot:

![Screenshot 2024-05-04 at 11 54 38 PM](https://github.com/fastfetch-cli/fastfetch/assets/1120118/35f665c6-581b-43a1-9f34-7c8036ddba05)

The content of the configuration file you use (if any):
```
(None)
```

Output of `fastfetch --list-features`:
```
threads
vulkan
imagemagick7
chafa
zlib
sqlite3
```

**Comment by CarterLi** [comment]
Can you please printthe result of pstree?

**Comment by CarterLi** [comment]
Can you please printthe result of pstree?

Also `fastfetch -s shell:terminal --format json`
