### ISSUE TITLE
[BUG] seems not work normally with lolcat 

### ISSUE THREAD

**Issue by ImTopz** [fastfetch-cli/fastfetch#880]
Screenshot:
<img width="1181" alt="image" src="https://github.com/fastfetch-cli/fastfetch/assets/80200569/e5bce434-b31c-4056-a98e-9ee364dbccee">
<img width="1048" alt="image" src="https://github.com/fastfetch-cli/fastfetch/assets/80200569/30e62db4-b299-40c0-8141-dd29c5252191">

* What happened: cannot use this with lolcat ,when type command like this 
```
neofetch | lolcat 
``` 
but use fastfetch, that not work
* What should happen: use fastfetch with lolcat normally 
* Fastfetch version used: latest
* Did it work in an older version: no
* Where did you get the binary: brew 
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? no 

# Often helpful information:

The content of the configuration file you use (if any):
```
//paste here
```

Output of `fastfetch -c ci.jsonc --format json`:

```
//paste here
```

Output of `fastfetch --list-features`:
```
//paste here
```

## If fastfatch crashed or freezed

Paste the stacktrace here. You may get it with:

```shell
# You may need Ctrl+C to stop the process if it freezes
gdb -q -ex 'set confirm off' -ex run -ex 'bt full' -ex quit --args /path/to/fastfetch
```

If you are able to identify which module crashed, the strace can be helpful too

```shell
strace /path/to/fastfetch --multithreading false -s {MODULE} --pipe
```

If you cannot do the instructions above, please upload the core dump file:

## If fastfetch is slow

Use `time fastfetch --stat` to show time usage for each module.

## If my image logo didn't show / work

* The image protocol you used: 
* The terminal you used: 
* Upload the image file here, or paste the image URL: 
* Does it work with `--logo-width {WIDTH} --logo-height {HEIGHT}`? 

## If fastfetch behaves incorrectly on shell starting

* The bug is reproduceable with fresh / clean shell configuration (i.e. `fastfetch` is the single line of `.zshrc` or `~/.config/fish/config.fish`): 
* Does `sleep 1` before running `fastfetch` work?

**Comment by CarterLi** [comment]
Duplicate of https://github.com/fastfetch-cli/fastfetch/issues/876

**Comment by CarterLi** [comment]
However, I think I can improve the pipe mode a bit more.

**Comment by ImTopz** [comment]
will thx so much, that shows mac logo successfully by the command 
```
 fastfetch --pipe false | lolcat
```
