### ISSUE TITLE
[BUG] Missing dependency glibc

### ISSUE THREAD

**Issue by CrazyWolf13** [fastfetch-cli/fastfetch#884]
# General description of bug:

After installing on RaspberryPi OS x32 I get a missing dependency error:
`wget https://github.com/fastfetch-cli/fastfetch/releases/download/2.11.3/fastfetch-linux-armv7l.deb
`
`sudo dpkg -i fastfetch-linux-armv7l.deb
`
`sudo apt-get install -f
`
Installation goes all successful until running fastfetch:
`pi@raspberrypi:~ $ fastfetch
fastfetch: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33' not found (required by fastfetch)
fastfetch: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.34' not found (required by fastfetch)`

**Comment by CrazyWolf13** [comment]
```
pi@raspberrypi:~ $ sudo apt policy libc6
libc6:
  Installed: 2.31-13+rpt2+rpi1+deb11u9
  Candidate: 2.31-13+rpt2+rpi1+deb11u9
  Version table:
 *** 2.31-13+rpt2+rpi1+deb11u9 500
        500 http://archive.raspberrypi.org/debian bullseye/main armhf Packages
        100 /var/lib/dpkg/status
     2.31-13+rpi1+deb11u8 500
        500 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages
```

**Comment by CarterLi** [comment]
> ```
> pi@raspberrypi:~ $ sudo apt policy libc6
> libc6:
>   Installed: 2.31-13+rpt2+rpi1+deb11u9
>   Candidate: 2.31-13+rpt2+rpi1+deb11u9
>   Version table:
>  *** 2.31-13+rpt2+rpi1+deb11u9 500
>         500 http://archive.raspberrypi.org/debian bullseye/main armhf Packages
>         100 /var/lib/dpkg/status
>      2.31-13+rpi1+deb11u8 500
>         500 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages
> ```

No luck. You have to compile it yourself

**Comment by CrazyWolf13** [comment]
> > ```
> > pi@raspberrypi:~ $ sudo apt policy libc6
> > libc6:
> >   Installed: 2.31-13+rpt2+rpi1+deb11u9
> >   Candidate: 2.31-13+rpt2+rpi1+deb11u9
> >   Version table:
> >  *** 2.31-13+rpt2+rpi1+deb11u9 500
> >         500 http://archive.raspberrypi.org/debian bullseye/main armhf Packages
> >         100 /var/lib/dpkg/status
> >      2.31-13+rpi1+deb11u8 500
> >         500 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages
> > ```
> 
> No luck. You have to compile it yourself

Noo, You got any instructions for self-compilint glibc ?
If so. even possible on the pi itself cause of ressource usage?

**Comment by delneg** [comment]
It's possible to statically compile glibc inside fastfetch (it can be distributed as an additional binary)
Or as an alternative you can try to install nix https://github.com/DeterminateSystems/nix-installer and do `nix shell nixpkgs#fastfetch`

**Comment by CrazyWolf13** [comment]
Statically compiling inside fastfetch would make more sense to me, as compilin as a raspberrypi has always been quite difficult, as far as I remember.

Also I guess that is a problem to all raspberrypi users, so everyone would benefit from this.

**Comment by FabioLolix** [comment]
You can't rebuild the .deb package against the local glibc version?

**Comment by CrazyWolf13** [comment]
> You can't rebuild the .deb package against the local glibc version?

I found the following commands which seem to make sense on rebuiliding agains local glibc;

```
mkdir fastfetch_temp
dpkg-deb -R fastfetch-linux-armv7l.deb fastfetch_temp
```
```
cd fastfetch_temp/DEBIAN
nano control
```
Here I should remove the dependent glibc version, but in this file there is no specific libc version specified?

```
dpkg-deb -b fastfetch_temp fastfetch-linux-armv7l-rebuilt.deb
```
After rebuilding and installing the issue was still there.

**Comment by CarterLi** [comment]
Please try this: https://github.com/fastfetch-cli/fastfetch/actions/runs/8965509200/artifacts/1475632995

**Comment by CrazyWolf13** [comment]
> Please try this: https://github.com/fastfetch-cli/fastfetch/actions/runs/8965509200/artifacts/1475632995

Thanks this worked. is this now default for any armv7l package?

**Comment by CarterLi** [comment]
Yes

**Comment by CrazyWolf13** [comment]
Awesome, ty

**Comment by Teraskull** [comment]
Is there a working build for aarch64? I'm using Pi OS 11 Bullseye, thanks!

```shell
./fastfetch: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./fastfetch)
./fastfetch: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./fastfetch)
```

**Comment by CrazyWolf13** [comment]
Confirming, recent build shows the same error again.
Even when using the commands to rebuild without glibc from above I get the following error:
```bash
pi@raspberrypi:~/fastfetch_temp/DEBIAN $ dpkg-deb -b fastfetch_temp fastfetch-linux-armv7l-rebuilt.deb^C
pi@raspberrypi:~/fastfetch_temp/DEBIAN $ cd ../..
pi@raspberrypi:~ $ dpkg-deb -b fastfetch_temp fastfetch-linux-armv7l-rebuilt.deb
dpkg-deb: building package 'fastfetch' in 'fastfetch-linux-armv7l-rebuilt.deb'.
pi@raspberrypi:~ $ dpkg -i fastfetch-linux-armv7l-rebuilt.deb 
dpkg: error: requested operation requires superuser privilege
pi@raspberrypi:~ $ sudo dpkg -i fastfetch-linux-armv7l-rebuilt.deb 
(Reading database ... 172332 files and directories currently installed.)
Preparing to unpack fastfetch-linux-armv7l-rebuilt.deb ...
Unpacking fastfetch:armhf (2.38.0) over (2.38.0) ...
Setting up fastfetch:armhf (2.38.0) ...
Processing triggers for man-db (2.11.2-2) ...
pi@raspberrypi:~ $ fastfetch
-bash: /usr/bin/fastfetch: cannot execute: required file not found
pi@raspberrypi:~ $ sudo fastfetch
sudo: unable to execute /usr/bin/fastfetch: No such file or directory
```

**Comment by CarterLi** [comment]
After [v2.36.1](https://github.com/fastfetch-cli/fastfetch/releases/tag/2.36.1), the official Linux builds for aarch64 no longer support Debian 11. You have to either build fastfetch yourself, or use an older version.

**Comment by CrazyWolf13** [comment]
@CarterLi  Though I run bookworm not bullseye :/
