### ISSUE TITLE
Logo and text overflow when the terminal windows is small [BUG]

### ISSUE THREAD

**Issue by MasterKing0806** [fastfetch-cli/fastfetch#886]
General description of bug:
* I am currently on the newest arch package version 2.11.3-1
* When using fastfetch in alacritty in a tiling window manager (Hyprland, Sway) the text and logo overflow in smaller terminal windows. * This results in the small terminal windows being quite messy.
* Expected behaviour would be that the text does not overflow and the information can still be viewed normally in a smaller window.
* I have tried the latest -git build from the aur but that didn't help either.
* following the troubleshooting step in the wiki under logo (clearing and setting height/width) did not help either

Often helpful information:
Screenshot:
![2024-05-05_16-05-1714919333](https://github.com/fastfetch-cli/fastfetch/assets/86056562/e4aee545-61cf-41c4-9425-af3c22b0ca8d)

Output of fastfetch --list-features:
threads
vulkan
wayland
xcb-randr
xcb
xrandr
x11
drm
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
egl
glx
osmesa
opencl
libpulse
libnm
libddcutil
Directx Headers
Proprietary GPU driver API
System yyjson
linux/videodev2
linux/wireless

**Comment by CarterLi** [comment]
> Expected behaviour would be that the text does not overflow and the information can still be viewed normally in a smaller window.

How can you do that?

**Comment by MasterKing0806** [comment]
I am not aware how myself. I should have mentioned before that I migrated from Neofetch and it did not happen there. 

![2024-05-05_17-05-1714921309](https://github.com/fastfetch-cli/fastfetch/assets/86056562/948022c2-84c6-44c4-aca6-9aff5a522e06)

Maybe the phrase "expected behaviour" was misleading in this case.

**Comment by CarterLi** [comment]
Try `fastfetch --disable-linewrap`

**Comment by MasterKing0806** [comment]
It fixes my issue when I manually starting fastfetch. But if I insert ``fastfetch --disable-linewrap`` in my bashrc file, the result stays the same as mentioned before.

**Comment by CarterLi** [comment]
try `sleep 1` before running fastfetch

**Comment by MasterKing0806** [comment]
It works but only partially. When splitting the window vertically the issue persists but horizontally it is resolved.

![2024-05-05_17-05-1714924739](https://github.com/fastfetch-cli/fastfetch/assets/86056562/bfa067c1-74f6-45b2-9605-77145cdfadd5)

**Comment by CarterLi** [comment]
Then try sleep 2. If it still does not work, try sleep 3. etc

**Comment by MasterKing0806** [comment]
Unfortunately it did not solve it.

**Comment by CarterLi** [comment]
I have no idea. If fastfetch works if you run fastfetch manually, it's not a fastfetch bug
