### ISSUE TITLE
[LOGO]

### ISSUE THREAD

**Issue by Cromix454** [fastfetch-cli/fastfetch#887]
Tip: A logo can be displayed by fastfetch without getting into fastfetch's official repo. For highly customized logo for personal use, it's recommended to keep it locally. Please refer to https://github.com/fastfetch-cli/fastfetch/wiki/Migrate-Neofetch-Logo-To-Fastfetch

# OS
```
Paste content of /etc/os-release and /etc/lsb-release here. If none of these files exist, describe a way to identify the distro
```

# Ascii
```
Paste ascii art here. https://github.com/Cromix454/Flyer61.com.git
```

**Comment by CarterLi** [comment]
spam
