### ISSUE TITLE
[BUG] macOS Sonoma 14.4.1 - no logo when using fastfetch in .zshrc

### ISSUE THREAD

**Issue by wojciehm** [fastfetch-cli/fastfetch#891]
# General description of bug:

* What happened: Fastfetch install via homebrew. Whenever I run the command in already opened terminal it works. When I put it in .zshrc information is displayed but not in the same way as run explicite from command line.
* What should happen: During opening of iterm2 fasfetch should display OS logo and all information
* Fastfetch version used: fastfetch 2.11.3 (aarch64)
* Did it work in an older version: 
* Where did you get the binary: homebrew
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)?

# Often helpful information:

Screenshot:
<img width="1296" alt="image" src="https://github.com/fastfetch-cli/fastfetch/assets/19718255/a086e157-d4cd-48f8-ab17-91e054d021ec">
<img width="2460" alt="image" src="https://github.com/fastfetch-cli/fastfetch/assets/19718255/8ff093e6-4d95-4055-a2c1-e7d98e468325">

The content of the configuration file you use (if any):
```
//paste here
```

Output of `fastfetch -c ci.jsonc --format json`:

```
//paste here
```

Output of `fastfetch --list-features`:
```
//paste here
```

## If fastfatch crashed or freezed

Paste the stacktrace here. You may get it with:

```shell
# You may need Ctrl+C to stop the process if it freezes
gdb -q -ex 'set confirm off' -ex run -ex 'bt full' -ex quit --args /path/to/fastfetch
```

If you are able to identify which module crashed, the strace can be helpful too

```shell
strace /path/to/fastfetch --multithreading false -s {MODULE} --pipe
```

If you cannot do the instructions above, please upload the core dump file:

## If fastfetch is slow

Use `time fastfetch --stat` to show time usage for each module.

## If my image logo didn't show / work

* The image protocol you used: no idea, I am not using any specific image
* The terminal you used: iterm2
* Upload the image file here, or paste the image URL: no image used by me, I want to see the same OS logo when I run CLI explicit from iterm
* Does it work with `--logo-width {WIDTH} --logo-height {HEIGHT}`? 

## If fastfetch behaves incorrectly on shell starting

* The bug is reproduceable with fresh / clean shell configuration (i.e. `fastfetch` is the single line of `.zshrc` or `~/.config/fish/config.fish`): 
* Does `sleep 1` before running `fastfetch` work?

**Comment by CarterLi** [comment]
Can you please follow the bug report instructions in `If my image logo didn't show / work` section?

**Comment by CarterLi** [comment]
Sorry wrong section.

`If fastfetch behaves incorrectly on shell starting` this one

**Comment by wojciehm** [comment]
astfetch --pipe false fixed the issue. Thanks for your support.
