### ISSUE TITLE
[BUG] Error: unknown option: --os-file

### ISSUE THREAD

**Issue by ceamac** [fastfetch-cli/fastfetch#894]
# General description of bug:

* What happened: if I start fastfetch with no arguments, it says `Error: unknown option: --os-file`
* Fastfetch version used: 2.11.4
* Did it work in an older version: yes, 2.11.3 works fine
* Where did you get the binary: Built from source
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? yes

# Often helpful information:

Output of `fastfetch --list-features`:
```
threads
vulkan
wayland
xcb-randr
xcb
xrandr
x11
drm
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
sqlite3
egl
glx
osmesa
opencl
libpulse
libnm
libddcutil
Proprietary GPU driver API
System yyjson
linux/videodev2
linux/wireless
```

Does the same with less features too:
```
threads
System yyjson
linux/videodev2
linux/wireless
```

**Comment by CarterLi** [comment]
This flag was removed in 2.11.4, in favor of the newly introduced CMake option `-DCUSTOM_OS_RELEASE_PATH=/path/to/os-release`, so that it can be configured at compile time by package managers.

Do you have any old `config.conf` file in `~/.config/fastfetch/`?

**Comment by ceamac** [comment]
Yes, that was it.  I removed it and all works fine.  Thanks!

**Comment by CarterLi** [comment]
I did find that I forgot to remove this flag in the help text...
