### ISSUE TITLE
[BUG]  OpenMandriva logo is no more displayed

### ISSUE THREAD

**Issue by AngryPenguinPL** [fastfetch-cli/fastfetch#896]
# General description of bug:

* What happened: From fastfetch 2.11.2 logo OpenMandriva is no more displayed. This is important to us because we have set fastfetch as the default installed program in the distribution.
* What should happen: OpenMandriva logo should be displayed again.
* Fastfetch version used:  2.11.2 to 2.11.4
* Did it work in an older version:  Yes it worked fine up to 2.11.1, problem appears in 2.11.2.
* Where did you get the binary:  Package compiled by myself and also tested in prebuild binary from GitHub release page.
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Yes.

# Often helpful information:

Screenshot:
 
![Screenshot_20240506_173034](https://github.com/fastfetch-cli/fastfetch/assets/3121142/270bf877-8a6d-4880-bf91-e328dda2810d)
On left side fastfetch 2.11.1 showing OpenMandriva logo, while on right side 2.11.4 without OpenMandriva logo.

The content of the configuration file you use (if any):
```
//paste here
```

Output of `fastfetch -c ci.jsonc --format json`:

long output so uploaded to pastebin: https://pastebin.com/Ngc7tRmv

Output of `fastfetch --list-features`:
```
fastfetch --list-features
threads
vulkan
wayland
xcb-randr
xcb
xrandr
x11
drm
gio
dconf
dbus
imagemagick7
chafa
zlib
sqlite3
rpm
egl
glx
osmesa
opencl
libpulse
libnm
Proprietary GPU driver API
linux/videodev2
linux/wireless

```

## If my image logo didn't show / work

* The image protocol you used: any
* The terminal you used:  gnome-terminal, gnome-console, kde konsole, kitty all affected
* Upload the image file here, or paste the image URL: 
* Does it work with `--logo-width {WIDTH} --logo-height {HEIGHT}`?  No

Worth to add logo is displayed correctly when I call it by `fastfetch -l openmandriva`

**Comment by CarterLi** [comment]
Strangely I don't change things about OpenMandriva logo in 2.11.1. It would be very helpful if you can find the bad commit by using `git bitsect`

**Comment by CarterLi** [comment]
I think I find what the problem is. OpenMandriva should have `/etc/lsb-release` and `DISTRIB_ID=OpenMandriva Lx`.

**Comment by CarterLi** [comment]
v2.11.5 will be released soon to fix this issue

**Comment by AngryPenguinPL** [comment]
Indeed, the problem has been solved. Thanks
