### ISSUE TITLE
"terminal font: "section not appearing for st (suckless terminal) but it's appearing for alacritty

### ISSUE THREAD

**Issue by nitrogenxx** [fastfetch-cli/fastfetch#900]
on **st (suckless terminal)** `neofetch` is showing terminal font section but `fastfetch` is not showing terminal font sections 
butttt...🍑👋
on **alacritty** terminal `fastfetch` is showing terminal font section but `neofetch` is not showing terminal font section there 
(vice versa)

btw on xfce4-terminal both `neofetch` `fastfetch` both are showing terminal font section 
# I'm looking fastfetch solution for st terminal  
why some terminal show some section but some don't

# General description of bug:

* What happened baby: **font name is not correct on fastfetch (or terminal font entry not showing)**
* What should happen: **fastfetch should show correct like neofetch like ST terminal**
* Fastfetch version used: **latest fastfetch 2.11.3-debug (x86_64)**
* Did it work in an older version: **IDK im new to fastfetch**
* Where did you get the binary: **installed via pacman on archlinux**
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? **IDK**

# Often helpful information:

Screenshot:
![image](https://github.com/fastfetch-cli/fastfetch/assets/132397259/fe022064-a9ba-4c86-a3bc-cb506c654878)

also neofetch not showing `font` section  |  fastfatch not showing `terminal font` section 

The content of the configuration file you use (if any): **default**

Output of `fastfetch -c ci.jsonc --format json`:
```
 {
    "type": "TerminalFont",
    "result": {
      "font": {
        "name": "Iosevka Nerd Font",
        "size": "14",
        "styles": [],
        "pretty": "Iosevka Nerd Font (14pt)"
      },
      "fallback": {
        "name": "",
        "size": "",
        "styles": [],
        "pretty": ""
      }
    },
    "stat": 0
  },
```

Output of `fastfetch --list-features`:
```
threads
vulkan
wayland
xcb-randr
xcb
xrandr
x11
drm
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
egl
glx
osmesa
opencl
libpulse
libnm
libddcutil
Directx Headers
Proprietary GPU driver API
System yyjson
linux/videodev2
linux/wireless
```

## If fastfatch crashed or freezed
nope

## If fastfetch is slow
nope

* The terminal you used: st (suckless terminal) and xfce4-terminal and alacritty and kitty

## If fastfetch behaves incorrectly on shell starting
nope, using default bash

**Comment by CarterLi** [comment]
If it's detected with `-c ci.jsonc --format json`, it should also be detected with the default config. What does `fastfetch --show-errors` print?

**Comment by CarterLi** [comment]
`Font section` is the global system font setting, not terminal font.

**Comment by nitrogenxx** [comment]
> 1. What does `fastfetch --show-errors` print?
![image](https://github.com/fastfetch-cli/fastfetch/assets/132397259/d0fd337b-7726-4a6e-98b1-a89eabfdcfdf)

`Terminal Font: st was not executed with -f parameter`
why fastfetch is asking for terminal font explicitly 
like  `st -f "Iosevka Nerd Font:pixelsize=19"`
when terminal font is already configured in st terminal config and working perfectly through out the terminal expect fastfetch
it should detect terminal font automatically 

> 2\. What does `fastfetch --list-config-paths` print?
```bash
/home/user/.config/fastfetch/
/home/user/fastfetch/
/etc/xdg/fastfetch/
/etc/fastfetch/

```


> 3\. What is the command line you use to start st?

command: "st" (without quote)

I'm really glad to seek help from you 🍁

**Comment by CarterLi** [comment]
I checked the implementation in neofetch

https://github.com/dylanaraps/neofetch/blob/master/neofetch#L3563-L3568

It should not work since neofetch was searching for lower cased `font` while you specified `Font`. I wonder how you get the correct result.

Anyway, I have implemented the similar logic which searches for `size=`. Please test the latest dev build
