### ISSUE TITLE
Able to change the color of the information text

### ISSUE THREAD

**Issue by TriDEntApollO** [fastfetch-cli/fastfetch#904]
## Disclaimer

I don't know if this is already available or not i was unable to find it 

## Wanted features:

to be able to customize the color of the information text and not only the key

```
{
    "modules": [
        {
            "type": "host",
            "key": "Machine",
            "keyColor": "yellow",
            "textColor": "blue" // add this property
        }
    ]
}
```

![image](https://github.com/fastfetch-cli/fastfetch/assets/68052236/3a147d0c-1c87-417b-afa9-b684222774a3)

customize color of these texts

**Comment by CarterLi** [comment]
Doable, but it is kind of troublesome when some texts are already colored

**Comment by CarterLi** [comment]
BTW, you need a nerd font

**Comment by CarterLi** [comment]
```jsonc
{
  "display": {
    "color": {
      "output": "green" // default color
    },
  },
  "modules": [
    "os", // show in green
    {
      "type": "host",
      "outputColor": "red" // show in red
    }
  ]
}
```

**Comment by TriDEntApollO** [comment]
> Please test the dev build
> 
> ```js
> {
>   "display": {
>     "color": {
>       "output": "green" // default color
>     },
>   },
>   "modules": [
>     "os", // show in green
>     {
>       "type": "host",
>       "outputColor": "red" // show in red
>     }
>   ]
> }
> ```

i tried this on y current fastfetch install and it did not work, i am using the latest 2.11.5 version on windows and i installed it with scoop. 

Also where can i find the dev build

**Comment by CarterLi** [comment]
https://github.com/fastfetch-cli/fastfetch/actions/runs/8998574253
