### ISSUE TITLE
[BUG]  Packages Breaks Pacman on ArcoLinux

### ISSUE THREAD

**Issue by Burnsedia** [fastfetch-cli/fastfetch#905]
# General description of bug:
I installed fastfetch on arcolinux and I am now unable to update my system. 
* What happened: All updates crash, unable to lunch program either
* What should happen: Program lunches, system still updates
* Fastfetch version used: 
* Did it work in an older version: 
* Where did you get the binary: 
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)?

# Often helpful information:

Screenshot:

The content of the configuration file you use (if any):
```
//paste here
```

Output of `fastfetch -c ci.jsonc --format json`:

```
//paste here
```

Output of `fastfetch --list-features`:
```
//paste here
```

## If fastfatch crashed or freezed

Paste the stacktrace here. You may get it with:

```shell
# You may need Ctrl+C to stop the process if it freezes
gdb -q -ex 'set confirm off' -ex run -ex 'bt full' -ex quit --args /path/to/fastfetch
```

If you are able to identify which module crashed, the strace can be helpful too

```shell
strace /path/to/fastfetch --multithreading false -s {MODULE} --pipe
```

If you cannot do the instructions above, please upload the core dump file:

## If fastfetch is slow

Use `time fastfetch --stat` to show time usage for each module.

## If my image logo didn't show / work

* The image protocol you used: 
* The terminal you used: 
* Upload the image file here, or paste the image URL: 
* Does it work with `--logo-width {WIDTH} --logo-height {HEIGHT}`? 

## If fastfetch behaves incorrectly on shell starting

* The bug is reproduceable with fresh / clean shell configuration (i.e. `fastfetch` is the single line of `.zshrc` or `~/.config/fish/config.fish`): 
* Does `sleep 1` before running `fastfetch` work?

**Comment by CarterLi** [comment]
I don't think fastfetch has this kind of power, or I would have named fastfetch as nuclear-missle

**Comment by CarterLi** [comment]
Submit your bug to arcolinux instead.

**Comment by Burnsedia** [comment]
Thanks. maybe pacman. I can't even remove the package.

maybe the person packaging this added mailware. This is not in the AUR but it was in the community repo

**Comment by CarterLi** [comment]
Please don't spread misinformation. Most system package managers are installed in system folder `/usr/bin`. A user application can NOT modify it without root permissions.

AFAIK arcolinux uses the official archlinux packages. [Fastfetch has been in archlinux official repo for half a year](https://gitlab.archlinux.org/archlinux/packaging/packages/fastfetch/-/commits/main), and [it has been in AUR for three years](https://aur.archlinux.org/packages/fastfetch-git). I don't think you are the first one to install fastfetch by pacman.
