### ISSUE TITLE
[FEAT] Option to show CPU and GPU temps in fahrenheit

### ISSUE THREAD

**Issue by ask-compu** [fastfetch-cli/fastfetch#908]
in the cpu and gpu modules allow choosing the unit the temperature is displayed in

**Comment by CarterLi** [comment]
`display.temp.unit: F`

See `fastfetch -h temp-unit`

**Comment by ask-compu** [comment]
> `display.temp.unit: F`
> 
> See `fastfetch -h temp-unit`

i get an `Error: unknown option: --temp-unit` when trying to use it

**Comment by ask-compu** [comment]
![image](https://github.com/fastfetch-cli/fastfetch/assets/11810555/92fa609d-f722-4234-ba0d-ef10adab2422)

**Comment by CarterLi** [comment]
Use display.temp.unit in config.json

**Comment by ask-compu** [comment]
ah ok i figured it out, but that unknown option bug needs fixing
