### ISSUE TITLE
[FEAT] Enable compile_commands.json generation through cmake

### ISSUE THREAD

**Issue by ManuaL46** [fastfetch-cli/fastfetch#912]
## Wanted feature:

Hi this is a very simple request, can we enable the feature to generate compile_commands.json for clangd in cmake.
We simply would have to add `set(CMAKE_EXPORT_COMPILE_COMMANDS ON)` to the cmake file.

## Motivation:

Would make working on the code much easier right after cloning the repo and the change itself is pretty simple.

**Comment by CarterLi** [comment]
Since you use clangd, doesn't LSP add this flag automatically?
