### ISSUE TITLE
[BUG] Neofetch preset error

### ISSUE THREAD

**Issue by Tiagoquix** [fastfetch-cli/fastfetch#916]
### General description of bug:

* What happened: when using the neofetch preset, theme line has weird characters:
`Theme: Breeze (Dark) [QT], Breeze [GTK3]{?3} {3} [Plasma], {?}{7}`

* What should happen: should not have weird characters.
* Fastfetch version used: 2.9.1
* Did it work in an older version: I didn't use any version before this one.
* Where did you get the binary: Fedora Linux repositories
```
Repository   : @System
From repo    : updates
```
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? I don't know. I know it also happens on 2.11.3 on NixOS (tested by a friend of mine).

# Often helpful information:

Screenshot:
![image](https://github.com/fastfetch-cli/fastfetch/assets/30274161/818c4d09-aa45-431e-b1fb-b274afa00410)

The content of the configuration file you use (if any):
```
Default config, but with "-c neofetch".
```

Output of `fastfetch -c ci.jsonc --format json`:
```
I don't think it's necessary for this case.
```

Output of `fastfetch --list-features`:
<details>

```
threads
vulkan
wayland
xcb-randr
xcb
xrandr
x11
drm
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
sqlite3
rpm
egl
glx
osmesa
opencl
libpulse
libnm
libddcutil
videodev2
Proprietary GPU driver API
```

</details>

**Comment by CarterLi** [comment]
It has been fixed in newer versions
