### ISSUE TITLE
[BUG] Unable to show nfs disk mounts with fastfetch

### ISSUE THREAD

**Issue by masterdokuro** [fastfetch-cli/fastfetch#920]
This maybe a feature request or a bug so please change the label if I have placed it incorrectly.

I'm moving off neofetch to fastfetch and I'm having one problem which I'm hoping you can help me with.  I'd like to display nfs disk/mount information via fastfetch.  Is this possible with fastfetch?  I'm able to do it with neofetch so I'm hoping its possible with fastfetch as well.

**Description:**
As an example, I have a mount **192.168.1.4:/nfs/4a-Music** mounted to **/data/MediaServer/4a-Music** and when I configure the disk module like this ...
        {
            "type": "disk",
            "keyColor": "cyan",
            "folders": "/data/MediaServer/4a-Music",
            "key": "Disk (4a-Music)"
        },
... it does not display.  There is no error, it just does not display.  I've tried adding the showExternal property but that doesn't help. Is this somehow possible ?

My OS is fedora 40 which is running **fastfetch 2.9.1 (x86_64)** installed via dnf.

**Comment by CarterLi** [comment]
2.9.1 is kind of old. Please try installing the latest version: https://github.com/fastfetch-cli/fastfetch/releases/download/2.12.0/fastfetch-linux-amd64.rpm

If it still doesn't work, please paste the content of `fastfetch -c none -s disk --format json`

**Comment by masterdokuro** [comment]
Thank you for the quick reply.  I installed **fastfetch 2.12.0** linked above and its now detecting the nfs mounts as I was expecting.  I guess the fedora repro is just a bit behind.
