### ISSUE TITLE
Manjaro is given arch logo

### ISSUE THREAD

**Issue by kareemAbd0** [fastfetch-cli/fastfetch#921]
# General description of bug:

Manjaro is given arch logo after the recent update

* What happened: gotten arch logo
* What should happen: manjaro logo like before the update
* Fastfetch version used:  fastfetch 2.11.5-debug (x86_64)

* Did it work in an older version:  yes, I am not sure which version
* Where did you get the binary:  pacman

![image](https://github.com/fastfetch-cli/fastfetch/assets/89319659/cea104ee-93f8-44bd-8083-b53e50d4a7ce)

```

Output of `fastfetch --list-features`:

```
 fastfetch --list-features
threads
vulkan
wayland
xcb-randr
xcb
xrandr
x11
drm
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
egl
glx
osmesa
opencl
libpulse
libnm
libddcutil
Directx Headers
Proprietary GPU driver API
System yyjson
linux/videodev2
linux/wireless
```

**Comment by CarterLi** [comment]
Please paste the content of `/etc/lsb-release` and `/etc/os-release`

**Comment by kareemAbd0** [comment]
/etc/lsb-release

DISTRIB_ID="ManjaroLinux"
DISTRIB_RELEASE="24.0.0"
DISTRIB_CODENAME="Wynsdey"
DISTRIB_DESCRIPTION="Manjaro Linux"

################

/etc/os-release

NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux

**Comment by DarNCelsius** [comment]
Confirmed. I'm not sure, but I think the previous version may have been 2.8.7.

**Comment by CarterLi** [comment]
This bug was introduced in https://github.com/fastfetch-cli/fastfetch/commit/8b838cef61a4012c4887d72492e93f17fe3ca30e in which I priorized `/etc/lsb-release` over `/etc/os-release`. A similar issue has been reported in #896

**Comment by kareemAbd0** [comment]
the issue is solved after testing this in a manual from source build, thank you.
