### ISSUE TITLE
[FEAT] Identify the boot manager

### ISSUE THREAD

**Issue by patrick-g** [fastfetch-cli/fastfetch#922]
## Wanted features:

It would be nice to display the boot manager (whether the OS is using GRUB, systemd-boot, etc).

## Motivation:

Fastfetch already support the "Bios" module so adding a module for the boot manager would be a valuable addition.

**Comment by CarterLi** [comment]
Done. Please test the latest dev build.

Note we support UEFI mode only, because we grab the information from UEFI variables.

**Comment by patrick-g** [comment]
I confirm it works fine. Thanks a lot!

![ff](https://github.com/fastfetch-cli/fastfetch/assets/396194/47cb6f8f-8083-4e17-b933-57b6e37597a2)

**Comment by CarterLi** [comment]
What is the firmware?

**Comment by patrick-g** [comment]
The BOOTMGR.
