### ISSUE TITLE
[BUG] terminalfont module returns badly formated font name

### ISSUE THREAD

**Issue by masterdokuro** [fastfetch-cli/fastfetch#924]
Not sure if this is a bug or something just odd on my system.  I'm using the following ...
        {
            "type": "terminalfont",
            "keyColor": "blue",
            "key": "│ Terminal Font"
        },
... within my config file and it returns **Terminal Font - LiberationMono (9pt)** when I run fastfetch.  Notice there is no space between Liberation and Mono.  

If I run **gsettings get org.gnome.desktop.interface monospace-font-name** it returns **'Liberation Mono 9'**.  This has the space between Liberation and Mono.

My terminal is kitty and I'm using version **fastfetch 2.12.0 (x86_64)**.

**Comment by CarterLi** [comment]
It's returned by kitty. Please try `kitty +kitten query-terminal`

**Comment by masterdokuro** [comment]
Interesting... that returns ...

```
allow_hyperlinks: yes
bold_font: LiberationMono-Bold
bold_italic_font: LiberationMono-BoldItalic
clipboard_control: write-clipboard write-primary read-clipboard-ask read-primary-ask
font_family: LiberationMono
font_size: 9
italic_font: LiberationMono-Italic
name: xterm-kitty
version: 0.34.1
```
I do have the following within my kitty.conf

font_family 		Liberation Mono
bold_font 		Liberation Mono Bold
italic_font 		Liberation Mono Italic
bold_italic_font 	Liberation Mono Bold Italic
font_size 9

... which I took the values from **kitty +list-fonts**.  Anyhow, let me see if there is something funky on my config file.  Thanks.
