### ISSUE TITLE
[FEAT] More than 9 colors in ascii custom logos

### ISSUE THREAD

**Issue by FrancescoCaracciolo** [fastfetch-cli/fastfetch#928]
## Wanted features:

Support for more than 9 colors in displaying the ASCII, at the moment it is only possible to add $N [1-9] colors.

## Motivation:

The logo I want to use has like 236 different colors...

**Comment by CarterLi** [comment]
$N was designed for changing color palette in config file. A logo that has 236 different colors makes $N meaningless. In this case, you can embed ANSI escape code directly in the logo file.

https://github.com/fastfetch-cli/fastfetch/blob/9f35ba7751773103827ee8cb92ae5013c5fd397b/src/logo/ascii/furreto.txt

**Comment by CarterLi** [comment]
Worth noting that we don't accept logos that has so many colors. You either reduce the number of colors, or maintain the logo yourself.

**Comment by FrancescoCaracciolo** [comment]
![image](https://github.com/fastfetch-cli/fastfetch/assets/67018178/be5dabc6-d7c5-4eb7-a27c-b2f9496d716d)
Am I missing something?
