### ISSUE TITLE
[FEAT] Performance core and Efficiency core counts

### ISSUE THREAD

**Issue by rrotter** [fastfetch-cli/fastfetch#930]
## Wanted features:

Display number of performance and efficiency cores in cpu. Presumably this would just get skipped for systems that don't have E cores.

I'm not sure how to get this on other OSes, but at least on macOS this is available with:
```
sysctl hw.nperflevels
sysctl hw.perflevel0
sysctl hw.perflevel1
```

## Motivation:

This is important information about the performance of a personal computer that tends to be obscure to locate, esp useful as P/E cores are increasingly ubiquitous on client computers.

**Comment by CarterLi** [comment]
It's definitely not an easy work. AFAIK other than macOS, there are no such sysctls to query P/E core count and you have to use some platform-specific instructions (`cpuinfo`) or to guess it with max frequency.

In my Android smartphone, there are even 3 level (1 Prime X3 + 5 Performance A720 + 2 Efficiency A520) cores. 5 Performance cores even have different max frequencies.

For now, I suggest you use cpufetch. This is not what fastfetch is good at.

**Comment by CarterLi** [comment]
Done. Please test the latest dev build.

```
$ ./fastfetch -l none -s cpu --cpu-format '{1} ({9}) @ {7} GHz'
CPU: 13th Gen Intel(R) Core(TM) i7-13700KF (16 + 8) @ 5.4 GHz
```

Note: we detect logical core count instead of physical core count ( which makes no difference for Apple )

**Comment by CarterLi** [comment]
Fastfetch prints

```
CPU: SM8650 (1 + 3 + 2 + 2) @ 3.3024 GHz
```

on my Android smartphone.I wonder if I should make it the default output format

**Comment by rrotter** [comment]
```
~ % fastfetch -l none -s cpu
CPU: Apple M2 Max (12) @ 3.50 GHz
~ % fastfetch -l none -s cpu --cpu-format '{1} ({9}) @ {7} GHz'
CPU: Apple M2 Max (8 + 4) @ 3.504 GHz
```
👍 thanks.
