### ISSUE TITLE
[BUG] `disk` module + `logo` causes straggling characters that disappear on window resize

### ISSUE THREAD

**Issue by brian6932** [fastfetch-cli/fastfetch#935]
# General description of bug:

* What happened: With `{"modules":["disk"]}` set as the `config.jsonc` (to be clear it happens with more than one module, just that module has to enabled), invoking the command will generate `\`s before the first driver letter. The few other straggling characters, will show if any module's present + `logo`. It was resized back to the same size with <kbd>ALT</kbd>+<kbd>ENTER</kbd> 2x in Alacritty, starting window size doesn't seem to matter.
* What should happen: Should look the same as the resized window has been resized.
* Fastfetch version used: fastfetch 2.12.0 (x86_64)
* Did it work in an older version: Somewhat, but there was a similar bug.
* Where did you get the binary: Scoop (GitHub release)
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? yes

# Often helpful information:

Screenshot:

<details>
	<summary>invocation</summary>

```
❯ fastfetch
l\\\\                           ..,         Disk (C:\): 421.07 GiB / 3.72 TiB (11%) - NTFS
                    ....,,:;+ccllll    Disk (D:\): 1.54 TiB / 1.82 TiB (85%) - NTFS
      ...,,+:;  cllllllllllllllllll
,cclllllllllll  lllllllllllllllllll
llllllllllllll  lllllllllllllllllll
llllllllllllll  lllllllllllllllllll
llllllllllllll  lllllllllllllllllll
llllllllllllll  lllllllllllllllllll
llllllllllllll  lllllllllllllllllll

llllllllllllll  lllllllllllllllllll
llllllllllllll  lllllllllllllllllll
llllllllllllll  lllllllllllllllllll
llllllllllllll  lllllllllllllllllll
llllllllllllll  lllllllllllllllllll
`'ccllllllllll  lllllllllllllllllll
       `' \*::  :ccllllllllllllllll
                       ````''*::cll
h                                ``                             ``
```
</details>

<details>
	<summary>window resize</summary>

```
❯ fastfetch
                                ..,    Disk (C:\): 421.07 GiB / 3.72 TiB (11%) - NTFS
                    ....,,:;+ccllll    Disk (D:\): 1.54 TiB / 1.82 TiB (85%) - NTFS
      ...,,+:;  cllllllllllllllllll
,cclllllllllll  lllllllllllllllllll
llllllllllllll  lllllllllllllllllll
llllllllllllll  lllllllllllllllllll
llllllllllllll  lllllllllllllllllll
llllllllllllll  lllllllllllllllllll
llllllllllllll  lllllllllllllllllll

llllllllllllll  lllllllllllllllllll
llllllllllllll  lllllllllllllllllll
llllllllllllll  lllllllllllllllllll
llllllllllllll  lllllllllllllllllll
llllllllllllll  lllllllllllllllllll
`'ccllllllllll  lllllllllllllllllll
       `' \*::  :ccllllllllllllllll
                       ````''*::cll
                                 ``
```
</details>

<details>
	<summary>logo null (no resize needed)</summary>

```
❯ fastfetch
Disk (C:\): 421.07 GiB / 3.72 TiB (11%) - NTFS
Disk (D:\): 1.54 TiB / 1.82 TiB (85%) - NTFS
```
</details>

The content of the configuration file you use (if any):
<details>
	<summary>invocation & resize</summary>

```json
{
  "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
  "modules": [
    "disk"
  ]
}

```
</details>

<details>
	<summary>logo null</summary>

```json
{
  "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
  "logo": null,
  "modules": [
    "disk"
  ]
}

```
</details>

Output of `fastfetch --list-features`:
```
threads
vulkan
zlib
opencl
Proprietary GPU driver API
```

Shell: PowerShell 7.5.0-preview.2
Term: alacritty 0.14.0-dev (3a7f21b0)
OpenConsole/conhost: 1.20.2405.06001
Windows: 10.0.19044.4412

**Comment by CarterLi** [comment]
Can you reproduce it with Windows Terminal?

**Comment by brian6932** [comment]
Nope doesn't happen on `wt`.

**Comment by CarterLi** [comment]
Doesn't happen on Wezterm either. I think you should report it to alacritty

**Comment by CarterLi** [comment]
I think it was caused by the hyperlink escape code. I don't know if alacritty supports it. If not, the escape should be silently ignored

**Comment by brian6932** [comment]
Yes `fastfetch --pipe` works, there's just no color.

**Comment by CarterLi** [comment]
`fastfetch --disk-key 'Disk ({1})'` should also work

**Comment by CarterLi** [comment]
Tested in Linux. alacritty worked fine. Therefore it should be a Windows specific issue.

**Comment by brian6932** [comment]
> `fastfetch --disk-key 'Disk ({1})'` should also work

Yea it does, is there a way to set that in `config.jsonc`?

**Comment by CarterLi** [comment]
I downloaded and tried alacritty. It worked for me in both Win11 and Win10 (VM)

![image](https://github.com/fastfetch-cli/fastfetch/assets/6134068/bd16bf57-60ce-4377-bf78-5c04ec78c2bb)

Have no idea what's wrong in your machine.

**Comment by brian6932** [comment]
It might be because I replace `conhost` with `OpenConsole`, you need to either use `msys` or power off your vm, and then `cp OpenConsole.exe /c/windows/System32/conhost.exe -f` https://github.com/microsoft/terminal/releases/tag/v1.20.11271.0 with the zip as your working dir. Then try launching Alacritty and see if you can repro 🤔.

**Comment by brian6932** [comment]
Uhh, I restarted my PC, and the issue disappeared, I have no clue what the cause was o_O.
