### ISSUE TITLE
Raspberry pi5 running bookworm. Cannot install fastfetch

### ISSUE THREAD

**Issue by bert269** [fastfetch-cli/fastfetch#938]
The supplied PPA on installation page does not work:
admin@piWarden:~ $ sudo add-apt-repository ppa:zhangsongcui3371/fastfetch
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 362, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/add-apt-repository", line 345, in main
    shortcut = handler(source, **shortcut_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 86, in __init__
    if self.lpppa.publish_debug_symbols:
       ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
                  ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 113, in lpteam
    self._lpteam = self.lp.people(self.teamname)
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'people'

So I tried to install the .deb package. It installs, but when I execute fastfetch, I get this error:
admin@piWarden:~ $ fastfetch
**fastfetch: error while loading shared libraries: libm.so.6: ELF load command address/offset not page-aligned**

Any thoughts?

**Comment by bert269** [comment]
I added: kernel=kernel8.img to /boot/firmware/config.txt, rebooted and it worked!.
Any ideas why?

**Comment by CarterLi** [comment]
No idea.

**Comment by plsnotracking** [comment]
@CarterLi and @bert269 I think it's because the compilation of `fastfetch` is on a 4KB page size.

More context [here](https://www.raspberrypi.com/documentation/computers/linux_kernel.html)

> The standard, bcm2711_defconfig-based kernel (kernel8.img) also runs on Raspberry Pi 5. For best performance you should use kernel_2712.img, but for situations where a 4KB page size is required then kernel8.img (kernel=kernel8.img) should be used.

I don't exactly understand the context/implications of doing this, I'll wait for someone more educated to tell me this is ok. Thanks.

**Comment by CarterLi** [comment]
I tried https://github.com/fastfetch-cli/fastfetch/releases/download/2.13.2/fastfetch-linux-aarch64.tar.gz in my M1 MBP (asahilinux, which uses 16KiB page size too), it worked fine.

I manually compiled fastfetch in asahilinux. Can you try it?

[fastfetch-aarch64.tar.gz](https://github.com/fastfetch-cli/fastfetch/files/15450246/fastfetch-aarch64.tar.gz)

**Comment by ChaosBlades** [comment]
@CarterLi 
Should re-open this issue.
Also a problem on Pi4. Same exact error as OP.
The proposed solution is not a solution and probably has consequences.

You can manually install the aarch64.deb file manually and it works. Seems to specifically be a problem with the PPA.

```
wget https://github.com/fastfetch-cli/fastfetch/releases/download/2.30.1/fastfetch-linux-aarch64.deb
sudo apt install ./fastfetch-linux-aarch64.deb
```
```
       _,met$$$$$gg.           akanar@voron-mini
    ,g$$$$$$$$$$$$$$$P.        -----------------
  ,g$$P"         """Y$$.".     OS: Debian GNU/Linux bookworm 12.8 aarch64
 ,$$P'               `$$$.     Host: Raspberry Pi 4 Model B Rev 1.5
',$$P       ,ggs.     `$$b:    Kernel: Linux 6.6.51+rpt-rpi-v8
`d$$'     ,$P"'   .    $$$     Uptime: 12 mins
 $$P      d$'     ,    $$$P    Packages: 771 (dpkg)
 $$:      $.   -    ,d$$'      Shell: bash 5.2.15
 $$;      Y$b._   _,d$P'       Terminal: /dev/pts/1
 Y$$.    `.`"Y$$$$P"'          CPU: BCM2711 (4) @ 1.80 GHz
 `$$b      "-.__               GPU: Broadcom bcm2711-vc5 [Integrated]
  `Y$$                         Memory: 261.70 MiB / 1.80 GiB (14%)
   `Y$$.                       Swap: 0 B / 512.00 MiB (0%)
     `$$b.                     Disk (/): 9.15 GiB / 58.01 GiB (16%) - ext4
       `Y$$b.                  Local IP (eth0): 192.168.1.168/24
          `"Y$b._              Locale: en_GB.UTF-8
             `"""
                                                       
                                                       
```

**Comment by ryuupendragon** [comment]
For this "Traceback (most recent call last): - AttributeError: 'NoneType' object has no attribute 'people'" error, you need to install be packages. And you need to replace bookworm with jammy in sources list then install fastfetch.

sudo apt-get install software-properties-common python3-launchpadlib
