### ISSUE TITLE
[FEAT]  short models?

### ISSUE THREAD

**Issue by amithiel** [fastfetch-cli/fastfetch#946]
## Wanted features:

Short cpu/gpu model names

Example: NVIDIA GeForce RTX 3070 Lite Hash Rate [Discrete]

can this be turned into: GeForce RTX 3070 ?

in neofetch there was an option called gpu_brand="off" that would at least take the "nvidia" brand away.
Is something like this possible with fastfetch?

cheers

**Comment by CarterLi** [comment]
`fastfetch --gpu-format '{2}'` should take the vendor name (Nvidia) away.

See `fastfetch -h gpu-format` for detail

**Comment by amithiel** [comment]
thanks a bunch!! totally missed that
