### ISSUE TITLE
[BUG] "Terminal: pk-command-not-found"

### ISSUE THREAD

**Issue by megatux** [fastfetch-cli/fastfetch#950]
# General description of bug:

Just installed on Nobara (Fedora 39 based) and ran on Gnome terminal.
Seems ok, except for "Terminal: pk-command-not-found"

Should I install something else?

```
fastfetch --version
fastfetch 2.2.3 (x86_64)
```

**Comment by CarterLi** [comment]
2.2.3 is too old. Please install the latest version from fastfetch release page and try again.

**Comment by CarterLi** [comment]
Reopen this issue if it exists in the latest version
