### ISSUE TITLE
[FEAT] Add fastfetch to winget

### ISSUE THREAD

**Issue by lemon-sundae** [fastfetch-cli/fastfetch#959]
## Before requesting a new feature

* A lot of features are not enabled by default. Please try `fastfetch --list-modules` and `fastfetch -c all.jsonc` to see if it has been supported
* Fastfetch supports `Command` module, which can be used to grab output from a custom shell script. Please check if it fits your needs

```jsonc
// ~/.config/fastfetch/fastfetch.jsonc
{
    "modules": [
        {
            "type": "command",
            "text": "/path/to/your/script",
            "key": "Feature Title"
        }
    ]
}
```

## Wanted features:

Include `fastfetch` in winget source so that Windows users can install fastfetch with `winget install fastfetch` or something similar.

## Motivation:

Winget is the offical command line package manager released by Microsoft. It is easy to use and pre-installed in new versions of Windows. As some users may not have scoop installed and prefer to use winget instead, it will be more convenient if it is possible to directly install fastfetch with winget.

**Comment by CarterLi** [comment]
https://github.com/microsoft/winget-pkgs/blob/master/manifests/f/Fastfetch-cli/Fastfetch/2.13.1/Fastfetch-cli.Fastfetch.installer.yaml
