### ISSUE TITLE
[BUG] iterm logo does not work in Mintty / Git Bash terminal

### ISSUE THREAD

**Issue by ykhan21** [fastfetch-cli/fastfetch#962]
Be sure to read [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

# General description of bug:

* What happened: `fastfetch --logo Pictures/image.png --logo-type iterm --logo-width 20 --logo-height 20` does not display an image and instead prints output over the existing terminal buffer.

* What should happen: The image should display as mintty supports iterm and sixel.
* Fastfetch version used: fastfetch 2.13.2 (x86_64)
* Did it work in an older version: 
* Where did you get the binary: scoop
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)?

# Often helpful information:
- It probably is due to conpty intercepting the escape sequences. Compiling with cygwin tools might help.
- `export MSYS=disable_pcon` causes fastfetch to print the Windows logo.
- `export MSYS=enable_pcon` causes the ff output to be over existing text in the terminal. The `wezterm imgcat` command works in the Git Bash / Mintty terminal to display iterm images.
- Sixel also does not work.

Screenshot:
![image](https://github.com/fastfetch-cli/fastfetch/assets/51864191/a3522c8b-6b27-4962-a508-e75cb884e3ac)

## If my image logo didn't show / work

* The image protocol you used: iterm (and sixel)
* The terminal you used: Git Bash / Mintty terminal (from git for windows)
* Does it work with `--logo-width {WIDTH} --logo-height {HEIGHT}`? No.

**Comment by CarterLi** [comment]
It was expected

See previous discussion: https://github.com/mintty/mintty/issues/1192
