### ISSUE TITLE
[FEAT] output stdout like neofetch?

### ISSUE THREAD

**Issue by Epikcoder** [fastfetch-cli/fastfetch#967]
Be sure to read [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

## Wanted features:

Hi, just wanted to ask that it would probably be a good idea to add the --stdout format to fast fetch

**Comment by CarterLi** [comment]
`neofetch --stdout` is equivalent to `fastfetch --pipe -l none`
