### ISSUE TITLE
[BUG] Error: GPU detection failed on Android (Termux).

### ISSUE THREAD

**Issue by AcatXIo** [fastfetch-cli/fastfetch#976]
# General description of bug:

* What happened:
I'm using Motorola G32 smartphone with Qualcomm SM6225 Snapdragon 680 4G chipset, Adreno 610 GPU, and LineageOS 21.0-20240525 (Android 14) custom ROM installed and rooted.
I installed fastfetch on it with Termux using ```pkg install fastfetch```.
Running ```fastfetch -c all.jsonc``` (both with and without root permissions) doesn't show the GPU, and running with ```--fomat json``` shows ```"error": "GPU detection failed"```.
CPU detection works correctly.
I also tried ```--gpu-detection-method pci```, ```--gpu-detection-method vulkan``` and ```--gpu-detection-method opengl```, but all of them also failed to detect the GPU.
I tried some android system information apps from play store, and those did detect the GPU correctly.

* What should happen: The GPU detection should work correctly, or a more descriptive error should be printed, explaining why it doesn't work.

* Fastfetch version used: 2.13.2.

* Did it work in an older version: I don't know.

* Where did you get the binary: Termux ```pkg install fastfetch```.

* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/): Yes.

# Often helpful information:
The content of the configuration file you use (if any): I used all.jsonc without changes.

Output of `fastfetch -c ci.jsonc --format json`:
```json
{
  "type": "GPU",
  "error": "GPU detection failed"
}
```

Output of `fastfetch --list-features`:
```txt
threads
vulkan
freetype
linux/videodev2
linux/wireless
```

**Comment by CarterLi** [comment]
What does `fastfetch -s vulkan --format json` print?

**Comment by AcatXIo** [comment]
```json
{
  "type": "Vulkan",
  "error": "ffvkCreateInstance() failed"
}
```

**Comment by CarterLi** [comment]
> ```json
> {
>   "type": "Vulkan",
>   "error": "ffvkCreateInstance() failed"
> }
> ```

No luck. Fastfetch relies on working Vulkan driver reporting GPU models. All other methods are disabled on Vulkan because they are known not to work in non-rooted devices.

**Comment by CarterLi** [comment]
> some android system information apps from play store

Fastfetch has much more limitations compare to native android apps, because fastfetch doesn't have access to the Android Java APIs.

**Comment by CarterLi** [comment]
In v2.14.0, fastfetch will report more information about why creating vulkan instance fails. You should try it after fastfetch gets updated by Termux

**Comment by AcatXIo** [comment]
It now says:
```json
{
  "type": "Vulkan",
  "error": "ffvkCreateInstance() failed: VK_ERROR_INCOMPATIBLE_DRIVER"
}
```
Is there any way I can fix this, or is this the OS's fault?

**Comment by CarterLi** [comment]
```
[
  {
    "type": "Vulkan",
    "result": {
      "apiVersion": "1.3.128",
      "conformanceVersion": "1.3",
      "driver": "Qualcomm Technologies Inc. Adreno Vulkan Driver",
      "gpus": [
        {
          "type": "Integrated",
          "vendor": "Qualcomm",
          "name": "Adreno (TM) 750",
          "driver": "Driver Build: 62c1f322ce, Id0077aad60, 1700555917\nDate: 11/21/23\nCompiler Version: E031.42.23.09\nDriver Branch: \n",
          "platformApi": "Vulkan 1.3.128",
          "memory": {
            "dedicated": {
              "total": 0,
              "used": null
            },
            "shared": {
              "total": 20240965632,
              "used": null
            }
          },
          "deviceId": 1124406273
        }
      ]
    }
  }
]
```

**Comment by CarterLi** [comment]
You need to ask LineageOS. GPU / hardware support is not enough. A proper driver need to be installed to.

**Comment by AcatXIo** [comment]
Alright, thanks for your help.
