### ISSUE TITLE
[FEAT] Json export

### ISSUE THREAD

**Issue by mrdev023** [fastfetch-cli/fastfetch#986]
Be sure to read [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

## Wanted features:

Export result as json, fastfetch can be usefull to use in another tools.

## Motivation:

I want to make tools with common known bugs but i need know (DE used with version, Graphics card with version, OS, ...). To get all bugs corresponding to the configuration. 
Today, i not found common lib to get this but a lot of tools like neofetch or fastfetch which reimplement this.

**Comment by CarterLi** [comment]
I'm not sure I fully got what you meant but I think you need `fastfetch --format json`

**Comment by mrdev023** [comment]
I just found `fastfetch -- --format json`

**Comment by mrdev023** [comment]
> I'm not sure I fully got what you meant but I think you need `fastfetch --format json`

Yes ^^ i just found it but is not in `fastfetch --help`

**Comment by mrdev023** [comment]
https://github.com/fastfetch-cli/fastfetch/issues/830
