### ISSUE TITLE
Strange strings behaviour on kitty terminal (Fedora Bluefin) [BUG] 

### ISSUE THREAD

**Issue by cyscarinci** [fastfetch-cli/fastfetch#987]
# General description of bug:

* What happened: Running fastfetch on kitty (on Fedora Bluefin) there are strange strings around the icons. On ptyxis terminal on the same machine it works fine.

* Fastfetch version used: fastfetch 2.2.3 (x86_64)

* Where did you get the binary: default installation on Fedora Bluefin

Screenshot:

on kitty:
![Screenshot from 2024-06-03 09-54-49](https://github.com/fastfetch-cli/fastfetch/assets/54469881/b766c226-d30e-43eb-becb-7517197c1821)

on ptyxis:
![Screenshot from 2024-06-03 10-03-59](https://github.com/fastfetch-cli/fastfetch/assets/54469881/5d346e7f-a60a-43b3-b78d-f274878ed3e1)

Output of `fastfetch -c ci.jsonc --format json`:
```
❯ fastfetch -c ci.jsonc --format json
Error: couldn't find config: ci.jsonc
```

Output of `fastfetch --list-features`:
```
❯ fastfetch --list-features
threads
libpci
vulkan
wayland
xcb-randr
xcb
xrandr
x11
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
sqlite3
rpm
egl
glx
osmesa
opencl
libddcutil
```

**Comment by CarterLi** [comment]
Please provide the config file

**Comment by CarterLi** [comment]
[I found it myself](https://github.com/ublue-os/bluefin/blob/main/system_files/shared/usr/share/ublue-os/ublue-os.jsonc). It's incorrectly configured by bluefin developers. I will submit a PR to them

**Comment by CarterLi** [comment]
Closing in favor of https://github.com/ublue-os/bluefin/pull/1364

**Comment by cyscarinci** [comment]
Thank you for your great work!
