### ISSUE TITLE
[FEAT]  Make guix package manager detection faster

### ISSUE THREAD

**Issue by Dariqq** [fastfetch-cli/fastfetch#988]
While putting fastfetch 2.14 on a slower laptop of mine i noticed that my implementation for package counts for guix is quite slow taking 60-70ms for each of the 3 profiles on my main machine and up to 2-3x that on a slow laptop.

The main cause for this is waiting for guile to return the list of installed packages. 

I have taken a look at what is happening behind the scenes: 
- The `-I` flag of `guix package` calls the `list-installed` function from [here](https://git.savannah.gnu.org/cgit/guix.git/tree/guix/scripts/package.scm#n777).
- Which then uses `profile-manifest` (from [here](https://git.savannah.gnu.org/cgit/guix.git/tree/guix/profiles.scm#n284)) to read and parse the manifest of the profile at `PROFILE/manifest`.

This manifest files currently look like this:

```scm
(manifest
 (version 4)
 (packages
  (("emacs"
    "29.3"
    "out"
    "/gnu/store/1bi7n031g6b5b07hvps3gyi0rhi44qkb-emacs-29.3"
    ;; ...
    )
   ("fastfetch"
    "2.14.0"
    "out"
    "/gnu/store/kamkxrxi8mdcfagfg0z4nfranhfn8csb-fastfetch-2.14.0"
    ;; ...
    )
   ("btop"
    "1.3.2"
    "out"
    "/gnu/store/0j1ya0g65nk613lnq56dyhnv4fk8blvb-btop-1.3.2")
   ;; .....
   )))
```
(Somtimes there is additional information for a package like search paths, propagated packages or provenance information, etc which I have omitted here for clarity)

All that gets displayed using `guix package -I` are the entries in the `packages` list. 

Would it be possible to parse this file with C instead? Are there any other examples I could look at which do something similiar?

EDIT: 
The thing that I tried was using `GetNumStrings` for `"/gnu/store/"` but that also catches additional entries from the additional fields that i omitted above. But at least it is a lot faster reducing the total time for packages to 4ms

**Comment by CarterLi** [comment]
> Would it be possible to parse this file with C instead? Are there any other examples I could look at which do something similiar?

If you can make sure that the structure of this file will NEVER change, parsing this file can be easy: just count the number of `(` chars

**Comment by CarterLi** [comment]
I don't get what you are doing. What's the content of `filename`?

**Comment by CarterLi** [comment]
A simple implimentation can be:

1. add all hash string into a list
2. sort the list
3. count unique entries.

**Comment by CarterLi** [comment]
You may upload the file and I will have a try.

**Comment by CarterLi** [comment]
```c
static uint32_t getGuixPackagesImpl(char* path)
{
    FF_STRBUF_AUTO_DESTROY content = ffStrbufCreate();
    if (!ffAppendFileBuffer(path, &content))
        return 0;

    char* pend = content.chars;

    for (const char* pattern = content.chars; (pattern = strstr(pattern, "/gnu/store/")); pattern += 32)
    {
        pattern += strlen("/gnu/store/");
        memmove(pend, pattern, 32);
        pend += 32;
    }

    if (pend == content.chars)
        return 0;

    qsort(content.chars, (size_t) (pend - content.chars) / 32, 32, compare32);

    uint32_t count = 1;
    for (const char* p = content.chars + 32; p < pend; p += 32)
        count += memcmp(p - 32, p, 32) != 0;

    return count;
}
```

Try this please.

**Comment by CarterLi** [comment]
```c
static int compare32(const void* a, const void* b)
{
    return memcmp(*(const char**) a, *(const char**) b, 32);
}

static uint32_t getGuixPackagesImpl(char* path)
{
    FF_STRBUF_AUTO_DESTROY content = ffStrbufCreate();
    if (!ffAppendFileBuffer(path, &content))
        return 0;

    FFlist hashes = ffListCreate(sizeof(const char*));

    for (const char* pattern = content.chars; (pattern = strstr(pattern, "/gnu/store/")); pattern += 32)
    {
        pattern += strlen("/gnu/store/");
        *(const char**)ffListAdd(&hashes) = pattern;
    }

    if (hashes.length == 0)
        return 0;

    ffListSort(&hashes, compare32);

    uint32_t count = 1;
    for (uint32_t i = 1; i < hashes.length; ++i)
    {
        count += memcmp(
            *FF_LIST_GET(const char*, hashes, i - 1),
            *FF_LIST_GET(const char*, hashes, i),
            32) != 0;
    }

    return count;
}
```

Also this. May be faster than previous impl.

**Comment by CarterLi** [comment]
Up to you

**Comment by CarterLi** [comment]
Off topic: does the initsystem module crash in your PC?

**Comment by CarterLi** [comment]
I actually prefer the first one. Please make a PR after you tested it carefully.
