### ISSUE TITLE
[FEAT] Added newline after modules print

### ISSUE THREAD

**Issue by retrobit** [fastfetch-cli/fastfetch#989]
Be sure to read [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

## Wanted features:

Simply put, a newline to separate the fetch output from any shell greeting or the prompt would be nice. I figure it would be best in `flashfetch.c` after module printing, or in the call to `init.c`s `ffFinish()` right after.

## Motivation:

It's purely subjective, but Neofetch had it (maybe two, actually) and it looks nice/it's easier to read. Examples of Neofetch output vs fastfetch output attached.

![fastfetch](https://github.com/fastfetch-cli/fastfetch/assets/6226450/7415f96c-a4ab-405f-beeb-e6ee8c6ed63c)
![Neofetch](https://github.com/fastfetch-cli/fastfetch/assets/6226450/42098027-73f7-497f-a9c9-54d8a4ebeb0e)

**Comment by CarterLi** [comment]
Two options:

1. Add a `"break"` at the end of `config.jsonc`
2. Use `fastfetch && echo`

**Comment by retrobit** [comment]
Thanks! I hadn't considered the configuration file solution; I did want to avoid an `echo` as it seemed less clean.

**Comment by retrobit** [comment]
Configuration solution worked perfectly
