### ISSUE TITLE
[FEAT] Detect cache amounts for CPUs.

### ISSUE THREAD

**Issue by Get-Newsletters-Int** [fastfetch-cli/fastfetch#992]
## Wanted features:
Allow detection of L3, L2, and L1 cache amounts for CPUs.

## Motivation:
Cache amounts are important, especially with processors like AMD Ryzen X3D.

**Comment by CarterLi** [comment]
What's your CPU?

**Comment by Get-Newsletters-Int** [comment]
I tested it on Intel Core i3-380M.
