### ISSUE TITLE
[BUG] "fastfetch -s shell --format json" return "fastfetch" instead of "bash" or "zsh" 

### ISSUE THREAD

**Issue by omnigenous** [fastfetch-cli/fastfetch#994]
# General description of bug:

* What happened: `fastfetch` returned when running `fastfetch -s shell --format json` in custom command
* What should happen: return correct shell
* Fastfetch version used: 2.0.12 
* Did it work in an older version: no 
* Where did you get the binary: arch repos
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? haven't tried but I didn't see anything related to this in changelog

```
...
    {
      "type": "command",
      "key": "custom-shell",
      "text": "echo my shell is $(fastfetch -s shell --format json | jq -r '.[0].result.prettyName')"
    },
...
```

```
...
shell   my shell is fastfetch
...
```

## Workaround

```sh
echo $SHELL
```

Output of `fastfetch --list-features`:
```
threads
vulkan
wayland
xcb-randr
xcb
xrandr
x11
drm
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
egl
glx
osmesa
opencl
libpulse
libnm
libddcutil
Directx Headers
Proprietary GPU driver API
System yyjson
linux/videodev2
linux/wireless
```

**Comment by omnigenous** [comment]
@CarterLi I tried building from https://github.com/fastfetch-cli/fastfetch/commit/10fd7d61ae06aea581725f251abb9976eea99703 and it still returns `fastfetch`  (I am running `./run.sh`)

```
{ "exe": "./fastfetch", "exeName": "fastfetch", "exePath": "/home/user/github/fastfetch/build/fastfetch", "pid": 32499, "ppid": 32301, "processName": "fastfetch", "prettyName": "fastfetch", "version": "", "tty": 4 }
```

**Comment by CarterLi** [comment]
How did you get this output?

**Comment by omnigenous** [comment]
@CarterLi Made my terminal really wide and:
```
    {
      "type": "command",
      "key": "custom-shell",
      "text": "echo my shell is $(fastfetch -s shell --format json | jq -r '.[0].result')"
    },
```

**Comment by CarterLi** [comment]
Works for me

**Comment by CarterLi** [comment]
BTW why do you want to use `command` in this case? What about `fastfetch --shell-format 'my shell is {pretty-name}'`?

**Comment by omnigenous** [comment]
> Works for me

Yeah, I'm stupid. Had to replace `fastfetch -s shell` with `/path/to/fork/fastfetch/build/fastfetch -s shell`

**Comment by omnigenous** [comment]
Thank you for fixing this :heart:
